// Characterization of the unchanged game. Test arrangements affect only an isolated VM.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {setup}=require('./runtime.cjs');const root=path.resolve(__dirname,'..');
process.chdir(path.join(root,'baseline_0.20.0'));
const r=setup('index.html'),E=s=>r.eval(s),checks=[],fixtures=[];
const write=(p,o)=>fs.writeFileSync(path.join(root,p),JSON.stringify(o,null,2)+'\n');
const base=E('JSON.stringify(captureGameProgress())');
function check(id,expr,expected=true){try{const value=typeof expr==='function'?expr():E(expr);const same=JSON.stringify(value)===JSON.stringify(expected);checks.push({id,status:same?'PASS':'OBSERVED_FAILURE',expected,actual:value});return same;}catch(e){checks.push({id,status:'ERROR',error:e.message});return false;}}
function fresh(){E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(base)}));for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);menuOpen=false;document.hidden=false;playerDead=false;scene='surface';V013City.setFloor(0);player.wallLevel=false;moveX=moveY=movePower=0;firing=false;frameScale=1;stopControls(true);cancelNavigation();`);}
function power(on=true){E(`V09Power.running=${on};V09Power.fuel=${on?80:0};V010Energy.battery.charge=0;for(const k of Object.keys(V09Power.roomEnabled))V09Power.roomEnabled[k]=true;for(const d of Object.values(V09Power.devices))d.enabled=true;V09Power.allocation();`);}
function clearBag(){E('bag.fill(null);V013Inventory.items.fill(null);V013Inventory.sync();');}
function step(ms,code='update();',interval=16.667){for(let t=0;t<ms;t+=interval){const dt=Math.min(interval,ms-t);r.advance(dt);E(`frameScale=${dt/16.667};${code}`);}}
function arm(type,rounds=0,mag='magazine_standard'){E(`addItem('${type}',1);V013Inventory.equip('${type}');window.testWeapon=V010Combat.currentWeapon();testWeapon.magazineType=${JSON.stringify(mag)};testWeapon.rounds=${rounds};updateAmmoHud();`);}
function projection(){return E(`(()=>{const d=captureGameProgress();return {player:{scene:d.player.scene,health:d.player.health},bag:d.bag,equipment:d.equipment,quick:d.quick013,storage:d.storage,drone:d.robots014,walls:d.base015,doors:d.building018,turrets:d.turret016,farm:d.farm.map(s=>({crop:s.crop,harvestLeft:s.harvestLeft})),plantDurations:d.farm014.beds.map(a=>a?.map(p=>({duration:p.duration,planted:p.planted,harvested:p.harvested,qty:p.qty}))??null),jobs:d.v09.crafting,craft:d.v010.modules.craft};})()`);}
function fixture(id,description){
 const d=E('captureGameProgress()'),raw=JSON.stringify(d,null,2)+'\n',file='fixtures/'+id+'.json';
 fs.writeFileSync(path.join(root,file),raw);
 const before=projection();E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(raw)}));`);const after=projection();
 check('save.'+id+'.roundtrip',()=>JSON.stringify(before)===JSON.stringify(after));
 const valid=check('save.'+id+'.decoder',`!!decodeGameProgress(${JSON.stringify(raw)})`);
 fixtures.push({id,file,description,synthetic:true,sourceVersion:d.gameVersion,savedAt:d.savedAt,sha256:crypto.createHash('sha256').update(raw).digest('hex'),decoderAccepted:valid,expected:before});
}
async function main(){
 check('launch.version',"captureGameProgress().gameVersion",'0.20.0');
 check('launch.ready','gameSaveReady&&!gameSaveBlocked');
 check('launch.quickSlots','V013Inventory.items.length',5);
 fixture('fresh_game','Fresh startup generated by the original runtime, not a user save.');

 fresh();E('player.x=800;player.y=850;window.beforeX=player.x;moveX=1;moveY=0;movePower=1;');step(400,'updatePlayer();');
 check('movement.joystick','player.x>beforeX');E('movePower=0;window.stoppedX=player.x;');step(100,'updatePlayer();');check('movement.release','player.x===stoppedX');
 fresh();E("player.x=surface.hatch.x;player.y=surface.hatch.y+50;executeInteraction(interactionObjects().find(o=>o.id==='hatch')); ");r.flushTimers(700);check('levels.enterBunker',"scene==='bunker'");
 E("executeInteraction(interactionObjects().find(o=>o.id==='exit')); ");r.flushTimers(700);check('levels.exitBunker',"scene==='surface'");

 for(const type of ['rifle_ak74','rifle_m4']){
  fresh();clearBag();arm(type,10);E(`addItem(V09Craft.weapons['${type}'].ammo,7);`);
  check(type+'.reload.start','reloadWeapon()');step(2200,'V010Combat.tick(16.667*frameScale);');
  check(type+'.reload.conservation',"[testWeapon.rounds,bagCount(V09Craft.weapons[testWeapon.type].ammo)]",[17,0]);
  E('window.beforeRounds=testWeapon.rounds;shoot();');check(type+'.shotConsumesOne','testWeapon.rounds===beforeRounds-1');
  check(type+'.removeMagazine','V0162Magazines.remove(testWeapon)');
  check(type+'.noMagazine','!canFire()&&testWeapon.rounds===0&&V010Combat.gunSpec(testWeapon).mag===0');
  E('window.reserveBefore=bagCount(V09Craft.weapons[testWeapon.type].ammo);shoot();');check(type+'.cannotShootWithoutMagazine','bagCount(V09Craft.weapons[testWeapon.type].ammo)===reserveBefore&&testWeapon.rounds===0');
  E("addItem('magazine_module',1);");check(type+'.install60',"V0162Magazines.installFirst(testWeapon,'magazine_module')");
  check(type+'.empty60','testWeapon.rounds===0&&V010Combat.gunSpec(testWeapon).mag===60');
  E('testWeapon.rounds=37;');fixture(type+'_37_60','Loaded physical extended magazine, 37/60 rounds.');
  E('V0162Magazines.remove(testWeapon);');fixture(type+'_no_magazine','Removed magazine; loaded ammunition is returned to inventory.');
 }
 for(const [n,expected]of [[300,[600,600,330]],[590,[600,600,600,20]]]){
  fresh();clearBag();arm('rifle_ak74',30);E(`bag[0]={type:'ammo',qty:600};bag[1]={type:'ammo',qty:600};bag[2]={type:'ammo',qty:${n}};`);
  check('ammo.return.'+n,'V0162Magazines.remove(testWeapon)');check('ammo.stacks.'+n,"bag.filter(s=>s?.type==='ammo').map(s=>s.qty)",expected);
 }
 fresh();clearBag();arm('rifle_ak74',30);E("for(let i=0;i<BAG_SLOTS;i++)bag[i]={type:'wood',qty:100};window.beforeFull=JSON.stringify({bag,weapon:testWeapon});");
 check('ammo.fullBagRefuses','!V0162Magazines.remove(testWeapon)');check('ammo.fullBagAtomic','JSON.stringify({bag,weapon:testWeapon})===beforeFull');
 fixture('full_backpack','Full backpack, loaded weapon: magazine removal must remain atomic.');

 fresh();clearBag();E("addItem('wood',90);addItem('wood',30);storageChests[0].items=[];");
 check('inventory.stack100',"bag.filter(Boolean).map(s=>s.qty)",[100,20]);
 check('inventory.transfer','V010Inventory.transfer("bag",0,0,35)',35);
 check('inventory.transferConservation',"bagCount('wood')+storageChests[0].items.reduce((n,s)=>n+(s?.qty||0),0)",120);
 E("addItem('vest5',1);window.gearIndex=bag.findIndex(s=>s?.type==='vest5');window.gear=bag[gearIndex];V010Combat.ensure(gear);gear.level=5;");
 check('equipment.equip','V010Inventory.equip(gearIndex)');check('equipment.stats','V010Combat.refreshStats().hp>100');
 fixture('equipment_storage','Upgraded armor equipped, partial stacks and chest contents.');
 check('equipment.unequip',"V010Inventory.unequip('body')");

 fresh();clearBag();E("scene='bunker';addItem('fish',5);V014Fish.normalize(bag.find(s=>s?.type==='fish'));window.fishBefore=V013Inventory.fishWeight();");
 fixture('fish_instances','Individual fish IDs and gram weights inside a stack.');
 check('fish.cook','V013Inventory.cook(2)');check('fish.massConservation',"bagCount('cooked_fish')*500+V013Inventory.fishWeight()===fishBefore");

 fresh();power();clearBag();E("addItem('iron_ore',10);addItem('copper_ore',10);");
 check('craft.startIron',"V09Craft.start('furnace','iron',3)");
 check('craft.queueCopper',"V09Craft.start('furnace','copper',2)");
 fixture('craft_in_progress','Iron smelting plus queued copper; ingredients already reserved.');
 step(6200,'V09Craft.tick(16.667*frameScale);');
 check('craft.finishedIron',"V09Craft.collect('furnace')>=3&&bagCount('iron')>=3");
 step(4200,'V09Craft.tick(16.667*frameScale);');check('craft.finishedCopper',"V09Craft.collect('furnace')>=2&&bagCount('copper')>=2");

 for(let crop=0;crop<E('farmCrops.length');crop++){
  fresh();power();clearBag();E(`scene='bunker';window.bed=getFarmBeds()[0];player.x=bed.x+bed.w/2;player.y=bed.y+bed.h/2;window.seedType=V0141Farm.seedType(${crop});addItem(seedType,2);`);
  check('farm.'+crop+'.plant',`V0141Farm.plant(0,${crop})`);
  check('farm.'+crop+'.seedConsumed','bagCount(seedType)',1);
  check('farm.'+crop+'.cropType','farmState[0].crop',crop);
  check('farm.'+crop+'.individualGrowth','V011Farm.plants(farmState[0]).length===50&&V011Farm.plants(farmState[0]).every(p=>p.duration>=farmGrowMs(farmState[0].crop)*.9&&p.duration<=farmGrowMs(farmState[0].crop)*1.1)');
  fixture('crop_'+crop,'Planted crop '+E(`farmCrops[${crop}].itemType`)+', all 50 plant durations retained.');
  const elapsed=E('V011Farm.plants(farmState[0])[0].elapsed');r.advance(4000);E('V011Farm.settle();');
  check('farm.'+crop+'.grows',`V011Farm.plants(farmState[0])[0].elapsed>${elapsed}`);
  E('V011Farm.plants(farmState[0]).forEach(p=>p.elapsed=p.duration);');
  check('farm.'+crop+'.harvest','V0141Farm.harvest(0)',50);
  check('farm.'+crop+'.emptyAfterHarvest','farmState[0].crop===null');
  check('farm.'+crop+'.replant',`V0141Farm.plant(0,${crop})`);
 }
 fresh();clearBag();E("scene='bunker';window.bed=getFarmBeds()[0];player.x=bed.x+50;player.y=bed.y+50;");check('farm.noSeedRefuses','!V0141Farm.plant(0,2)&&farmState[0].crop===null');

 fresh();clearBag();power(false);E("Object.assign(V014Robots.state,{battery:0,task:'disabled',scene:'surface',x:2300,y:3000,cargo:[{type:'wood',qty:17}]});");
 fixture('drone_empty_far','Powered-off drone far from station with retained cargo.');
 check('drone.rescue','V014Robots.pack()');check('drone.uniquePacked',"V014Robots.state.packed&&bag.filter(s=>s?.type==='drone014').length===1");
 fixture('drone_packed','Same drone packed with cargo, zero battery.');
 E("scene='bunker';player.x=1264;player.y=740;");check('drone.install','V014Robots.install()');step(100,'V014Robots.tick(16.667*frameScale);');
 check('drone.noPower','V014Robots.stationInfo().status','NO_POWER');const off=E('V014Robots.state.battery');step(500,'V014Robots.tick(16.667*frameScale);');check('drone.noFreeCharge',`V014Robots.state.battery===${off}`);
 power();step(1000,'V014Robots.tick(16.667*frameScale);');check('drone.zeroBatteryRecovers','V014Robots.state.battery>0&&V014Robots.stationInfo().status===\'CHARGING\'');
 fixture('drone_charging','Recovered drone charging at powered station with original cargo.');
 E('V014Robots.state.battery=99.99;');step(200,'V014Robots.tick(16.667*frameScale);');check('drone.full','V014Robots.state.battery===100&&V014Robots.stationInfo().status===\'FULLY_CHARGED\'');
 check('drone.leaveDock','V014Robots.follow()');
 E("Object.assign(V014Robots.state,{battery:14,task:'follow',x:1200,y:820});");step(100,'V014Robots.tick(16.667*frameScale);');check('drone.autoReturn',"['return','docking','docked'].includes(V014Robots.state.task)");
 E("scene='surface';Object.assign(V014Robots.state,{scene:'bunker',packed:false,task:'disabled',battery:0});");
 check('drone.mapDifferentLevel',"V0151Station.mapMarker().other&&V0151Station.mapMarker().arrow==='↓'&&V0151Station.mapMarker().x===surface.hatch.x");
 E("scene='bunker';Object.assign(V014Robots.state,{scene:'surface',x:2300,y:3000});");check('drone.mapOtherDirection',"V0151Station.mapMarker().other&&V0151Station.mapMarker().arrow==='↑'&&V0151Station.mapMarker().x===bunker.entrance.x");
 E("scene='surface';");check('drone.mapOffRealPosition',"!V0151Station.mapMarker().other&&V0151Station.mapMarker().off&&V0151Station.mapMarker().x===2300&&V0151Station.mapMarker().y===3000");

 fresh();E("V015Base.sections[0].hp=3750;V015Base.sections[1].level=4;V015Base.sections[1].maxHp=60000;V015Base.sections[1].hp=29000;V015Base.changed();V016Turret.guns[0].ammo=137;V016Turret.guns[0].level=3;");fixture('damaged_base_turret','Different wall damage/upgrade levels and deployed turret ammo.');
 fresh();E('V016Lighting.restore({schema:1,day:10,minute:1380});zombies.forEach(z=>V017Monsters.prepare(z));');
 check('event.dayX','V017Monsters.isDayX()');check('event.heavyHP','V017Monsters.stats("heavy").hp',630);fixture('day_x','Day 10 at night with boosted current monster types.');

 fresh();clearBag();E("addItem('axe',1);addItem('wood',10);V0162Quick.open(4);");check('ui.quickPicker','document.querySelectorAll(".v162PickCell").length',2);
 check('ui.quickUnavailable','document.querySelectorAll(".v162Unavailable").length',1);
 E('document.querySelector(".v162Unavailable").click();');check('ui.quickRedFeedback','document.querySelector(".v162Unavailable").classList.contains("v013Missing")&&V013Inventory.items[4]===null');
 E('document.querySelectorAll(".v162PickCell")[0].click();');check('ui.quickAllowed',"V013Inventory.items[4]?.type==='axe'&&!bag.some(s=>s?.type==='axe')");
 E("V013Inventory.returnItem(4);V0162Quick.open(4);");
 E('for(const o of document.querySelectorAll(".overlay.open"))closeOverlay(o);openOverlay(el("inventoryOverlay"));V0162Quick.open(4);');check('ui.quickFromInventory','el("inventoryOverlay").classList.contains("open")&&document.querySelectorAll(".v162PickCell").length===2');
 E("window.backgroundClicks=0;el('inventoryGrid').addEventListener('click',()=>backgroundClicks++);");
 r.emit('pointerdown',r.doc.getElementById('inventoryGrid'));r.emit('pointerup',r.doc.getElementById('inventoryGrid'));r.emit('click',r.doc.getElementById('inventoryGrid'));
 check('ui.dismissConsumesGesture',"!el('v0162QuickPicker').classList.contains('open')&&el('inventoryOverlay').classList.contains('open')&&backgroundClicks===0");
 r.emit('pointerdown',r.doc.getElementById('inventoryGrid'));r.emit('pointerup',r.doc.getElementById('inventoryGrid'));r.emit('click',r.doc.getElementById('inventoryGrid'));
 check('ui.nextGestureWorks','backgroundClicks===1');
 E('for(const o of document.querySelectorAll(".overlay.open"))closeOverlay(o);openOverlay(el("settingsOverlay"));');check('ui.settings','el("settingsOverlay").classList.contains("open")&&menuOpen');

 fresh();await Promise.all([...E('Object.keys(V011Art.sources).map(k=>V011Art.image(k).decode())'),...E('[1,2,3,4,5].map(n=>V020Walls.image(n).decode())')]);
 check('assets.imageDecode',"Object.keys(V011Art.sources).every(k=>V011Art.ready(k))&&[1,2,3,4,5].every(n=>V020Walls.ready(n))");
 E('update();draw();');check('render.fullFrameNoErrors',()=>r.errors.length===0);
 fs.writeFileSync(path.join(root,'reports/baseline_surface.png'),r.canvas.toBuffer('image/png'));
 const legacy=setup('source/baseline_0.19.1.html');const old=legacy.eval('captureGameProgress()');write('fixtures/legacy_0.19.1.json',old);
 check('save.legacyMigration',()=>{E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(JSON.stringify(old))}));`);return E('V015Base.sections.length===28&&captureGameProgress().base015.schema===4');});
 write('fixtures/index.json',{origin:'Synthetic QA states produced with unmodified 0.20.0 runtime and deterministic harness, not user progress. Legacy fixture comes from bundled original 0.19.1.',epoch:'2026-09-19T12:00:00Z',randomSeed:20260919,fixtures});
 const summary={passed:checks.filter(c=>c.status==='PASS').length,observedFailures:checks.filter(c=>c.status==='OBSERVED_FAILURE').length,errors:checks.filter(c=>c.status==='ERROR').length,fixtures:fixtures.length+1};
 write('reports/behavior.json',{version:'0.20.0',summary,checks,consoleErrors:r.errors,scope:'Real game JS in deterministic VM, modeled DOM and real Canvas2D. No physical mobile/browser claims.'});
 console.log(JSON.stringify(summary));for(const c of checks)if(c.status!=='PASS')console.log(JSON.stringify(c));
}
main().catch(e=>{console.error(e.stack);process.exitCode=1;});
