/* Compact local equipment controls; all mutations pass through authorities. */
window.GameDefenseUI=(()=>{
 const t=(k,p)=>I18n.t('defense.'+k,p),node=(tag,cls)=>{const n=document.createElement(tag);if(cls)n.className=cls;return n;},overlay=v09Overlay('defenseOverlay',''),body=overlay.querySelector('.v09Body');let selected=null,draft=0;
 const hero=node('div','defenseHero'),icon=node('img','buildIcon'),stats=node('p'),status=node('p','coreHint'),actions=node('div','defenseActions'),cost=node('p','coreHint'),direction=node('section','defenseDirection'),label=node('label'),slider=node('input'),compass=node('canvas'),angleText=node('output');hero.append(icon,stats);compass.width=240;compass.height=150;slider.type='range';slider.min='-180';slider.max='180';slider.step='5';slider.id='searchlightDirection';label.htmlFor=slider.id;slider.oninput=()=>{draft=Number(slider.value)*Math.PI/180;drawAim();};
 const buttons={};function button(key,fn,parent=actions){const b=node('button','menuButton');b.type='button';b.dataset.defenseAction=key;b.onclick=fn;parent.append(b);buttons[key]=b;return b;}
 function result(out){if(!out.ok)message(I18n.t('defense.error.'+out.reason));refresh();return out;}
 button('power',()=>{const d=GameBaseControl.get(selected);if(d)result(GameBaseControl.request(selected,'power',{value:!d.on,previous:d.on}));});
 button('load',()=>result(GameDefense.request(selected,'load',{units:DefenseDefinitions.types[GameEquipment.get(selected).typeId].capacity})));
 button('unload',()=>result(GameDefense.request(selected,'unload')));button('repair',()=>result(GameDefense.request(selected,'repair')));button('upgrade',()=>result(GameDefense.request(selected,'upgrade')));
 button('pickup',()=>{closeOverlay(overlay);GamePickup.beginInteraction(selected);});
 direction.append(label,compass,slider,angleText);const aimActions=node('div','defenseActions');direction.append(aimActions);button('left',()=>{draft=Math.max(-Math.PI,draft-Math.PI/12);slider.value=String(Math.round(draft*180/Math.PI));drawAim();},aimActions);button('right',()=>{draft=Math.min(Math.PI,draft+Math.PI/12);slider.value=String(Math.round(draft*180/Math.PI));drawAim();},aimActions);button('aim',()=>result(GameDefense.request(selected,'aim',{angle:draft})),direction);
 body.append(hero,status,actions,cost,direction);
 function drawAim(){const c=compass.getContext('2d'),cx=120,cy=75;c.clearRect(0,0,240,150);c.fillStyle='#102624';c.fillRect(0,0,240,150);c.strokeStyle='#638277';c.lineWidth=1;c.beginPath();c.arc(cx,cy,55,0,Math.PI*2);c.moveTo(cx-68,cy);c.lineTo(cx+68,cy);c.moveTo(cx,cy-64);c.lineTo(cx,cy+64);c.stroke();c.fillStyle='#ffe8ab55';c.beginPath();c.moveTo(cx,cy);c.arc(cx,cy,58,draft-.48,draft+.48);c.closePath();c.fill();c.strokeStyle='#ffebaf';c.lineWidth=3;c.beginPath();c.moveTo(cx,cy);c.lineTo(cx+58*Math.cos(draft),cy+58*Math.sin(draft));c.stroke();angleText.textContent=t('degrees',{angle:I18n.number(Math.round(draft*180/Math.PI))});}
 function refresh(){if(!overlay.classList.contains('open'))return;const r=GameEquipment.get(selected);if(!r||r.placement!=='installed'){reset();return;}const d=DefenseDefinitions.types[r.typeId],on=!!V09Power.devices[r.refs.device]?.enabled,near=GameDefense.reachable(GameActors.local,r),broken=r.state.condition.hp===0,light=r.typeId==='searchlight';overlay.querySelector('.v09Title').textContent=I18n.t('build.type.'+r.typeId);icon.src=AssetManifest.images['buildable/'+r.typeId].path;icon.alt=I18n.t('build.type.'+r.typeId);stats.textContent=t('health',{hp:I18n.number(Math.ceil(r.state.condition.hp)),max:I18n.number(r.state.condition.maxHp)})+' · '+t('power',{value:I18n.number(d.powerKW)})+(light?'': '\n'+t('combat',{damage:Math.round(d.damage*(1+r.state.level*.1)),ammo:r.state.settings.ammo,max:d.capacity,level:r.state.level}));status.textContent=t(broken?'destroyed':r.state.settings.fallen?'fallen':!on?'off':!devicePowered(r.refs.device)?'noPower':'active');
  for(const [key,b]of Object.entries(buttons)){b.textContent=t(key);b.disabled=!near;}buttons.power.textContent=t(on?'offAction':'onAction');buttons.power.disabled=!near||broken||r.state.settings.fallen;for(const key of ['load','unload','upgrade'])buttons[key].hidden=light;buttons.load.disabled=light||!near||r.state.settings.ammo>=d.capacity||bagCount(d.ammoType)===0;buttons.unload.disabled=!near||!r.state.settings.ammo;buttons.repair.disabled=!near||r.state.condition.hp===r.state.condition.maxHp||r.state.settings.fallen;buttons.repair.textContent=t(broken?'rebuild':'repair');buttons.upgrade.disabled=!near||r.state.level>=5||broken;direction.hidden=!light;label.textContent=t('direction');slider.setAttribute('aria-label',t('direction'));slider.disabled=!near;cost.textContent=t('repairHint',{iron:GameDefense.repairCost(r).iron})+' '+t('pickupHint');if(!light&&r.state.level<5){const n=r.state.level+1;cost.textContent+=' '+t('upgradeHint',{iron:50*n,copper:25*n,parts:15*n,advanced:Math.max(0,n-3)*5});}drawAim();
 }
 function open(id){const r=GameEquipment.get(id);if(!GameDefense.is(r)||!GameDefense.reachable(GameActors.local,r))return false;selected=id;draft=r.state.settings.angle;slider.value=String(Math.round(draft*180/Math.PI));GameMovement.openUI();openOverlay(overlay);refresh();return true;}
 function reset(){closeOverlay(overlay);selected=null;}
 I18n.onChange(refresh);const updateOld=update;let clock=0;update=function(...args){const out=updateOld(...args);clock+=16.667*frameScale;if(clock>=200){clock=0;refresh();}return out;};
 v09Style(`#defenseOverlay .v09Panel{width:min(440px,calc(100vw - 24px));height:min(690px,calc(100dvh - 48px - env(safe-area-inset-top,0px) - env(safe-area-inset-bottom,0px)));box-sizing:border-box;display:flex;flex-direction:column;overflow:hidden}#defenseOverlay .v09Header{flex:0 0 44px}#defenseOverlay .v09Body{min-height:0;overflow-y:auto;overscroll-behavior:contain;padding-bottom:12px}.defenseHero{display:flex;gap:14px;align-items:center}.defenseHero p{white-space:pre-line;font-size:12px;line-height:1.6}.defenseHero .buildIcon{width:96px;height:96px;flex-basis:96px}.defenseActions{display:grid;grid-template-columns:1fr 1fr;gap:6px}.defenseActions button,#defenseOverlay button{min-height:44px;font-size:12px;margin:3px 0}.defenseDirection label,.defenseDirection output{display:block;font-size:13px;line-height:1.7}.defenseDirection canvas{display:block;width:240px;max-width:100%;height:auto;margin:8px auto}.defenseDirection input{width:100%;min-height:44px;touch-action:pan-x}#defenseOverlay [hidden]{display:none!important}#defenseOverlay .coreHint{font-size:12px;line-height:1.5;color:#b7cbbd}@media(max-height:500px){#defenseOverlay .v09Panel{height:calc(100dvh - 32px);margin:0}.defenseDirection canvas{width:180px}}`);
 return Object.freeze({open,refresh,reset});
})();
