/* Relative combat durations survive saves without offline catch-up. Entity HP,
   ammo, power, placements and rewards remain with their existing owners. */
window.GameActivitySave=(()=>{
 const cap=(v,max)=>clamp(Number(v)||0,0,max),copy=v=>JSON.parse(JSON.stringify(v));
 const freshActor=id=>({id,attackAgo:15000,sense:0,retarget:0,wall:null,fuse:null,jump:null,pause:0,wander:0,angle:0,wanderAngle:0,lastSeen:null,sawAgo:6000,phase:0});
 function fresh(data){return {schema:1,actors:(data.identity027?.enemies||data.zombies.map((_,i)=>'enemy:'+(i+1))).map(freshActor),turrets:data.equipment032.instances.filter(r=>DefenseDefinitions.types[r.typeId]?.ammoType).map(r=>({id:r.id,shot:0,scan:0,angle:null}))};}
 function capture(){const now=GameActivity.now();return {schema:1,actors:zombies.map(z=>{const r=V017Monsters.state(z);return {id:z.instanceId,attackAgo:cap(now-z.lastAttack,15000),sense:cap(r.nextSense-now,1000),retarget:cap(r.retarget-now,12000),wall:r.target?.id||null,fuse:r.fuse?{remaining:cap(r.fuse-now,10000),duration:cap(r.fuseDuration,10000)}:null,jump:r.jump?{...r.jump,start:undefined,elapsed:cap(now-r.jump.start,r.jump.duration)}:null,pause:cap(r.pauseUntil-now,3000),wander:cap(z.nextWanderChange-now,10000),angle:r.angle,wanderAngle:z.wanderAngle||0,lastSeen:r.lastSeen?{x:r.lastSeen.x,y:r.lastSeen.y}:null,sawAgo:cap(now-(r.sawPlayerAt||0),6000),phase:GameActivity.phase(z)};}),turrets:GameDefense.records().filter(r=>DefenseDefinitions.types[r.typeId].ammoType).map(r=>{const v=GameDefense.transient(r.id);return {id:r.id,shot:cap(v.shot,2),scan:cap(v.scan,.2),angle:v.angle};})};}
 const num=(v,max,min=0)=>Number.isFinite(v)&&v>=min&&v<=max;
 const exact=(o,keys)=>o&&typeof o==='object'&&!Array.isArray(o)&&Object.keys(o).sort().join()===keys.split(',').sort().join();
 function validate(d){const s=d.activity040;if(!exact(s,'schema,actors,turrets')||s.schema!==1||!Array.isArray(s.actors)||!Array.isArray(s.turrets)||s.actors.length!==d.zombies.length||s.turrets.length!==d.equipment032.instances.filter(r=>DefenseDefinitions.types[r.typeId]?.ammoType).length)throw Error('Invalid world activity state');
  const ids=new Set(d.identity027.enemies),seen=new Set();for(const a of s.actors){if(!exact(a,'id,attackAgo,sense,retarget,wall,fuse,jump,pause,wander,angle,wanderAngle,lastSeen,sawAgo,phase')||!ids.has(a.id)||seen.has(a.id)||!num(a.attackAgo,15000)||!num(a.sense,1000)||!num(a.retarget,12000)||a.wall!==null&&!V015Base.byId.has(a.wall)||!num(a.pause,3000)||!num(a.wander,10000)||!num(a.angle,100,-100)||!num(a.wanderAngle,100,-100)||!num(a.sawAgo,6000)||!num(a.phase,350)||a.lastSeen!==null&&(!exact(a.lastSeen,'x,y')||!num(a.lastSeen.x,100000,-100000)||!num(a.lastSeen.y,100000,-100000))||a.fuse!==null&&(!exact(a.fuse,'remaining,duration')||!num(a.fuse.remaining,10000)||!num(a.fuse.duration,10000))||a.jump!==null&&(!exact(a.jump,'windup,duration,speed,angle,elapsed')||!num(a.jump.windup,1000)||!num(a.jump.duration,10000,1)||!num(a.jump.speed,50)||!num(a.jump.angle,100,-100)||!num(a.jump.elapsed,a.jump.duration)))throw Error('Invalid enemy activity');seen.add(a.id);}
  const guns=new Map(d.equipment032.instances.filter(r=>DefenseDefinitions.types[r.typeId]?.ammoType).map(r=>[r.id,r]));seen.clear();for(const t of s.turrets){const r=guns.get(t.id);if(!exact(t,'id,shot,scan,angle')||!r||seen.has(t.id)||!num(t.shot,DefenseDefinitions.types[r.typeId].intervalMs/1000)||!num(t.scan,.2)||t.angle!==null&&!num(t.angle,Math.PI,-Math.PI))throw Error('Invalid defense activity');seen.add(t.id);}return true;
 }
 function restore(d){validate(d);GameActivity.reset();const now=GameActivity.now(),actors=new Map(d.activity040.actors.map(a=>[a.id,a]));for(const z of zombies){const a=actors.get(z.instanceId),r=V017Monsters.state(z);z.lastAttack=now-a.attackAgo;z.nextWanderChange=now+a.wander;z.wanderAngle=a.wanderAngle;Object.assign(r,{nextSense:now+a.sense,sees:false,retarget:now+a.retarget,target:a.wall?V015Base.byId.get(a.wall):null,fuse:a.fuse?now+Math.max(.001,a.fuse.remaining):0,fuseDuration:a.fuse?.duration||0,fuseAt:a.fuse?now+a.fuse.remaining-a.fuse.duration:0,jump:a.jump?{...copy(a.jump),start:now-a.jump.elapsed}:null,pauseUntil:now+a.pause,angle:a.angle,lastSeen:copy(a.lastSeen),sawPlayerAt:now-a.sawAgo});GameActivity.restorePhase(z,a.phase);}
  for(const t of d.activity040.turrets)Object.assign(GameDefense.transient(t.id),{shot:t.shot,scan:t.scan,angle:t.angle});
 }
 GameSave.extend('capture','simulation.activity',function(previous){const d=previous();d.activity040=capture();return d;});
 // Validation runs after historical identity migrations in GameSave.decode.
 GameSave.extend('restore','simulation.activity',function(previous,d){validate(d);const out=previous(d);restore(d);return out;});
 GameState.register('activity',{capture},{source:'simulation/activity-save.js',saved:['activity040'],transient:['active areas','cadence metrics','spatial query context']});
 return Object.freeze({capture,validate,restore,migrate(d){d.activity040=fresh(d);},completeMigration(d){d.activity040=fresh(d);}});
})();
