/* Presentation consumes the owners, never writes progression or inventory. */
(()=>{
 const B=GameplayBalance.survival,keys=['tea','regen','energy','vitality','adrenaline','oil'];
 const details=V011UI.details;V011UI.details=function(where,index){details(where,index);const item=where==='bag'?bag[index]:null,d=item&&B.uses[item.type];if(!d)return;
  const b=v09Button(I18n.t('survival.'+d.action),()=>{const result=SurvivalUse.request(index);if(result.ok){for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);}else message(I18n.t(result.reason==='full'?'survival.full':'survival.interrupted'));});b.dataset.survivalAction=d.action;b.disabled=!GameSurvival.useful(item.type);el('v010ItemDetails').querySelector('.v011ItemActions').prepend(b);
 };
 const grid=el('inventoryGrid'),filters=document.createElement('div');filters.id='survivalFilters';let filter='all';
 const filterButtons=[];function applyFilter(){for(const c of grid.children){const item=bag[Number(c.dataset.v010Index)];c.hidden=filter!=='all'&&ITEM[item?.type]?.category!==filter;}for(const b of filterButtons)b.setAttribute('aria-pressed',String(b.dataset.category===filter));}
 for(const category of ['all','food','drink','healing','buff']){const b=v09Button(I18n.t('survival.filter.'+category),()=>{filter=category;applyFilter();});b.dataset.category=category;filters.append(b);filterButtons.push(b);}grid.before(filters);
 const render=renderBag;renderBag=function(...a){const out=render(...a);applyFilter();return out;};
 const bar=el('v163Vitals'),thirst=document.createElement('div');thirst.className='v163Thirst';thirst.setAttribute('role','meter');thirst.setAttribute('aria-valuemin','0');thirst.setAttribute('aria-valuemax','100');thirst.innerHTML='<span class="v163ThirstFill"></span><span class="v163HungerLabel">💧 <span id="survivalThirstValue">100</span></span>';bar.append(thirst);
 const icons=document.createElement('div');icons.id='survivalEffects';const nodes={};for(const k of keys){const b=document.createElement('button');b.type='button';b.hidden=true;b.onclick=()=>message(I18n.t('survival.effect.'+k));icons.append(b);nodes[k]=b;}bar.append(icons);
 let signature='';function refresh(){const h=Math.round(player.hunger),t=Math.round(player.thirst);let key=I18n.language+'/'+h+'/'+t;for(const k of keys)key+='/'+(k==='oil'?GameSurvival.remaining(k):Math.ceil(GameSurvival.remaining(k)/1000));if(key===signature)return;signature=key;
  bar.style.setProperty('--thirst',t+'%');bar.classList.toggle('hungerLow',h<=B.low);bar.classList.toggle('thirstLow',t<=B.low);el('survivalThirstValue').textContent=t;thirst.setAttribute('aria-valuenow',String(t));thirst.setAttribute('aria-label',I18n.t('survival.thirst'));
  for(const k of keys){const b=nodes[k],n=k==='oil'?GameSurvival.remaining(k):Math.ceil(GameSurvival.remaining(k)/1000);b.hidden=n<=0;b.textContent=B.effects[k].icon+' '+(k==='oil'?n:Math.floor(n/60)+':'+String(n%60).padStart(2,'0'));b.title=I18n.t('survival.effect.'+k);b.setAttribute('aria-label',b.title+' '+b.textContent);}
 }
 const updateVitals=V0163Vitals.refresh;V0163Vitals.refresh=function(){updateVitals();refresh();};const old=update;update=function(...a){const r=old(...a);refresh();return r;};
 I18n.onChange(()=>{for(const b of filterButtons)b.textContent=I18n.t('survival.filter.'+b.dataset.category);signature='';refresh();});
 v09Style(`#survivalFilters{display:flex;gap:3px;flex-wrap:wrap;margin:6px 0}#survivalFilters button{min-height:36px;padding:4px 7px;font-size:10px;flex:1;margin:0}#survivalFilters [aria-pressed="true"]{border-color:#c5d998;background:#34483a}#inventoryGrid>[hidden]{display:none!important}#v163Vitals>.v163Hunger,#v163Vitals>.v163Thirst{position:absolute;bottom:16px;width:calc(50% - 2px);height:9px;line-height:9px;font-size:8px;border:1px solid #acc3b62c;box-sizing:border-box;border-radius:5px;overflow:hidden;text-align:center;background:#132522ba}#v163Vitals>.v163Hunger{left:0}#v163Vitals>.v163Thirst{right:0}.v163ThirstFill{position:absolute;inset:0 auto 0 0;width:var(--thirst,100%);background:#497fa3}#v163Vitals.hungerLow .v163HungerFill,#v163Vitals.thirstLow .v163ThirstFill{background:#ac5144}#survivalEffects{position:absolute;bottom:30px;left:0;right:0;display:flex;justify-content:center;gap:3px;pointer-events:none}#survivalEffects button{pointer-events:auto;margin:0;padding:3px 2px;min-width:32px;min-height:26px;border:1px solid #c0d4bb44;border-radius:4px;background:#152720cc;color:#eff5dd;font:9px Arial;white-space:nowrap}#survivalEffects button[hidden]{display:none}`);
 refresh();
})();
