// Project asset preparation: preserve generated alpha and export consistent
// thumbnail views. Vector devices use the same shapes as their world renderer.
const fs=require('fs'),path=require('path'),{createCanvas,loadImage}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/@napi-rs/canvas':'@napi-rs/canvas');
(async()=>{const m=JSON.parse(fs.readFileSync('assets/manifest.json')),dir='assets/images/buildables';
const add=(key,file,w,h,crop)=>{m.images['art/'+key]={path:file,size:[w,h],...(crop?{crop}:{})};m.art[key]='art/'+key;};
const im=await loadImage('docs/art-source/utility_workbench_source.png'),probe=createCanvas(im.width,im.height),pc=probe.getContext('2d');pc.drawImage(im,0,0);const a=pc.getImageData(0,0,im.width,im.height).data;let x=im.width,y=im.height,right=0,bottom=0;for(let py=0;py<im.height;py++)for(let px=0;px<im.width;px++)if(a[(py*im.width+px)*4+3]>24){x=Math.min(x,px);y=Math.min(y,py);right=Math.max(right,px);bottom=Math.max(bottom,py);}
const c=createCanvas(512,256),ctx=c.getContext('2d');ctx.drawImage(im,x,y,right-x+1,bottom-y+1,8,8,496,240);fs.writeFileSync(dir+'/utility_workbench.png',c.toBuffer('image/png'));add('utility_workbench',dir+'/utility_workbench.png',512,256,{x:8,y:8,w:496,h:240});
for(const [key,w,h]of [['battery0352',105,215],['drone_station0352',148,86],['base_lamp',44,44]]){const c=createCanvas(w,h),q=c.getContext('2d');q.fillStyle='#36565f';q.strokeStyle='#90aaa3';q.lineWidth=2;
 if(key==='battery0352'){q.beginPath();q.roundRect(2,2,101,212,7);q.fill();q.stroke();q.fillStyle='#1b3440';q.fillRect(20,31,65,105);for(let i=0;i<7;i++){q.fillStyle='#8cc7a5';q.fillRect(29,118-i*12,46,7);}q.fillStyle='#203943';q.fillRect(17,166,72,23);}
 if(key==='drone_station0352'){q.beginPath();q.roundRect(1,1,w-2,h-2,8);q.fill();q.stroke();q.fillStyle='#1d3238';q.fillRect(9,10,w-18,h-20);q.strokeStyle='#7eaaa1';q.beginPath();q.arc(74,45,29,0,Math.PI*2);q.stroke();q.fillStyle='#71837a';q.fillRect(7,7,26,72);q.fillStyle='#8adbbb';q.fillRect(11,14,18,26);}
 if(key==='base_lamp'){q.fillStyle='#314b4f';q.beginPath();q.arc(22,22,13,0,Math.PI*2);q.fill();q.stroke();q.fillStyle='#f6e4ba';q.beginPath();q.arc(22,22,8,0,Math.PI*2);q.fill();q.fillStyle='#83968e';q.fillRect(10,18,24,3);}
 fs.writeFileSync(dir+'/'+key+'.png',c.toBuffer('image/png'));add(key,dir+'/'+key+'.png',w,h);
}
for(const [type,key]of Object.entries({utility_workbench:'utility_workbench',craft_bench:'workbench',furnace:'furnace',storage_crate:'chest',fuel_tank:'tank',generator:'generator',reserve_battery:'battery0352',drone_station:'drone_station0352',enhancement_cradle:'upgrade_station0161',base_lamp:'base_lamp'})){const d=m.images[m.art[key]],im=await loadImage(d.path),b=d.crop||{x:0,y:0,w:im.width,h:im.height},c=createCanvas(128,128),q=c.getContext('2d'),s=Math.min(120/b.w,120/b.h);q.drawImage(im,b.x,b.y,b.w,b.h,(128-b.w*s)/2,(128-b.h*s)/2,b.w*s,b.h*s);const file=dir+'/'+type+'_icon.png';fs.writeFileSync(file,c.toBuffer('image/png'));m.images['buildable/'+type]={path:file,size:[128,128]};}
fs.writeFileSync('assets/manifest.json',JSON.stringify(m,null,2)+'\n');console.log('Prepared 10 icons and utility/device art with alpha');})();
