// Deterministic, dependency-free catalog validation and classic-script generation.
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'locales');
const read=f=>JSON.parse(fs.readFileSync(path.join(dir,f),'utf8'));
function validate(){
 const manifest=read('manifest.json'),legacy=read('legacy.json'),catalogs={};
 if(!manifest.locales.some(l=>l.id===manifest.default))throw Error('Missing default locale');
 for(const l of manifest.locales){
  if(!/^[a-z]{2}(?:-[A-Z]{2})?$/.test(l.id)||l.file!==l.id+'.json'||catalogs[l.id])throw Error('Invalid locale: '+l.id);
  new Intl.NumberFormat(l.intl);catalogs[l.id]=read(l.file);
 }
 const base=catalogs[manifest.default],keys=Object.keys(base).sort();
 const forms=v=>typeof v==='string'?[v]:v&&typeof v==='object'&&typeof v.other==='string'?Object.values(v):[];
 const params=s=>[...new Set([...s.matchAll(/\{([a-zA-Z][\w]*)\}/g)].map(m=>m[1]))].sort().join(',');
 for(const [lang,catalog]of Object.entries(catalogs)){
  if(JSON.stringify(Object.keys(catalog).sort())!==JSON.stringify(keys))throw Error('Locale key mismatch: '+lang);
  for(const key of keys){const values=forms(catalog[key]);if(!values.length||values.some(s=>typeof s!=='string'||!s.trim()))throw Error('Empty translation: '+lang+'/'+key);
   for(const value of values)if(params(value)!==params(forms(base[key])[0]))throw Error('Placeholder mismatch: '+lang+'/'+key);
  }
 }
 for(const [source,key]of Object.entries(legacy))if(!source||!Object.hasOwn(base,key))throw Error('Invalid legacy alias: '+source);
 return {manifest,catalogs,legacy};
}
function generate(check=false){const data=validate(),content='// Generated by tools/locales.cjs. Edit locales/*.json.\nconst LocaleCatalog='+JSON.stringify(data)+';\n',file=path.join(root,'src/i18n/catalogs.js');
 if(check){if(fs.readFileSync(file,'utf8')!==content)throw Error('Stale locale bundle');}else fs.writeFileSync(file,content);
 return {languages:data.manifest.locales.map(l=>l.id),keys:Object.keys(data.catalogs[data.manifest.default]).length,bytes:Buffer.byteLength(content)};
}
module.exports={validate,generate};if(require.main===module)console.log(generate(process.argv.includes('--check')));
