// Build only from a complete current-runtime regression gate and measured comparison.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]||path.join(root,'..','deliverables-stage-g'));process.chdir(root);fs.mkdirSync(out,{recursive:true});
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),read=file=>JSON.parse(fs.readFileSync(file)),runtimeSha256=sha(fs.readFileSync('js/game.js')),version=read('package.json').version;
const base=read('qa/stage-g-base/release_manifest.json'),baselineHash='f150417f1d5fa1899eb91fd2a2575d180848cd0322bcc41676f8306b27aee952';assert.equal(version,'0.38.0');assert.equal(base.version,'0.37.1');assert.equal(base.runtimeSha256,baselineHash);assert.equal(sha(fs.readFileSync('qa/stage-g-base/js/game.js')),baselineHash);
const summary=read('qa/results/summary.json'),checkpoint=read('qa/results/run-checkpoint.json'),perf=read('qa/results/stage-g-performance.json');
assert.ok(checkpoint.complete&&summary.passed&&summary.runtimeUnchanged&&!summary.filtered);assert.equal(summary.runtimeSha256,runtimeSha256);assert.equal(summary.version,version);assert.equal(summary.runs.length,62);for(const r of summary.runs){assert.equal(r.exitCode,0,r.id);assert.equal(r.runtimeSha256,runtimeSha256,r.id);}
for(const id of ['stage-g','stage-g-routes']){const r=read('qa/results/'+id+'.json');assert.equal(r.failed,0);assert.equal(r.runtimeSha256,runtimeSha256);assert.ok(r.passed>=33);}
assert.ok(perf.complete&&perf.runtimeUnchanged);assert.equal(perf.runtimeSha256,runtimeSha256);assert.equal(perf.baselineRuntimeSha256,baselineHash);assert.equal(perf.rows.length,13);
for(const f of base.files.filter(f=>f.file.startsWith('assets/')))assert.equal(sha(fs.readFileSync(f.file)),f.sha256,f.file+' accepted asset');
const reference=read('qa/stage-g-source-reference.json');for(const kind of ['changes','added'])for(const [file,hashes]of Object.entries(reference[kind]))assert.equal(sha(fs.readFileSync(file)),hashes.after,file+' source reference');
cp.execFileSync(process.execPath,['tools/build.cjs','--check'],{stdio:'inherit'});
const report='STAGE_G_REPORT_RU.md';assert.ok(fs.existsSync(report));assert.ok(!fs.readFileSync(report,'utf8').includes('<!-- FINAL_RESULTS -->'));
const proof={version,runtimeSha256,passed:true,baseline:'LAST_BASE_0.37.1_Stage_F_Final_GitHub_REUPLOAD.zip',baselineSha256:'3dc21f17f951fe26bf67847ac2db7fed7a74f095cb1ccf76f4d38257ac7b373d',baselineRuntimeSha256:baselineHash,regressionGroups:summary.runs.length,automatedAssertions:summary.automatedAssertions,allGroupsSameRuntime:true,fullRegressionRepeated:true,performanceRepeated:true,performanceReport:'qa/results/stage-g-performance.json',performanceLimitations:perf.limitations,performanceCompletedTasks:perf.rows.filter(r=>r.status==='PASS').length,performanceRetainedTasks:perf.retainedRows?.length||0,saveVersion:18,newMigration:'17→18',explorationSchema:1,explorationRevision:1,researchSchema:1,storySchema:1,chapterRevision:6,existingAssetsByteIdentical:true,officialIntroSha256:sha(fs.readFileSync('assets/video/last-base-intro.mp4')),sectors:12,physicalResearchSources:3,newFieldResearchDataTotal:36,oldRouteAccessPreserved:true,personalMapStateSeparate:true,networkTransportAdded:false,report,browserVisualQAPassed:false,physicalAudioVerified:false,level2Implemented:false,stageHStarted:false,nextStageStarted:false,manualAcceptance:'pending',limitations:summary.limitations};
fs.writeFileSync('qa/results/stage-g-release-validation.json',JSON.stringify(proof,null,2)+'\n');
function walk(dir=''){return fs.readdirSync(path.join(root,dir),{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name,'en')).flatMap(e=>{if(['node_modules','.git','.DS_Store','__pycache__'].includes(e.name))return [];const rel=path.posix.join(dir,e.name);if(e.isSymbolicLink())throw Error('Unexpected symlink '+rel);return e.isDirectory()?walk(rel):[rel];});}
const before=new Map(base.files.map(f=>[f.file,f.sha256])),changes=[],added=[];for(const name of walk()){if(['release_manifest.json','STAGE_G_CHANGESET.json'].includes(name))continue;const hash=sha(fs.readFileSync(name));if(!before.has(name))added.push({file:name,sha256:hash});else if(hash!==before.get(name))changes.push({file:name,before:before.get(name),after:hash});}const removed=[...before.keys()].filter(f=>!fs.existsSync(f));assert.deepEqual(removed,[]);fs.writeFileSync('STAGE_G_CHANGESET.json',JSON.stringify({version,baseline:'0.37.1 Stage F Final',changes,added,removed},null,2)+'\n');
const files=walk().filter(f=>f!=='release_manifest.json').map(file=>{const b=fs.readFileSync(file);return {file,bytes:b.length,sha256:sha(b)};});fs.writeFileSync('release_manifest.json',JSON.stringify({...proof,patch:'stage-g',builtAt:new Date().toISOString(),automatedGatePassed:true,validationReport:'qa/results/stage-g-release-validation.json',regressionSummary:'qa/results/summary.json',files},null,2)+'\n');
const stem='LAST_BASE_0.38.0_Stage_G',zip=path.join(out,stem+'_GitHub.zip');if(fs.existsSync(zip))throw Error('Refusing to overwrite an existing release');cp.execFileSync('zip',['-q','-9',zip,'-@'],{cwd:root,input:walk().join('\n')+'\n',maxBuffer:1024*1024});cp.execFileSync('unzip',['-tq',zip],{maxBuffer:1024*1024});
cp.execFileSync('python3',['-c',`import hashlib,json,pathlib,sys,zipfile
root=pathlib.Path(sys.argv[2])
with zipfile.ZipFile(sys.argv[1]) as z:
 assert z.testzip() is None
 m=json.loads(z.read('release_manifest.json'));names=z.namelist()
 assert len(names)==len(set(names))==len(m['files'])+1
 assert set(names)=={f['file'] for f in m['files']}|{'release_manifest.json'}
 for f in m['files']:
  b=z.read(f['file']);assert len(b)==f['bytes'] and hashlib.sha256(b).hexdigest()==f['sha256'],f['file']
  assert b==(root/f['file']).read_bytes(),f['file']
 assert z.read('release_manifest.json')==(root/'release_manifest.json').read_bytes()
`,zip,root],{maxBuffer:1024*1024});
const result={zip,bytes:fs.statSync(zip).size,sha256:sha(fs.readFileSync(zip)),files:files.length+1,crcPassed:true,allManifestHashesPassed:true,sourceTreeEqualityPassed:true,runtimeSha256,report:path.join(out,stem+'_Report_RU.md')};fs.copyFileSync(report,result.report);const verification=path.join(out,stem+'_Verification.json');fs.writeFileSync(verification,JSON.stringify({...proof,archive:result},null,2)+'\n');fs.writeFileSync(path.join(out,stem+'_SHA256.txt'),result.sha256+'  '+path.basename(zip)+'\n');console.log(JSON.stringify({...result,verification}));
