import json,pathlib
p=pathlib.Path('qa/results');read=lambda n:json.loads((p/(n+'.json')).read_text())
a=read('perf-before');b=read('perf-after');assert a['complete'] and b['complete'];before={r['id']:r for r in a['rows']}
labels={'idle':'0 Zombies, покой','ak_empty':'0 + AK непрерывно','m4_empty':'0 + M4 непрерывно','z10':'10 Zombies','z25':'25 Zombies','z50':'50 Zombies','z100':'100 Zombies (stress)','z25_ak':'25 + AK','z50_ak':'50 + AK','z50_turrets':'50 + Automatic/Heavy','z50_lights':'50 + Turrets + 2 Searchlights','offzone':'50 снаружи, Player в Bunker','return':'Возврат на Surface','offzone_combat':'I1: контактный бой у стены + турели','return_combat':'I1: возврат после контактного боя'}
rows=[]
for n in b['rows']:
 o=before.get(n['id']);row={'id':n['id'],'label':labels[n['id']]}
 if n.get('limitation')or not o or o.get('limitation'):row['limitation']=n.get('limitation')or(o or{}).get('limitation','missing baseline')
 else:
  row.update(before={k:o[k]for k in ['frame','update','renderAudio','heap','end']},after={k:n[k]for k in ['frame','update','renderAudio','heap','end']},frameMedianChangePercent=(n['frame']['p50']/o['frame']['p50']-1)*100,updateMedianChangePercent=(n['update']['p50']/o['update']['p50']-1)*100)
 rows.append(row)
comparison={'baselineRuntimeSha256':a['runtimeSha256'],'runtimeSha256':b['runtimeSha256'],'scope':b['scope'],'method':'Final isolated sequential before and after. Initial profiled baseline and first after series (overlapping targeted QA rechecks) retained. Lower ms is better. No phone/browser FPS inference.','rows':rows}
(p/'perf-comparison.json').write_text(json.dumps(comparison,ensure_ascii=False,indent=2)+'\n')
summary=read('summary');assert summary['passed'];out=['## Итоговые результаты',f"Полный regression pass: **{len(summary['runs'])} групп, {summary['automatedAssertions']:,} проверок, 0 ошибок**. Все child runs относятся к одному runtime SHA-256 `{summary['runtimeSha256']}`. Дополнительно: 25 проверок настоящего улучшения Hammer на станке, с пятью границами Save/Load. Финальный ZIP содержит машинные отчёты, изменения тестовых ожиданий и цепочку исходных hashes.", 'Сначала выполнены все regression/rechecks, затем итоговая изолированная пара замеров. В исходной первой серии off-zone враги подходили с другой стороны базы, поэтому турели не стреляли в трёхсекундном окне. Эта серия не удалена; дополнительно введены **две одинаковые before/after контактные сцены**, где есть реальные выстрелы и повреждение стены.','### Время кадра на стенде, ms','| Сценарий | До: median / p95 | После: median / p95 | Δ median |','|---|---:|---:|---:|']
for r in rows:
 if r.get('limitation'):out.append('| '+r['label']+' | — | limitation: '+r['limitation'][:120]+' | — |');continue
 o,n=r['before'],r['after'];out.append(f"| {r['label']} | {o['frame']['p50']:.2f} / {o['frame']['p95']:.2f} | {n['frame']['p50']:.2f} / {n['frame']['p95']:.2f} | {r['frameMedianChangePercent']:+.1f}% |")
out+=['Отрицательная Δ — меньше времени; положительная — ухудшение. Один короткий запуск не позволяет оценить статистическую значимость малых процентов или тепловой throttling телефона.','### Update и Audio/render/flush, median ms','| Сценарий | Update до → после | Audio/render/flush до → после |','|---|---:|---:|']
for r in rows:
 if r.get('limitation'):continue
 o,n=r['before'],r['after'];out.append(f"| {r['label']} | {o['update']['p50']:.2f} → {n['update']['p50']:.2f} | {o['renderAudio']['p50']:.2f} → {n['renderAudio']['p50']:.2f} |")
profiles=read('perf-subsystems')['profiles'];sub={r['report']:r for r in profiles if r['id']=='z50_lights'and r['report']in['before','after']}
out+=['### Разделение CPU: 50 Zombies + турели + прожекторы','Ниже sampled **inclusive CPU ms на кадр** за 180 кадров, включая прогрев. Категории перекрываются, их нельзя складывать или приравнивать к wall-clock median. Нативные Canvas calls не всегда сохраняют JS stack в профиле.','| Подсистема | До | После |','|---|---:|---:|']
for k,label in [('enemy AI/update','Zombie AI/update'),('pathfinding','Pathfinding'),('enemy target decision','Выбор цели/пролома врага'),('world collision','World collision'),('turret targeting/update','Turret target/update'),('LOS/raycast','LOS/raycast'),('weapon firing','Weapon firing (в этой сцене Player не стреляет)'),('projectiles/hits','Projectiles/hits'),('muzzle/effects','Muzzle/effects'),('animations + actor render','Animations + actor render'),('HP indicators','HP indicators'),('audio','Audio JS'),('lighting/shadows','Lighting/shadows'),('render','Render JS inclusive'),('state allocation/validation/power','State cloning/validation/power allocation'),('V8 GC','V8 GC'),('native Canvas/host (custom_gc, NOT V8 GC)','Native Canvas/host custom_gc — НЕ JS GC')]:
 out.append(f"| {label} | {sub.get('before',{}).get('inclusiveMs',{}).get(k,0)/180:.3f} | {sub.get('after',{}).get('inclusiveMs',{}).get(k,0)/180:.3f} |")
out+=['Отдельный таймер separation в instrumented копии этой сцены:']
for label in ['before-detail','after-detail']:
 r=next((r for r in profiles if r['report']==label and r['id']=='z50_lights'),None)
 if r and r.get('separationTimer'):out.append(f"- {label}: {r['separationTimer']['ms']/180:.3f} ms/кадр, {r['separationTimer']['calls']} исполнений блока.")
out+=['В текущем пути Zombie используется локальное движение/обход, а не полноценный A* на каждого врага. Нулевой sampled pathfinding означает отсутствие/порог дискретизации в этой сцене, а не отключение Player navigation. Shot pipeline отдельно записан в профилях `ak_empty`, `m4_empty`, `z25_ak`, `z50_ak`; все `.cpuprofile` сохранены. Высокая стоимость `matches/querySelectorAll` принадлежит моделируемому DOM стенда и не оптимизировалась как будто это код телефона.','### Что осталось дорогим','Направленный свет/тени и нативная отрисовка продолжают занимать заметную долю времени. Они не отключены. Тяжёлая сцена не стала гарантированно укладываться в 16,7 ms; численные улучшения стенда не заменяют проверку на телефоне. Кеш спрайтов меняет повторную растеризацию на ограниченную дополнительную память (до 12 MiB). `heap` в JSON — JS heap процесса до/после GC; он не включает полную память изображений/GPU и не выдаётся за RAM телефона.','### Сохранённые серии и ограничения','- `perf-before-first-series.json`: исходное профилирование до оптимизации; все его результаты сохранены.','- `perf-after-first-series.json`: первая серия candidate, часть пересеклась с targeted QA rechecks; не использована как итоговое изолированное сравнение.','- `perf-before.json`, `perf-after.json`: полная итоговая изолированная пара, 15 сцен.','- `perf-pilot.json`: три промежуточных сценария раннего runtime, не финальные цифры.','- `perf-before-short-initial.json` и `perf-before-initial-fixture.json`: первоначальные короткие/неполные fixtures; в первом M4 успевал только начать reload, во втором был исправлен аргумент DEV выдачи Buildable. Они сохранены как история измерений.','- `perf-*-detail.json`: инструментированная стоимость separation и V8 profiles; frame time содержит overhead инструмента.','- `perf-subsystems.json`, `perf-comparison.json`: развёрнутые результаты, p95/mean/heap/состояние боя.','- В `perf-initial-pass` / `perf-intermediate-pass` сохранены промежуточные неуспешные/смешанные по runtime прогоны. Выпуск опирается исключительно на финальный `summary.json`, где runtime неизменен.']
# All unfavorable prior numbers are explicit as well as preserved in raw reports.
out+=['### Предварительные серии: median frame ms (не итоговый A/B)','| Сценарий | Исходная первая серия | Candidate первая серия |','|---|---:|---:|']
old={r['id']:r for r in read('perf-before-first-series')['rows']};prior={r['id']:r for r in read('perf-after-first-series')['rows']}
for k in labels:
 f=lambda r:f"{r['frame']['p50']:.2f}"if r and 'frame'in r else '—'
 out.append(f"| {labels[k]} | {f(old.get(k))} | {f(prior.get(k))} |")
report=pathlib.Path('PERFORMANCE_GAMEPLAY_REPORT_RU.md');s=report.read_text();assert '<!-- FINAL_RESULTS -->'in s;report.write_text(s.replace('<!-- FINAL_RESULTS -->','\n'.join(out)))
print('Comparison/report finalized',len(rows),'scenarios')
