/* Deliberately compact QA console. One responsive UI on PC / touch devices. */
window.GameDevUI=(()=>{
 const text=(ru,en)=>I18n.language==='ru'?ru:en;
 const node=(tag,label)=>{const n=document.createElement(tag);if(label)n.textContent=label;return n;};
 const version=node('button','LAST BASE 0.40.1');version.id='qaVersion';version.type='button';version.setAttribute('data-i18n-skip','');version.style.cssText='background:transparent;border:0;color:#9aabaa;font-size:11px;padding:10px;min-height:36px';
 el('settingsOverlay').querySelector('.panel').append(version);
 const badge=node('button','DEV/TEST');badge.id='qaBadge';badge.type='button';badge.hidden=true;badge.setAttribute('data-i18n-skip','');document.body.append(badge);
 const live=node('div');live.id='qaLiveMetrics';live.hidden=true;live.setAttribute('data-i18n-skip','');document.body.append(live);
 let taps=0,lastTap=0,panel=null,body=null,status=null,measure=null,tab='time',lastSample=0,lastFrame=0,fps=0;
 const errors={disabled:['DEV выключен','DEV is disabled'],session:['Сначала откройте игру и закройте Intro','Start a game and finish Intro first'],slots:['Нет свободного слота. Освободите один слот для тестовой копии.','No free slot. Free one slot for a test copy.'],copy:['Не удалось создать копию. Исходный слот сохранён.','Copy failed. Original slot is preserved.'],clock:['Этот браузер не поддерживает часы DEV','DEV clock is unavailable in this browser'],paused:['Игра на паузе','Game is paused'],selection:['Недопустимый выбор','Invalid selection'],limit:['Достигнут лимит экземпляров / врагов / ячеек','Instance / enemy / slot limit reached'],inventory:['Рюкзак заполнен','Backpack is full'],space:['Нет свободного безопасного места','No safe placement space'],surface:['Для сценария выйдите на Surface, на землю','Go to Surface ground level for this scenario'],backward:['Только вперёд. Для раннего этапа создайте новую тестовую игру.','Forward only. Use a fresh test game for an earlier stage.'],prerequisite:['Не удалось подготовить существующие prerequisites','Could not prepare existing prerequisites'],actor_denied:['Команда недоступна этому игроку','Actor denied'],stale_revision:['Состояние изменилось. Повторите действие.','State changed. Try again.']};
 const label=id=>{const s=errors[id];return s?text(...s):text('Команда отклонена','Command rejected');};
 function report(r){if(!status)return;status.textContent=r.ok?(r.notice?label(r.notice):text('Готово','Done'))+(r.count!==undefined?' · '+r.count:'')+(r.turrets?' · '+text('турели: ','turrets: ')+r.turrets:'')+(r.skipped?' · '+text('занятые участки пропущены: ','occupied sections skipped: ')+r.skipped:''):label(r.reason);}
 const action=(a,p={})=>{const r=GameDevQA.request(a,p);report(r);return r;};
 function button(ru,en,fn){const b=node('button',text(ru,en));b.type='button';b.addEventListener('click',fn);return b;}
 function row(...children){const r=node('div');r.className='qaRow';r.append(...children);body.append(r);return r;}
 function note(ru,en){body.append(node('p',text(ru,en)));}
 function select(id,items){const s=node('select');s.id=id;s.setAttribute('aria-label',id);for(const [value,title]of items){const o=node('option',title);o.value=value;s.append(o);}s.value=items[0]?.[0]||'';return s;}
 function build(){
  body.replaceChildren();if(!GameDevQA.enabled){note('DEV создаёт отдельную копию в свободном слоте. Оригинал не изменяется. Метка DEV/TEST сохраняется и после выключения режима.','DEV creates a separate copy in a free slot. Original is preserved. DEV/TEST remains after disabling the mode.');row(button(GameDevQA.marked?'Включить DEV':'Создать тестовую копию',GameDevQA.marked?'Enable DEV':'Create test copy',()=>{report(GameDevQA.enable());build();refresh();}));return;}
  const tabs=select('qaTabs',[['time',text('Время','Time')],['enemies',text('Враги','Enemies')],['resources',text('Ресурсы / предметы','Resources / items')],['equipment',text('Оборудование','Equipment')],['base',text('Игрок / база','Player / base')],['progress',text('Прогресс','Progression')],['stress','I1 STRESS TEST']]);tabs.value=tab;tabs.addEventListener('change',()=>{tab=tabs.value;build();});row(tabs,button('Выключить DEV','Disable DEV',()=>{GameDevQA.disable();build();}));
  if(tab==='time'){
   row(...[[60,'+1 час','+1 hour'],[360,'+6 часов','+6 hours'],[1440,'+1 день','+1 day']].map(([m,ru,en])=>button(ru,en,()=>action('time',{minutes:m}))));
   const day=node('input');day.type='number';day.min='1';day.max='10000';day.value=String(WorldClock.day+1);day.inputMode='numeric';day.setAttribute('aria-label',text('Игровой день','Game day'));row(day,button('Перейти к дню','Go to day',()=>action('time',{day:Number(day.value)})));
   row(...[1,10,50,'MAX'].map(v=>button(v==='MAX'?'MAX':'×'+v,v==='MAX'?'MAX':'×'+v,()=>action('speed',{value:v}))));
   row(button('К ночи','Next night',()=>action('time',{night:true})),button('Следующий Day X','Next Day X',()=>action('time',{dayX:true})),button('Стоп / ×1','Stop / ×1',()=>action('stop')));
   note('Переход выполняет реальные игровые шаги. Во время ожидания возможны бой и смерть. MAX ограничен нагрузкой; цель ×50 не гарантирует ×50 на каждом устройстве. Прогресс можно остановить.','Fast-forward runs real game steps. Combat and death remain possible. MAX is CPU-budgeted; ×50 is a target, not a device guarantee. You can stop at any point.');
  }else if(tab==='enemies'){
   const types=select('qaEnemy',[['mixed',text('Смешанные','Mixed')],...Object.entries(V017Monsters.specs).map(([id,s])=>[id,I18n.text(s.name)])]);row(types);row(...[1,10,25,50].map(count=>button('Создать '+count,'Spawn '+count,()=>action('spawn',{count,type:types.value}))));
   row(button('Атака · 25','Attack · 25',()=>action('attack',{kind:'normal'})),button('Тяжёлая · 50','Heavy · 50',()=>action('attack',{kind:'heavy'})),button('Убрать тестовых врагов','Clear test enemies',()=>action('clear')));
   note('Атаки используют существующую осаду Day X: обычная — 25 смешанных, тяжёлая — 50 громил. Очистка убирает только созданных DEV врагов без наград и взрывов.','Attacks use the existing Day X siege: regular = 25 mixed; heavy = 50 brutes. Clear removes only DEV-spawned enemies, without rewards or explosions.');
   row(button('Вернуть события календарю','Return events to calendar',()=>action('event',{id:'day_x',value:null})));
  }else if(tab==='resources'){
   const first=['wood','stone','iron','copper','coal','fuel','concrete','ammo'],all=GameDevQA.catalog.resources(),ids=[...first.filter(t=>all.includes(t)),...all.filter(t=>!first.includes(t))];
   const items=select('qaResource',ids.map(t=>[t,I18n.text(ITEM[t].name)]));row(items);row(...[10,100,1000].map(amount=>button('+'+amount,'+'+amount,()=>action('resource',{id:items.value,amount}))));note('Предметы занимают настоящие ячейки. Если места мало, выдаётся только вместившееся количество.','Items use real slots. If space is limited, only the amount that fits is granted.');
  }else if(tab==='equipment'){
   const ids=GameDevQA.catalog.buildables(),s=select('qaBuildable',ids.map(t=>[t,I18n.t('build.type.'+t)]));row(s,button('Выдать в Inventory','Grant to inventory',()=>action('buildable',{id:s.value})));
   note('Настоящий type → instance → Inventory → Place. Лимиты типов сохранены: второй экземпляр singleton-генератора или бака не создаётся. Для переноса существующего используйте Pick Up.','Real type → instance → Inventory → Place. Type limits stay intact: no duplicate singleton generator or tank. Use Pick Up to move an existing one.');
  }else if(tab==='base'){
   row(button('Вылечить Player','Heal player',()=>action('heal')),button('Заполнить бак','Fill fuel tank',()=>action('fuel')),button('Зарядить Battery','Charge battery',()=>action('battery')),button('Восстановить Power','Restore power',()=>action('power')),button('Repair Base','Repair base',()=>action('repair')));
   const walls=select('qaWall',[...V018Build.structures.values()].filter(r=>r.kind==='wall').map(r=>[r.id,(r.object.side||r.object.group)+' · '+r.id+' · '+Math.ceil(r.object.hp)+' HP']));row(walls);row(button('−50% HP','−50% HP',()=>action('wall',{id:walls.value,fraction:.5})),button('Разрушить','Destroy',()=>action('wall',{id:walls.value,fraction:1})));
   note('Power заполняет топливо, заряжает батарею и включает установленный генератор. Потребители сохраняют свои переключатели. Repair не замуровывает занятые проходы.','Power fills fuel, charges the battery and starts the installed generator. Consumers keep their switches. Repair skips occupied openings.');
  }else if(tab==='progress'){
   const ch=select('qaChapter',GameCampaign.definitions.chapters.map(c=>[c.id,I18n.t(c.title)]));row(ch,button('Открыть этап','Open chapter',()=>action('chapter',{id:ch.value})));
   const re=select('qaResearch',ResearchDefinitions.research.map(r=>[r.id,I18n.t(r.title)]));row(re,button('Открыть Research','Unlock research',()=>action('research',{id:re.value})));
   const bp=select('qaBlueprint',ResearchDefinitions.blueprints.map(r=>[r.id,I18n.t(r.title)]));row(bp,button('Получить чертёж','Discover blueprint',()=>action('blueprint',{id:bp.value})));
   const ev=select('qaEvent',WorldEvents.definitions().map(r=>[r.id,r.id==='day_x'?'Day X':r.id]));row(ev,button('Запустить событие','Start event',()=>action('event',{id:ev.value,value:true})),button('По календарю','Use calendar',()=>action('event',{id:ev.value,value:null})));
   note('Только существующий контент. Research готовит необходимые локальные источники и при необходимости завершает Chapter 1 в тестовой копии. Unlock не выдаёт бесплатное оборудование.','Existing content only. Research prepares required local sources and, when needed, completes Chapter 1 in the test copy. Unlock does not grant free equipment.');
  }else{
   note('Выйдите на Surface, на землю. Сценарий выдаст и разместит до 3 турелей в допустимых местах, загрузит реальные боеприпасы, восстановит питание и создаст 50 врагов осады. Затем можно обычным способом уйти в Bunker.','Go to Surface ground level. The scenario grants and places up to 3 turrets in valid positions, loads real ammo, restores power and spawns 50 siege enemies. Then enter Bunker normally.');
   row(button('ЗАПУСТИТЬ I1 STRESS TEST','START I1 STRESS TEST',()=>action('stress')),button('Очистить тестовых врагов','Clear test enemies',()=>action('clear')),button('По календарю','Use calendar',()=>action('event',{id:'day_x',value:null})));
   note('Показатель «вне зоны» считает живых врагов и работающие турели вне области Player. Это количество объектов, не отдельная симуляция.','Off-zone counts living enemies and powered turrets outside the player area. It is an entity count, not a separate simulation.');
  }
 }
 function mount(){if(panel)return;panel=v09Overlay('qaOverlay','DEV / QA');panel.setAttribute('data-i18n-skip','');body=panel.querySelector('.v09Body');status=node('p');status.id='qaStatus';status.setAttribute('role','status');measure=node('p');measure.id='qaMetrics';panel.querySelector('.v09Header').after(measure);measure.after(status);}
 function open(){mount();build();closeOverlay(el('settingsOverlay'));openOverlay(panel);refresh();}
 version.addEventListener('click',()=>{const now=GameDevQA.rawNow();taps=now-lastTap<4000?taps+1:1;lastTap=now;if(taps>=6){taps=0;open();}});
 badge.addEventListener('click',()=>{if(GameDevQA.enabled)open();});
 function refresh(){live.hidden=!GameDevQA.enabled;badge.hidden=!GameDevQA.marked;badge.textContent=GameDevQA.enabled?'DEV/TEST · QA':'DEV/TEST';if(panel)sample(GameDevQA.rawNow(),true);}
 function sample(timestamp,force=false){if(!GameDevQA.marked&&!GameDevQA.enabled)return;if(lastFrame&&timestamp>lastFrame)fps=fps?fps*.9+1000/(timestamp-lastFrame)*.1:1000/(timestamp-lastFrame);lastFrame=timestamp;
  if(!force&&timestamp-lastSample<500)return;lastSample=timestamp;if(!measure)return;
  if(!GameDevQA.enabled){measure.textContent=text('DEV выключен · сохранение остаётся DEV/TEST','DEV disabled · save remains DEV/TEST');return;}
  const m=GameDevQA.metrics();live.textContent=measure.textContent='FPS '+Math.round(fps)+' · '+text('враги ','enemies ')+m.activeEnemies+'/'+m.enemies+' · '+text('вне зоны ','off-zone ')+m.offZone+' · '+text('турели ','turrets ')+m.activeTurrets+' · update '+m.updateMs.toFixed(1)+' ms · ×'+m.actualRate.toFixed(1)+' / '+m.rate+(m.target?' · '+text('цель: день ','target: day ')+Math.floor(m.target/1440):'')+' · '+text('сейчас день ','now day ')+WorldClock.day+' '+Math.floor(WorldClock.minute/60)+':'+String(Math.floor(WorldClock.minute%60)).padStart(2,'0');
 }
 I18n.onChange(()=>{if(panel){build();refresh();}});
 v09Style(`#qaBadge{position:fixed;z-index:14000;top:calc(30px + max(env(safe-area-inset-top),var(--tg-content-safe-area-inset-top,0px)));right:max(8px,env(safe-area-inset-right));background:#5a451ddd;color:#ffe7a6;border:1px solid #d5ba76;border-radius:6px;padding:5px 9px;font:11px Arial;min-height:30px}#qaBadge[hidden],#qaLiveMetrics[hidden]{display:none!important}#qaLiveMetrics{position:fixed;pointer-events:none;z-index:14000;top:calc(67px + max(env(safe-area-inset-top),var(--tg-content-safe-area-inset-top,0px)));right:max(8px,env(safe-area-inset-right));width:min(225px,55vw);padding:5px;background:#10201bd9;color:#dfeacf;border-radius:5px;font:10px/1.45 monospace;font-variant-numeric:tabular-nums}#qaOverlay{z-index:15000}#qaOverlay .panel{box-sizing:border-box;width:min(600px,calc(100vw - 16px));height:min(660px,calc(100dvh - 28px - env(safe-area-inset-top) - env(safe-area-inset-bottom) - var(--tg-content-safe-area-inset-top,0px)));margin:0;padding:12px;display:flex;flex-direction:column;overflow:hidden}#qaOverlay .v09Header{flex:none;margin-bottom:4px;padding-bottom:4px}#qaOverlay .v09Body{overflow:auto;min-height:0;overscroll-behavior:contain;touch-action:pan-y}#qaOverlay p{font-size:12px;line-height:1.4;margin:6px 0}#qaMetrics{flex:none;color:#cbe4bb;font-variant-numeric:tabular-nums}#qaStatus{flex:none;min-height:18px;color:#ffd895}.qaRow{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0}.qaRow button,.qaRow input,.qaRow select{box-sizing:border-box;flex:1 1 90px;min-width:0;min-height:42px;max-width:100%;padding:7px;background:#233b40;color:#e9f1e8;border:1px solid #61756d;border-radius:5px;font-size:14px;touch-action:manipulation}.qaRow select{flex-basis:100%;font-size:16px}.qaRow input{font-size:16px;width:100px}@media(max-height:500px){#qaOverlay .panel{height:calc(100dvh - 12px - env(safe-area-inset-bottom));padding:8px}#qaOverlay .v09Title{font-size:16px}#qaOverlay p{font-size:11px;margin:3px 0}}`);
 return Object.freeze({open,refresh,sample});
})();
