/* Pass A adds floor/save/water/spoil state; existing farm and command owners stay authoritative. */
window.BunkerPassA=(()=>{
 const B=GameplayBalance.farm,copy=x=>JSON.parse(JSON.stringify(x)),tr=(k,p)=>I18n.t('farm.'+k,p),fresh=()=>({readyAt:null,rotten:false,warned:false});
 const water={clean:0,produced:0};let rot=Array.from({length:5},fresh),at=AgricultureTime.now(),seq=0,recovered=[];
 const tank={id:'clean_water_tank',kind:'clean_water',x:4832,y:-48,w:104,h:105,range:58},fixtures=[tank,{id:'water_pump',x:4822,y:120,w:48,h:64},{id:'water_purifier',x:4893,y:120,w:55,h:64}];
 function readyAt(i,n){if(rot[i].readyAt===null)rot[i].readyAt=n;}
 const rotten=i=>rot[i]?.rotten===true,remaining=i=>rot[i].readyAt===null?null:Math.max(0,rot[i].readyAt+B.spoilDays*WorldClock.dayMs-AgricultureTime.now());
 function tick(){const now=AgricultureTime.now(),dt=Math.max(0,now-at);at=now;if(GameSave.restoring||GameFlow.paused||document.hidden||playerDead)return;
  if(dt&&devicePowered('water_system')){const n=Math.min(B.cleanCapacity-water.clean,dt/WorldClock.dayMs*B.waterPerDay);water.clean+=n;water.produced+=n;}
  if(devicePowered('water_system')){const n=Math.min(water.clean,B.waterCapacity-V011Farm.state.water);water.clean-=n;V011Farm.state.water+=n;}
  V011Farm.settle(now);for(let i=0;i<5;i++){if(farmState[i].crop===null){rot[i]=fresh();continue;}if(!V011Farm.ready(i))continue;readyAt(i,now);const left=remaining(i);if(left<=0)rot[i].rotten=true;else if(left<=B.warnDays*WorldClock.dayMs&&!rot[i].warned){rot[i].warned=true;V010.log(tr('spoilWarning',{n:i+1}));}}
 }
 function roomFor(type,n){let free=0;for(let i=0;i<BAG_SLOTS;i++){const s=bag[i];free+=!s?itemStackLimit(type,true):s.type===type?itemStackLimit(type,true)-s.qty:0;}return free>=n;}
 const commands=EquipmentCommands.create({get:id=>id==='water'||/^bed[0-4]$/.test(id)||/^discard:\d+$/.test(id)?{id}:null},{actor:id=>GameActors.get(id),authorized:a=>a.id===GameActors.localId,access(a,r){if(a.dead)return false;if(r.id.startsWith('discard:'))return true;const b=r.id==='water'?tank:getFarmBeds()[Number(r.id.slice(3))];return a.scene==='bunker'&&b&&rectHit(a.entity.x,a.entity.y,75,b);},perform(c){tick();
  if(c.action==='collect'&&c.instanceId==='water'){const n=Math.min(Math.floor(water.clean),Math.max(1,Math.min(100,Math.floor(c.payload?.amount||1))));if(!n)return {ok:false,reason:'empty'};if(!roomFor('water',n))return {ok:false,reason:'space'};addItem('water',n);water.clean-=n;return {ok:true,amount:n};}
  if(c.action==='clear'&&/^bed[0-4]$/.test(c.instanceId)){const i=Number(c.instanceId.slice(3));if(!rotten(i))return {ok:false,reason:'state'};const n=Math.ceil(V011Farm.plants(farmState[i]).filter(p=>p.planted&&!p.harvested).length/4);if(!roomFor('plant_waste',n))return {ok:false,reason:'space'};addItem('plant_waste',n);farmState[i]={crop:null,plantedAt:0};rot[i]=fresh();return {ok:true,amount:n};}
  if(c.action==='discard'&&c.instanceId.startsWith('discard:')){const i=Number(c.instanceId.slice(8)),s=bag[i];if(!s||!ITEM[s.type]?.discardable||s.type!==c.payload?.type||s.qty!==c.payload?.qty)return {ok:false,reason:'state'};bag[i]=null;return {ok:true};}return {ok:false,reason:'state'};
 },changed(){queueGameSave();renderBag();}});
 function request(id,action,payload={}){if(GameFlow.paused)return {ok:false,reason:'paused'};const r=commands.execute({actorId:GameActors.localId,instanceId:id,action,payload,expectedRevision:commands.revision,requestId:'bunker-a:'+commands.revision+':'+(++seq)});if(!r.ok)message(tr(r.reason==='space'?'space':r.reason==='empty'?'tankEmpty':'unavailable'));return r;}
 function openTank(){tick();const o=v09Overlay('cleanWater043',tr('cleanTank')),b=o.querySelector('.v09Body');b.innerHTML='';const p=document.createElement('p');p.textContent=tr('tankStatus',{n:Math.floor(water.clean),buffer:Math.floor(V011Farm.state.water)});b.append(p);for(const n of [1,5,10])b.append(v09Button(tr('collect',{n}),()=>{request('water','collect',{amount:n});openTank();}));openOverlay(o);}
 const up={id:'stairs_l2_up',kind:'bunker_floor',x:4635,y:-385,w:130,h:175,range:75};
 function go(floor){if(scene!=='bunker'||GameFlow.paused||playerDead||![1,2].includes(floor))return false;const from=BunkerLayout.floorAt(player.x,player.y);if(from===floor||!rectHit(player.x,player.y,75,from===1?BunkerLayout.stairs[1]:up))return false;stopControls();cancelNavigation();V014Controls.stopRoute();V011Living.stop();window.GamePlacementUI?.cancel();Object.assign(player,floor===2?{x:4700,y:-160}:{x:1300,y:-170});player.floor=floor;player.wallLevel=false;const d=V014Robots.state;if(!d.packed&&d.scene==='bunker'&&d.task==='follow'){d.x=player.x+38;d.y=player.y+38;V014Robots.motion.reset();}CommandCoreUI.syncLocation();const v=V010Camera.view();camera.x=player.x-v.w/2;camera.y=player.y-v.h/2;invalidateGeometry();V091Light.invalidate();queueGameSave();return true;}
 const oldObjects=interactionObjects;interactionObjects=function(s=scene){const a=oldObjects(s);return s==='bunker'?a.filter(o=>!BunkerLayout.removed(o.id)).concat({...tank,name:tr('cleanTank')},{...up,name:I18n.t('bunker.l2.up')}):a;};
 const oldSolids=solidObjects;solidObjects=function(s){const a=oldSolids(s);return s==='bunker'?a.filter(o=>!BunkerLayout.removed(o.id)).concat(fixtures):a;};
 const oldExecute=executeInteraction;executeInteraction=function(o){if(o?.id===up.id){if(canInteract(o,player.x,player.y))go(1);return;}if(o?.id===tank.id){if(canInteract(o,player.x,player.y))openTank();return;}return oldExecute(o);};
 function capture(){return {schema:1,floor:scene==='bunker'?BunkerLayout.floorAt(player.x,player.y):1,water:copy(water),rot:copy(rot),recovered:copy(recovered),commands:commands.capture()};}
 function validate(d){const s=d.bunker043;if(!s||s.schema!==1||![1,2].includes(s.floor)||!s.water||!Number.isFinite(s.water.clean)||s.water.clean<0||s.water.clean>B.cleanCapacity+1e-6||!Number.isFinite(s.water.produced)||s.water.produced<0||!Array.isArray(s.rot)||s.rot.length!==5||!Array.isArray(s.recovered)||s.recovered.length>192||s.recovered.some(id=>!d.equipment032.instances.some(r=>r.id===id)))throw Error('Invalid Pass A');if(d.player.scene==='bunker'&&s.floor!==BunkerLayout.floorAt(d.player.x,d.player.y))throw Error('Invalid floor');for(const r of s.rot)if(!r||typeof r.rotten!=='boolean'||typeof r.warned!=='boolean'||r.readyAt!==null&&(!Number.isFinite(r.readyAt)||r.readyAt<0||r.readyAt>d.bunker030.agricultureAt)||r.rotten&&r.readyAt===null)throw Error('Invalid spoil clock');commands.validate(s.commands);}
 function migrate(d){if(d.bunker043)return;const clock=d.bunker030.agricultureAt,s=d.bunker043={schema:1,floor:1,water:{clean:0,produced:0},rot:Array.from({length:5},fresh),recovered:[],commands:{revision:0,receipts:[]}};
  if(d.farmV011){const n=d.farmV011.water;d.farmV011.water=Math.min(B.waterCapacity,n);s.water.clean=Math.min(B.cleanCapacity,Math.max(0,n-B.waterCapacity));d.farmV011.at=clock;}
  for(let i=0;i<5;i++){const f=d.farm[i];if(f.crop===null)continue;const old=FARM_CROP_MINUTES[f.crop]*60000,total=farmGrowMs(f.crop),n=B.crops[farmCrops[f.crop].itemType].yield;f.elapsedMs=Math.min(total,Math.max(0,f.elapsedMs/old*total));if(d.farmV011)d.farmV011.grown[i]=Math.min(total,d.farmV011.grown[i]/old*total);const a=d.farm014?.beds[i];if(a){const keep=a.filter(p=>p.planted&&!p.harvested).slice(0,n);for(const p of keep){const ratio=p.elapsed/p.duration,v=Math.max(.9,Math.min(1.1,p.duration/old));p.duration=Math.round(total*v);p.elapsed=p.duration*ratio;p.qty=1;}d.farm014.beds[i]=Array.from({length:50},(_,j)=>keep[j]||{planted:false,harvested:true,elapsed:0,duration:0,qty:1});if(keep.length&&keep.every(p=>p.elapsed>=p.duration))s.rot[i].readyAt=clock;if(d.farm014.irrigation)d.farm014.irrigation[i]=null;}}
  const p=d.v09.power;for(const id of Object.keys(V09Power.rooms))if(!Object.hasOwn(p.roomEnabled,id))p.roomEnabled[id]=true;
  const keys=new Set([...Object.keys(V09Power.devices).filter(id=>!GameEquipment.get(id)?.refs.device),...d.equipment032.instances.map(r=>r.refs.device).filter(Boolean)]);for(const id of keys)if(!Object.hasOwn(p.deviceEnabled,id))p.deviceEnabled[id]=true;
  for(const x of v09Doors)if(!p.doors.some(v=>v.id===x.id))p.doors.push({id:x.id,open:0,away:0,manual:false});for(const x of V018Build.doorRecords)if(!d.building018.doors.some(v=>v.id===x.id))d.building018.doors.push({id:x.id,level:1,hp:V018Build.definition(x).levels[1]});
  const seeds=new Map(EquipmentInstances.defaults.map(r=>[r.id,r]));
  for(const r of d.equipment032.instances){const seed=seeds.get(r.id),old=EquipmentInstances.legacyDefaults.find(v=>v.id===r.id),authored=old&&['x','y','room'].every(k=>r.transform[k]===old.transform[k]);
   if(authored&&seed&&(/^chest[0-9]$/.test(r.id)||r.id==='feed_craft')){r.transform=copy(seed.transform);continue;}
   const room=r.transform.room,displaced=['room4','room6','room7','reserve_l1','storage','farm'].includes(room)||room==='corridor'&&(r.transform.y>750||r.transform.x<1390&&r.transform.x+EquipmentInstances.definitions[r.typeId].footprint.w>1030&&r.transform.y<410&&r.transform.y+EquipmentInstances.definitions[r.typeId].footprint.h>130);
   if(r.placement==='installed'&&displaced){r.placement='packed';r.ownerId=d.identity027?.playerId||'player:1';r.state.settings.layoutRecovery=true;s.recovered.push(r.id);}const rule=EquipmentInstances.placement[r.typeId];if(rule&&!rule.rooms.includes(r.transform.room))r.transform.room=rule.rooms[0];
  }
  const slots=ITEM[d.equipment.backpack.type].capacity;for(const id of s.recovered){if(d.bag.some(v=>v?.instanceId===id)||d.carry0353.legacyOverflow.includes(id))continue;let i=0;while(i<slots&&d.bag[i])i++;if(i<slots)d.bag[i]=GameCarried.token(id);else d.carry0353.legacyOverflow.push(id);}
  if(d.player.scene==='bunker'&&(d.player.x>=3500||d.player.y>750||d.player.x<810&&d.player.y>260||d.player.x>1610&&d.player.y>260))Object.assign(d.player,BunkerLayout.arrivals[0]);if(d.player.scene==='bunker'){d.v091.fortress.x=d.player.x;d.v091.fortress.y=d.player.y;}
 }
 GameState.register('bunkerPassA',{capture},{source:'base/pass-a.js',saved:['bunker043'],transient:['local request sequence','water tick cursor']});
 GameSave.extend('capture','bunker.pass-a',function(previous){tick();const d=previous();d.bunker043=capture();return d;});
 GameSave.extend('decode','bunker.pass-a',function(previous,raw){const d=previous(raw);validate(d);return d;});
 GameSave.extend('restore','bunker.pass-a',function(previous,d){validate(d);Object.assign(water,d.bunker043.water);rot=copy(d.bunker043.rot);recovered=copy(d.bunker043.recovered);AgricultureTime.restore(d.bunker030.agricultureAt);at=AgricultureTime.now();const result=previous(d);player.floor=d.bunker043.floor;commands.restore(d.bunker043.commands);if(recovered.length){message(tr('recovered',{n:recovered.length}));recovered=[];}return result;});
 const oldDetails=V011UI.details;V011UI.details=function(where,index){oldDetails(where,index);const s=where==='bag'&&bag[index];if(!s||!ITEM[s.type]?.discardable)return;const payload={type:s.type,qty:s.qty};el('v010ItemDetails').querySelector('.v011ItemActions').append(v09Button(tr('discard'),()=>{const o=v09Overlay('discard043',tr('confirmDiscard')),b=o.querySelector('.v09Body');b.innerHTML='';b.append(v09Button(tr('discard'),()=>{request('discard:'+index,'discard',payload);closeOverlay(o);closeOverlay(el('v010ItemDetails'));}));openOverlay(o);}));};
 return Object.freeze({water,fixtures,tank,up,tick,readyAt,rotten,remaining,request,commands,capture,validate,migrate,go,clear:i=>request('bed'+i,'clear')});
})();
