const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');process.chdir(root);process.env.LAST_BASE_ASSETS=root;
const {boot}=require('./audio-harness.cjs'),{setup}=require('./runtime.cjs'),checks=[];
const manifest=require('../assets/manifest.json'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack});}}
(async()=>{
 const h=boot(),{r,E,J,advance,meter}=h;await h.load();
 const initial=E('JSON.stringify(captureGameProgress())');
 function reset(){E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(initial)}));GameAudio.reset();for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);menuOpen=false;document.hidden=false;playerDead=false;scene='surface';player.wallLevel=false;player.x=800;player.y=850;masterVolume=.7;audioCtx.state='running';zombies=[];frameScale=1;GameAudio.sync();`);}
 check('assets.everyRequiredClipExistsAndDecodes',()=>{assert.equal(Object.keys(manifest.audio).length,57);assert.equal(E('Object.keys(audioBuffers).length'),57);assert.equal(meter.requests.length,57);assert.equal(new Set(meter.requests).size,57);for(const d of Object.values(manifest.audio)){assert.equal(d.optional,false);assert.ok(fs.existsSync(d.path));}});
 check('assets.everyCueHasAvailableBuffers',()=>{for(const [name,cue]of Object.entries(J('GameAudio.cues')))for(const clip of cue.clips)assert.ok(manifest.audio[clip],name+':'+clip);});
 check('assets.wavBoundariesAndNoSourceClipping',()=>{for(const d of Object.values(manifest.audio)){const b=fs.readFileSync(d.path);assert.equal(b.toString('ascii',0,4),'RIFF');assert.equal(b.readUInt16LE(22),1);let peak=0;for(let i=44;i<b.length;i+=2)peak=Math.max(peak,Math.abs(b.readInt16LE(i)));assert.ok(peak>1000&&peak<32767,d.path);}});
 check('steps.fourRecordedVariantsSameScale',()=>{const a=['footsteps','footstep2','footstep3','footstep4'].map(k=>manifest.audio[k]);assert.equal(new Set(a.map(d=>sha(fs.readFileSync(d.path)))).size,4);for(const d of a){assert.equal(d.volumeScale,.5);assert.equal(fs.readFileSync(d.path).readUInt32LE(24),32000);}});
 check('assets.loadingConcurrencyTwo',()=>assert.ok(E('GameAudio.inspect().peakLoads')<=2));
 await h.load();check('assets.secondPreloadDoesNotRequestAgain',()=>assert.equal(meter.requests.length,57));
 check('audio.singleContext',()=>assert.equal(meter.contexts,1));
 check('audio.noNewRafOrIntervals',()=>{const before={...r.scheduler},n=r.scheduler.rafRequests;for(let i=0;i<80;i++)advance(100,'GameAudioWorld.tick()');assert.equal(r.scheduler.rafRequests,n);assert.equal(r.scheduler.intervals.length,before.intervals.length);});
 check('crowd.zombieAndAnimalVoicesBounded',()=>{reset();E("for(let i=0;i<300;i++){const z={x:player.x+i%20,y:player.y,alive:true};GameAudio.play('zombie',{owner:z,x:z.x,y:z.y,cooldownKey:String(i)});GameAudio.play('zombieAttack',{owner:z,x:z.x,y:z.y,cooldownKey:String(i)});GameAudio.play('cow',{cooldownKey:String(i)});GameAudio.play('chicken',{cooldownKey:String(i)});}");const s=J('GameAudio.inspect()');assert.equal(s.families.groan,2);assert.equal(s.families.enemy,3);assert.equal(s.families.animal,1);assert.ok(s.oneShots<=16);});
 check('combat.prioritySurvivesAmbientCrowd',()=>{reset();const stolen=E('GameAudio.inspect().stolen');E("for(let i=0;i<60;i++)for(const cue of ['zombie','zombieAttack','constructionHit','inventoryMove','cow'])GameAudio.play(cue,{cooldownKey:String(i)});for(let i=0;i<8;i++)GameAudio.play('shotAK');");assert.equal(E('GameAudio.inspect().families.combat'),8);assert.equal(E('GameAudio.inspect().oneShots'),16);assert.ok(E('GameAudio.inspect().stolen')>=stolen+4);});
 check('loops.repeatedDesiredStateIsIdempotent',()=>{reset();const n=meter.sources;E("for(let i=0;i<100;i++)GameAudio.loop('rotor','rotor')");assert.equal(meter.sources-n,1);assert.equal(E('GameAudio.inspect().loops'),1);});
 check('loops.budgetAndStop',()=>{reset();E("for(let i=0;i<100;i++)GameAudio.loop('loop'+i,'rotor')");assert.equal(E('GameAudio.inspect().loops'),6);E('GameAudio.reset()');assert.equal(meter.active.size,0);});
 check('loops.crossfadeTailsBounded',()=>{reset();for(let i=0;i<80;i++)E(`GameAudio.loop('ambience','${i%2?'bunker':'night'}')`);assert.ok(E('GameAudio.inspect().tails')<=2);advance(500);E('GameAudio.reset()');assert.equal(meter.active.size,0);});
 check('voices.completedNodesCleaned',()=>{reset();for(let i=0;i<1000;i++){E("GameAudio.play('shotAK')");advance(480);}assert.equal(E('GameAudio.inspect().oneShots'),0);assert.equal(meter.active.size,0);});
 check('lifecycle.hiddenStopsLoopsAndContacts',()=>{reset();E("GameAudio.loop('rotor','rotor');playAnimationSound('footsteps','step');document.hidden=true;GameAudio.sync()");assert.equal(meter.active.size,0);});
 for(const state of ['suspended','interrupted']){reset();E(`audioCtx.state='${state}';GameAudio.sync();unlockGameAudio({isTrusted:true})`);await new Promise(setImmediate);check('lifecycle.resume.'+state,()=>{assert.equal(E('audioCtx.state'),'running');assert.equal(meter.contexts,1);assert.equal(meter.requests.length,57);});}
 check('lifecycle.muteStopsAndSuppresses',()=>{reset();E("GameAudio.loop('rotor','rotor');masterVolume=0;GameAudio.sync()");assert.equal(meter.active.size,0);assert.equal(E("GameAudio.play('shotAK')"),false);});
 check('lifecycle.saveRestoreClearsNonpersistentVoices',()=>{reset();E("GameAudio.loop('rotor','rotor');GameAudio.play('shotAK')");E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(initial)}))`);assert.equal(meter.active.size,0);assert.ok(!E('JSON.stringify(captureGameProgress())').includes('audioBuffers'));});
 check('distance.sceneAndRangeRejectInaudibleSounds',()=>{reset();assert.equal(E("GameAudio.play('cow',{scene:'bunker'})"),false);assert.equal(E("GameAudio.play('shotAK',{x:10000,y:10000})"),false);assert.equal(E("GameAudio.play('zombie',{x:player.x,y:player.y,level:true})"),false);});
 check('distance.groundZombiesSilentOnUpperCityFloor',()=>{reset();E('V013City.setFloor(1)');try{assert.equal(E("GameAudio.play('zombie',{x:player.x,y:player.y,scene:'surface',level:false})"),false);}finally{E('V013City.setFloor(0)');}});
 check('zombie.killedOwnerStopsGroan',()=>{reset();E("window.az={x:player.x,y:player.y,alive:true};playZombieBuffer(az);az.alive=false;stopInvalidZombieAudio()");assert.equal(E('GameAudio.inspect().families.groan'),0);});
 check('combat.actualShotAndMuzzleShareFrame',()=>{reset();E("V013Inventory.equip('rifle_ak74');V010Combat.currentWeapon().rounds=10;lastShot=-1000;shoot()");assert.ok(E('muzzleFlash.time')>=0);assert.equal(E('V010Combat.currentWeapon().rounds'),9);assert.equal(E('GameAudio.inspect().families.combat'),1);assert.equal(meter.starts.at(-1).at,E('muzzleFlash.time')/1000);});
 check('combat.reloadStagesFollowProgressWithoutTimers',()=>{reset();E("window.jobAudio={remainingMs:2000,totalMs:2000};GameAudio.reload(jobAudio,true)");let n=meter.starts.length;advance(500);E('jobAudio.remainingMs=800;GameAudio.reload(jobAudio)');assert.equal(meter.starts.length,n+1);advance(500);E('jobAudio.remainingMs=100;GameAudio.reload(jobAudio)');assert.equal(meter.starts.length,n+2);E('GameAudio.reload(jobAudio)');assert.equal(meter.starts.length,n+2);});
 check('combat.cancelReloadStopsItsSound',()=>{reset();E("V013Inventory.equip('rifle_ak74');V010Combat.currentWeapon().rounds=0;addItem('ammo',30);reloadWeapon();V010Combat.cancelReload()");assert.equal(E('GameAudio.inspect().families.combat'),0);});
 check('combat.restoredReloadDoesNotReplayPassedStages',()=>{reset();const n=meter.starts.length;E('GameAudio.reload({remainingMs:100,totalMs:2000})');assert.equal(meter.starts.length,n);});
 check('world.machineOnlyWhenPoweredAndActive',()=>{reset();E("scene='bunker';player.x=400;player.y=0;V09Power.running=true;V09Power.fuel=100;V09Craft.craftQueue.paused.furnace=false;addItem('stone',10);V09Craft.start('furnace','concrete',1);GameAudioWorld.tick(true)");assert.ok(J('GameAudio.inspect().loopKeys').includes('machine'));E("V09Craft.craftQueue.paused.furnace=true;GameAudioWorld.tick(true)");assert.ok(!J('GameAudio.inspect().loopKeys').includes('machine'));});
 check('world.dormantIrrigationDoesNotStartLoop',()=>{reset();E("scene='bunker';player.x=getFarmBeds()[0].x+40;player.y=getFarmBeds()[0].y+40;V09Power.running=true;V09Power.fuel=100;V011Farm.state.water=100;farmState.forEach((b,i)=>{b.crop=0;b.irrigation028={phase:'spray',remainingMs:3000}});GameAudioWorld.tick(true)");assert.ok(!J('GameAudio.inspect().loopKeys').includes('water'));assert.equal(J('GameAudio.inspect().loopKeys').filter(k=>k==='water').length,0);E('V011Farm.state.water=0;GameAudioWorld.tick(true)');assert.ok(!J('GameAudio.inspect().loopKeys').includes('water'));});
 check('world.droneRotorFollowsFlightState',()=>{reset();E("Object.assign(V014Robots.state,{x:player.x,y:player.y,scene,packed:false,hp:100,battery:100,task:'follow'});GameAudioWorld.tick(true)");assert.ok(J('GameAudio.inspect().loopKeys').includes('rotor'));E("V014Robots.state.task='docked';GameAudioWorld.tick(true)");assert.ok(!J('GameAudio.inspect().loopKeys').includes('rotor'));});
 check('world.droneChargeCueRequiresActualBatteryIncrease',()=>{reset();E("scene='bunker';Object.assign(V014Robots.state,{x:player.x,y:player.y,scene,packed:false,hp:100,battery:20,task:'docked'});window.chargeCalls=0;window.oldAudioPlay=GameAudio.play;GameAudio.play=function(name,...args){if(name==='droneCharge')chargeCalls++;return oldAudioPlay(name,...args)};GameAudioWorld.tick(true)");try{for(let i=0;i<5;i++)advance(110,'GameAudioWorld.tick(true)');assert.equal(E('chargeCalls'),0);for(let i=0;i<5;i++)advance(110,'V014Robots.state.battery+=.1;GameAudioWorld.tick(true)');assert.equal(E('chargeCalls'),1);advance(110,'GameAudioWorld.tick(true)');advance(700,'V014Robots.state.battery+=.1;GameAudioWorld.tick(true)');assert.equal(E('chargeCalls'),2);}finally{E('GameAudio.play=oldAudioPlay');}});
 check('world.dayXEndsExactlyAtSix',()=>{reset();E('WorldClock.restore({schema:1,day:10,minute:359});GameAudioWorld.tick(true)');assert.ok(meter.starts.some(s=>s.buffer===E('audioBuffers.dayX')));E('WorldClock.advance(WorldClock.dayMs/1440*2);GameAudioWorld.tick(true)');assert.equal(E("WorldEvents.isActive('day_x')"),false);assert.ok(!J('GameAudio.inspect().loopKeys').includes('ambience'));assert.equal(E('audioBuffers.day'),undefined);});
 check('world.sceneChangeStopsAnimalAndMachineVoices',()=>{reset();E("scene='bunker';GameAudioWorld.tick(true);GameAudio.play('cow');scene='surface';GameAudioWorld.tick(true)");assert.equal(E('GameAudio.inspect().families.animal'),0);assert.ok(!J('GameAudio.inspect().loopKeys').includes('machine'));});
 check('rng.cowTimerAndGameplaySequenceMatchStableInput',()=>{
  const reference=path.join(__dirname,'pre-audio');assert.ok(fs.existsSync(reference+'/index.html'),'stable archive must be extracted for differential');
  const a=setup(reference+'/index.html'),b=setup(root+'/index.html');
  for(const q of [a,b])q.eval("scene='bunker';livestockAlive=true;window.rngTrace=[]");
  for(let i=0;i<240;i++){for(const q of [a,b]){q.advance(500);q.eval('updateLivestockAudio();rngTrace.push([nextCowMooAt,Math.random()])');}}
  assert.equal(a.eval('JSON.stringify(rngTrace)'),b.eval('JSON.stringify(rngTrace)'));
 });
 check('rng.audioVariationsDoNotConsumeGameplayRandom',()=>{reset();E('window.savedRandom=Math.random;Math.random=()=>{throw Error("Gameplay RNG used by audio")};');try{for(let i=0;i<80;i++)advance(300,"GameAudio.play('zombie');GameAudio.play('shotAK');playAnimationSound('footsteps','step')");}finally{E('Math.random=savedRandom');}});
 check('scope.saveVersionBalanceAndActorManifestUnchanged',()=>{const ref=require('../qa/audio-stable-reference.json');assert.deepEqual(manifest.actors,ref.actors);assert.equal(sha(fs.readFileSync('src/config/gameplay.js')),ref.balanceSha256);require('./bunker-contract.cjs').assertSource('src/save/format.js',ref.saveFormatSha256);});
 check('runtime.noErrors',()=>assert.deepEqual(r.errors,[]));
 const result={patch:'audio-pass-recovered-1',passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks,limits:J('GameAudio.limits'),audio:J('GameAudio.inspect()'),limitations:['Modeled DOM/WebAudio, real WAV files and native Canvas. No physical device listening.']};
 fs.writeFileSync('qa/results/audio-pass.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));if(result.failed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
