// R2 integration: approved geometry, migration, suspended agriculture, existing owners.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');process.chdir(path.resolve(__dirname,'..'));
const {setup}=require('./runtime.cjs'),r=setup('index.html'),old=setup('qa/bunker-base/index.html'),E=s=>r.eval(s),J=s=>JSON.parse(JSON.stringify(E(s))),checks=[];
const copy=v=>JSON.parse(JSON.stringify(v));
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack?.slice(0,2400)});}}
const fresh=E('JSON.stringify(captureGameProgress())'),legacy=old.eval('JSON.stringify(captureGameProgress())');
const reset=()=>E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(fresh)}));GameFlow.resume();scene='bunker';player.x=1120;player.y=-120;menuOpen=false;playerDead=false;document.hidden=false;V09Power.running=true;V09Power.fuel=80;V010Energy.battery.charge=1.5;for(const d of v09Doors){d.open=1;d.manual=false;}invalidateGeometry();`);
check('layout.sevenRoomsPlusMainHall',()=>{assert.equal(E('BunkerLayout.roomData.length'),8);const x=J('BunkerLayout.rooms');assert.equal((x.corridor.right-x.corridor.left)*(x.corridor.bottom-x.corridor.top),1200000);for(const [id,q]of Object.entries(x))if(id!=='corridor')assert.equal((q.right-q.left)*(q.bottom-q.top),260000);});
check('core.centerAndPermanentNotBuildable',()=>{reset();assert.equal(E('BunkerLayout.core.x+BunkerLayout.core.w/2'),1210);assert.equal(E('BunkerLayout.core.y+BunkerLayout.core.h/2'),510);assert.equal(E("worldCollision(1210,510,10,'bunker')"),true);assert.equal(E("V018Build.record('command_core_l1')"),undefined);assert.equal(E("V018Build.damage('command_core_l1',999999)"),false);assert.equal(E('Object.isFrozen(BunkerLayout.core)'),true);});
check('core.newGameAndReloadAlwaysExists',()=>{for(let i=0;i<4;i++){E('restoreGameProgress(GameSave.newGameData())');assert.equal(E('solidObjects("bunker").filter(o=>o.id==="command_core_l1").length'),1);}});
check('stairs.downCannotBeDestroyedOrEntered',()=>{reset();assert.equal(E("V018Build.damage('stairs_down_locked',1e9)"),false);for(const y of [-260,-320,-440])assert.equal(E(`worldCollision(1300,${y},10,'bunker')`),true);assert.equal(E("worldCollision(1120,-350,10,'bunker')"),false);assert.equal(E("interactionObjects('bunker').filter(o=>o.id==='exit'||o.id==='stairs_down_locked').length"),2);});
check('farm.absentFromActiveGeometryAndInteractions',()=>{reset();assert.equal(E("solidObjects('bunker').some(o=>BunkerLayout.agricultureId(o.id))"),false);assert.equal(E("interactionObjects('bunker').some(o=>BunkerLayout.agricultureId(o.id))"),false);assert.equal(E("worldCollision(700,-600,10,'bunker')"),true);assert.equal(E('storageChests.length'),14);assert.equal(E('livestockAnimals.length'),old.eval('livestockAnimals.length'));});
for(const id of ['generator','tank','battery','bed','shower','robots014_dock','furnace','craft_bench','upgrade0161'])check('anchor.'+id,()=>{reset();const a=J(`interactionObjects('bunker').find(o=>o.id==='${id}')`),b=J(`['bed','shower','robots014_dock'].includes('${id}')?BunkerLayout.fixture('${id}'):GameFootprints.body('${id}')`);for(const k of ['x','y','w','h'])assert.equal(a[k],b[k]);});
for(const [room,x,y]of [['workshop',600,30],['room4',590,510],['room6',650,1050],['room5',1870,90],['reserve_l1',1870,510],['storage',1870,1010],['room7',1260,1460]]){
 check('path.entryTo.'+room,()=>{reset();assert.equal(E(`worldCollision(${x},${y},15,'bunker')`),false);const p=E(`findWalkPath(1120,-120,{id:'ground',kind:'ground',x:${x},y:${y},r:0,range:1},'bunker',15)`);assert.ok(p?.length);let a={x:1120,y:-120};for(const b of p){assert.equal(E(`lineClear(${a.x},${a.y},${b.x},${b.y},15,'bunker')`),true);a=b;}});
 check('door.automaticManual.'+room,()=>{reset();E(`window.testDoor=v09Doors.find(d=>d.room==='${room}');testDoor.open=0;testDoor.away=4;player.x=testDoor.x+testDoor.w/2;player.y=testDoor.y+testDoor.h/2;`);E('for(let n=0;n<8;n++)V09Power.tick(.1)');assert.equal(E('testDoor.open'),1);E('player.x=1210;player.y=900;V09Power.running=false;V010Energy.battery.charge=0;testDoor.open=0;testDoor.manual=true;V09Power.tick(.1)');assert.ok(E('testDoor.open>0'));});
}
for(const [name,x,y,expected]of [['energy',1100,590,[1870,90]],['storage',1100,1010,[1870,1010]],['living',1150,-40,[1260,1460]],['oldFarm',700,-600,null],['oldWall',610,300,null],['newCore',725,510,null]])check('migration.playerDrone.'+name,()=>{
 const d=JSON.parse(legacy);Object.assign(d.player,{scene:'bunker',x,y});Object.assign(d.v091.fortress,{x,y,wallLevel:false});Object.assign(d.robots014,{scene:'bunker',x:x+30,y,task:'guard',guard:{scene:'bunker',x,y}});
 const source=JSON.stringify(d);E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(source)}))`);assert.equal(JSON.stringify(d),source);assert.equal(E("worldCollision(player.x,player.y,player.radius,'bunker')"),false);assert.equal(E("worldCollision(V014Robots.state.x,V014Robots.state.y,10,'bunker')"),false);if(expected){assert.ok(Math.hypot(E('player.x')-expected[0],E('player.y')-expected[1])<.01);}
 for(const k of ['bag','equipment','storage','quick013'])assert.deepEqual(require('./stage-c1-contract.cjs').project(J('captureGameProgress()'))[k],require('./stage-c1-contract.cjs').project(d)[k]);for(const k of ['hp','battery','cargo','modules','ammo'])assert.deepEqual(J('V014Robots.state.'+k),d.robots014[k]);
});
check('migration.idempotentAndInvalidCurrentRejected',()=>{const a=E(`decodeGameProgress(${JSON.stringify(legacy)})`),b=E(`decodeGameProgress(${JSON.stringify(JSON.stringify(a))})`);assert.deepEqual(copy(a),copy(b));const bad=copy(a);delete bad.bunker030;const before=E('JSON.stringify(captureGameProgress())');assert.throws(()=>E(`restoreGameProgress(${JSON.stringify(bad)})`));assert.equal(E('JSON.stringify(captureGameProgress())'),before);});
check('migration.farmMarkersPreservedDormant',()=>{const d=JSON.parse(legacy);d.v010.modules.camera.markers=[{x:700,y:-600,scene:'bunker',name:'Old crop'},{x:1100,y:600,scene:'bunker',name:'Generator'}];d.v010.modules.camera.goal={x:700,y:-600,scene:'bunker'};E(`restoreGameProgress(${JSON.stringify(d)})`);assert.equal(E('captureGameProgress().bunker030.dormantMarkers.length'),2);assert.deepEqual(J('V010Camera.capture().markers'),[{x:1870,y:100,scene:'bunker',name:'Generator'}]);});
// Seed an actual 0.29 save through its original public crop/craft owners.
old.eval("GameFlow.resume();scene='bunker';V09Power.running=true;V09Power.fuel=80;V011Farm.beginBed(0,0);for(let i=0;i<50;i++)V011Farm.plantOne(0,i);farmState[0].irrigation028={phase:'spray',remainingMs:5000,rng:12345};V011Farm.state.water=71;feedCraftLoaded=10;V09Craft.startFeed();");
const farmSave=old.eval('JSON.stringify(captureGameProgress())');
const farmView=d=>({farm:d.farm,plants:d.farm014,water:d.farmV011.water,grown:d.farmV011.grown,animals:d.livestock,storage:d.storage.slice(8),feed:d.v09.crafting.feed,chickens:d.v09.chickenBreedMs,queues:d.v010.modules.craft.queues,ready:d.v010.modules.craft.ready});
check('farm.oldStateExactOnMigration',()=>{E(`restoreGameProgress(${farmSave})`);assert.deepEqual(farmView(J('captureGameProgress()')),farmView(JSON.parse(farmSave)));});
for(const place of ['surface','bunker'])check('farm.fullPauseOfflineAndRepeatedLoad.'+place,()=>{
 E(`restoreGameProgress(${farmSave});scene='${place}';`);const before=farmView(J('captureGameProgress()'));r.advance(3*86400000);E('V011Farm.settle();updateLivestockProduction();updateLivestockAnimals();updateCowBreeding();updateFeedCraft();V09Craft.tick(100);');assert.deepEqual(farmView(J('captureGameProgress()')),before);
 for(let i=0;i<4;i++){const raw=E('JSON.stringify(captureGameProgress())');r.advance(86400000);E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(raw)}))`);assert.deepEqual(farmView(J('captureGameProgress()')),before);}
});
check('farm.commandsAndPowerDormant',()=>{assert.equal(E('V0141Farm.plant(1,1)'),false);assert.equal(E('V0141Farm.harvest(0)'),0);assert.equal(E('V011Farm.refill(100)'),0);assert.equal(E('V09Craft.startFeed()'),false);assert.equal(E('V011Farm.pumpDemand()'),0);assert.ok(E("[...V09Power.allocation().served].every(id=>V09Power.devices[id].room!=='farm')"));});
check('farm.cowTimerStillConsumesItsScheduledRandomDraw',()=>{E("scene='bunker';livestockAlive=true;window.randomDraws=0;window.savedRandom=Math.random;Math.random=()=>{randomDraws++;return .5;};nextCowMooAt=Date.now()-1;updateLivestockAudio();Math.random=savedRandom;");assert.equal(E('randomDraws'),1);assert.equal(E('nextCowMooAt-Date.now()'),9000);});
check('production.workshopContinues',()=>{reset();E("bag=[];addItem('coal',5)");assert.equal(E("V09Craft.start('furnace','gunpowder',1)"),true);const ms=E("V09Craft.craftQueue.getJob('furnace').remainingMs");E('V09Craft.tick(100)');assert.equal(E("V09Craft.craftQueue.getJob('furnace').remainingMs"),ms-100);});
for(const language of ['ru','en'])check('localizedLabels.'+language,()=>{E(`I18n.setLanguage('${language}')`);for(const k of ['bunker.core.name','bunker.down.locked','bunker.up.label'])assert.ok(!E(`I18n.t('${k}')`).includes('bunker.'));});
for(const mode of ['PC','MOBILE'])check('map.completeR2Centered.'+mode,()=>{reset();E(`GameInput.setMode('${mode}');V010Camera.showMap();`);assert.deepEqual(J('V010Camera.mapViewport.pan'),{x:1210,y:660});const bounds=J('V010Camera.mapBounds()');assert.deepEqual(bounds,J('BunkerLayout.bounds'));E('closeOverlay(el("v010MapOverlay"))');});
check('console.noErrors',()=>{assert.deepEqual(r.errors,[]);assert.deepEqual(old.errors,[]);});
const result={version:require('../package.json').version,passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks};fs.writeFileSync('qa/results/bunker-level1.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(c=>c.status==='FAIL')}));if(result.failed)process.exitCode=1;
