// R2 contracts against the immutable delivered R1, including actual save decoding.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
process.chdir(path.resolve(__dirname,'..'));
const {setup}=require('./runtime.cjs'),r=setup('index.html'),prior=setup('qa/bunker-r1-base/index.html');
const E=s=>r.eval(s),J=s=>JSON.parse(JSON.stringify(E(s))),checks=[];
const baseline=prior.eval('JSON.stringify(captureGameProgress())');
const check=(id,fn)=>{try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack?.slice(0,3000)});}};
const decode=d=>J(`decodeGameProgress(${JSON.stringify(JSON.stringify(d))})`);
const restore=d=>E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(JSON.stringify(d))}))`);
function unaffected(d){d=JSON.parse(JSON.stringify(d));delete d.gameVersion;delete d.saveVersion;delete d.bunker030.layout;for(const p of [d.player,d.robots014,d.robots014.guard,d.v091.fortress,...(d.v010.modules.camera.markers||[]),d.v010.modules.camera.goal])if(p){delete p.x;delete p.y;}return d;}
check('geometry.exact800x1500AndCoreUnmoved',()=>{assert.deepEqual(J('({w:bunker.corridor.right-bunker.corridor.left,h:bunker.corridor.bottom-bunker.corridor.top})'),{w:800,h:1500});assert.deepEqual(J('BunkerLayout.core'),JSON.parse(JSON.stringify(prior.eval('BunkerLayout.core'))));assert.equal(E('BunkerLayout.core.x-bunker.corridor.left'),220);assert.equal(E('bunker.corridor.right-BunkerLayout.core.x-BunkerLayout.core.w'),220);});
check('stairs.smallerSeparatedAndSharedGeometry',()=>{const stairs=J('BunkerLayout.stairs');assert.deepEqual(stairs.map(s=>[s.w,s.h]),[[140,200],[140,200]]);assert.equal(stairs[1].x-stairs[0].x-stairs[0].w,40);assert.equal(E('BunkerLayout.up.x'),stairs[0].x+70);assert.equal(E('BunkerLayout.down.x'),stairs[1].x);assert.equal(E('BunkerLayout.down.w'),140);});
const cases=[['kitchen',400,30,600,30],['medical',390,510,590,510],['workshop',450,1050,650,1050],['energy',2070,90,1870,90],['storage',2070,1010,1870,1010],['reserve',2070,510,1870,510],['living',1260,1460,1260,1460],['hall',1510,800,1410,800],['upstairs',1070,-360,1120,-340]];
for(const [name,x,y,nx,ny]of cases)check('migration.R1.'+name+'.stateAndPosition',()=>{
 const d=JSON.parse(baseline);Object.assign(d.player,{scene:'bunker',x,y});Object.assign(d.v091.fortress,{x,y,wallLevel:false});Object.assign(d.robots014,{scene:'bunker',x:x+30,y:y+35,task:'guard',packed:false,guard:{scene:'bunker',x,y}});
 d.v010.modules.camera.markers=[{scene:'bunker',x,y,name:name},{scene:'surface',x:700,y:850,name:'Surface'}];d.v010.modules.camera.goal={scene:'bunker',x,y};d.bunker030.dormantMarkers=[{scene:'bunker',x:700,y:-600,name:'Dormant crop'}];
 const input=JSON.stringify(d),m=decode(d);assert.equal(JSON.stringify(d),input);assert.equal(m.saveVersion,5);assert.equal(m.bunker030.layout,2);assert.ok(Math.hypot(m.player.x-nx,m.player.y-ny)<.001);assert.deepEqual(unaffected(m),unaffected(d));assert.deepEqual(m.bunker030.dormantMarkers,d.bunker030.dormantMarkers);assert.equal(m.bunker030.agricultureAt,d.bunker030.agricultureAt);assert.deepEqual(m.v010.modules.camera.markers[0],{scene:'bunker',x:nx,y:ny,name:name});assert.deepEqual(m.v010.modules.camera.markers[1],d.v010.modules.camera.markers[1]);assert.deepEqual(decode(m),m);
 restore(d);assert.equal(E("worldCollision(player.x,player.y,player.radius,'bunker')"),false);assert.equal(E("worldCollision(V014Robots.state.x,V014Robots.state.y,10,'bunker')"),false);assert.ok(Math.hypot(E('player.x')-nx,E('player.y')-ny)<.001);
 const save=J('captureGameProgress()');for(const key of ['bag','equipment','storage','quick013','farm','farm014','livestock','building018'])assert.deepEqual(save[key],d[key]);assert.equal(save.bunker030.agricultureAt,d.bunker030.agricultureAt);
});
for(const [x,y]of [[1210,510],[1810,280],[800,-500],[1350,-400]])check(`migration.R1.invalidPosition.${x}.${y}`,()=>{const d=JSON.parse(baseline);Object.assign(d.player,{scene:'bunker',x,y});Object.assign(d.robots014,{scene:'bunker',x,y,packed:false,task:'guard',guard:{scene:'bunker',x,y}});restore(d);assert.equal(E("worldCollision(player.x,player.y,player.radius,'bunker')"),false);assert.equal(E("worldCollision(V014Robots.state.x,V014Robots.state.y,10,'bunker')"),false);assert.ok(E('Math.hypot(player.x-V014Robots.state.x,player.y-V014Robots.state.y)>23'));});
check('migration.R1.dockedDroneFollowsStation',()=>{const d=JSON.parse(baseline);Object.assign(d.robots014,{scene:'bunker',packed:false,task:'docked',x:2234,y:195});restore(d);assert.equal(E('V014Robots.atDock()'),true);const p=J('V014Robots.dockPosition()');assert.equal(E('V014Robots.state.x'),p.x);assert.equal(E('V014Robots.state.y'),p.y);});
check('migration.futureOrMissingLayoutRejectedBeforeMutation',()=>{const before=E('JSON.stringify(captureGameProgress())');for(const layout of [null,0,3,99]){const d=JSON.parse(baseline);if(layout===null)delete d.bunker030;else d.bunker030.layout=layout;assert.throws(()=>restore(d));assert.equal(E('JSON.stringify(captureGameProgress())'),before);}});
check('newGame.R2AndNoDormantSimulation',()=>{E('restoreGameProgress(GameSave.newGameData())');assert.equal(E('captureGameProgress().bunker030.layout'),2);assert.equal(E('AgricultureTime.available'),false);const before=J('({farm:farmState,animals:livestockAnimals,water:V011Farm.state.water,at:AgricultureTime.now()})');r.advance(7*86400000);E('V011Farm.settle();updateLivestockProduction();updateLivestockAnimals();updateCowBreeding();');assert.deepEqual(J('({farm:farmState,animals:livestockAnimals,water:V011Farm.state.water,at:AgricultureTime.now()})'),before);});
check('fixtures.renderUsesWorldAnchorsInAllMovedRooms',()=>{
 E("window.renderProbe=[];window.savedArt=V011Art.draw;V011Art.draw=function(key,x,y,w,h){const t=ctx.getTransform();renderProbe.push({key,x:t.a*x+t.c*y+t.e,y:t.b*x+t.d*y+t.f,w,h});return true;};scene='bunker';ctx.setTransform(1,0,0,1,0,0);drawBunker();V011Art.draw=savedArt;");
 prior.eval("window.renderProbe=[];window.savedArt=V011Art.draw;V011Art.draw=function(key,x,y,w,h){const t=ctx.getTransform();renderProbe.push({key,x:t.a*x+t.c*y+t.e,y:t.b*x+t.d*y+t.f,w,h});return true;};scene='bunker';ctx.setTransform(1,0,0,1,0,0);drawBunker();V011Art.draw=savedArt;");
 for(const [key,dx]of [['furnace',200],['workbench',200],['generator',-200],['tank',-200],['bed',0]]){const a=J(`renderProbe.find(p=>p.key==='${key}')`),b=JSON.parse(JSON.stringify(prior.eval(`renderProbe.find(p=>p.key==='${key}')`)));assert.ok(a,key);assert.ok(Math.abs(a.x-b.x-dx)<=.5,key+'.x');for(const k of ['y','w','h'])assert.equal(a[k],b[k],key+'.'+k);}

});
check('fixtures.medicalKitchenFallbackAndWorkshopLightRelocated',()=>{
 E("window.rectProbe=[];window.savedRect=ctx.fillRect;ctx.fillRect=function(x,y,w,h){const t=ctx.getTransform();rectProbe.push({x:t.a*x+t.c*y+t.e,y:t.b*x+t.d*y+t.f,w,h});return savedRect.call(this,x,y,w,h);};drawBunker();ctx.fillRect=savedRect;");
 for(const id of ['medical_table','kitchen']){const f=J(`BunkerLayout.fixture('${id}')`);assert.ok(J('rectProbe').some(p=>['x','y','w','h'].every(k=>p[k]===f[k])),id);}
 E("window.savedVisual=V09Craft.visualState;V09Craft.visualState=()=>({working:true});window.gradients=[];window.savedGradient=ctx.createRadialGradient;ctx.createRadialGradient=function(...a){gradients.push(a);return savedGradient.apply(this,a);};V011Rooms.paintDarkness(ctx,'workshop',bunker.workshop,false);ctx.createRadialGradient=savedGradient;V09Craft.visualState=savedVisual;");assert.ok(J('gradients').some(g=>g[0]===419&&g[1]===878));
});
check('audio.generatorAndProductionUseRelocatedFixtureCenters',()=>{
 E("GameFlow.resume();menuOpen=false;playerDead=false;scene='bunker';V09Power.running=true;V09Power.fuel=80;bag=[];addItem('coal',5);V09Craft.start('furnace','gunpowder',1);window.loopProbe=[];window.savedSync=GameAudio.sync;window.savedLoop=GameAudio.loop;GameAudio.sync=()=>true;GameAudio.loop=(key,event,p)=>loopProbe.push({key,event,p});GameAudioWorld.tick(true);GameAudio.loop=savedLoop;GameAudio.sync=savedSync;");
 for(const [key,id]of [['generator','generator'],['machine','furnace']]){const p=J(`loopProbe.find(p=>p.key==='${key}')`),f=J(`BunkerLayout.fixture('${id}')`);assert.equal(p.event,key);assert.equal(p.p.x,f.x+f.w/2);assert.equal(p.p.y,f.y+f.h/2);}
});
check('art.newLocalCoreIsRegisteredOnce',()=>{const m=require('../assets/manifest.json');assert.equal(m.images['art/command_core'].path,'assets/images/props/command_core_r2.png');assert.equal(Object.values(m.images).filter(i=>i.path===m.images['art/command_core'].path).length,1);assert.ok(fs.existsSync(m.images['art/command_core'].path));});
check('console.noErrors',()=>{assert.deepEqual(r.errors,[]);assert.deepEqual(prior.errors,[]);});
const report={version:require('../package.json').version,passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks};fs.writeFileSync('qa/results/bunker-r2.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,failed:report.failed,failures:checks.filter(c=>c.status==='FAIL')}));if(report.failed)process.exitCode=1;
