// Behavioral Stage A contracts: immutable R2 saves, isolated actors and live UI.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
process.chdir(path.resolve(__dirname,'..'));const {setup}=require('./runtime.cjs');
const checks=[],copy=v=>JSON.parse(JSON.stringify(v));
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack?.slice(0,4500)});}}
const pure={window:{}};pure.window=pure;vm.createContext(pure);
for(const f of ['conditions','definitions','domain'])vm.runInContext(fs.readFileSync('src/campaign/'+f+'.js','utf8'),pure);
function world(){const facts={generatorRunning:false,corePowered:false,mined:30},actors={a:{id:'a'},b:{id:'b'},guest:{id:'guest'},dead:{id:'dead',dead:true}},events=[];let available=true,reason='campaign.reason.power';
 const campaign=pure.GameCampaignDomain.create(pure.CampaignDefinitions,{facts:()=>({...facts}),actor:id=>actors[id],permission:actor=>actor.id!=='guest',access:(_actor,id)=>({available:available&&id==='command_core_l1',reason}),emit:e=>events.push(e)});
 return {campaign,facts,events,deny(r){available=false;reason=r;},cmd(extra={}){return {type:'ADVANCE_CHAPTER',actorId:'a',targetId:'command_core_l1',chapterId:campaign.view().chapter,expectedRevision:campaign.view().revision,requestId:'one',...extra};},ready(){facts.generatorRunning=true;facts.corePowered=true;campaign.refresh();facts.mined++;campaign.refresh();}};
}
check('conditions.AND_OR_and_explanations',()=>{const c={all:[{fact:'x',atLeast:10,reason:'short'},{any:[{fact:'y',equals:true},{fact:'z',equals:true}]}]};assert.equal(pure.GameConditions.validate(c,['x','y','z']),true);assert.equal(pure.GameConditions.evaluate(c,{x:9,y:true}).reason,'short');assert.equal(pure.GameConditions.evaluate(c,{x:10,z:true}).available,true);assert.equal(pure.GameConditions.evaluate(c,{x:10}).available,false);});
for(const [id,change]of [['unknownFact',d=>d.chapters[0].objectives[0].condition.fact='missing'],['unknownObjective',d=>d.chapters[0].objectives[1].requires=['missing']],['objectiveCycle',d=>d.chapters[0].objectives[0].requires=['ore_after']],['chapterCycle',d=>d.chapters[1].next='base_check'],['unknownChapter',d=>d.chapters[0].next='missing'],['duplicateObjective',d=>d.chapters[0].objectives[1].id='power_once'],['unreachable',d=>d.chapters[0].next=null],['transientDependency',d=>d.chapters[0].objectives[1].requires=['core_current']]])check('definitions.reject.'+id,()=>{const d=copy(pure.CampaignDefinitions);change(d);assert.throws(()=>pure.GameCampaignDomain.validateDefinitions(d));});
check('semantics.current_reverts_once_stays_after_ignores_history',()=>{const w=world();w.campaign.refresh();assert.equal(w.campaign.view().objectives.ore_after.active,false);w.facts.generatorRunning=true;w.facts.corePowered=true;w.campaign.refresh();assert.equal(w.campaign.capture().objectives.ore_after.baseline,30);assert.equal(w.campaign.view().objectives.ore_after.done,false);w.facts.generatorRunning=false;w.facts.corePowered=false;w.campaign.refresh();assert.equal(w.campaign.view().objectives.power_once.done,true);assert.equal(w.campaign.view().objectives.core_current.done,false);w.facts.mined++;w.campaign.refresh();assert.equal(w.campaign.view().objectives.ore_after.done,true);});
check('ready_is_not_transition_and_snapshots_are_pure',()=>{const w=world();w.ready();assert.equal(w.campaign.view().ready,true);assert.equal(w.campaign.view().chapter,'base_check');const a=w.campaign.capture();a.activeChapter='forged';assert.equal(w.campaign.view().chapter,'base_check');assert.equal(w.events.length,0);});
check('commands.closed_UI_two_actors_duplicate_and_stale',()=>{const w=world();w.ready();const one=w.cmd(),two=w.cmd({actorId:'b',requestId:'two'});assert.equal(w.campaign.execute(one).ok,true);assert.equal(w.campaign.execute(one).replayed,true);assert.equal(w.campaign.execute(two).ok,false);assert.equal(w.campaign.capture().transitions.length,1);assert.equal(w.events.length,1);assert.equal(w.campaign.view().chapter,'free_preparation');});
for(const [id,extra]of [['foreign',{actorId:'unknown'}],['dead',{actorId:'dead'}],['permissions',{actorId:'guest'}],['stale',{expectedRevision:999}],['wrongChapter',{chapterId:'free_preparation'}],['wrongTarget',{targetId:'other'}],['badRequest',{requestId:''}],['wrongType',{type:'CLAIM'}]])check('commands.reject.'+id,()=>{const w=world();w.ready();const before=w.campaign.capture();assert.equal(w.campaign.execute(w.cmd(extra)).ok,false);assert.deepEqual(w.campaign.capture(),before);});
for(const reason of ['power','distance','target'])check('commands.revalidate.'+reason,()=>{const w=world();w.ready();w.deny('campaign.reason.'+reason);assert.equal(w.campaign.execute(w.cmd()).ok,false);assert.equal(w.campaign.capture().completed.length,0);});
check('commands.reused_id_different_payload_rejected',()=>{const w=world();w.ready();const cmd=w.cmd();w.campaign.execute(cmd);assert.equal(w.campaign.execute({...cmd,targetId:'forged'}).ok,false);});
check('restore_never_emits_or_grants_and_duplicate_survives',()=>{const w=world();w.ready();const cmd=w.cmd();w.campaign.execute(cmd);const saved=w.campaign.capture(),x=world();x.campaign.restore(saved);assert.equal(x.events.length,0);assert.equal(x.campaign.execute(cmd).replayed,true);assert.deepEqual(x.campaign.capture(),saved);});
for(const [id,change]of [['futureSchema',s=>s.schema=2],['futureContent',s=>s.contentRevision=pure.CampaignDefinitions.revision+1],['unknownActive',s=>s.activeChapter='future'],['unknownObjective',s=>s.objectives.unknown={active:true,done:true,baseline:null}],['missingObjective',s=>delete s.objectives.power_once],['forgedCompletion',s=>s.completed=['base_check']],['negativeBaseline',s=>s.objectives.ore_after.baseline=-1],['invalidBoolean',s=>s.objectives.power_once.done=1]])check('save.reject.'+id,()=>{const w=world(),before=w.campaign.capture(),bad=copy(before);change(bad);assert.throws(()=>w.campaign.restore(bad));assert.deepEqual(w.campaign.capture(),before);});
const r=setup('index.html'),E=s=>r.eval(s),J=s=>copy(E(s)),old=setup('qa/stage-a-base/index.html'),oldSave=old.eval('JSON.stringify(captureGameProgress())');
const reset=()=>E("restoreGameProgress(GameSave.newGameData());GameFlow.resume();menuOpen=false;playerDead=false;document.hidden=false;scene='bunker';player.x=1210;player.y=675;stopControls(true);");
function strip(d){d=require('./stage-c1-contract.cjs').project(d);d=require('./stage-ab-contract.cjs').previousLayout(d);delete d.equipment032;delete d.campaign031;delete d.v09.power.deviceEnabled.command_core_l1;delete d.saveVersion;delete d.gameVersion;return d;}
check('migration.R2_decode_is_additive_and_pure',()=>{const before=J('captureGameProgress()'),storage=Object.fromEntries(r.storage),d=J(`decodeGameProgress(${JSON.stringify(oldSave)})`);assert.equal(d.saveVersion,r.eval('SaveFormat.version'));assert.equal(d.campaign031.profile,'legacy');assert.deepEqual(strip(d),strip(JSON.parse(oldSave)));assert.deepEqual(J('captureGameProgress()'),before);assert.deepEqual(Object.fromEntries(r.storage),storage);assert.deepEqual(J(`decodeGameProgress(${JSON.stringify(JSON.stringify(d))})`),d);});
check('migration.old_R2_restore_preserves_equipment_progress_and_geometry',()=>{old.eval("V010Progression.unlock('tools_upgrade',true);V010Progression.record('mined',5);V09Power.running=true;V09Power.fuel=80;");const raw=old.eval('JSON.stringify(captureGameProgress())');old.eval(`restoreGameProgress(decodeGameProgress(${JSON.stringify(raw)}))`);E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(raw)}))`);assert.deepEqual(strip(J('captureGameProgress()')),strip(copy(old.eval('captureGameProgress()'))));assert.deepEqual(J('BunkerLayout.core'),copy(old.eval('BunkerLayout.core')));assert.deepEqual(require('./stage-ab-contract.cjs').previousRooms(J('BunkerLayout.rooms')),copy(old.eval('BunkerLayout.rooms')));assert.deepEqual(J('BunkerLayout.stairs'),copy(old.eval('BunkerLayout.stairs')));assert.equal(E("V010Progression.isUnlocked('tools_upgrade')"),true);});
check('migration.no_starter_rewards_or_backdated_actions',()=>{const before=J('({bag,storage:storageChests,progression:V010Progression.capture()})');E('GameCampaign.refresh(true)');assert.equal(E('GameCampaign.view().objectives.power_once.done'),true);assert.equal(E('GameCampaign.view().objectives.ore_after.done'),false);assert.deepEqual(J('({bag,storage:storageChests,progression:V010Progression.capture()})'),before);});
check('save.current_missing_owner_rejected_before_live_or_slot_changes',()=>{const d=J('captureGameProgress()');delete d.campaign031;const before=J('captureGameProgress()'),storage=Object.fromEntries(r.storage);assert.throws(()=>E(`restoreGameProgress(${JSON.stringify(d)})`));assert.deepEqual(J('captureGameProgress()'),before);assert.deepEqual(Object.fromEntries(r.storage),storage);});
check('new_game_has_separate_profile_no_damage_and_no_old_completion',()=>{reset();assert.equal(E('GameCampaign.capture().profile'),'new');assert.equal(E('GameCampaign.view().completed.length'),0);assert.deepEqual(J('captureGameProgress().base015'),copy(old.eval('GameSave.newGameData().base015')));});
check('UI.offline_journal_and_physical_Core_display_goals',()=>{reset();E("I18n.setLanguage('ru')");assert.equal(E("CommandCoreUI.show('chapters',true)"),true);assert.ok(r.doc.getElementById('campaignJournalOverlay').textContent.includes('Запустить генератор'));assert.equal(r.doc.getElementById('campaignJournalOverlay').querySelector('#campaignAdvance'),null);E('closeOverlay(el("campaignJournalOverlay"));executeInteraction(interactionObjects("bunker").find(o=>o.id===BunkerLayout.core.id));');assert.equal(r.doc.getElementById('commandCoreOverlay').classList.contains('open'),true);assert.ok(r.doc.getElementById('commandCoreOverlay').textContent.includes('Нет питания'));});
check('events_and_polling_update_closed_UI_without_item_transfer_credit',()=>{reset();E('V09Power.running=true;v09PowerChanged()');assert.equal(E('GameCampaign.view().objectives.ore_after.active'),true);E("bag=[];addItem('iron_ore',10);GameCampaign.refresh(true)");assert.equal(E('GameCampaign.view().objectives.ore_after.done'),false);E("V010.emit('mined',{type:'iron_ore',qty:1});");assert.equal(E('GameCampaign.view().ready'),true);assert.equal(E('GameCampaign.view().chapter'),'base_check');});
check('Core.consumer_uses_existing_network_independent_of_UI',()=>{const before=E('V09Power.allocation().load');E('CommandCoreUI.show();closeOverlay(el("commandCoreOverlay"))');assert.equal(E('V09Power.allocation().load'),before);E('V09Power.devices.command_core_l1.enabled=false');assert.ok(Math.abs(before-E('V09Power.allocation().load')-.05)<1e-9);E('V09Power.devices.command_core_l1.enabled=true');});
check('commands.full_inventory_has_no_partial_expense_and_no_new_reward',()=>{E("bag=Array.from({length:BAG_SLOTS},()=>({type:'stone',qty:itemStackLimit('stone',true)}));GameCampaign.refresh(true);window.advanceCommand={type:'ADVANCE_CHAPTER',actorId:GameActors.localId,targetId:BunkerLayout.core.id,chapterId:GameCampaign.view().chapter,expectedRevision:GameCampaign.view().revision,requestId:'integration'};");const before=J('({bag,storage:storageChests,claimed:V010Progression.state.claimed})');assert.equal(E('GameCampaign.execute(advanceCommand).ok'),true);assert.equal(E('GameCampaign.execute(advanceCommand).replayed'),true);assert.deepEqual(J('({bag,storage:storageChests,claimed:V010Progression.state.claimed})'),before);});
check('save_transition_roundtrip_and_duplicate_restores_once',()=>{E('restoreGameProgress(decodeGameProgress(JSON.stringify(captureGameProgress())))');assert.equal(E('GameCampaign.execute(advanceCommand).replayed'),true);assert.equal(E('GameCampaign.capture().transitions.length'),1);});
check('power_off_and_distance_rechecked_on_commit',()=>{reset();E("V09Power.running=true;GameCampaign.refresh(true);V010.emit('mined',{type:'iron_ore',qty:1});window.advanceCommand={type:'ADVANCE_CHAPTER',actorId:GameActors.localId,targetId:BunkerLayout.core.id,chapterId:GameCampaign.view().chapter,expectedRevision:GameCampaign.view().revision,requestId:'recheck'};V09Power.running=false;V010Energy.battery.charge=0;");assert.equal(E('GameCampaign.execute(advanceCommand).reason'),'campaign.reason.power');E('V09Power.running=true;player.x=100;player.y=100;');assert.equal(E('GameCampaign.execute(advanceCommand).reason'),'campaign.reason.distance');assert.equal(E('GameCampaign.view().completed.length'),0);});
check('pause_hidden_resume_does_not_advance_campaign',()=>{reset();const before=J('GameCampaign.capture()');E('document.hidden=true;V09Power.running=true;GameCampaign.tick(1000)');assert.deepEqual(J('GameCampaign.capture()'),before);assert.equal(E('GameCampaign.execute({}).reason'),'campaign.reason.paused');E('document.hidden=false;GameCampaign.tick(250)');assert.equal(E('GameCampaign.view().objectives.power_once.done'),true);});
for(const language of ['ru','en'])for(const mode of ['PC','MOBILE'])check('UI.localized_tabs_and_legacy_access.'+language+'.'+mode,()=>{reset();E(`I18n.setLanguage('${language}');GameInput.setMode('${mode}');CommandCoreUI.show();`);const o=r.doc.getElementById('commandCoreOverlay'),txt=o.textContent;assert.ok(!txt.includes('campaign.'));if(language==='en')assert.ok(!/[А-Яа-яЁё]/.test(txt));assert.equal(o.querySelectorAll('.campaignTabs button').length,4);r.doc.getElementById('coreTab_base').click();assert.ok(o.textContent.includes('0.05')||o.textContent.includes('0,05'));o.querySelectorAll('.campaignLinks button')[0].click();assert.equal(r.doc.getElementById('v010ProgressOverlay').classList.contains('open'),true);E('closeOverlay(el("v010ProgressOverlay"))');});
check('snapshots_do_not_mutate_campaign_or_random_sequence',()=>{reset();const before=J('GameCampaign.capture()');E('window.randomCalls=0;window.savedRandom=Math.random;Math.random=()=>{randomCalls++;return .5};for(let i=0;i<30;i++){GameCampaign.capture();GameCampaign.view();}Math.random=savedRandom;');assert.equal(E('randomCalls'),0);assert.deepEqual(J('GameCampaign.capture()'),before);});
check('console.clean',()=>{assert.deepEqual(r.errors,[]);assert.deepEqual(old.errors,[]);});
const result={version:require('../package.json').version,passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks};fs.writeFileSync('qa/results/campaign.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));if(result.failed)process.exitCode=1;
