// Summarize paired measurements; never label VM timings as phone FPS.
const fs=require('node:fs'),assert=require('node:assert/strict');
const read=name=>JSON.parse(fs.readFileSync(__dirname+'/results/'+name+'.json'));
const base=read('performance-stage4-baseline'),next=read('performance-stage4'),lb=read('loading-stage4-baseline'),ln=read('loading-stage4');
const rb=read('performance-stage4-day-baseline'),rn=read('performance-stage4-day-candidate');
function compare(a,b){assert.equal(a.controlMode,b.controlMode);assert.deepEqual(a.environment,b.environment);assert.deepEqual(a.consoleErrors,[]);assert.deepEqual(b.consoleErrors,[]);return a.scenes.map((x,i)=>{const y=b.scenes[i];assert.equal(x.id,y.id);assert.deepEqual(x.scenario,y.scenario);assert.equal(x.samples,y.samples);assert.equal(x.warmupFrames,y.warmupFrames);assert.deepEqual(x.consoleErrors,[]);assert.deepEqual(y.consoleErrors,[]);return{id:x.id,scenario:x.scenario,reference:{p50Ms:x.combined.p50Ms,p95Ms:x.combined.p95Ms,rssBytes:x.memoryEnd.rss,heapBytes:x.memoryEnd.heapUsed},candidate:{p50Ms:y.combined.p50Ms,p95Ms:y.combined.p95Ms,rssBytes:y.memoryEnd.rss,heapBytes:y.memoryEnd.heapUsed},p50ChangePercent:(y.combined.p50Ms/x.combined.p50Ms-1)*100,p95ChangePercent:(y.combined.p95Ms/x.combined.p95Ms-1)*100};});}
assert.deepEqual(lb.consoleErrors,[]);assert.deepEqual(ln.consoleErrors,[]);assert.deepEqual(lb.domImageSources,ln.domImageSources);
const result={reference:base.gameVersion,candidate:next.gameVersion,pairedScenariosValid:true,sceneResults:compare(base,next),daytimeReverseOrderRecheck:compare(rb,rn),startup:{viewport:ln.viewport,reference:{canvasRequests:lb.canvas.requested,compressedCanvasBytes:lb.canvas.compressedBytes,estimatedCanvasRGBABytes:lb.canvas.estimatedRGBABytes,uniqueCanvasAndDOMFiles:lb.uniqueCanvasAndDOMResources,uniqueCanvasAndDOMBytes:lb.uniqueCanvasAndDOMCompressedBytes,localBootAndDecodeMs:lb.totalLocalBootAndDecodeMs,rssBytes:lb.memoryAfter.rss},candidate:{canvasRequests:ln.canvas.requested,compressedCanvasBytes:ln.canvas.compressedBytes,estimatedCanvasRGBABytes:ln.canvas.estimatedRGBABytes,uniqueCanvasAndDOMFiles:ln.uniqueCanvasAndDOMResources,uniqueCanvasAndDOMBytes:ln.uniqueCanvasAndDOMCompressedBytes,localBootAndDecodeMs:ln.totalLocalBootAndDecodeMs,rssBytes:ln.memoryAfter.rss}},interpretation:'Initial daytime p95 increase did not reproduce in a reverse-order targeted recheck. No sustained slowdown established by these measurements; real phone validation remains manual.',limitations:[...base.limitations,...ln.limitations]};
fs.writeFileSync(__dirname+'/results/performance-stage4-comparison.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result.sceneResults.map(r=>({scene:r.id,p50Change:r.p50ChangePercent,p95Change:r.p95ChangePercent})),null,2));
