// Device/event regression against real owners. The DOM is modeled; this is not
// a substitute for the native browser/phone check in the release report.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {setup}=require('./runtime.cjs');process.chdir(path.resolve(__dirname,'..'));
const checks=[],key='last_base_control_mode_v1';
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack?.slice(0,3000)||e.message});}}
const clone=x=>JSON.parse(JSON.stringify(x));
const mediaPC={'(pointer: fine)':true,'(hover: hover)':true,'(any-pointer: fine)':true,'(any-hover: hover)':true};
const mediaTouch={'(pointer: coarse)':true};
for(const [id,storage,options,expected,pref]of [
 ['desktop',{}, {media:mediaPC},'PC','AUTO'],
 ['narrowDesktop',{}, {media:mediaPC,width:380,height:840},'PC','AUTO'],
 ['wideTouch',{}, {media:mediaTouch,maxTouchPoints:5,width:1366,height:1024},'MOBILE','AUTO'],
 ['touchLaptop',{}, {media:mediaPC,maxTouchPoints:10},'PC','AUTO'],
 ['touchFallback',{}, {maxTouchPoints:5},'MOBILE','AUTO'],
 ['manualPC',{[key]:'PC'}, {media:mediaTouch,maxTouchPoints:5},'PC','PC'],
 ['manualMobile',{[key]:'MOBILE'}, {media:mediaPC},'MOBILE','MOBILE'],
 ['corruptSetting',{[key]:'BROKEN'}, {media:mediaTouch,maxTouchPoints:5},'MOBILE','AUTO']
])check('mode.initial.'+id,()=>{const r=setup('index.html',storage,options);assert.equal(r.eval('GameInput.mode'),expected);assert.equal(r.eval('GameInput.preference'),pref);assert.deepEqual(r.errors,[]);});
const r=setup('index.html',{}, {media:mediaPC}),E=s=>r.eval(s),canvas=r.doc.getElementById('canvas');
const baseline=E('JSON.stringify(captureGameProgress())');
function fresh(mode='PC',which='surface'){
 E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(baseline)}));for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);GameInput.setMode(${JSON.stringify(mode)});stopControls(true);V014Controls.stopRoute();V010Camera.resetTouch();el('fade').classList.remove('show');scene=${JSON.stringify(which)};player.wallLevel=false;player.x=800;player.y=850;playerDead=false;document.hidden=false;frameScale=1;zombies=[];V013City.setFloor(0);updateCamera();`);
}
function screen(point){return E(`worldToScreen(${point.x},${point.y})`);}
function pointer(type,point={},props={},target=canvas){const p=point.x===undefined?{x:640,y:400}:point;return r.emit(type,target,{pointerId:1,pointerType:'mouse',clientX:p.x,clientY:p.y,button:0,detail:1,...props});}
function tap(p,props={}){pointer('pointerdown',p,props);pointer('pointerup',p,props);pointer('click',p,props);}
function keypress(code,keyValue=code){return r.emit('keydown',r.doc,{code,key:keyValue});}
function noOverlay(){return E('!document.querySelector(".overlay.open")');}
function ground(){return E(`(()=>{for(const [x,y]of [[800,950],[750,950],[850,950],[850,850],[750,850]])if(!worldCollision(x,y,player.radius,scene)&&!hitInteraction(x,y))return {x,y};throw Error('no test ground');})()`);}
E(`window.inputCalls={move:0,object:0,execute:0,shoot:0,reload:0,slot:0};
 window.moveOriginal=approachPoint;approachPoint=function(...a){inputCalls.move++;return moveOriginal(...a);};
 window.objectOriginal=approachObject;approachObject=function(...a){inputCalls.object++;return objectOriginal(...a);};
 window.executeOriginal=executeInteraction;executeInteraction=function(...a){inputCalls.execute++;return executeOriginal(...a);};
 window.shootOriginal=shoot;shoot=function(...a){inputCalls.shoot++;return shootOriginal(...a);};
 window.reloadOriginal=reloadWeapon;reloadWeapon=function(...a){inputCalls.reload++;return reloadOriginal(...a);};
 window.slotOriginal=selectHandSlot;selectHandSlot=function(...a){inputCalls.slot++;return slotOriginal(...a);};`);
const resetCounts=()=>E('for(const k of Object.keys(inputCalls))inputCalls[k]=0;');
function equip(){E("V013Inventory.equip('rifle_ak74');window.testGun=V010Combat.currentWeapon();testGun.rounds=20;lastShot=0;V010Combat.cancelReload();");}
check('pc.clickMovesExactlyOnce',()=>{fresh();resetCounts();const g=ground();tap(screen(g));assert.equal(E('inputCalls.move'),1);assert.ok(E('navigation'));assert.equal(E('inputCalls.shoot'),0);assert.equal(E('leftPointerId'),null);});
check('pc.hiddenJoystickHasNoHitZone',()=>{fresh();resetCounts();const p=E('joystickCenters().left');tap(p);assert.equal(E(`joystickAt(${p.x},${p.y})`),null);assert.equal(E('leftPointerId'),null);assert.equal(E('inputCalls.move'),1);assert.equal(E('firing'),false);});
check('pc.noWASD',()=>{fresh();resetCounts();for(const k of ['W','A','S','D'])keypress('Key'+k,k.toLowerCase());assert.equal(E('inputCalls.move'),0);assert.equal(E('movePower'),0);});
check('pc.holdToFollowPreserved',()=>{fresh();resetCounts();const p=screen(ground());pointer('pointerdown',p);r.advance(200);E('updatePointerFollow();');assert.ok(E('objectPointer.following&&navigation._pointerFollow'));assert.equal(E('inputCalls.move'),0);pointer('pointerup',p);assert.equal(E('inputCalls.move'),1);assert.ok(E('navigation'));});
check('pc.hoverNeverMovesOrFires',()=>{fresh();resetCounts();for(let i=0;i<30;i++)pointer('pointermove',{x:200+i,y:200},{buttons:0});assert.deepEqual(clone(E('inputCalls')),{move:0,object:0,execute:0,shoot:0,reload:0,slot:0});});
check('pc.RMBFireUsesExistingWeaponOnce',()=>{fresh();equip();resetCounts();const p=screen({x:1000,y:850});pointer('pointerdown',p,{button:2,buttons:2});assert.equal(E('inputCalls.shoot'),1);assert.equal(E('testGun.rounds'),19);assert.equal(E('inputCalls.move'),0);assert.equal(E('objectPointer'),null);assert.ok(E('GameInput.pcFiring&&rightAimActive&&firing'));pointer('pointerup',p,{button:2,buttons:0});pointer('click',p,{button:2,buttons:0});assert.equal(E('testGun.rounds'),19);assert.equal(E('firing||rightAimActive||GameInput.pcFiring'),false);});
check('pc.RMBAimFollowsCursor',()=>{fresh();equip();pointer('pointerdown',screen({x:1000,y:850}),{button:2,buttons:2});pointer('pointermove',screen({x:800,y:1050}),{buttons:2});assert.ok(E('player.aimY>.999&&Math.abs(player.aimX)<.001'));pointer('pointerup',{}, {button:2});});
check('pc.targetLockPreserved',()=>{fresh();equip();E('zombies=[makeZombie(800,1030)];');tap(screen({x:800,y:1030}));assert.ok(E('V0105.target===zombies[0]'));const p=screen({x:1000,y:850});pointer('pointerdown',p,{button:2,buttons:2});assert.ok(E('player.aimY>.999&&Math.abs(player.aimX)<.001'));pointer('pointerup',p,{button:2});});
check('pc.buttonChordDoesNotMove',()=>{fresh();equip();resetCounts();const p=screen(ground());pointer('pointerdown',p,{button:2,buttons:2});pointer('pointermove',p,{button:0,buttons:3});pointer('pointermove',p,{button:2,buttons:1});assert.equal(E('firing'),false);pointer('pointerup',p,{button:0,buttons:0});assert.equal(E('inputCalls.move'),0);assert.equal(E('inputCalls.shoot'),1);});
for(const [id,event]of [['cancel','pointercancel'],['lostCapture','lostpointercapture']])check('pc.release.'+id,()=>{fresh();equip();const p=screen(ground());pointer('pointerdown',p,{button:2,buttons:2});pointer(event,p,{button:2});assert.equal(E('firing||rightAimActive||GameInput.pcFiring'),false);});
for(const [id,code]of [['blur',null],['hidden',"document.hidden=true;"],['menu',"openOverlay(el('settingsOverlay'));"],['transition',"transition('TEST',()=>{});"],['death','killPlayer();GameInput.refreshAim();']])check('pc.release.'+id,()=>{fresh();equip();pointer('pointerdown',screen(ground()),{button:2,buttons:2});if(code)E(code);if(id==='blur')r.dispatch('blur');if(id==='hidden')r.emit('visibilitychange',r.doc);assert.equal(E('firing||rightAimActive||GameInput.pcFiring'),false);});
check('pc.reload.RAndButtonSameOwner',()=>{fresh();equip();resetCounts();keypress('KeyR','r');assert.equal(E('inputCalls.reload'),1);E('V010Combat.cancelReload();');r.emit('click',r.doc.getElementById('v010ReloadButton'),{detail:0});assert.equal(E('inputCalls.reload'),2);});
check('keyboard.noRepeatNoModifiersNoEditableInput',()=>{fresh();equip();resetCounts();r.emit('keydown',r.doc,{code:'KeyR',key:'r',repeat:true});r.emit('keydown',r.doc,{code:'KeyR',key:'r',ctrlKey:true});r.emit('keydown',r.doc,{code:'KeyR',key:'r',isComposing:true});const input=r.doc.createElement('input');r.doc.body.append(input);r.emit('keydown',input,{code:'KeyR',key:'r'});const editable=r.doc.createElement('div');editable.setAttribute('contenteditable','true');r.doc.body.append(editable);r.emit('keydown',editable,{code:'KeyR',key:'r'});assert.equal(E('inputCalls.reload'),0);input.remove();editable.remove();});
check('keyboard.layoutIndependentCodes',()=>{fresh();equip();resetCounts();keypress('KeyR','к');assert.equal(E('inputCalls.reload'),1);});
for(let i=0;i<5;i++)check('pc.quickSlot.'+(i+1),()=>{fresh();resetCounts();const expected=E(`handSlots[${i}]?${i}:activeHandSlot`);keypress('Digit'+(i+1),String(i+1));assert.equal(E('activeHandSlot'),expected);assert.equal(E('inputCalls.slot'),1);});
check('pc.inventoryToggle',()=>{fresh();keypress('KeyI','i');assert.ok(E('el("inventoryOverlay").classList.contains("open")'));keypress('KeyI','i');assert.ok(noOverlay());});
check('pc.mapToggle',()=>{fresh();keypress('KeyM','m');assert.ok(E('el("v010MapOverlay").classList.contains("open")'));keypress('KeyM','m');assert.ok(noOverlay());});
check('pc.escapeSettings',()=>{fresh();keypress('Escape');assert.ok(E('el("settingsOverlay").classList.contains("open")'));keypress('Escape');assert.ok(noOverlay());});
check('pc.escapeOneNestedWindowOnly',()=>{fresh();E('openOverlay(el("inventoryOverlay"));V0162Quick.open(4);');keypress('Escape');assert.ok(E('el("inventoryOverlay").classList.contains("open")&&!el("v0162QuickPicker").classList.contains("open")'));keypress('Escape');assert.ok(noOverlay());});
check('pc.escapeMapOptionsFirst',()=>{fresh();keypress('KeyM','m');E('V012Map.setOptions(true);');keypress('Escape');assert.ok(E('el("v011MapFilterOptions").hidden&&el("v010MapOverlay").classList.contains("open")'));keypress('Escape');assert.ok(noOverlay());});
check('pc.escapeCannotDismissDeath',()=>{fresh();E('killPlayer();');keypress('Escape');assert.ok(E('el("deathOverlay").classList.contains("open")'));});
check('pc.shortcutCannotActThroughMenu',()=>{fresh();equip();E('openOverlay(el("settingsOverlay"));');resetCounts();for(const k of ['KeyR','Digit1','KeyC','KeyM','KeyI'])keypress(k);assert.equal(E('inputCalls.reload+inputCalls.slot'),0);assert.ok(E('el("settingsOverlay").classList.contains("open")'));});
check('pc.contextmenuWorldOnly',()=>{fresh();assert.ok(pointer('contextmenu',{}, {button:2}).defaultPrevented);assert.equal(pointer('contextmenu',{}, {button:2},r.doc.getElementById('hotbar')).defaultPrevented,false);});
check('mode.switchReleasesBothJoysticks',()=>{fresh('MOBILE');equip();const c=E('joystickCenters()');pointer('pointerdown',{x:c.left.x+22,y:c.left.y},{pointerId:5,pointerType:'touch'});pointer('pointerdown',{x:c.right.x+28,y:c.right.y},{pointerId:6,pointerType:'touch'});assert.ok(E('movePower>0&&firing'));E('GameInput.setMode("PC");');assert.ok(E('leftPointerId===null&&rightPointerId===null&&movePower===0&&!firing&&!rightAimActive'));pointer('pointerup',c.left,{pointerId:5,pointerType:'touch'});pointer('pointerup',c.right,{pointerId:6,pointerType:'touch'});assert.equal(E('movePower'),0);});
check('mode.switchReleasesRMB',()=>{fresh();equip();pointer('pointerdown',screen(ground()),{button:2,buttons:2});E('GameInput.setMode("MOBILE");');assert.equal(E('firing||rightAimActive||GameInput.pcFiring'),false);});
check('mode.noDuplicateListenersOrPlayer',()=>{fresh();const before=r.listenerCounts();E('window.samePlayer=player;');for(let i=0;i<100;i++)E('GameInput.setMode("MOBILE");GameInput.setMode("PC");');assert.deepEqual(r.listenerCounts(),before);assert.ok(E('player===samePlayer'));resetCounts();tap(screen(ground()));assert.equal(E('inputCalls.move'),1);});
check('mode.savedSeparatelyFromAllSlots',()=>{fresh();const raw=E('JSON.stringify(captureGameProgress())'),before=Object.fromEntries(r.storage);E('GameInput.setMode("MOBILE");');assert.equal(r.storage.get(key),'MOBILE');assert.equal(E('JSON.stringify(captureGameProgress())'),raw);for(const [k,v]of Object.entries(before))if(k!==key)assert.equal(r.storage.get(k),v);});
check('mode.persistenceReload',()=>{const next=setup('index.html',Object.fromEntries(r.storage),{media:mediaPC});assert.equal(next.eval('GameInput.preference'), 'MOBILE');assert.equal(next.eval('GameInput.mode'),'MOBILE');});
check('mode.settingsSelectionUsesLiveSwitch',()=>{fresh();const s=r.doc.getElementById('controlModeSelect');s.value='MOBILE';r.emit('change',s);assert.equal(E('GameInput.mode'),'MOBILE');assert.equal(E('el("actionButton").getAttribute("aria-hidden")'),'false');s.value='PC';r.emit('change',s);assert.equal(E('el("actionButton").getAttribute("aria-hidden")'),'true');});
check('mode.invalidValueRejected',()=>{fresh();assert.equal(E('GameInput.setMode("BAD")'),false);assert.equal(E('GameInput.preference'),'PC');});
check('mode.storageDeniedIsSafe',()=>{fresh();E('window.oldSet=localStorage.setItem;localStorage.setItem=()=>{throw Error("denied")};GameInput.setMode("MOBILE");localStorage.setItem=oldSet;');assert.equal(E('GameInput.mode'),'MOBILE');assert.ok(E('el("message").textContent.includes("не разрешил")'));});
check('auto.actualPointerChangesMode',()=>{fresh('AUTO');tap(screen(ground()),{pointerId:6,pointerType:'touch'});assert.equal(E('GameInput.mode'),'MOBILE');tap(screen(ground()));assert.equal(E('GameInput.mode'),'PC');assert.equal(E('GameInput.preference'),'AUTO');});
check('auto.compatibilityClickCannotChangeModeOrDuplicate',()=>{fresh('AUTO');const p=screen(ground());tap(p,{pointerId:6,pointerType:'touch'});resetCounts();pointer('click',p,{pointerType:'mouse'});assert.equal(E('GameInput.mode'),'MOBILE');assert.equal(E('inputCalls.move'),0);});
check('auto.manualOverrideWins',()=>{fresh('MOBILE');tap(screen(ground()));assert.equal(E('GameInput.mode'),'MOBILE');fresh('PC');tap(screen(ground()),{pointerType:'touch',pointerId:6});assert.equal(E('GameInput.mode'),'PC');});
check('auto.capabilitiesCanChange',()=>{fresh('AUTO');r.setCapabilities(mediaTouch,5);assert.equal(E('GameInput.mode'),'MOBILE');r.setCapabilities(mediaPC,5);assert.equal(E('GameInput.mode'),'PC');});
check('mode.layoutAndOrientationPreserved',()=>{fresh('MOBILE');const before=E('JSON.stringify(layouts)');for(const [w,h]of [[390,844],[844,390],[1280,800]]){E(`innerWidth=${w};innerHeight=${h};`);r.dispatch('resize');assert.equal(E('GameInput.mode'),'MOBILE');const p=E('joystickCenters().left');assert.equal(E(`joystickAt(${p.x},${p.y})`),'left');E('GameInput.setMode("PC");GameInput.setMode("MOBILE");');assert.equal(E('JSON.stringify(layouts)'),before);}});
check('mobile.touchActionUsesSameInteraction',()=>{fresh('MOBILE','bunker');E('player.x=800;player.y=800;updateAction();window.actionOriginal=executeInteraction;window.nearTarget=interactionTarget;');resetCounts();r.emit('pointerdown',r.doc.getElementById('actionButton'),{pointerType:'touch'});if(E('!!nearTarget'))assert.equal(E('inputCalls.execute'),1);else assert.ok(E('el("message").textContent.length>0'));});
check('mobile.pinchNeverMovesOrFiresTwice',()=>{fresh('MOBILE');resetCounts();const a={x:450,y:350},b={x:650,y:350};pointer('pointerdown',a,{pointerType:'touch',pointerId:20});pointer('pointerdown',b,{pointerType:'touch',pointerId:21});assert.ok(E('V010Camera.touchActive'));pointer('pointermove',{x:750,y:350},{pointerType:'touch',pointerId:21});pointer('pointerup',a,{pointerType:'touch',pointerId:20});pointer('pointerup',b,{pointerType:'touch',pointerId:21});assert.equal(E('inputCalls.move+inputCalls.shoot'),0);assert.equal(E('objectPointer'),null);});
check('mobile.modeSwitchClearsPinch',()=>{fresh('MOBILE');pointer('pointerdown',{x:450,y:350},{pointerType:'touch',pointerId:20});pointer('pointerdown',{x:650,y:350},{pointerType:'touch',pointerId:21});E('GameInput.setMode("PC");');assert.equal(E('V010Camera.touchActive'),false);});
check('mobile.editorStillOpens',()=>{fresh('MOBILE');r.emit('click',r.doc.getElementById('settingsButton'),{detail:0});r.emit('click',r.doc.getElementById('openControlSettings'),{detail:0});assert.ok(E('el("controlOverlay").classList.contains("open")'));});
// Same touch samples and simulation steps on the accepted build and candidate.
const a=setup('qa/stage3/index.html'),b=setup('index.html',{[key]:'MOBILE'});
for(const runtime of [a,b])runtime.eval("for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);stopControls(true);scene='surface';player.x=800;player.y=850;frameScale=1;zombies=[];V013Inventory.equip('rifle_ak74');V010Combat.currentWeapon().rounds=30;lastShot=0;updateCamera();");
const snap=runtime=>clone(runtime.eval('({moveX,moveY,movePower,player,aimPower,rightAimActive,firing,leftPointerId,rightPointerId,rounds:V010Combat.currentWeapon()?.rounds,bullets})'));
for(const [id,type,side,dx,dy,pointerId]of [
 ['leftBegin','pointerdown','left',22,0,8],['leftMove','pointermove','left',24,12,8],['rightBegin','pointerdown','right',30,0,9],['rightMove','pointermove','right',0,30,9],['rightRelease','pointerup','right',0,30,9],['leftRelease','pointerup','left',24,12,8]
])check('mobile.baselineExact.'+id,()=>{for(const q of [a,b]){const c=q.eval('joystickCenters().'+side);q.emit(type,q.doc.getElementById('canvas'),{pointerType:'touch',pointerId,clientX:c.x+dx,clientY:c.y+dy});}assert.deepEqual(snap(b),snap(a));});
check('console.noErrors',()=>{assert.deepEqual(r.errors,[]);assert.deepEqual(a.errors,[]);assert.deepEqual(b.errors,[]);});
const result={version:require('../package.json').version,environment:'VM/Pointer Events model, native Canvas2D; no native browser layout',passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status!=='PASS').length,checks};
fs.mkdirSync('qa/results',{recursive:true});fs.writeFileSync('qa/results/controls.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(c=>c.status!=='PASS')}));if(result.failed)process.exitCode=1;
