// Corrective UX contracts, using real owners, routes, input events and saves.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
process.chdir(path.resolve(__dirname,'..'));
const {setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),checks=[],json=v=>JSON.parse(JSON.stringify(v));
const baseline=E('JSON.stringify(captureGameProgress())'),canvas=r.doc.getElementById('canvas');
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack?.slice(0,2500)});}}
function reset(mode='PC'){E(`for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);GameFlow.resume();restoreGameProgress(decodeGameProgress(${JSON.stringify(baseline)}));playerDead=false;document.hidden=false;menuOpen=false;GameInput.setMode('${mode}');V014Controls.stopRoute();stopControls();scene='surface';player.wallLevel=false;player.x=800;player.y=850;frameScale=1;zombies=[];el('fade').classList.remove('show');`);}
function frames(n,code='update();'){for(let i=0;i<n;i++){r.advance(17);E(code);}}
function routeTo(x,y,mode='point'){assert.equal(E(`GameActions.dispatch('MOVE',{kind:'${mode}',x:${x},y:${y}})`),true);}
const routeFrames=n=>frames(n,'V09Power.tick(1/60);V011Living.tick(16.667);updatePlayer();');
function equip(){E("bag=[];addItem('rifle_ak74',1);addItem('ammo',100);V013Inventory.equip('rifle_ak74');V010Combat.currentWeapon().rounds=0;");}
for(const mode of ['PC','MOBILE']){
 for(const kind of ['point','route'])for(const action of ['target','reload','slot','inventory','settings','map','drone'])check(`${mode}.movement.${kind}.${action}`,()=>{
  reset(mode);equip();routeTo(920,850,kind);frames(1,'updatePlayer()');const start=E('player.x');
  if(action==='target')E("zombies=[makeZombie(870,780)];GameActions.dispatch('WORLD_TARGET',{x:870,y:780});");
  if(action==='reload')assert.equal(E("GameActions.dispatch('RELOAD')"),true);
  if(action==='slot')E("GameActions.dispatch('SELECT_SLOT',{index:0})");
  if(action==='drone')E('V014Robots.open()');
  if(['inventory','settings','map'].includes(action))E(`GameActions.dispatch('${action.toUpperCase()}')`);
  assert.ok(E('!!navigation'));frames(8,'updatePlayer();V010Combat.tick(16.667);');assert.ok(E('player.x')>start+1);
 });
 check(`${mode}.ui.worldAndAttacksContinue`,()=>{reset(mode);E("player.x=1700;player.y=1250;zombies=[makeZombie(1735,1250)];V017Monsters.prepare(zombies[0]);openOverlay(el('inventoryOverlay'));");const clock=E('WorldClock.capture().minute'),hp=E('player.health');frames(100);assert.ok(E('WorldClock.capture().minute')>clock);assert.ok(E('player.health')<hp);});
 check(`${mode}.loot.selectedAndLast`,()=>{reset(mode);E("bag=[];openLoot({id:'ux_loot',kind:'car',searched:true,loot:[{type:'wood',qty:1},{type:'parts',qty:2}]});");r.doc.getElementById('lootList').children[0].click();assert.equal(E("V0163Loot.take('bag')"),true);assert.equal(E("el('lootOverlay').classList.contains('open')"),true);assert.equal(E('activeLoot.length'),1);E("V0163Loot.take('bag')");assert.equal(E("el('lootOverlay').classList.contains('open')"),false);assert.equal(E('activeLootObject.loot.length'),0);});
 for(const source of ['car','house'])check(`${mode}.loot.takeAll.${source}`,()=>{reset(mode);E(`bag=[];openLoot({id:'ux_loot',kind:'${source}',searched:true,loot:[{type:'wood',qty:2},{type:'parts',qty:2}]});V0163Loot.take('bag');`);assert.equal(E("el('lootOverlay').classList.contains('open')"),false);assert.equal(E('bagCount("wood")+bagCount("parts")'),4);});
 check(`${mode}.loot.partialStaysOpen`,()=>{reset(mode);E("bag=Array.from({length:BAG_SLOTS},()=>({type:'wood',qty:100}));bag[0].qty=99;openLoot({id:'ux_loot',kind:'car',searched:true,loot:[{type:'wood',qty:4}]});V0163Loot.take('bag');");assert.equal(E('activeLoot[0].qty'),3);assert.equal(E("el('lootOverlay').classList.contains('open')"),true);});
 for(const kind of ['point','route'])check(`${mode}.bath.${kind}.closedThenOneCommand`,()=>{reset(mode);E("scene='bunker';player.x=1030;player.y=-60;V09Power.running=true;V09Power.fuel=50;for(let i=0;i<5;i++)V011Living.tick(100);invalidateGeometry();");assert.equal(E('V011Living.state().doorProgress'),0);routeTo(1030,190,kind);assert.equal(E('V011Living.state().doorProgress'),0);assert.ok(E('!!navigation||V014Controls.planning'));routeFrames(230);assert.ok(E('Math.hypot(player.x-1030,player.y-190)')<3,E('JSON.stringify({x:player.x,y:player.y,nav:navigation})'));});
 check(`${mode}.gate.noRemoteOpenAndOneCommand`,()=>{reset(mode);E('player.x=800;player.y=900;gateOpen=false;invalidateGeometry();');routeTo(800,1220);assert.equal(E('gateOpen'),false);routeFrames(250);assert.ok(E('Math.hypot(player.x-800,player.y-1220)')<3);assert.equal(E('gateOpen'),true);});
 check(`${mode}.stairs.exactFourCentered`,()=>{reset(mode);assert.equal(E('V091Fortress.stairs.length'),4);assert.deepEqual(json(E('V091Fortress.stairs.map(s=>s.side).sort()')),['E','N','S','W']);assert.ok(E('V091Fortress.stairs.every(s=>!worldCollision(s.foot.x,s.foot.y,player.radius,"surface")&&!V091Fortress.elevatedCollision(s.x,s.y,player.radius))'));});
 for(let i=0;i<4;i++)check(`${mode}.stairs.${i}.climbAndDescend`,()=>{reset(mode);E(`window.stair=V091Fortress.stairs[${i}];player.x=stair.foot.x;player.y=stair.foot.y;GameActions.dispatch('INTERACT',{id:'v091stairs_'+stair.id,kind:'v091stairs'});`);frames(50,'updatePlayer()');assert.equal(E('player.wallLevel'),true);E("GameActions.dispatch('INTERACT',{id:'v091stairs_'+stair.id,kind:'v091stairs'});updateAutoWalk();");frames(50,'updatePlayer()');assert.equal(E('player.wallLevel'),false);});
}
check('mobile.heldStick.targetReloadAndUI',()=>{reset('MOBILE');equip();E('leftPointerId=71;moveX=1;moveY=0;movePower=.6;zombies=[makeZombie(870,780)];updateCamera();');const p=E('worldToScreen(870,780)');r.emit('pointerdown',canvas,{pointerId:72,pointerType:'touch',clientX:p.x,clientY:p.y,button:0});assert.equal(E('V0105.target===zombies[0]'),true);assert.equal(E('movePower'),.6);assert.equal(E("GameActions.dispatch('RELOAD')"),true);E("GameActions.dispatch('INVENTORY')");assert.equal(E('movePower'),.6);r.emit('pointerup',r.doc.getElementById('inventoryOverlay'),{pointerId:71,pointerType:'touch',clientX:0,clientY:0});assert.equal(E('leftPointerId'),null);assert.equal(E('movePower'),0);});
check('doors.unpoweredNotPotentiallyOpen',()=>{reset();E('scene="bunker";V09Power.running=false;V010Energy.battery.charge=0;window.door=v09Doors[0];door.manual=false;door.open=0;');assert.equal(E('GamePassages.plan(()=>GamePassages.canPlanThrough(door.id))'),false);E('door.manual=true');assert.equal(E('GamePassages.plan(()=>GamePassages.canPlanThrough(door.id))'),true);});
check('stationary.miningStopsBothRoutes',()=>{for(const kind of ['point','route']){reset();E("bag=[];addItem('pickaxe',1);V013Inventory.equip('pickaxe');window.ore=interactionObjects('surface').find(o=>o.kind==='ore09');player.x=ore.x+ore.r+25;player.y=ore.y;");routeTo(E('player.x')+35,E('player.y'),kind);E('executeInteraction(ore)');assert.equal(E('navigation'),null);assert.equal(E('movePower'),0);assert.ok(E('V09World.miningState()'));}});
check('pause.explicitRetained',()=>{reset();const clock=E('WorldClock.capture().minute');E('GameFlow.pause();gameLoop(performance.now()+16.667)');assert.equal(E('WorldClock.capture().minute'),clock);E('GameFlow.resume();gameLoop(performance.now()+33.334)');assert.ok(E('WorldClock.capture().minute')>clock);});
check('ui.reloadCompletes',()=>{reset();equip();E("reloadWeapon();openOverlay(el('settingsOverlay'));V010Combat.tick(10000);");assert.equal(E('V010Combat.reloading'),null);assert.ok(E('V010Combat.currentWeapon().rounds')>0);});
for(const hp of [0,1,74,100])for(const station of [false,true])check(`drone.repair.hp${hp}.station${station}`,()=>{reset();E(`scene='bunker';player.x=V014Robots.dockPosition().x;player.y=V014Robots.dockPosition().y+35;Object.assign(V014Robots.state,V014Robots.dockPosition(),{task:'docked',packed:false,hp:${hp},battery:0});bag=[];addItem('parts',10);`);const before=E('bagCount("parts")'),ok=E(`V014Robots.repair(${station})`);assert.equal(ok,hp<100&&(station||hp>0));assert.equal(E('V014Robots.state.battery'),0);assert.equal(E('V014Robots.state.hp'),ok?100:hp);assert.equal(E('bagCount("parts")'),before-(ok?Math.ceil((100-hp)/25):0));});
check('drone.repair.noMaterialsAtomic',()=>{reset();E("scene='bunker';player.x=V014Robots.dockPosition().x;player.y=V014Robots.dockPosition().y+35;V014Robots.state.hp=0;bag=[];");const before=E('JSON.stringify(V014Robots.state)');assert.equal(E('V014Robots.repair(true)'),false);assert.equal(E('JSON.stringify(V014Robots.state)'),before);});
check('drone.recovery.packInstallRepairLoad',()=>{reset();E("scene='surface';player.x=800;player.y=850;Object.assign(V014Robots.state,{x:820,y:850,scene:'surface',task:'disabled',packed:false,hp:0,battery:0});bag=[];addItem('parts',5);");assert.equal(E('V014Robots.follow()'),false);assert.equal(E('V014Robots.pack()'),true);E("scene='bunker';player.x=V014Robots.dockPosition().x;player.y=V014Robots.dockPosition().y+35;");assert.equal(E('V014Robots.install()'),true);E('V014Robots.tick(100)');assert.equal(E('V014Robots.atDock()'),true);assert.equal(E('V014Robots.repair(true)'),true);const saved=E('JSON.stringify(captureGameProgress())');E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(saved)}))`);assert.equal(E('V014Robots.state.hp'),100);assert.equal(E('V014Robots.state.battery'),0);});
check('drone.repair.priceDataDriven',()=>{reset();E("scene='bunker';player.x=V014Robots.dockPosition().x;player.y=V014Robots.dockPosition().y+35;V014Robots.state.hp=50;bag=[];addItem('parts',10);V014Robots.definition.repair.durabilityPerUnit=10;");try{assert.equal(E('V014Robots.repair(true)'),true);assert.equal(E('bagCount("parts")'),5);}finally{E('V014Robots.definition.repair.durabilityPerUnit=25');}});
for(const lang of ['ru','en'])check('drone.ui.terminology.'+lang,()=>{reset();E(`I18n.setLanguage('${lang}');V014Robots.open();V014Robots.openStation();`);for(const id of ['v014DronePanel','v0151Station']){const t=r.doc.getElementById(id).textContent;assert.ok(t.includes(lang==='ru'?'Прочность':'Durability'),t);assert.ok(t.includes(lang==='ru'?'Заряд':'Battery'));}E("I18n.setLanguage('ru')");});
check('worldEvents.advanceAcrossBoundaryInUI',()=>{reset();E("WorldClock.restore({schema:1,day:10,minute:359.99});openOverlay(el('settingsOverlay'));");frames(5);assert.equal(E("WorldEvents.isActive('day_x')"),false);});
for(let i=0;i<7;i++)check('doors.powered.'+i+'.oneCommand',()=>{reset();E(`scene='bunker';V09Power.running=true;V09Power.fuel=80;window.door=v09Doors.filter(d=>BunkerLayout.roomActive(d.room))[${i}];door.open=0;door.manual=false;door.away=4;window.cx=door.x+door.w/2;window.cy=door.y+door.h/2;player.x=door.horizontal?cx:cx+(BunkerLayout.rooms[door.room].side==='left'?90:-90);player.y=door.horizontal?cy-95:cy;invalidateGeometry();`);const tx=E("door.horizontal?cx:cx+(BunkerLayout.rooms[door.room].side==='left'?-80:80)"),ty=E("door.horizontal?cy+80:door.room==='room5'?cy+40:cy");assert.equal(E(`worldCollision(${tx},${ty},player.radius,'bunker')`),false);routeTo(tx,ty);assert.equal(E('door.open'),0);routeFrames(240);assert.ok(E(`Math.hypot(player.x-(${tx}),player.y-(${ty}))`)<3,E('JSON.stringify({x:player.x,y:player.y,nav:navigation})'));});
check('stairs.destroyedSupportUnavailable',()=>{reset();E('window.st=V091Fortress.stairs[0];V020Walls.supportAt(st.x,st.y).hp=0;V015Base.changed();');assert.equal(E('V020Walls.usable(st)'),false);assert.equal(E("interactionObjects().some(o=>o.id==='v091stairs_'+st.id)"),false);});
check('ui.droneContinuesFollowing',()=>{reset();E("Object.assign(V014Robots.state,{scene:'surface',x:950,y:850,hp:100,battery:100,packed:false,task:'follow'});openOverlay(el('inventoryOverlay'));window.beforeDrone=V014Robots.state.x;");frames(20);assert.ok(E('V014Robots.state.x<beforeDrone'));});
check('ui.stationContinuesCharging',()=>{reset();E("scene='bunker';player.x=V014Robots.dockPosition().x;player.y=V014Robots.dockPosition().y+35;V09Power.running=true;V09Power.fuel=80;Object.assign(V014Robots.state,V014Robots.dockPosition(),{task:'docked',battery:20,packed:false,hp:100});V014Robots.openStation();");frames(30);assert.ok(E('V014Robots.state.battery')>20);});
check('ui.turretContinuesAttacking',()=>{reset();E("V09Power.running=true;V09Power.fuel=80;window.turret=GameDefense.guns()[0];const q=JSON.parse(JSON.stringify(GameEquipment.get(turret.id)));q.state.settings.ammo=100;GameEquipment.change(q);V09Power.devices[turret.id].enabled=true;zombies=[makeZombie(turret.x,turret.y+110)];V017Monsters.prepare(zombies[0]);openOverlay(el('settingsOverlay'));");frames(50);assert.ok(E('GameEquipment.get(turret.id).state.settings.ammo')<100);});
check('architecture.openCloseDoesNotAddLoopsOrListeners',()=>{reset();const a=r.listenerCounts(),loops=json(r.scheduler);for(let i=0;i<10;i++)E("openOverlay(el('settingsOverlay'));closeOverlay(el('settingsOverlay'));");assert.deepEqual(r.listenerCounts(),a);assert.deepEqual(json(r.scheduler),loops);});
for(const mode of ['PC','MOBILE'])for(let i=0;i<4;i++)check(`${mode}.stairs.${i}.approachFromCourtyard`,()=>{reset(mode);E(`window.st=V091Fortress.stairs[${i}];player.x=st.foot.x+(st.foot.x-st.x)*.65;player.y=st.foot.y+(st.foot.y-st.y)*.65;`);assert.equal(E("worldCollision(player.x,player.y,player.radius,'surface')"),false);assert.equal(E("GameActions.dispatch('INTERACT',{id:'v091stairs_'+st.id,kind:'v091stairs'})"),true);frames(130,'updatePlayer()');assert.equal(E('player.wallLevel'),true);});
check('stationary.repeatTreeKeepsExistingWork',()=>{reset();E("bag=[];addItem('axe',1);V013Inventory.equip('axe');window.tree=interactionObjects('surface').find(o=>o.kind==='tree'&&!o.ref.felled);player.x=tree.x+tree.r+25;player.y=tree.y;executeInteraction(tree);window.work=chopState;executeInteraction(tree);");assert.ok(E('work'));assert.equal(E('chopState===work'),true);assert.equal(E('movePower'),0);});
check('passages.dronePowerSnapshotAndActorPermission',()=>{reset();E("window.oldPlanningKey=V014Robots.planningKey;window.oldDoorPowered=V014Robots.motion.doorPowered;window.oldAllocation=V09Power.allocation;V014Robots.planningKey=()=> 'test-drone';V014Robots.motion.doorPowered=()=>true;V09Power.allocation=()=>{throw Error('Unexpected power recomputation in drone path probe')};V09Power.pathfinding=true;");try{assert.equal(E("GamePassages.canPlanThrough('gate')"),true);assert.equal(E("GamePassages.canPlanThrough('living_bath_door')"),true);assert.equal(E("GamePassages.canPlanThrough(v09Doors[0].id)"),true);}finally{E('V014Robots.planningKey=oldPlanningKey;V014Robots.motion.doorPowered=oldDoorPowered;V09Power.allocation=oldAllocation;V09Power.pathfinding=false');}});
check('console.noErrors',()=>assert.deepEqual(r.errors,[]));
const result={version:require('../package.json').version,passed:checks.filter(x=>x.status==='PASS').length,failed:checks.filter(x=>x.status==='FAIL').length,checks};fs.writeFileSync('qa/results/corrective.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(x=>x.status==='FAIL')}));if(result.failed)process.exitCode=1;
