const fs=require('fs'),assert=require('assert/strict'),{boot}=require('./audio-harness.cjs'),checks=[];
function test(id,f){try{f();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack});}}
(async()=>{
 const a=boot(process.cwd(),{beforeScripts:s=>{const Old=s.AudioContext;const p=()=>({value:1,setValueAtTime(v){this.value=v},linearRampToValueAtTime(v){this.value=v}});s.AudioContext=class extends Old{createOscillator(){const source=this.createBufferSource();source.frequency=p();source.buffer={duration:1e9};source.loop=true;return source;}};}});
 await a.load();const {E,J}=a;E("StoryPlayer.cancel();for(const reason of GameFlow.reasons)GameFlow.resume(reason);scene='surface';player.x=800;player.y=850;GameAudio.reset();WorldClock.restore({schema:1,day:10,minute:0});GameAudioWorld.tick(true)");
 test('synth_hum_one_shared_audio_owner',()=>{assert.ok(J('GameAudio.inspect().loopKeys').includes('dayxHum'));let n=a.meter.sources;for(let i=0;i<100;i++)E('GameAudioWorld.tick(true)');assert.equal(a.meter.sources,n);assert.equal(a.meter.contexts,1);});
 test('horde_uses_existing_four_clips_lowpass_pitch',()=>{assert.deepEqual(J('GameAudio.cues.dayXHorde.clips'),['zombie','zombie2','zombie3','zombieAttack']);a.advance(10000);E('GameAudioWorld.tick(true)');assert.ok(a.meter.starts.some(x=>x.rate>=.65&&x.rate<=.95));});
 test('existing_audio_cues_and_gain_unchanged',()=>{const old=fs.readFileSync('qa/dayx-baseline/js/game.js','utf8'),now=fs.readFileSync('src/audio/runtime.js','utf8');const block=s=>s.slice(s.indexOf("  define('gunshot"),s.indexOf('  const transmissionCues='));assert.equal(block(now).replace(/^  define\('dayXHorde'.*\n/m,''),block(old));});
 test('mute_background_reset_stop_hum',()=>{E('masterVolume=0;GameAudio.sync()');assert.equal(E('GameAudio.inspect().loops'),0);E('masterVolume=.7;GameAudio.sync();GameAudioWorld.tick(true)');assert.ok(J('GameAudio.inspect().loopKeys').includes('dayxHum'));E('document.hidden=true;GameAudio.sync()');assert.equal(E('GameAudio.inspect().loops'),0);E('document.hidden=false;GameAudio.sync();GameAudioWorld.tick(true)');});
 test('0600_stops_hum_and_distant_voices',()=>{E('WorldClock.restore({schema:1,day:10,minute:360});GameAudioWorld.tick(true)');assert.ok(!J('GameAudio.inspect().loopKeys').includes('dayxHum'));assert.equal(E('GameAudio.inspect().families.groan'),0);});
 test('zone_transition_does_not_duplicate_hum',()=>{E("WorldClock.restore({schema:1,day:20,minute:100});GameAudioWorld.tick(true);scene='bunker';GameAudioWorld.tick(true);scene='surface';GameAudioWorld.tick(true)");assert.equal(J('GameAudio.inspect().loopKeys').filter(x=>x==='dayxHum').length,1);E('GameAudio.reset()');assert.equal(E('GameAudio.inspect().loops'),0);});
 test('no_runtime_errors',()=>assert.deepEqual(a.r.errors,[]));const out={passed:checks.filter(x=>x.status==='PASS').length,failed:checks.filter(x=>x.status==='FAIL').length,checks,scope:'WebAudio graph mock, not physical-device audibility'};fs.writeFileSync('qa/results/dayx-audio.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out));if(out.failed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
