const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');process.chdir(path.resolve(__dirname,'..'));process.env.LAST_BASE_ASSETS=process.cwd();process.env.LAST_BASE_TEST_LANGUAGE='ru';
const initialHash=crypto.createHash('sha256').update(fs.readFileSync('js/game.js')).digest('hex');
const {setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),J=s=>JSON.parse(E('JSON.stringify('+s+')')),checks=[];
const test=(id,fn)=>{try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack});}console.log(id,checks.at(-1).status);};
const cmd=(a,p={})=>J(`GameDevQA.request(${JSON.stringify(a)},${JSON.stringify(p)})`);
function clean(){E("StoryPlayer.cancel();for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);for(const reason of GameFlow.reasons)GameFlow.resume(reason);menuOpen=false;playerDead=false;document.hidden=false;stopControls(true)");}
function base(){E('GameDevQA.disable();restoreGameProgress(GameNewGame.create());GameStory.request("finish_intro",{outcome:"skipped"})');clean();E("for(let i=1;i<=5;i++){localStorage.removeItem(v09SlotKey(i));localStorage.removeItem(v09BackupKey(i));}GameState.session.activeSlot=1;GameState.session.name='Original';GameState.session.lastVerified=null;GameState.session.blocked=false;saveGameProgress();");}
function enabled(){base();assert.equal(J('GameDevQA.enable()').ok,true);clean();}
function save(){E('window.qaRound=captureGameProgress();restoreGameProgress(decodeGameProgress(JSON.stringify(qaRound)))');clean();}
function frame(ms=16.667){r.advance(ms);E(`frameScale=${ms/16.667};GameDevQA.runFrame(update)`);}
function sameExceptVersion(a,b){a=require('./stage-c2-contract.cjs').project(a);b=require('./stage-c2-contract.cjs').project(b);delete a.gameVersion;delete b.gameVersion;assert.deepEqual(a,b);}
test('disabled_commands_and_events_do_not_mutate',()=>{base();const s=J('captureGameProgress()');assert.equal(cmd('resource',{id:'wood',amount:100}).reason,'disabled');assert.equal(E("WorldEvents.setQAEvent('day_x',true)"),false);assert.equal(E('GameDevQA.enabled'),false);assert.equal(E('!!captureGameProgress().devQA0401'),false);assert.deepEqual(J('captureGameProgress()'),s);});
test('hidden_six_taps_and_read_only_open',()=>{base();E("openOverlay(el('settingsOverlay'));for(let i=0;i<5;i++)el('qaVersion').click()");assert.equal(E("!!el('qaOverlay')?.classList.contains('open')"),false);E("el('qaVersion').click()");assert.equal(E("el('qaOverlay').classList.contains('open')"),true);assert.equal(E('GameDevQA.marked'),false);clean();});
test('activation_forks_original_and_never_overwrites_it',()=>{base();const s=J('captureGameProgress()');assert.equal(J('GameDevQA.enable()').ok,true);assert.equal(E('GameState.session.activeSlot'),2);assert.equal(E('GameDevQA.capture().sourceSlot'),1);cmd('resource',{id:'iron',amount:100});E('saveGameProgress()');r.context.original=s;assert.equal(E("JSON.parse(localStorage.getItem(v09SlotKey(1))).devQA0401===undefined"),true);assert.deepEqual(J('JSON.parse(localStorage.getItem(v09SlotKey(1))).bag'),s.bag);assert.equal(E("JSON.parse(localStorage.getItem(v09SlotKey(2))).devQA0401.label"),'DEV/TEST');});
test('full_slots_reject_without_mutation',()=>{base();E("for(let i=2;i<=5;i++)localStorage.setItem(v09SlotKey(i),localStorage.getItem(v09SlotKey(1)))");const b=J('captureGameProgress()');assert.equal(J('GameDevQA.enable()').reason,'slots');assert.deepEqual(J('captureGameProgress()'),b);});
test('marker_survives_disable_rename_save_load_not_auto_enabled',()=>{enabled();cmd('resource',{id:'wood',amount:10});E("GameDevQA.disable();V09Saves.rename(2,'ordinary looking')");save();assert.equal(E('GameDevQA.marked'),true);assert.equal(E('GameDevQA.enabled'),false);assert.equal(E("el('qaBadge').hidden"),false);assert.equal(E('GameDevQA.capture().commands.revision'),1);});
test('new_game_and_original_load_remove_test_mode',()=>{enabled();cmd('event',{id:'day_x',value:true});cmd('speed',{value:50});E('V09Saves.load(1)');clean();assert.equal(E('GameDevQA.enabled'),false);assert.equal(E('GameDevQA.marked'),false);assert.equal(E("WorldEvents.isActive('day_x')"),false);assert.equal(E('!!GameNewGame.create().devQA0401'),false);});
for(const id of ['wood','stone','iron','copper','coal','fuel','concrete','ammo'])test('resource_'+id,()=>{enabled();E('bag=[]');assert.equal(cmd('resource',{id,amount:1000}).ok,true);assert.equal(E(`bagCount('${id}')`),1000);save();assert.equal(E(`bagCount('${id}')`),1000);});
test('resources_respect_real_capacity',()=>{enabled();E("bag=Array.from({length:BAG_SLOTS},()=>({type:'wood',qty:100}));");const before=J('bag');const x=cmd('resource',{id:'copper',amount:100});assert.equal(x.ok,false);assert.deepEqual(J('bag'),before);});
for(const type of ['automatic_turret','heavy_turret','searchlight','utility_workbench','furnace','storage_crate','base_lamp'])test('real_buildable_'+type,()=>{enabled();const x=cmd('buildable',{id:type});assert.equal(x.ok,true,JSON.stringify(x));assert.equal(E(`GameEquipment.get('${x.instanceId}').typeId`),type);assert.equal(E(`GameCarried.owns('${x.instanceId}')`),true);save();assert.equal(E(`GameCarried.owns('${x.instanceId}')`),true);});
test('singleton_not_duplicated',()=>{enabled();assert.equal(cmd('buildable',{id:'generator'}).reason,'limit');assert.equal(E("GameEquipment.records.filter(r=>r.typeId==='generator').length"),1);});
for(const type of ['normal','heavy','fast','leaper','bloater'])test('spawn_real_'+type,()=>{enabled();const n=E('zombies.length');assert.equal(cmd('spawn',{count:10,type}).count,10);assert.equal(E(`zombies.slice(${n}).every(z=>z.type==='${type}')`),true);save();assert.equal(E('GameDevQA.capture().enemies.length'),10);});
test('spawn_cap_and_selective_cleanup_no_rewards',()=>{enabled();E('zombies=zombies.slice(0,40)');const ids=J('zombies.map(z=>z.instanceId)');cmd('spawn',{count:50,type:'mixed'});cmd('spawn',{count:50,type:'mixed'});assert.equal(cmd('spawn',{count:10,type:'normal'}).reason,'limit');const progress=J('V010Progression.capture()');assert.equal(cmd('clear').count,100);assert.deepEqual(J('zombies.map(z=>z.instanceId)'),ids);assert.deepEqual(J('V010Progression.capture()'),progress);});
test('command_duplicate_actor_revision_guards_and_save_receipt',()=>{enabled();E("window.packet={actorId:GameActors.localId,instanceId:'qa',requestId:'dup',expectedRevision:GameDevQA.revision,action:'resource',payload:{id:'wood',amount:100}}");const a=J('GameDevQA.execute(packet)'),n=E("bagCount('wood')");assert.equal(a.ok,true);assert.equal(J('GameDevQA.execute(packet)').replayed,true);assert.equal(E("bagCount('wood')"),n);assert.equal(J("GameDevQA.execute({...packet,actorId:'player:other',requestId:'foreign'})").reason,'actor_denied');assert.equal(J("GameDevQA.execute({...packet,requestId:'stale'})").reason,'stale_revision');save();E('GameDevQA.enable()');assert.equal(J('GameDevQA.execute(packet)').replayed,true);assert.equal(E("bagCount('wood')"),n);});
for(const action of ['fuel','battery','power','heal','repair'])test('base_'+action,()=>{enabled();E('player.health=20');const x=cmd(action);assert.equal(x.ok,true,JSON.stringify(x));if(action==='heal')assert.ok(E('player.health')>20);if(action==='fuel'||action==='power')assert.equal(E('V09Power.fuel'),E('V09Power.capacity'));if(action==='battery'||action==='power')assert.equal(E('V010Energy.battery.charge'),E('V010Energy.battery.capacity'));save();});
test('wall_damage_and_restore_use_real_structure',()=>{enabled();const id=E("V015Base.sections.find(s=>s.group==='outer'&&s.hp===s.maxHp).id");assert.equal(cmd('wall',{id,fraction:1}).ok,true);assert.equal(E(`V015Base.byId.get('${id}').hp`),0);save();E('GameDevQA.enable()');cmd('repair');assert.ok(E(`V015Base.byId.get('${id}').hp`)>0);});
for(const id of ['research.station_fabrication','research.precision_weapons','research.scout_service','research.workshop_efficiency'])test('research_real_receipts_'+id,()=>{enabled();const equipment=J('GameEquipment.capture()');assert.equal(cmd('research',{id}).ok,true);assert.equal(E(`GameResearch.capture().completed.includes('${id}')`),true);assert.deepEqual(J('GameEquipment.capture()'),equipment);save();assert.equal(E(`GameResearch.capture().completed.includes('${id}')`),true);E('GameDevQA.enable()');const before=J('GameResearch.capture()');assert.equal(cmd('research',{id}).ok,true);assert.deepEqual(J('GameResearch.capture()'),before);});
for(const id of ['blueprint.precision_weapons','blueprint.scout_service'])test('blueprint_real_source_'+id,()=>{enabled();assert.equal(cmd('blueprint',{id}).ok,true);save();assert.equal(E(`GameResearch.capture().blueprints.includes('${id}')`),true);});
test('chapter_jump_valid_no_future_chapter',()=>{enabled();assert.equal(cmd('chapter',{id:'base_restored'}).ok,true);save();assert.equal(E("GameCampaign.view().completed.includes('chapter_1')"),true);E('GameDevQA.enable()');assert.equal(cmd('chapter',{id:'chapter_2'}).ok,false);assert.equal(cmd('chapter',{id:'chapter_1'}).ok,false);});
test('event_override_saves_resets_on_normal_load',()=>{enabled();assert.equal(cmd('event',{id:'day_x',value:true}).ok,true);assert.equal(E('V017Monsters.isDayX()'),true);save();assert.equal(E('V017Monsters.isDayX()'),true);assert.equal(E('GameDevQA.enabled'),false);E('V09Saves.load(1)');assert.equal(E('V017Monsters.isDayX()'),false);});
test('speed_10_runs_real_clock_fuel_and_combat_timers',()=>{enabled();cmd('power');const minute=E('WorldClock.minute'),fuel=E('V09Power.fuel'),now=E('GameActivity.now()');cmd('speed',{value:10});frame();assert.ok(Math.abs((E('WorldClock.minute')-minute)-.2)<.001);assert.ok(E('V09Power.fuel')<fuel);assert.ok(Math.abs(E('GameActivity.now()')-now-166.67)<.01);assert.equal(J('GameDevQA.metrics()').steps,10);save();assert.equal(J('GameDevQA.metrics()').rate,1);});
test('speed50_and_max_bounded_steps',()=>{enabled();cmd('speed',{value:50});frame();assert.equal(J('GameDevQA.metrics()').steps,50);cmd('speed',{value:'MAX'});frame();assert.equal(J('GameDevQA.metrics()').steps,240);});
test('time_job_runs_clock_stops_at_target_and_can_cancel',()=>{enabled();E('zombies=[]');const start=E('WorldClock.minute');assert.equal(cmd('time',{minutes:60}).ok,true);for(let i=0;i<13&&E('GameDevQA.metrics().target!==null');i++)frame();assert.ok(Math.abs(E('WorldClock.minute')-start-60)<1e-5);assert.equal(J('GameDevQA.metrics()').rate,1);cmd('time',{minutes:1440});frame();cmd('stop');assert.equal(J('GameDevQA.metrics()').target,null);assert.equal(cmd('time',{day:1}).reason,'backward');});
test('time_crosses_day_x_boundary_through_real_tick',()=>{enabled();E('WorldClock.restore({schema:1,day:9,minute:1439.8})');cmd('time',{dayX:true});frame();assert.equal(E('WorldClock.day'),10);assert.equal(E('V017Monsters.isDayX()'),true);assert.equal(J('GameDevQA.metrics()').target,null);});
test('pause_hidden_no_accelerated_ticks',()=>{enabled();cmd('speed',{value:50});const minute=E('WorldClock.minute');E("GameFlow.pause('qa-test')");frame();assert.equal(E('WorldClock.minute'),minute);E("GameFlow.resume('qa-test');document.hidden=true");frame();assert.equal(E('WorldClock.minute'),minute);E('document.hidden=false');frame();assert.ok(E('WorldClock.minute')>minute);});
test('stress_surface_real_placement_then_offzone_ammo',()=>{enabled();E("scene='surface';player.x=800;player.y=850;player.wallLevel=false;V013City.setFloor(0);zombies=[]");const x=cmd('stress');assert.equal(x.ok,true);assert.equal(x.turrets,3);assert.equal(x.count,50);assert.ok(J('GameDevQA.metrics()').activeTurrets>=3);save();assert.ok(J('GameDevQA.metrics()').activeTurrets>=3);E('GameDevQA.enable()');const ids=J("GameDefense.records().filter(r=>r.id.startsWith('build:')&&r.typeId!=='searchlight').map(r=>r.id)");r.context.gunId=ids[0];E("var g=GameEquipment.get(gunId),p=GameDefense.pivot(g);for(const d of Object.values(V09Power.devices))d.enabled=d.id===g.refs.device;var point=null;for(let i=0;i<16&&!point;i++){const a=i*Math.PI/8,q={x:p.x+Math.cos(a)*120,y:p.y+Math.sin(a)*120};if(!GameActivity.collision(q.x,q.y,18)&&GameDefense.clear(g,q))point=q;}if(!point)throw Error('No clear test target');zombies=[makeZombie(point.x,point.y)];V017Monsters.prepare(zombies[0]);scene='bunker';player.x=1210;player.y=680");const ammo=E('GameEquipment.get(gunId).state.settings.ammo');cmd('speed',{value:10});for(let i=0;i<20;i++)frame();assert.ok(E('GameEquipment.get(gunId).state.settings.ammo')<ammo);assert.ok(J('GameDevQA.metrics()').offZone>0);});
for(const [name,change]of [['label',"d.devQA0401.label='NORMAL'"],['revision',"d.devQA0401.commands.revision=-1"],['enemies',"d.devQA0401.enemies=['bad']"],['events',"d.devQA0401.events.threat=true"],['extra',"d.devQA0401.unlocked=true"]])test('reject_invalid_dev_metadata_'+name,()=>{enabled();const before=J('captureGameProgress()');r.context.d=JSON.parse(JSON.stringify(before));E(change);assert.throws(()=>E('restoreGameProgress(d)'));assert.deepEqual(J('captureGameProgress()'),before);});
test('normal_0400_save_load_preserves_all_owners',()=>{const old=setup('qa/dev-base/index.html');const d=JSON.parse(old.eval('JSON.stringify(captureGameProgress())'));r.context.oldSave=d;const decoded=J('decodeGameProgress(JSON.stringify(oldSave))');sameExceptVersion(decoded,JSON.parse(JSON.stringify(d)));E('restoreGameProgress(decodeGameProgress(JSON.stringify(oldSave)))');assert.equal(E('GameDevQA.marked'),false);});
test('disabled_runtime_matches_0400_updates',()=>{const a=setup('qa/dev-base/index.html'),b=setup('index.html');for(const h of [a,b])h.eval("scene='bunker';player.x=1210;player.y=790;stopControls(true);for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o)");for(let i=0;i<120;i++)for(const h of [a,b]){h.advance(17);h.eval('frameScale=1;update()');}sameExceptVersion(JSON.parse(a.eval('JSON.stringify(captureGameProgress())')),JSON.parse(b.eval('JSON.stringify(captureGameProgress())')));});
for(const [w,h]of [[1280,800],[390,844],[844,390]])test('responsive_controls_'+w,()=>{E(`innerWidth=${w};innerHeight=${h}`);enabled();E('GameDevUI.open()');for(const id of ['time','enemies','resources','equipment','base','progress','stress']){r.context.tabId=id;E("el('qaTabs').value=tabId;el('qaTabs').dispatchEvent({type:'change'})");assert.ok(E("el('qaOverlay').querySelectorAll('button').length")>=3);}E("I18n.setLanguage('en')");assert.ok(E("el('qaOverlay').textContent.includes('START I1 STRESS TEST')"));E("I18n.setLanguage('ru')");assert.ok(E("el('qaOverlay').textContent.includes('ЗАПУСТИТЬ I1 STRESS TEST')"));});
test('i1_clock_save_owner_unchanged',()=>{const manifest=require('./dev-base/release_manifest.json');for(const name of ['src/simulation/activity.js','src/simulation/activity-save.js'])assert.equal(crypto.createHash('sha256').update(fs.readFileSync(name)).digest('hex'),manifest.files.find(f=>f.file===name).sha256);});

test('attack_presets_real_raid_and_exact_counts',()=>{for(const kind of ['normal','heavy']){enabled();E('zombies=[]');const x=cmd('attack',{kind});assert.equal(x.count,kind==='normal'?25:50);assert.equal(E('V017Monsters.isDayX()'),true);if(kind==='heavy')assert.equal(E("zombies.every(z=>z.type==='heavy')"),true);save();assert.equal(E('V017Monsters.isDayX()'),true);}});
test('single_spawn_and_cleanup_after_load',()=>{enabled();const n=E('zombies.length');assert.equal(cmd('spawn',{count:1,type:'bloater'}).count,1);save();E('GameDevQA.enable()');const before=J('V010Progression.capture()');assert.equal(cmd('clear').count,1);assert.equal(E('zombies.length'),n);assert.deepEqual(J('V010Progression.capture()'),before);});
test('repair_skips_occupied_broken_wall',()=>{enabled();E("var w=V015Base.sections.find(o=>o.group==='outer');w.hp=0;scene='surface';player.x=w.x+w.w/2;player.y=w.y+w.h/2;player.wallLevel=false;invalidateGeometry()");assert.ok(cmd('repair').skipped>=1);assert.equal(E('w.hp'),0);});
test('stop_available_on_death_pause',()=>{enabled();cmd('speed',{value:50});E('playerDead=true');assert.equal(cmd('stop').ok,true);assert.equal(J('GameDevQA.metrics()').rate,1);assert.equal(cmd('heal').ok,true);assert.equal(E('playerDead'),false);});
test('accelerated_fuse_uses_single_existing_explosion',()=>{enabled();E("scene='bunker';zombies=[makeZombie(1900,1200)];var f=zombies[0];f.type='bloater';V017Monsters.prepare(f);V017Monsters.armFuse(V017Monsters.state(f),GameActivity.now(),650)");cmd('speed',{value:50});frame();assert.equal(E('f.alive'),false);const n=E('V017Monsters.effects.length');frame();assert.ok(E('V017Monsters.effects.length')<=n);});
test('legacy_loot_elapsed_ages_in_accelerated_steps',()=>{enabled();E("var lootQA=scavenges.find(o=>o.kind!=='car');lootQA.searched=true;lootQA.loot=[];lootQA.searchedAt=Date.now()-V091Loot.dayMs+500");cmd('speed',{value:50});frame();assert.equal(E('lootQA.searched'),false);save();});
test('live_metrics_remain_visible_when_panel_closed',()=>{enabled();E("GameDevUI.open();closeOverlay(el('qaOverlay'));GameDevUI.sample(GameDevQA.rawNow()+600,true)");assert.equal(E("el('qaLiveMetrics').hidden"),false);assert.ok(E("el('qaLiveMetrics').textContent.includes('FPS')"));E('GameDevQA.disable()');assert.equal(E("el('qaLiveMetrics').hidden"),true);assert.equal(E("el('qaBadge').hidden"),false);});

test('full_pool_reuses_dead_slots_without_deleting_live_enemies',()=>{enabled();E("zombies=Array.from({length:144},(_,i)=>{const z=makeZombie(2200+i*3,2800);V017Monsters.prepare(z);if(i>=80){z.alive=false;z.health=0;}return z;});window.liveQA=zombies.filter(z=>z.alive).map(z=>z.instanceId)");assert.equal(cmd('spawn',{count:50,type:'normal'}).count,50);assert.equal(E('zombies.length'),144);assert.equal(E('liveQA.every(id=>zombies.some(z=>z.alive&&z.instanceId===id))'),true);save();});
test('legacy_campaign_after_objectives_can_be_opened_for_qa',()=>{base();E('restoreGameProgress(GameSave.newGameData())');clean();assert.equal(J('GameDevQA.enable()').ok,true);assert.equal(cmd('chapter',{id:'free_preparation'}).ok,true);save();assert.equal(E('GameCampaign.view().chapter'),'free_preparation');});
test('runtime_unchanged',()=>assert.equal(crypto.createHash('sha256').update(fs.readFileSync('js/game.js')).digest('hex'),initialHash));
test('no_console_errors',()=>assert.deepEqual(r.errors,[]));
const report={version:'0.40.1',runtimeSha256:crypto.createHash('sha256').update(fs.readFileSync('js/game.js')).digest('hex'),passed:checks.filter(x=>x.status==='PASS').length,failed:checks.filter(x=>x.status==='FAIL').length,checks};fs.writeFileSync('qa/results/dev-qa.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.checks.filter(x=>x.status==='FAIL')));if(report.failed)process.exitCode=1;
