const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');process.chdir(path.resolve(__dirname,'..'));
const {setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),checks=[],baseline=E('JSON.stringify(captureGameProgress())');
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack?.slice(0,1800)});}}
function reset(mode,x,y,scene='bunker',open=false){E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(baseline)}));GameFlow.resume();GameInput.setMode('${mode}');scene='surface';player.x=800;player.y=850;zombies=[];document.hidden=false;playerDead=false;V09Power.running=true;V09Power.fuel=80;V010Energy.battery.charge=V010Energy.battery.capacity;for(const d of v09Doors){d.open=${open?1:0};d.manual=${open};d.away=4;}gateOpen=${open};invalidateGeometry();Object.assign(V014Robots.state,{x:${x},y:${y},scene:'${scene}',task:'guard',packed:false,hp:50,battery:15,lowWarn:false});`);}
function frames(n,until=false){for(let i=0;i<n;i++){const before=E('({x:V014Robots.state.x,y:V014Robots.state.y,scene:V014Robots.state.scene})');r.advance(50);E('V09Power.tick(.05);V011Living.tick(50);V014Robots.tick(50);');const after=E('({x:V014Robots.state.x,y:V014Robots.state.y,scene:V014Robots.state.scene})');if(before.scene===after.scene&&Math.hypot(before.x-after.x,before.y-after.y)>.001)assert.equal(E(`lineClear(${before.x},${before.y},${after.x},${after.y},10,'${after.scene}')`),true,'Physical sweep intersects a wall/panel');if(until&&E('V014Robots.atDock()||V014Robots.stationInfo().blocked'))return i+1;}return n;}
const starts=[['bath',1140,1642],['living',1260,1460],['kitchen',400,30],['workshop',450,1050],['reserve',2070,510],['door-corner',650,612],['outside-gate',800,1240,'surface'],['west-surface',-900,800,'surface']];
for(const mode of ['PC','MOBILE'])for(const open of [false,true])for(const [name,x,y,scene]of starts)check(`${mode}.${open?'open':'closed'}.${name}.repairReturn`,()=>{reset(mode,x,y,scene,open);assert.equal(E(`worldCollision(${x},${y},10,'${scene||'bunker'}')`),false);assert.equal(E('V014Robots.returnToDock()'),true);frames(1800,true);assert.equal(E('V014Robots.atDock()'),true,E('JSON.stringify(V014Robots.returnProgress())'));assert.equal(E('V014Robots.state.hp'),50);assert.ok(E('V014Robots.state.battery>0'));});
for(const mode of ['PC','MOBILE'])check(`${mode}.lowBatteryAutomaticallyReturnsAcrossDoors`,()=>{reset(mode,1210,850);frames(1);assert.equal(E('V014Robots.state.task'),'return');assert.equal(E('V014Robots.state.lowWarn'),true);frames(1800,true);assert.equal(E('V014Robots.atDock()'),true);assert.equal(E('V014Robots.state.lowWarn'),false);const battery=E('V014Robots.state.battery');frames(100);assert.ok(E('V014Robots.state.battery')>battery);});
check('noRoute.waitsStopsRetriesAndExplicitRetryAfterPower',()=>{reset('PC',450,1050);E("V09Power.running=false;V010Energy.battery.charge=0;V014Robots.returnToDock();");frames(1800,true);assert.equal(E('V014Robots.stationInfo().blocked'),true);const searches=E('V014Robots.motion.metrics.searches'),pos=E('JSON.stringify([V014Robots.state.x,V014Robots.state.y])');frames(300);assert.equal(E('V014Robots.motion.metrics.searches'),searches);assert.equal(E('JSON.stringify([V014Robots.state.x,V014Robots.state.y])'),pos);E('V09Power.running=true;V09Power.fuel=80;V014Robots.returnToDock();');frames(1800,true);assert.equal(E('V014Robots.atDock()'),true);});
check('commands.noRemoteGateOpenDuringPlanning',()=>{reset('PC',800,1400,'surface');E('V014Robots.returnToDock()');assert.equal(E('gateOpen'),false);frames(1);assert.equal(E('gateOpen'),false);frames(1800,true);assert.equal(E('gateOpen'),true);assert.equal(E('V014Robots.atDock()'),true);});
check('console.noErrors',()=>assert.deepEqual(r.errors,[]));
const result={version:require('../package.json').version,passed:checks.filter(x=>x.status==='PASS').length,failed:checks.filter(x=>x.status==='FAIL').length,checks};fs.writeFileSync('qa/results/drone-return.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(x=>x.status==='FAIL')}));if(result.failed)process.exitCode=1;
