const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
process.chdir(path.resolve(__dirname,'..'));const {setup}=require('./runtime.cjs');const checks=[];
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack?.slice(0,2500)});}}
const boot=(storage={},options={})=>setup('index.html',storage,{mainMenu:true,language:'en',...options});
const json=x=>JSON.parse(JSON.stringify(x)),storage=r=>Object.fromEntries(r.storage),prefix='survival_base_v09_slot_';
const source=fs.readFileSync('qa/stage2/fixtures/fresh_game.json','utf8');
function save(name,time=100,scene='surface'){const d=JSON.parse(source);d.saveName=name;d.savedAt=time;d.player.scene=scene;return JSON.stringify(d);}
function tap(r,id,type='mouse'){const n=typeof id==='string'?r.doc.getElementById(id):id;r.emit('pointerdown',n,{pointerType:type});r.emit('pointerup',n,{pointerType:type});r.emit('click',n,{pointerType:type,detail:1});}
const r=boot(),E=s=>r.eval(s);
check('boot.menuVisible.noSave.noLoop.noAutoSave',()=>{assert.ok(E('MainMenu.active'));assert.equal(E('GameState.session.ready'),false);assert.ok(!r.doc.getElementById('mainMenu').hidden);assert.equal(r.scheduler.rafRequests,0);assert.equal(r.scheduler.intervals.length,0);assert.equal(r.doc.getElementById('menuContinue').disabled,true);assert.deepEqual(storage(r),{last_base_language_v1:'en'});});
check('boot.timeAndInputCannotActivateSimulation',()=>{const stable=()=>{const d=json(E('captureGameProgress()'));delete d.savedAt;delete d.farmV011.at;for(const key of ['eggMs','milkMs','needMs','breedMs'])delete d.livestock[key];return d;};const before=stable();r.flushTimers(20000);assert.equal(r.scheduler.rafRequests,0);for(const command of ['MOVE','FIRE','INTERACT','RELOAD','MAP','INVENTORY'])assert.equal(E(`GameActions.dispatch('${command}',{x:900,y:900,active:true})`),false);assert.deepEqual(stable(),before);assert.equal([...r.storage.keys()].filter(k=>k.startsWith(prefix)).length,0);});
check('settings.closeAndEscapeKeepMenuPaused',()=>{tap(r,'menuSettings');assert.ok(r.doc.getElementById('settingsOverlay').classList.contains('open'));tap(r,'closeSettings');assert.ok(E('MainMenu.active&&menuOpen'));tap(r,'menuSettings');r.emit('keydown',r.doc.body,{key:'Escape'});assert.ok(!r.doc.getElementById('settingsOverlay').classList.contains('open'));assert.ok(E('MainMenu.active&&menuOpen'));assert.equal(r.scheduler.rafRequests,0);});
check('localization.liveMenuAndSettings',()=>{E("I18n.setLanguage('ru')");assert.equal(r.doc.getElementById('menuContinue').textContent,'ПРОДОЛЖИТЬ');tap(r,'menuNew');assert.equal(r.doc.getElementById('mainMenuTitle').textContent,'НОВАЯ ИГРА');E("I18n.setLanguage('en')");assert.equal(r.doc.getElementById('mainMenuTitle').textContent,'NEW GAME');tap(r,'mainMenuBack');assert.equal(r.doc.getElementById('menuExit').textContent,'EXIT');});
check('new.fiveEmptySlotsNoWriteUntilSelection',()=>{tap(r,'menuNew');const nodes=r.doc.getElementById('mainMenuSlots').children;assert.equal(nodes.length,5);assert.ok(nodes.every(b=>b.textContent.includes('Empty slot')));assert.equal([...r.storage.keys()].filter(k=>k.startsWith(prefix)).length,0);});
check('new.touchSelectedSlot.launchExactlyOnce',()=>{tap(r,r.doc.getElementById('mainMenuSlots').children[2],'touch');assert.equal(E('GameState.session.activeSlot'),3);assert.equal(E('MainMenu.active'),false);assert.ok(r.doc.getElementById('mainMenu').hidden);assert.equal(r.scheduler.rafRequests,1);assert.equal(r.scheduler.intervals.length,1);E('MainMenu.sessionSelected();MainMenu.continueGame();MainMenu.mount(()=>{throw Error("duplicate")})');assert.equal(r.scheduler.rafRequests,1);assert.equal(r.scheduler.intervals.length,1);assert.equal(r.doc.getElementById('mainMenuMedia').childNodes.length,0);});
check('new.saveLoadAfterLaunch',()=>{assert.equal(E('saveGameProgress()'),true);assert.equal(E('V09Saves.load(3)'),true);assert.equal(r.scheduler.rafRequests,1);assert.ok(E('GameState.session.ready'));assert.deepEqual(r.errors,[]);});
check('continue.noImplicitNewSaveWhenLegacyDisappears',()=>{const s=boot(),key=s.eval('GAME_SAVE_KEY');s.storage.set(key,source);const get=s.context.localStorage.getItem;let reads=0;s.context.localStorage.getItem=k=>{if(k===key&&++reads===2)s.storage.delete(key);return get(k);};assert.equal(s.eval('MainMenu.continueGame()'),false);assert.equal([...s.storage.keys()].filter(k=>k.startsWith(prefix)).length,0);assert.equal(s.scheduler.rafRequests,0);});
check('continue.oneSave.noMutationAtBoot',()=>{const s=boot({[prefix+2]:save('Камень',10000)});assert.equal(s.storage.get(prefix+2),save('Камень',10000));assert.equal(s.doc.getElementById('menuContinue').disabled,false);tap(s,'menuContinue');assert.equal(s.eval('GameState.session.activeSlot'),2);assert.equal(s.eval('GameState.session.name'),'Камень');assert.equal(s.storage.get(prefix+2),save('Камень',10000));assert.equal([...s.storage.keys()].filter(k=>k.startsWith(prefix)).length,1);assert.equal(s.scheduler.rafRequests,1);});
check('continue.latestTimestampOverActivePointer',()=>{const s=boot({[prefix+1]:save('Old',10000),[prefix+4]:save('Latest',30000),[prefix+5]:save('Middle',20000),survival_base_v09_active_slot:'1'});tap(s,'menuContinue');assert.equal(s.eval('GameState.session.activeSlot'),4);});
check('continue.backupFallbackAndInvalidSlot',()=>{const s=boot({[prefix+1]:'broken',[prefix+1+'_backup']:save('Backup',30000),[prefix+2]:save('Older',10000)});tap(s,'menuContinue');assert.equal(s.eval('GameState.session.activeSlot'),1);assert.equal(s.storage.get(prefix+1),'broken');});
check('continue.allInvalidDisabledNoOverwrite',()=>{const s=boot({[prefix+1]:'broken'}),before=storage(s);assert.equal(s.doc.getElementById('menuContinue').disabled,true);assert.equal(s.eval('MainMenu.continueGame()'),false);assert.deepEqual(storage(s),before);});
check('load.fiveSlotsMetadataAndLiteralSaveName',()=>{const s=boot({[prefix+4]:save('Камень <script>',20000)});tap(s,'menuLoad');const rows=s.doc.getElementById('mainMenuSlots').children;assert.equal(rows.length,5);assert.ok(rows[3].textContent.includes('Камень <script>'));assert.ok(rows[3].textContent.includes('Surface'));assert.equal(rows[0].disabled,true);tap(s,rows[3]);assert.equal(s.eval('GameState.session.activeSlot'),4);});
const all=Object.fromEntries(Array.from({length:5},(_,i)=>[prefix+(i+1),save('Progress '+(i+1),10000+i)]));
check('new.fullSlotsNeedsExplicitConfirmation.cancelSafe',()=>{const s=boot(all),before=storage(s);tap(s,'menuNew');tap(s,s.doc.getElementById('mainMenuSlots').children[1]);assert.equal(s.doc.getElementById('mainMenuConfirm').hidden,false);assert.deepEqual(storage(s),before);tap(s,'mainMenuCancel');assert.deepEqual(storage(s),before);assert.ok(s.eval('MainMenu.active'));assert.equal(s.eval('V09Saves.newGame(2)'),false);});
check('new.confirmReplacesOnlyChosenSlot',()=>{const s=boot({...all,[prefix+2+'_backup']:save('Old backup',1)});tap(s,'menuNew');tap(s,s.doc.getElementById('mainMenuSlots').children[1]);tap(s,'mainMenuReplace');assert.equal(s.eval('GameState.session.activeSlot'),2);assert.equal(s.eval('MainMenu.active'),false);assert.notEqual(s.storage.get(prefix+2),all[prefix+2]);assert.ok(!s.storage.has(prefix+2+'_backup'));for(const id of [1,3,4,5])assert.equal(s.storage.get(prefix+id),all[prefix+id]);});
check('new.changedSlotCannotBeOverwrittenByStaleConfirmation',()=>{const s=boot(all);tap(s,'menuNew');tap(s,s.doc.getElementById('mainMenuSlots').children[1]);s.storage.set(prefix+2,save('Changed',90000));tap(s,'mainMenuReplace');assert.equal(s.storage.get(prefix+2),save('Changed',90000));assert.ok(s.eval('MainMenu.active'));});
check('new.quotaFailurePreservesOccupiedSave',()=>{const s=boot(all);tap(s,'menuNew');tap(s,s.doc.getElementById('mainMenuSlots').children[1]);const write=s.context.localStorage.setItem;s.context.localStorage.setItem=(k,v)=>{if(k===prefix+2)throw Error('quota');write(k,v);};tap(s,'mainMenuReplace');assert.equal(s.storage.get(prefix+2),all[prefix+2]);assert.ok(s.eval('MainMenu.active'));assert.equal(s.scheduler.rafRequests,0);});
check('new.activePointerFailureRollsBackReplacement',()=>{const s=boot({...all,[prefix+2+'_backup']:save('Original backup',10)}),before=storage(s);tap(s,'menuNew');tap(s,s.doc.getElementById('mainMenuSlots').children[1]);const write=s.context.localStorage.setItem;s.context.localStorage.setItem=(k,v)=>{if(k==='survival_base_v09_active_slot')throw Error('quota');write(k,v);};tap(s,'mainMenuReplace');assert.deepEqual(storage(s),before);assert.ok(s.eval('MainMenu.active'));});
check('storage.failureIsDisplayedAndNoSimulation',()=>{const s=boot();s.context.localStorage.getItem=()=>{throw Error('blocked')};s.eval('MainMenu.refresh()');assert.equal(s.doc.getElementById('menuContinue').disabled,true);assert.ok(s.doc.getElementById('mainMenuStatus').textContent.includes('unavailable'));assert.equal(s.scheduler.rafRequests,0);});
check('exit.browserDoesNotCallForbiddenWindowClose',()=>{const s=boot();s.context.close=()=>{throw Error('forbidden')};tap(s,'menuExit');assert.ok(s.doc.getElementById('mainMenuStatus').textContent.includes('close this browser'));assert.ok(s.eval('MainMenu.active'));});
check('exit.telegramCloseAndFailureFallback',()=>{const s=boot();let calls=0;s.context.Telegram={WebApp:{initData:'telegram-context',close(){calls++}}};tap(s,'menuExit');assert.equal(calls,1);s.context.Telegram.WebApp.close=()=>{throw Error('blocked')};tap(s,'menuExit');assert.ok(s.doc.getElementById('mainMenuStatus').textContent.includes('close this browser'));});
check('exit.telegramPlatformAndBrowserSDK',()=>{const s=boot();let calls=0;s.context.Telegram={WebApp:{initData:'',platform:'unknown',close(){calls++}}};tap(s,'menuExit');assert.equal(calls,0);s.context.Telegram.WebApp.platform='android';tap(s,'menuExit');assert.equal(calls,1);});
check('loop.settingsAndLanguageRepeatedNoNewListeners',()=>{const s=boot();const before=s.listenerCounts();for(let i=0;i<10;i++){tap(s,'menuSettings');s.eval(`I18n.setLanguage('${i%2?'ru':'en'}')`);tap(s,'closeSettings');}assert.deepEqual(s.listenerCounts(),before);assert.equal(s.scheduler.rafRequests,0);assert.equal(s.scheduler.intervals.length,0);});
check('legacy.continueMigratesExistingDataOnlyAfterSelection',()=>{const s=boot({survival_base_progress_v084:source});/* Use actual historical key, not a duplicate save schema. */s.storage.delete('survival_base_progress_v084');s.storage.set(s.eval('GAME_SAVE_KEY'),source);s.eval('MainMenu.refresh()');assert.equal(s.doc.getElementById('menuContinue').disabled,false);tap(s,'menuContinue');assert.equal(s.eval('MainMenu.active'),false);assert.ok(s.storage.has(s.eval('GAME_SAVE_KEY')));assert.equal(s.scheduler.rafRequests,1);});
for(const lang of ['en','ru'])for(const mode of ['PC','MOBILE'])check(`input.${lang}.${mode}`,()=>{const s=boot({}, {language:lang});s.eval(`GameInput.setMode('${mode}')`);tap(s,'menuSettings',mode==='PC'?'mouse':'touch');s.doc.getElementById('languageSelect').value=lang==='en'?'ru':'en';s.doc.getElementById('languageSelect').dispatchEvent({type:'change'});tap(s,'closeSettings');tap(s,'menuNew',mode==='PC'?'mouse':'touch');tap(s,s.doc.getElementById('mainMenuSlots').children[0],mode==='PC'?'mouse':'touch');assert.ok(!s.eval('MainMenu.active'));assert.equal(s.eval('GameInput.mode'),mode);assert.equal(s.scheduler.rafRequests,1);assert.deepEqual(s.errors,[]);});
for(const stage of ['stage0','stage1','stage2'])for(const file of fs.readdirSync('qa/'+stage+'/fixtures').filter(n=>n.endsWith('.json')&&n!=='index.json'))check(`oldSave.menuLoad.${stage}.${file}`,()=>{const raw=fs.readFileSync('qa/'+stage+'/fixtures/'+file,'utf8'),s=boot({[prefix+3]:raw});tap(s,'menuLoad');tap(s,s.doc.getElementById('mainMenuSlots').children[2]);assert.ok(!s.eval('MainMenu.active'));assert.equal(s.eval('GameState.session.activeSlot'),3);assert.equal(s.eval('saveGameProgress()'),true);assert.equal(s.eval('V09Saves.load(3)'),true);assert.deepEqual(s.errors,[]);assert.equal(s.scheduler.rafRequests,1);});
check('assets.pictureBothPathsExternalAndValid',()=>{const html=fs.readFileSync('index.html','utf8');for(const format of ['portrait','landscape']){const p=`assets/images/menu/background-${format}.png`;assert.ok(html.includes(p));assert.ok(fs.statSync(p).size>1e6);}assert.ok(html.includes('media="(orientation: portrait)"'));assert.ok(!html.includes('data:image'));const css=fs.readFileSync('styles/main-menu.css','utf8');for(const property of ['object-fit:cover','--menu-brightness','--menu-mist-opacity','--menu-ui-x','--menu-ui-bottom','--menu-button-height'])assert.ok(css.includes(property));});
for(const [kind,asset]of Object.entries(require('./main-menu-assets.json')))check('assets.unchangedOriginal.'+kind,()=>assert.equal(crypto.createHash('sha256').update(fs.readFileSync(asset.file)).digest('hex'),asset.sha256));
const result={version:require('../package.json').version,passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks,limitations:['Modeled DOM plus native Canvas. Physical PC/phone visual acceptance is required.']};fs.writeFileSync('qa/results/main-menu.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(c=>c.status==='FAIL')}));if(result.failed)process.exitCode=1;
