const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
process.chdir(path.resolve(__dirname,'..'));const {setup}=require('./runtime.cjs'),checks=[];
const r=setup('index.html'),E=s=>r.eval(s),clone=v=>JSON.parse(JSON.stringify(v));
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack?.slice(0,2300)});}}
function fresh(mode='PC'){E(`for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);GameInput.setMode('${mode}');V014Controls.stopRoute();V09World.stopMining();cancelChop();cancelSearch();el('fade').classList.remove('show');playerDead=false;document.hidden=false;scene='surface';player.x=800;player.y=850;player.wallLevel=false;V013City.setFloor(0);stopControls(true);zombies=[];updateCamera();`);}
const map=r.doc.getElementById('v010WorldMap'),go=r.doc.getElementById('v014MapGo');
for(const mode of ['PC','MOBILE']){
 check('map.realSelectionStartsRoute.'+mode,()=>{fresh(mode);E('V010Camera.showMap();');const target={x:800,y:940},v=E('V010Camera.mapViewport'),b=E('V010Camera.mapBounds()'),scale=Math.min(map.width/b.w,map.height/b.h)*v.zoom;
  const clientX=((target.x-v.pan.x)*scale+map.width/2)/map.width*100,clientY=((target.y-v.pan.y)*scale+map.height/2)/map.height*100;
  for(const type of ['pointerdown','pointerup'])r.emit(type,map,{clientX,clientY,pointerType:mode==='PC'?'mouse':'touch'});
  assert.ok(E('menuOpen&&V010Camera.selected!==null'));r.emit('click',go,{detail:0});assert.ok(E('!!V014Controls.route&&!!navigation&&!menuOpen'));
  const before=E('player.y');for(let i=0;i<16;i++){r.advance(16.667);E('frameScale=1;update();');}assert.ok(E('player.y')>before+1);E('V014Controls.stopRoute();');
 });
 check('map.savedGoalFallback.'+mode,()=>{fresh(mode);E('V010Camera.setGoal({x:800,y:940});V010Camera.showMap();');assert.equal(E('V010Camera.selected'),null);r.emit('click',go,{detail:0});assert.ok(E('V014Controls.route&&navigation.destination.y===940'));});
 check('map.settingsBelowMap.'+mode,()=>{fresh(mode);E('openOverlay(el("settingsOverlay"));V010Camera.showMap();V010Camera.setSelected({x:800,y:940});');r.emit('click',go,{detail:0});assert.ok(E('!!V014Controls.route'));});
}
for(const [id,code]of [['empty','V010Camera.setSelected(null);V010Camera.clearGoal();'],['dead','playerDead=true;'],['hidden','document.hidden=true;'],['transition','el("fade").classList.add("show");'],['otherPanelOnTop','openOverlay(el("settingsOverlay"));'],['wrongScene','V010Camera.setSelected(null);V010Camera.setGoal({x:800,y:940});scene="bunker";']])check('map.guards.'+id,()=>{fresh();E('V010Camera.showMap();V010Camera.setSelected({x:800,y:940});'+code);r.emit('click',go,{detail:0});assert.equal(E('!!V014Controls.route'),false);});
check('map.generalMoveStillBlockedByPanel',()=>{fresh();E('V010Camera.showMap();');assert.equal(E('GameActions.dispatch("MOVE",{kind:"route",x:800,y:940})'),false);assert.equal(E('GameActions.dispatch("MOVE",{kind:"point",x:800,y:940})'),false);});
check('map.blockedDestinationStaysOpen',()=>{fresh();E('V010Camera.showMap();V010Camera.setSelected({x:400,y:120});');r.emit('click',go,{detail:0});assert.equal(E('!!V014Controls.route'),false);assert.ok(E('el("v010MapOverlay").classList.contains("open")'));});
for(const [w,h]of [[390,844],[844,390],[1280,800]])for(const zoom of [.6,1,1.4])for(const [corner,x,y]of [['NW',-2750,-2350],['NE',4350,-2350],['SW',-2750,9550],['SE',4350,9550]])check(`bar.projection.${w}x${h}.${zoom}.${corner}`,()=>{
 fresh('MOBILE');E(`innerWidth=${w};innerHeight=${h};refreshViewport();player.x=${x};player.y=${y};V010Camera.restore({...V010Camera.capture(),zoom:${zoom}});searchState={obj:scavenges[0],start:performance.now(),duration:10000};updateSearch();updateCamera();draw();`);
 const p=E('worldToScreen(player.x,player.y)'),bar=r.doc.getElementById('searchBarWrap');assert.equal(parseFloat(bar.style.left)+46,p.x);assert.equal(parseFloat(bar.style.top)+58,p.y);assert.equal(bar.style.display,'block');assert.notEqual(Math.round(p.x),Math.round(w/2));
});
for(const type of ['iron_ore','copper_ore','stone'])check('bar.realMining.'+type,()=>{fresh();E(`V013Inventory.equip('pickaxe');window.workOre=V09World.ores.find(o=>o.type==='${type}');workOre.x=-2730;workOre.y=-2330+['iron_ore','copper_ore','stone'].indexOf('${type}')*300;player.x=-2670;player.y=workOre.y;invalidateGeometry();V010Camera.restore({...V010Camera.capture(),zoom:1});V09World.resumeMining(GameGathering.start('pickaxe',workOre.id));`);r.advance(200);E('V09World.tickMining();updateCamera();draw();');assert.ok(E('!!V09World.miningState()'));const p=E('worldToScreen(player.x,player.y)'),bar=r.doc.getElementById('searchBarWrap');assert.equal(parseFloat(bar.style.left)+46,p.x);assert.equal(parseFloat(bar.style.top)+62,p.y);assert.ok(parseFloat(r.doc.getElementById('searchBarFill').style.width)>0);});
check('bar.woodFollowsAfterCameraChange',()=>{fresh();E(`V013Inventory.equip('axe');window.workTree=worldTrees[0];workTree.x=-2730;workTree.y=-1400;workTree.felled=false;workTree.wood=20;player.x=-2670;player.y=-1400;useTree(workTree);V010Camera.restore({...V010Camera.capture(),zoom:.6});updateChop();camera.x-=20;draw();`);assert.ok(E('!!chopState'));const p=E('worldToScreen(player.x,player.y)'),bar=r.doc.getElementById('searchBarWrap');assert.equal(parseFloat(bar.style.left)+46,p.x);assert.equal(parseFloat(bar.style.top)+58,p.y);});
check('console.noErrors',()=>assert.deepEqual(r.errors,[]));
const result={version:require('../package.json').version,passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks};fs.writeFileSync(process.argv[2]||'qa/results/map-workbar.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(c=>c.status==='FAIL')}));if(result.failed)process.exitCode=1;
