const fs=require('fs'),assert=require('assert/strict'),{setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),J=s=>JSON.parse(E('JSON.stringify('+s+')')),checks=[];
const test=(name,fn)=>{try{fn();checks.push({name,ok:true});}catch(e){checks.push({name,ok:false,error:e.stack});}console.log(name,checks.at(-1).ok?'PASS':'FAIL');};
const reset=()=>E('StoryPlayer.cancel();restoreGameProgress(GameNewGame.create());for(const p of GameFlow.reasons)GameFlow.resume(p);menuOpen=false;document.hidden=false;playerDead=false');
const power=()=>E('V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=1.5;for(const d of Object.values(V09Power.devices))d.enabled=false;V09Power.devices.water_system.enabled=V09Power.devices.irrigation014.enabled=true');
const save=()=>E('restoreGameProgress(decodeGameProgress(JSON.stringify(captureGameProgress())))');const hours=n=>E(`AgricultureTime.advance(${n}*60);BunkerPassA.tick()`);const near=(a,b,tol=.01)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`);
const plant=(i=0,crop=1)=>E(`scene='bunker';player.x=getFarmBeds()[${i}].x+50;player.y=getFarmBeds()[${i}].y-30;V011Farm.state.water=40;V0141Farm.plant(${i},${crop})`);
test('new_game_and_chapter_emergency',()=>{reset();assert.equal(E('captureGameProgress().saveVersion'),24);assert.equal(E('GameEquipment.get("chest0").refs.container'),'storage:0');assert.equal(E('storageChests[0].name'),'Аварийный контейнер');assert.equal(E('getFarmBeds().length'),5);save();});
test('stairs_floor_save_load',()=>{reset();E('player.x=1300;player.y=-180');assert.equal(E('BunkerPassA.go(2)'),true);assert.equal(E('scene'),'bunker');save();assert.equal(E('BunkerPassA.capture().floor'),2);assert.equal(E('worldCollision(player.x,player.y,player.radius,"bunker")'),false);assert.equal(E('BunkerPassA.go(1)'),true);save();assert.equal(E('BunkerPassA.capture().floor'),1);});
test('crop_days_yields_and_50_compatible_records',()=>{for(let i=0;i<10;i++){reset();power();assert.equal(plant(0,i),true);assert.equal(E('farmState[0].plants014.length'),50);assert.equal(E('farmState[0].plants014.filter(p=>p.planted&&!p.harvested).length'),E(`GameplayBalance.farm.crops[farmCrops[${i}].itemType].yield`));near(E(`farmGrowMs(${i})/WorldClock.dayMs`),E(`GameplayBalance.farm.crops[farmCrops[${i}].itemType].days`));save();}});
test('active_clock_pause_hidden_death_offline',()=>{reset();power();plant();E('V016Lighting.tick(1000)');assert.ok(E('AgricultureTime.now()')>0);for(const f of ['document.hidden=true','playerDead=true','GameFlow.pause("qa")']){reset();const a=E('AgricultureTime.now()');E(f+';V016Lighting.tick(1000)');near(E('AgricultureTime.now()'),a);}reset();power();plant();r.context.saved=E('JSON.stringify(captureGameProgress())');r.advance(86400000);E('restoreGameProgress(decodeGameProgress(saved))');near(E('farmState[0].plants014[0].elapsed'),0);});
test('siege_slowdown',()=>{reset();E('WorldClock.restore({schema:1,day:10,minute:0})');const a=E('AgricultureTime.now()');E('V016Lighting.tick(1000)');near(E('AgricultureTime.now()')-a,1000/3);});
test('water_28_capacity_and_20_irrigation',()=>{reset();power();E('V011Farm.state.water=40');hours(24);near(E('BunkerPassA.water.clean'),28);hours(120);near(E('BunkerPassA.water.clean'),100);E('BunkerPassA.water.clean=0;V09Power.devices.water_system.enabled=false;V011Farm.state.water=40;for(let i=0;i<5;i++){V011Farm.beginBed(i,8);for(let n=0;n<50;n++)V011Farm.plantOne(i,n)}');hours(24);near(E('V011Farm.state.water'),20);});
test('power_off_growing_pause_ready_spoil_and_roundtrip',()=>{reset();power();plant();E('V09Power.devices.irrigation014.enabled=false');hours(12);near(E('farmState[0].plants014[0].elapsed'),0);E('V09Power.devices.irrigation014.enabled=true');hours(30);assert.equal(E('V011Farm.ready(0)'),true);E('V09Power.devices.irrigation014.enabled=false');const left=E('BunkerPassA.remaining(0)');hours(left/E('WorldClock.dayMs')*24-.01);assert.equal(E('BunkerPassA.rotten(0)'),false);save();hours(.02);assert.equal(E('BunkerPassA.rotten(0)'),true);save();assert.equal(E('BunkerPassA.rotten(0)'),true);});
test('partial_harvest_waste_full_bag_discard_guards',()=>{reset();power();plant();hours(30);const at=E('BunkerPassA.capture().rot[0].readyAt');E('bag=Array.from({length:BAG_SLOTS},()=>({type:"stone",qty:100}));bag[0]={type:"carrot",qty:97}');assert.equal(E('V0141Farm.harvest(0)'),3);near(E('BunkerPassA.capture().rot[0].readyAt'),at);hours(49);assert.equal(J('BunkerPassA.clear(0)').reason,'space');E('bag[0]=null');assert.equal(J('BunkerPassA.clear(0)').ok,true);assert.equal(E('bagCount("plant_waste")'),2);// Waste leaves through the existing item action «Уничтожить»; there is no separate Discard command.
 E('window.confirm=()=>true;V011UI.details("bag",bag.findIndex(s=>s?.type==="plant_waste"))');const labels=E('[...document.querySelectorAll("#v010ItemDetails button")].map(b=>b.textContent).join("|")');assert.ok(!/Выбросить|Discard/.test(labels),labels);E('[...document.querySelectorAll("#v010ItemDetails button")].find(b=>b.textContent==="Уничтожить").click()');assert.equal(E('bagCount("plant_waste")'),0);assert.equal(J('BunkerPassA.request("discard:0","discard",{type:"stone",qty:100})').ok,false);});
test('water_one_to_one_idempotency_save',()=>{reset();power();E('BunkerPassA.water.clean=12;V011Farm.state.water=40;scene="bunker";player.x=4900;player.y=60;/* 0.43 Phase 0: the clean tank sits at the top wall */bag=[];window.c={actorId:GameActors.localId,instanceId:"water",action:"collect",payload:{amount:5},expectedRevision:BunkerPassA.commands.revision,requestId:"qa-water"}');assert.equal(J('BunkerPassA.commands.execute(c)').ok,true);assert.equal(J('BunkerPassA.commands.execute(c)').replayed,true);assert.equal(E('bagCount("water")'),5);near(E('BunkerPassA.water.clean'),7);save();assert.equal(J('BunkerPassA.commands.execute(c)').replayed,true);});
test('old_actual_save_migration_jobs_identity_and_crops',()=>{reset();r.context.old=JSON.parse(fs.readFileSync('qa/fixtures/pass-a-original.json'));E('restoreGameProgress(decodeGameProgress(JSON.stringify(old)))');near(E('V011Farm.state.water+BunkerPassA.water.clean'),140);near(E('farmState[0].plants014[0].elapsed/farmState[0].plants014[0].duration'),.5);near(E('BunkerPassA.remaining(1)'),2*E('WorldClock.dayMs'));assert.equal(E('farmState[0].plants014.filter(p=>p.planted&&!p.harvested).length'),10);for(const id of J('GameEquipment.records.filter(v=>["kitchen_stove","med_lab"].includes(v.typeId)).map(v=>v.id)')){r.context.sid=id;assert.equal(E('GameEquipment.get(sid).placement'),'packed');assert.equal(E('GameCarried.owns(sid)'),true);const ms=E('V09Craft.craftQueue.getJob(sid).remainingMs');E('V09Craft.tick(100)');near(E('V09Craft.craftQueue.getJob(sid).remainingMs'),ms);save();E('player.x=4700;player.y=100;window.pos=null;{const r=GameEquipment.get(sid),b=BunkerLayout.rooms[r.transform.room];for(let y=b.top+40;y<b.bottom-40&&!pos;y+=25)for(let x=b.left+40;x<b.right-40&&!pos;x+=25){const t=GamePlacement.centered(r.typeId,r.transform.room,x,y);if(GamePlacement.check(sid,t).ok)pos=t;}}');assert.ok(E('!!pos'));assert.equal(J('GamePlacement.request(sid,"place",pos)').ok,true);assert.equal(E('GameEquipment.get(sid).id'),id);save();}});
test('room_door_keys_old_preferences',()=>{reset();E('old.control0353.autoOpen.v09door_workshop=false;old.v09.power.doors.find(v=>v.id==="v09door_workshop").open=.4;restoreGameProgress(decodeGameProgress(JSON.stringify(old)))');assert.equal(E('GameBaseControl.autoOpen("v09door_workshop")'),false);near(E('v09Doors.find(d=>d.id==="v09door_workshop").open'),.4);assert.equal(E('V09Power.devices.water_system.enabled'),true);save();});
test('L2_routes_rest_shower_feed_and_control',()=>{reset();E('scene="bunker";player.x=4700;player.y=-160;for(const d of v09Doors)d.open=1;invalidateGeometry()');/* 0.43 Phase 0: kitchen point beside the new dining table; rest point beside the horizontal bed */for(const [x,y]of [[4450,-60],[4350,290],[4380,650],[4850,-125],[4910,305],[5250,495]]){E(`window.g={x:${x},y:${y}}`);assert.equal(E('worldCollision(g.x,g.y,player.radius,"bunker")'),false);assert.ok(E('findWalkPath(player.x,player.y,{...g,kind:"ground",range:0},"bunker",player.radius)')!==null);}E('player.x=4280;player.y=715');assert.equal(E('V011Living.start("rest")'),true);E('V011Living.stop();player.x=4070;player.y=835');assert.equal(E('V011Living.start("shower")'),true);E('V011Living.stop()');assert.deepEqual(J('EquipmentInstances.placement.feed_craft.rooms'),['pantry']);assert.equal(E('GameBaseControl.list().find(v=>v.deviceId==="water_system").level'),'bunker:2');});
// 0.43 Pass B: 'animals_inactive' removed — Pass B enables Animals on purpose (qa/pass-b.cjs covers them).
test('DEV_day_exact_clock_and_farm',()=>{reset();power();E('WorldClock.restore({schema:1,day:2,minute:480});GameDevQA.enable()');const a=E('AgricultureTime.now()');assert.equal(J('GameDevQA.request("time",{minutes:1440})').ok,true);E('for(let i=0;i<1000&&GameDevQA.metrics().target!==null;i++)GameDevQA.runFrame(()=>V016Lighting.tick(16.667*frameScale))');assert.equal(E('WorldClock.day'),3);near(E('WorldClock.minute'),480);near(E('AgricultureTime.now()')-a,E('WorldClock.dayMs'),.2);E('GameDevQA.disable()');});
test('physical_contact_all_existing_types',()=>{reset();E('scene="surface";player.wallLevel=false;player.x=800;player.y=850;zombies=[];WorldClock.restore({schema:1,day:2,minute:480});for(const type of ["normal","heavy","fast","leaper","bloater"]){const z=makeZombie(800,850);z.type=type;V017Monsters.prepare(z);zombies=[z];frameScale=1;updateZombies();if(Math.hypot(z.x-player.x,z.y-player.y)<z.radius+player.radius-.001)throw Error(type+" contact");}');});
test('RU_EN_mobile_sized_canvas',()=>{reset();for(const lang of ['ru','en']){E(`I18n.setLanguage('${lang}')`);assert.ok(!E('I18n.t("farm.cleanTank")').includes('farm.'));for(const [w,h]of [[390,844],[844,390],[1280,800]])for(const floor of [1,2])E(`innerWidth=${w};innerHeight=${h};devicePixelRatio=3;resizeCanvas();scene='bunker';player.x=${floor===1?1210:4700};player.y=0;updateCamera();draw()`);}assert.deepEqual(r.errors,[]);});
test('power_budget_existing_bus_overload',()=>{reset();E('V09Power.running=true;V09Power.fuel=100;V010Energy.battery.enabled=false;for(const d of Object.values(V09Power.devices))d.enabled=true;bag=[];addItem("iron_ore",100);V09Craft.start("furnace","iron",10)');const data=J('({allocation:{...V09Power.allocation(),served:[...V09Power.allocation().served]},devices:Object.values(V09Power.devices).map(d=>({id:d.id,kW:d.watts,active:!!d.active(),powered:devicePowered(d.id)}))})');fs.writeFileSync('qa/results/pass-a-power.json',JSON.stringify(data,null,2));assert.equal(data.allocation.supply,10);assert.ok(data.allocation.demand>10);assert.equal(E('devicePowered("water_system")'),false);});
test('core_remote_L2_map_uses_local_floor_bounds',()=>{reset();E("window.qaHost=document.createElement('div');window.qaRoute={page:'control|bunker:2|water_room',setPage(p){this.page=p}};window.qaRefresh=GameBaseControlUI.mount(qaHost,qaRoute,()=>true);qaRefresh()");const nodes=E("qaHost.querySelectorAll('[data-control-zone]')");assert.equal(nodes.length,E("GameBaseControl.levels.find(l=>l.id==='bunker:2').zones.length"));for(const n of nodes){assert.ok(n.style.cssText.includes('left:'));assert.ok(!n.style.cssText.includes('NaN'));}assert.ok(E("qaHost.querySelector('[data-control-instance=\"device:water_system\"]')"));});
test('all_save_blocks_have_registered_owner_and_bad_floor_rejected',()=>{reset();assert.equal(E("GameState.describe().some(v=>v.saved.includes('bunker043'))"),true);E('window.wrong=captureGameProgress();wrong.bunker043.floor=2');const a=J('captureGameProgress()');assert.throws(()=>E('restoreGameProgress(wrong)'));assert.deepEqual(J('captureGameProgress()'),a);});
test('migration_full_bag_overflow_no_loss_or_repeat',()=>{reset();r.context.oldFull=JSON.parse(fs.readFileSync('qa/fixtures/pass-a-original.json'));E("oldFull.bag=Array.from({length:ITEM[oldFull.equipment.backpack.type].capacity},()=>({type:'stone',qty:100}));restoreGameProgress(decodeGameProgress(JSON.stringify(oldFull)))");const ids=J("GameEquipment.records.filter(v=>v.placement==='packed'&&v.state.settings.layoutRecovery).map(v=>v.id)");assert.ok(ids.length>=2);for(const id of ids){r.context.checkId=id;assert.equal(E('GameCarried.owns(checkId)'),true);}const before=J('GameEquipment.capture()');save();save();assert.deepEqual(J('GameEquipment.capture()'),before);});
test('empty_L1_passages_stay_open_without_power_or_interaction',()=>{reset();E('V09Power.running=false;V010Energy.battery.charge=0;for(let i=0;i<100;i++)V09Power.tick(.1)');for(const id of ['v09door_reserve_l1','v09door_empty_l1']){r.context.did=id;assert.equal(E('v09Doors.find(d=>d.id===did).open'),1);assert.equal(E('v09DoorPanels(v09Doors.find(d=>d.id===did)).length'),0);assert.equal(E('interactionObjects("bunker").some(o=>o.id===did)'),false);}save();});
const result={runtimeSha256:require('crypto').createHash('sha256').update(fs.readFileSync('js/game.js')).digest('hex'),passed:checks.filter(c=>c.ok).length,failed:checks.filter(c=>!c.ok).length,checks};fs.writeFileSync('qa/results/pass-a.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(result.failed)process.exitCode=1;
