// 0.43 Pass B Animals: chickens, cows, needs, power/time, Pantry storages, movement, save, visual hook, performance.
const fs=require('fs'),assert=require('assert/strict'),{performance}=require('perf_hooks'),{setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),J=s=>JSON.parse(E('JSON.stringify('+s+')')),checks=[];
const test=(name,fn)=>{try{fn();checks.push({name,ok:true});}catch(e){checks.push({name,ok:false,error:e.stack});}console.log(name,checks.at(-1).ok?'PASS':'FAIL');};
const reset=()=>E('StoryPlayer.cancel();restoreGameProgress(GameNewGame.create());for(const p of GameFlow.reasons)GameFlow.resume(p);menuOpen=false;document.hidden=false;playerDead=false;scene="bunker";player.x=4700;player.y=-160;player.floor=2;GameLivestock.setRandom(null);V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=V010Energy.battery.capacity;for(const d of Object.values(V09Power.devices))d.enabled=true;V09Power.frame++');
const DAY=1440;const minutes=n=>E(`AgricultureTime.advance(${n});V09Power.frame++;GameLivestock.settle()`);const days=n=>minutes(n*DAY);
const K=()=>J('GameLivestock.constants');const save=()=>E('restoreGameProgress(decodeGameProgress(JSON.stringify(captureGameProgress())));for(const p of GameFlow.reasons)GameFlow.resume(p)');
const count=(i,t)=>E(`storageCount(${i},'${t}')`);const herd=()=>J('GameLivestock.animals');
const setHerd=list=>{r.context.qaHerd=list;E(`{const s=GameLivestock.state;s.animals=qaHerd.map(a=>({...a}));s.nextId=1000;GameLivestock.poses.clear();}`);};
const hen=(id,age=2*DAY*833.3333333,extra={})=>({id:'chicken:'+id,kind:'chicken',ageMs:age,stage:0,eggMs:0,brood:null,...extra});
// Normalise stages from ages (the owner recomputes stage on every step; tests build herds directly).
const fix=()=>E(`GameLivestock.state.animals.forEach(a=>{const d=GameLivestock.constants.DAY;a.stage=a.kind==='chicken'?(a.ageMs<d?0:a.ageMs<2*d?1:2):(a.ageMs<2*d?0:a.ageMs<5*d?1:2);})`);
const D=()=>E('GameLivestock.constants.DAY');
const chickens=(n,stage=2)=>Array.from({length:n},(_,i)=>({id:'chicken:'+(i+1),kind:'chicken',ageMs:[0,1.5,3][stage]*D(),stage,eggMs:0,brood:null}));
const cows=(n,stage=2,from=0)=>Array.from({length:n},(_,i)=>({id:'cow:'+(500+i),kind:'cow',ageMs:[0,3,6][stage]*D(),stage,milkMs:0,stall:from+i}));

// ---------------- Baseline / structure ----------------
test('start_herd_2_adult_chickens_2_adult_cows_no_rooster',()=>{reset();const h=herd();
 assert.deepEqual(h.map(a=>[a.kind,a.stage]).sort(),[['chicken',2],['chicken',2],['cow',2],['cow',2]]);
 assert.ok(h.every(a=>['chicken','cow'].includes(a.kind)));assert.ok(!/rooster|петух/i.test(fs.readFileSync('src/farm/livestock.js','utf8')));
 assert.deepEqual(J('[L2Systems.water,L2Systems.farm,L2Systems.animals,AgricultureTime.available,AgricultureTime.animalsAvailable]'),[true,true,true,true,true]);
 assert.deepEqual(J('GameLivestock.constants.CAP'),{chicken:{feed:10*384,water:10*384},cow:{feed:20*384,water:20*384}});
 assert.deepEqual(J('[GameplayBalance.animals.chickenMax,GameplayBalance.animals.cowMax,GameplayBalance.animals.chickenMin,GameplayBalance.animals.cowMin]'),[12,6,2,2]);});
test('l2_systems_flags_toggle_animals_without_rewriting_l2',()=>{reset();E("L2Systems.set('animals',false)");const before=JSON.stringify(herd());days(2);assert.equal(JSON.stringify(herd()),before);assert.equal(E("interactionObjects('bunker').some(o=>o.kind==='livestock_chickens')"),false);assert.equal(E("V09Power.devices.animal_system.active()"),false);E("L2Systems.set('animals',true)");assert.equal(E("V09Power.devices.animal_system.active()"),true);assert.throws(()=>E("L2Systems.set('rooster',true)"));});
test('legacy_owners_removed',()=>{const src=fs.readFileSync('js/game.js','utf8');for(const token of ['LIVESTOCK_EGG_MS','LIVESTOCK_MILK_MS','LIVESTOCK_NEED_MS','LIVESTOCK_STARVE_MS','COW_BREED_MS','V09_CHICKEN_BREED_MS','V09_CHICKEN_MAX','livestockAnimals','livestockAlive','updateLivestockProduction','v09ChickenSlaughter','renderCowMenu'])assert.ok(!src.includes(token),token);
 assert.ok(!/Date\.now/.test(fs.readFileSync('src/farm/livestock.js','utf8')));assert.equal(E('typeof GameLivestock.update'),'function');assert.equal(E("!!el('cowOverlay')"),false);});

// ---------------- Chickens ----------------
test('eggs_one_per_adult_hen_per_day_with_offsets_to_storage10',()=>{reset();const offsets=J("GameLivestock.list('chicken').map(a=>a.eggMs)");assert.notEqual(offsets[0],offsets[1]);
 const e0=count(10,'eggs');days(1);assert.equal(count(10,'eggs')-e0,2);days(3);assert.equal(count(10,'eggs')-e0,8);
 // Offsets: the two hens lay at different quarter-hours inside one day.
 reset();setHerd([...chickens(2).map((a,i)=>({...a,eggMs:i?Math.round(D()*.75/12500)*12500:0})),...cows(2)]);const at=[];for(let s=0;s<96;s++){const b=count(10,'eggs');minutes(15);if(count(10,'eggs')>b)at.push(s);}assert.equal(at.length,2);assert.ok(at[1]-at[0]>=48,JSON.stringify(at));});
test('brood_1_to_6_free_slot_cap_eggs_debited_single_nest',()=>{reset();E("addToSlots(storageChests[10].items,'eggs',20,60)");
 for(const [n,reason] of [[0,'count'],[7,'count'],[1.5,'count']])assert.equal(J(`GameLivestock.brood(${n})`).reason,reason);
 setHerd([...chickens(9),...cows(2)]);assert.equal(E('GameLivestock.broodLimit()'),3);assert.equal(J('GameLivestock.brood(4)').reason,'slots');
 const e=count(10,'eggs');const res=J('GameLivestock.brood(3)');assert.equal(res.ok,true);assert.equal(count(10,'eggs'),e-3);assert.deepEqual(J(`GameLivestock.animals.find(a=>a.id==='${res.hen}').brood`),{eggs:3,progressMs:0});
 assert.equal(J('GameLivestock.brood(1)').reason,'nestBusy');assert.equal(E('GameLivestock.broodLimit()'),0);
 reset();setHerd([...chickens(2),...cows(2)]);E("storageChests[10].items=[];addToSlots(storageChests[10].items,'eggs',2,60)");assert.equal(J('GameLivestock.brood(3)').reason,'eggs');assert.equal(J('GameLivestock.brood(2)').ok,true);
 reset();setHerd([...chickens(2),...cows(2)]);E("storageChests[10].items=[]");assert.equal(J('GameLivestock.brood(1)').reason,'eggs');});
test('incubation_2_days_85_percent_deterministic_hatch_and_fail',()=>{for(const [roll,born] of [[.5,4],[.849,4],[.85,0],[.9,0]]){reset();setHerd([...chickens(2),...cows(2)]);E("addToSlots(storageChests[10].items,'eggs',4,60)");assert.equal(J('GameLivestock.brood(4)').ok,true);
  E(`GameLivestock.setRandom(()=>${roll})`);minutes(2*DAY-15);assert.equal(J("GameLivestock.list('chicken').length"),2,'not before 2 days');minutes(15);
  assert.equal(J("GameLivestock.list('chicken').length"),2+born,'roll '+roll);assert.equal(E("GameLivestock.list('chicken').some(a=>a.brood)"),false);
  assert.ok(J("GameLivestock.list('chicken').filter(a=>a.stage===0)").every(a=>a.ageMs===0));assert.equal(count(10,'eggs'),J("GameLivestock.list('chicken').filter(a=>a.stage===2&&!a.brood).length")*0+count(10,'eggs'));}
 // A mixed sequence: rolls .1,.95,.2,.9 -> exactly 2 chicks; failed eggs vanish without a waste item.
 reset();setHerd([...chickens(2),...cows(2)]);E("storageChests[10].items=[];addToSlots(storageChests[10].items,'eggs',4,60)");J('GameLivestock.brood(4)');E("GameLivestock.setRandom(null);window.qaRolls=[.1,.95,.2,.9];GameLivestock.setRandom(()=>qaRolls.length?qaRolls.shift():.99)");
 E("GameLivestock.state.animals.forEach(a=>{if(a.brood)a.brood.progressMs=GameLivestock.constants.DAY*2-12500})");minutes(15);assert.equal(J("GameLivestock.list('chicken').length"),4);assert.equal(E("bag.concat(...storageChests.map(c=>c.items)).some(s=>s&&/egg_?shell|rotten_egg|waste/.test(s.type)&&s.type!=='plant_waste')"),false);});
test('brooding_hen_no_eggs_no_movement_no_slaughter',()=>{reset();setHerd([...chickens(3),...cows(2)]);E("addToSlots(storageChests[10].items,'eggs',2,60)");const id=J('GameLivestock.brood(2)').hen;
 const e=count(10,'eggs');days(1);assert.equal(count(10,'eggs')-e,2,'only the 2 free hens lay');
 E('player.x=5107;player.y=120;player.floor=2');for(let i=0;i<120;i++)E('GameLivestock.update()');const v=J(`GameLivestock.view(GameLivestock.animals.find(a=>a.id==='${id}'))`);const seat=J('GameLivestock.nestSeat');assert.equal(v.mode,'brood');assert.equal(v.moving,false);assert.deepEqual([v.x,v.y],[seat.x,seat.y]);
 E("bag=[]");assert.equal(J("GameLivestock.slaughter('chicken')").ok,true);assert.ok(E(`GameLivestock.animals.some(a=>a.id==='${id}')`),'brooding hen kept');assert.equal(J("GameLivestock.slaughter('chicken')").reason,'minimum');});
test('chick_juvenile_adult_growth_only_adults_lay',()=>{reset();setHerd([...chickens(2),{id:'chicken:9',kind:'chicken',ageMs:0,stage:0,eggMs:0,brood:null},...cows(2)]);
 const c=()=>J("GameLivestock.animals.find(a=>a.id==='chicken:9')");days(1);assert.equal(c().stage,1);assert.equal(c().eggMs,0);days(1);assert.equal(c().stage,2);days(1);assert.equal(c().eggMs>0||count(10,'eggs')>=5,true);});
test('min_2_adult_chickens_and_max_12',()=>{reset();E('bag=[]');assert.equal(J("GameLivestock.slaughter('chicken')").reason,'minimum');setHerd([...chickens(3),...cows(2)]);const m=E("bagCount('chicken_meat')");assert.equal(J("GameLivestock.slaughter('chicken')").ok,true);assert.equal(E("bagCount('chicken_meat')")-m,5);
 setHerd([...chickens(2),...chickens(9,0).map((a,i)=>({...a,id:'chicken:'+(50+i)})),...cows(2)]);E("addToSlots(storageChests[10].items,'eggs',6,60)");assert.equal(E('GameLivestock.broodLimit()'),1);assert.equal(J('GameLivestock.brood(1)').ok,true);E('GameLivestock.setRandom(()=>0)');days(3);assert.equal(J("GameLivestock.list('chicken').length"),12);
 E("addToSlots(storageChests[10].items,'eggs',6,60)");assert.equal(E('GameLivestock.broodLimit()'),0);assert.equal(J('GameLivestock.brood(1)').reason,'slots');days(10);assert.ok(J("GameLivestock.list('chicken').length")<=12);});
test('juvenile_and_chick_cannot_be_slaughtered_or_brood',()=>{reset();setHerd([...chickens(2),...chickens(3,1).map((a,i)=>({...a,id:'chicken:'+(20+i)})),...cows(2)]);E('bag=[]');assert.equal(J("GameLivestock.slaughter('chicken')").reason,'minimum');E("addToSlots(storageChests[10].items,'eggs',2,60)");const id=J('GameLivestock.brood(1)').hen;assert.ok(/^chicken:[12]$/.test(id));});

// ---------------- Cows ----------------
test('milk_1_per_adult_plus_50_percent_second_to_storage11',()=>{for(const [roll,per] of [[.3,2],[.7,1]]){reset();setHerd([...chickens(2),...cows(2)]);E(`GameLivestock.setRandom(()=>${roll})`);const m=count(11,'milk');days(1);assert.equal(count(11,'milk')-m,2*per,'roll '+roll);}
 reset();setHerd([...chickens(2),...cows(2),...cows(2,0,2).map((a,i)=>({...a,id:'cow:'+(700+i)}))]);E('GameLivestock.setRandom(()=>.9)');const m=count(11,'milk');days(1);assert.equal(count(11,'milk')-m,2,'calves give no milk');});
test('herd_calf_timer_5_to_7_days_deterministic_and_conditions',()=>{reset();setHerd([...chickens(2),...cows(2)]);E('GameLivestock.state.calfMs=GameLivestock.constants.DAY*5');E('GameLivestock.setRandom(()=>.5)');
 days(5);const cw=J("GameLivestock.list('cow')");assert.equal(cw.length,3);const calf=cw.find(a=>a.stage===0);assert.equal(calf.stall,2);assert.equal(E('GameLivestock.state.calfMs'),6*D());
 for(const roll of [0,.999999]){reset();setHerd([...chickens(2),...cows(2)]);E(`GameLivestock.state.calfMs=12500;GameLivestock.setRandom(()=>${roll})`);minutes(15);const ms=E('GameLivestock.state.calfMs');assert.ok(ms>=5*D()&&ms<=7*D(),String(ms));}
 // Conditions: fewer than 2 adults, no free stall, no food, no power -> the event waits; population never exceeds 6.
 reset();setHerd([...chickens(2),...cows(2),...cows(4,1,2).map((a,i)=>({...a,id:'cow:'+(800+i)}))]);E('GameLivestock.state.calfMs=12500');days(1);assert.equal(J("GameLivestock.list('cow').length"),6);assert.equal(E('GameLivestock.state.calfMs'),0);
 reset();setHerd([...chickens(2),...cows(2)]);E('GameLivestock.state.cow.feed=0;GameLivestock.state.calfMs=12500');days(2);assert.equal(J("GameLivestock.list('cow').length"),2);assert.equal(E('GameLivestock.state.calfMs'),12500,'timer paused without food');});
test('stall_cap_6_calf_juvenile_adult_growth_milk_only_adult',()=>{reset();setHerd([...chickens(2),...cows(2),{id:'cow:900',kind:'cow',ageMs:0,stage:0,milkMs:0,stall:5}]);E('GameLivestock.setRandom(()=>.9);GameLivestock.state.calfMs=GameLivestock.constants.DAY*7');
 const c=()=>J("GameLivestock.animals.find(a=>a.id==='cow:900')");days(2);assert.equal(c().stage,1);assert.equal(c().milkMs,0);days(3);assert.equal(c().stage,2);assert.ok(new Set(J("GameLivestock.list('cow').map(a=>a.stall)")).size===J("GameLivestock.list('cow').length"));});
test('cow_slaughter_only_adults_never_below_2',()=>{reset();E('bag=[]');assert.equal(J("GameLivestock.slaughter('cow')").reason,'minimum');setHerd([...chickens(2),...cows(2),{id:'cow:901',kind:'cow',ageMs:0,stage:0,milkMs:0,stall:3}]);assert.equal(J("GameLivestock.slaughter('cow')").reason,'minimum','calf is not slaughterable');
 setHerd([...chickens(2),...cows(3)]);const b=E("bagCount('beef')");assert.equal(J("GameLivestock.slaughter('cow')").ok,true);assert.equal(E("bagCount('beef')")-b,20);assert.equal(J("GameLivestock.list('cow').length"),2);});

// ---------------- Needs ----------------
test('exact_feed_water_per_day_and_fractional_chickens',()=>{reset();setHerd([...chickens(3),...cows(2),...cows(1,1,2).map(a=>({...a,id:'cow:950'}))]);const f0=J('GameLivestock.state');minutes(15);let s=J('GameLivestock.state');
 assert.equal(f0.chicken.feed-s.chicken.feed,3);assert.equal(f0.chicken.water-s.chicken.water,3);assert.equal(f0.cow.feed-s.cow.feed,2*4+2);
 minutes(DAY-15);s=J('GameLivestock.state');assert.equal((f0.chicken.feed-s.chicken.feed)/384,.75);assert.equal((f0.cow.feed-s.cow.feed)/384,2.5);assert.equal((f0.cow.water-s.cow.water)/384,2.5);assert.ok(Number.isInteger(s.chicken.feed));});
test('capacities_and_manual_feed_loading_from_backpack',()=>{reset();E("GameLivestock.state.chicken.feed=0;GameLivestock.state.cow.feed=384*5+100;bag=[];addItem('animal_feed',30)");assert.equal(E("GameLivestock.loadFeed('chicken')"),10);assert.equal(E('GameLivestock.state.chicken.feed'),3840);assert.equal(E("bagCount('animal_feed')"),20);
 assert.equal(E("GameLivestock.loadFeed('cow')"),14);assert.equal(E('GameLivestock.state.cow.feed'),384*19+100);assert.equal(E("bagCount('animal_feed')"),6);assert.equal(E("GameLivestock.loadFeed('chicken')"),0);E('bag=[]');E('GameLivestock.state.cow.feed=0');assert.equal(E("GameLivestock.loadFeed('cow')"),0);});
test('water_automatic_from_clean_tank_without_power',()=>{reset();E('GameLivestock.state.chicken.water=0;GameLivestock.state.cow.water=384*19;BunkerPassA.water.clean=5.5;V09Power.running=false;V010Energy.battery.charge=0;V09Power.frame++');minutes(15);
 assert.equal(E('GameLivestock.state.chicken.water'),384*5+192);assert.equal(E('GameLivestock.state.cow.water'),384*19);assert.ok(Math.abs(E('BunkerPassA.water.clean'))<1e-9);
 E('BunkerPassA.water.clean=50');minutes(15);assert.equal(E('GameLivestock.state.chicken.water'),3840);assert.equal(E('GameLivestock.state.cow.water'),7680);assert.ok(Math.abs(E('BunkerPassA.water.clean')-44.5)<1e-6,String(E('BunkerPassA.water.clean')));
 assert.equal(E("storageCount(13,'water')"),E("storageCount(13,'water')"));});
test('no_food_or_water_pauses_everything_without_death_and_resumes',()=>{reset();setHerd([...chickens(2),...cows(2)]);E("addToSlots(storageChests[10].items,'eggs',2,60)");J('GameLivestock.brood(1)');E('GameLivestock.state.chicken.feed=0;GameLivestock.state.cow.water=0;BunkerPassA.water.clean=0;GameLivestock.state.calfMs=12500');
 const before=J('GameLivestock.state');const e=count(10,'eggs'),m=count(11,'milk');days(4);const after=J('GameLivestock.state');
 assert.deepEqual(after.animals,before.animals,'eggs, milk, growth, brood, calf all paused');assert.equal(after.calfMs,12500);assert.equal(count(10,'eggs'),e);assert.equal(count(11,'milk'),m);assert.equal(after.animals.length,4,'no deaths');
 E("GameLivestock.state.chicken.feed=3840;GameLivestock.state.cow.water=7680");minutes(15);const again=J('GameLivestock.state');const b0=before.animals.find(a=>a.brood),b1=again.animals.find(a=>a.brood);assert.equal(b1.brood.progressMs,b0.brood.progressMs+12500,'brood continues, not reset');assert.equal(again.animals.filter(a=>a.kind==='cow').length,3,'the waiting calf event fires once food and water return');});

// ---------------- Power / time ----------------
test('no_power_pauses_all_timers_no_death',()=>{reset();E('V09Power.running=false;V010Energy.battery.charge=0;V09Power.frame++');const before=J('GameLivestock.state.animals');const f=J('GameLivestock.state.chicken');days(3);assert.deepEqual(J('GameLivestock.state.animals'),before);assert.deepEqual(J('GameLivestock.state.chicken'),f);assert.equal(E('GameLivestock.powered()'),false);
 E('V09Power.running=true;V010Energy.battery.charge=V010Energy.battery.capacity;V09Power.frame++');days(1);assert.notDeepEqual(J('GameLivestock.state.animals'),before);});
test('agriculture_time_only_pause_hidden_death_siege_and_no_offline',()=>{for(const f of ['document.hidden=true','playerDead=true','GameFlow.pause("qa")']){reset();const a=J('GameLivestock.state.animals');E(f+';AgricultureTime.advance(2880);V016Lighting.tick(1000);GameLivestock.settle()');assert.deepEqual(J('GameLivestock.state.animals'),a,f);}
 reset();E('WorldClock.restore({schema:1,day:10,minute:0})');const a=E('AgricultureTime.now()');const age=E("GameLivestock.list('cow')[0].ageMs");for(let i=0;i<150;i++)E('V016Lighting.tick(1000)');E('V09Power.frame++;GameLivestock.settle()');const agri=E('AgricultureTime.now()')-a;assert.ok(Math.abs(agri-150000/3)<1,String(agri));assert.equal(E("GameLivestock.list('cow')[0].ageMs")-age,Math.floor(agri/12500)*12500,'siege slowdown slows animals');
 // Offline: Date.now moving forward between save and load gives no progress.
 reset();const raw=E('JSON.stringify(captureGameProgress())');const s0=J('GameLivestock.state');E('Date.now=(n=>()=>n+7*864e5)(Date.now())');r.context.qaRaw=raw;E('restoreGameProgress(decodeGameProgress(qaRaw));GameLivestock.settle()');const s1=J('GameLivestock.state');delete s0.at;delete s1.at;assert.deepEqual(s1,s0);});
test('dev_world_clock_advance_follows_farm_rules',()=>{reset();const a=E('AgricultureTime.now()');E('V016Lighting.tick(1000)');assert.ok(E('AgricultureTime.now()')>a);const b=E('AgricultureTime.now()');E('WorldClock.advance(60000)');assert.equal(E('AgricultureTime.now()'),b,'direct clock jumps do not feed AgricultureTime, exactly as the Pass A farm');});

// ---------------- Storage ----------------
test('pantry_storages_10_11_12_visible_13_retired',()=>{reset();const q=J('BunkerLayout.rooms.pantry');for(const i of [10,11,12]){const o=J(`interactionObjects('bunker').find(o=>o.id==='chest${i}')`);assert.ok(o&&o.kind==='storage','chest'+i);assert.ok(o.x>=q.left&&o.x+o.w<=q.right&&o.y>=q.top&&o.y+o.h<=q.bottom,'chest'+i+' in pantry');assert.equal(E(`solidObjects('bunker').some(s=>s.id==='chest${i}')`),true);
  E(`player.x=${o.x+o.w/2};player.y=${o.y-30}`);assert.equal(E(`canInteract(interactionObjects('bunker').find(o=>o.id==='chest${i}'),player.x,player.y)`),true);}
 assert.equal(E("interactionObjects('bunker').some(o=>o.id==='chest13')"),false);const w=count(13,'water');days(5);assert.equal(count(13,'water'),w,'#13 is not an animal water source');
 E("player.x=4700;player.y=-160;for(const d of v09Doors)d.open=1;invalidateGeometry()");for(const i of [10,11,12]){const o=J(`interactionObjects('bunker').find(o=>o.id==='chest${i}')`);assert.ok(E(`findWalkPath(4700,-160,{...interactionObjects('bunker').find(o=>o.id==='chest${i}'),range:40},'bunker',15)`)?.length,'route chest'+i);}});
test('storage_full_no_loss_no_duplication_for_eggs_and_milk',()=>{reset();E("storageChests[10].items=Array.from({length:60},()=>({type:'stone',qty:STACK_MAX}))");days(1);assert.equal(count(10,'eggs'),0);assert.equal(E('GameLivestock.state.pending.eggs'),2);save();assert.equal(E('GameLivestock.state.pending.eggs'),2);E('storageChests[10].items.pop()');minutes(15);assert.equal(count(10,'eggs'),2);assert.equal(E('GameLivestock.state.pending.eggs'),0);});
test('feed_mill_overflow_full_backpack_to_storage12_no_loss_no_dup',()=>{reset();E("scene='bunker';player.x=4960;player.y=-300;player.floor=2;bag=Array.from({length:BAG_SLOTS},()=>({type:'stone',qty:100}));storageChests[12].items=[];addToSlots(storageChests[8].items,'grain',20,60)");
 const BAG=()=>E('BAG_SLOTS');E("feedCraftLoaded=20");assert.equal(E("V09Craft.start('feed_craft','feed',2)"),true);E('for(let i=0;i<80;i++){V09Power.frame++;V09Craft.tick(100);}');assert.equal(E("bagCount('stone')"),BAG()*100);E("V09Craft.collect('feed_craft')");
 const inBag=E("bagCount('animal_feed')"),inChest=count(12,'animal_feed'),pending=E("(V09Craft.craftQueue.getJob('feed_craft')?.qty)||(pendingFeedCraft?.qty)||0");assert.equal(inBag+inChest+pending,40,JSON.stringify({inBag,inChest,pending}));assert.ok(inChest>0,'overflow reached visible #12');});

// ---------------- Movement ----------------
test('chickens_stay_inside_no_wall_feeder_cowfarm_crossing_and_spread',()=>{reset();setHerd([...chickens(8),...chickens(4,0).map((a,i)=>({...a,id:'chicken:'+(40+i)})),...cows(6)]);E('player.x=5107;player.y=120;player.floor=2');
 const roam=J('GameLivestock.roam'),fx=J('GameLivestock.fixtures'),ch=J('BunkerLayout.rooms.chicken_farm');let minPair=1e9,sumMin=0,samples=0;
 for(let f=0;f<1800;f++){r.advance?.(16.667);E('GameLivestock.update()');if(f%30)continue;const ps=J("GameLivestock.list('chicken').map(a=>GameLivestock.view(a))");
  for(const p of ps){assert.ok(p.x>=ch.left+15&&p.x<=ch.right-15&&p.y>=ch.top+15&&p.y<=ch.bottom-15,'inside '+JSON.stringify(p));for(const k of ['chickenFeeder','chickenDrinker','nest'])if(p.mode!=='brood'){const b=fx[k];assert.ok(!(p.x>b.x&&p.x<b.x+b.w&&p.y>b.y&&p.y<b.y+b.h),k);}
   assert.equal(E(`BunkerLayout.floorAt(${p.x},${p.y})`),2);assert.ok(p.x<J('BunkerLayout.rooms.cow_farm').left);}
  for(let i=0;i<ps.length;i++){let m=1e9;for(let j=0;j<ps.length;j++)if(i!==j)m=Math.min(m,Math.hypot(ps[i].x-ps[j].x,ps[i].y-ps[j].y));sumMin+=m;samples++;minPair=Math.min(minPair,m);}}
 assert.ok(sumMin/samples>=12,'flock spread, mean nearest '+sumMin/samples);assert.ok(minPair>=4,'no chicken passes through another '+minPair);
 for(const a of J("GameLivestock.list('cow')")){const v=J(`GameLivestock.view(GameLivestock.animals.find(a=>a.id==='${a.id}'))`),c=J(`GameLivestock.stallCenter(${a.stall})`);assert.deepEqual([v.x,v.y],[c.x,c.y]);assert.equal(v.moving,false);}});
test('player_routes_to_nest_feeders_drinkers',()=>{reset();E('player.x=4700;player.y=-160;player.floor=2;for(const d of v09Doors)d.open=1;invalidateGeometry()');for(const o of J("interactionObjects('bunker').filter(o=>o.kind==='livestock_chickens'||o.kind==='livestock_cows')")){r.context.qaO=o;assert.ok(E("findWalkPath(4700,-160,{...qaO},'bunker',15)")?.length,o.id);}});

// ---------------- Save ----------------
test('new_format_roundtrip_exact_mid_brood_and_calf',()=>{reset();E("addToSlots(storageChests[10].items,'eggs',3,60)");J('GameLivestock.brood(3)');days(1.3);minutes(7);const s0=J('GameLivestock.capture()');save();const s1=J('GameLivestock.capture()');delete s0.at;delete s1.at;assert.deepEqual(s1,s0);days(1);save();assert.equal(E("GameLivestock.animals.some(a=>a.brood)"),false);});
test('legacy_animal_save_starts_2_plus_2_and_drops_old_fields',()=>{reset();const old=JSON.parse(fs.readFileSync('qa/fixtures/phase0-corrective-save.json','utf8'));assert.ok(old.livestock&&old.v09.chickenBreedMs!==undefined&&!old.livestock043);
 old.livestock.animals=old.livestock.animals.concat(Array.from({length:10},()=>({...old.livestock.animals.find(a=>a.kind==='chicken')})));r.context.qaOld=JSON.stringify(old);E('restoreGameProgress(decodeGameProgress(qaOld));for(const p of GameFlow.reasons)GameFlow.resume(p)');
 assert.deepEqual(herd().map(a=>[a.kind,a.stage]).sort(),[['chicken',2],['chicken',2],['cow',2],['cow',2]]);const d=J('captureGameProgress()');assert.ok(d.livestock043);assert.equal('livestock' in d,false);assert.equal('chickenBreedMs' in d.v09,false);});
test('invalid_livestock_saves_rejected_without_mutation',()=>{reset();const good=J('captureGameProgress()');for(const bad of [d=>d.livestock043.animals.push({...d.livestock043.animals[0]}),d=>d.livestock043.chicken.feed=3841,d=>d.livestock043.animals=d.livestock043.animals.filter(a=>a.kind!=='cow'),d=>d.livestock043.animals[0].stage=0,d=>d.livestock043.animals.find(a=>a.kind==='cow').stall=9,d=>{d.livestock043.animals.forEach(a=>{if(a.kind==='chicken')a.brood={eggs:1,progressMs:0};});}]){const d=JSON.parse(JSON.stringify(good));bad(d);r.context.qaBad=JSON.stringify(d);assert.throws(()=>E('restoreGameProgress(decodeGameProgress(qaBad))'));assert.deepEqual(J('GameLivestock.capture().animals'),good.livestock043.animals);}});

// ---------------- UI / visual hook ----------------
test('ui_panels_brood_action_ru_en',()=>{for(const lang of ['ru','en']){reset();E(`I18n.setLanguage('${lang}')`);E("addToSlots(storageChests[10].items,'eggs',4,60)");const nest=J("interactionObjects('bunker').find(o=>o.id==='l2_nest')");E(`player.x=${nest.x+nest.w/2};player.y=${nest.y+nest.h+30}`);E("executeInteraction(interactionObjects('bunker').find(o=>o.id==='l2_nest'))");
  assert.equal(E("el('livestockChickens').classList.contains('open')"),true);const text=E("el('livestockChickens').textContent");assert.ok(!/animals\./.test(text),text);assert.ok(lang==='en'?/Set to Brood/.test(text):/Посадить на яйца/.test(text),text);
  E("el('livestockChickens').querySelector('[data-brood-plus]').click();el('livestockChickens').querySelector('[data-brood]').click()");assert.equal(E("GameLivestock.animals.find(a=>a.brood)?.brood.eggs"),2);E("closeOverlay(el('livestockChickens'))");
  const f=J("interactionObjects('bunker').find(o=>o.id==='l2_cow_feeder')");E(`player.x=${f.x+40};player.y=${f.y+f.h+30}`);E("executeInteraction(interactionObjects('bunker').find(o=>o.id==='l2_cow_feeder'))");assert.equal(E("el('livestockCows').classList.contains('open')"),true);assert.ok(!/animals\./.test(E("el('livestockCows').textContent")));E("closeOverlay(el('livestockCows'))");}
 E("I18n.setLanguage('ru')");const keys=[...new Set([...fs.readFileSync('src/farm/livestock.js','utf8').matchAll(/'animals\.([\w.]+)'/g)].map(m=>'animals.'+m[1]).concat([...fs.readFileSync('src/farm/livestock.js','utf8').matchAll(/T\('([\w.]+)'/g)].map(m=>'animals.'+m[1])))].filter(k=>!k.endsWith('.'));
 const ru=JSON.parse(fs.readFileSync('locales/ru.json')),en=JSON.parse(fs.readFileSync('locales/en.json'));for(const k of keys.concat(['animals.broodFail.nestBusy','animals.broodFail.slots','animals.broodFail.eggs','animals.broodFail.noHen','animals.broodFail.count','animals.broodFail.unavailable','animals.note.chickenFeed','animals.note.cowWater','animals.status.feed','animals.status.water','animals.status.power','animals.status.ok']))assert.ok(ru[k]&&en[k],k);});
test('visual_hook_drawLivestockAnimal_and_view_all_modes_stages',()=>{reset();setHerd([...chickens(2),...chickens(1,0).map(a=>({...a,id:'chicken:30'})),...chickens(1,1).map(a=>({...a,id:'chicken:31'})),...cows(2),...cows(1,0,2).map(a=>({...a,id:'cow:950'})),...cows(1,1,3).map(a=>({...a,id:'cow:951'}))]);E("addToSlots(storageChests[10].items,'eggs',1,60)");J('GameLivestock.brood(1)');
 assert.equal(E('typeof drawLivestockAnimal'),'function');const keys=['kind','stage','angle','mode','moving','speed','gestureAt'];E('player.x=5107;player.y=120;player.floor=2');const seen=new Set();
 for(let f=0;f<2400;f++){r.advance?.(16.667);E('GameLivestock.update()');if(f%20)continue;for(const v of J('GameLivestock.animals.map(a=>GameLivestock.view(a))')){for(const k of keys)assert.ok(k in v,k);seen.add(v.kind+':'+v.stage);seen.add(v.mode);}}
 for(const s of ['chicken:0','chicken:1','chicken:2','cow:0','cow:1','cow:2','brood','idle','walk','eat'])assert.ok(seen.has(s),s+' '+[...seen]);
 assert.deepEqual(J('GameLivestock.modes'),['idle','walk','run','eat','drink','brood']);assert.deepEqual(J('GameplayBalance.animals.stageScale'),{chicken:[.45,.7,1],cow:[.5,.7,1]});
 E('GameLivestock.animals.forEach((a,i)=>drawLivestockAnimal(a,i));GameLivestock.draw()');const saved=J('captureGameProgress().livestock043.animals');assert.ok(saved.every(a=>!('x' in a)&&!('angle' in a)&&!('mode' in a)),'poses are not saved');});
test('console_no_errors',()=>assert.deepEqual(r.errors,[]));
// ---------------- Performance ----------------
const perf={};
test('performance_18_animals_update_and_power_cache',()=>{reset();setHerd([...chickens(12).map((a,i)=>({...a,stage:i<6?2:i<9?1:0,ageMs:[0,1.5,3][i<6?2:i<9?1:0]*D()})),...cows(6)]);fix();E('player.x=5107;player.y=120;player.floor=2');
 for(const n of [0,12,18]){const list=n===0?[...chickens(2),...cows(2)]:n===12?[...chickens(8),...cows(4)]:[...chickens(12),...cows(6)];setHerd(list);if(n===0)E("L2Systems.set('animals',false)");for(let i=0;i<60;i++)E('GameLivestock.update()');
  const t=[];for(let i=0;i<600;i++){r.advance?.(16.667);const a=performance.now();E('GameLivestock.update()');t.push(performance.now()-a);}t.sort((a,b)=>a-b);perf['animals'+n]={p50:+t[300].toFixed(4),p95:+t[570].toFixed(4),max:+t.at(-1).toFixed(4)};E("L2Systems.set('animals',true)");}
 assert.ok(perf.animals18.p50<1,JSON.stringify(perf));
 // No per-animal power recalculation: one step asks the power owner once, frames without a step never.
 setHerd([...chickens(12),...cows(6)]);fix();E('window.qaAlloc=0;window.qaWrap=V09Power.allocation;V09Power.allocation=function(dt){qaAlloc++;return qaWrap(dt);}');E('GameLivestock.settle()');for(let i=0;i<100;i++)E('GameLivestock.update()');const idle=E('qaAlloc');E('qaAlloc=0;AgricultureTime.advance(15);V09Power.frame++;GameLivestock.settle()');const one=E('qaAlloc');E('V09Power.allocation=qaWrap');
 perf.powerAllocationCalls={framesWithoutStep100:idle,oneStep18Animals:one};assert.equal(idle,0);assert.ok(one<=2,String(one));
 // A 30-day catch-up (e.g. DEV) is bounded work.
 const a=performance.now();days(30);perf.thirtyDaySettleMs=+(performance.now()-a).toFixed(2);assert.ok(perf.thirtyDaySettleMs<2000);});
const result={runtimeSha256:require('crypto').createHash('sha256').update(fs.readFileSync('js/game.js')).digest('hex'),passed:checks.filter(c=>c.ok).length,failed:checks.filter(c=>!c.ok).length,performance:perf,checks};fs.writeFileSync('qa/results/pass-b.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(result.failed)process.exitCode=1;
