// Stage 7 contracts: real commands and owners, no server or simulated peers.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
process.chdir(path.resolve(__dirname,'..'));
const {setup}=require('./runtime.cjs'),checks=[],r=setup('index.html'),E=s=>r.eval(s),json=v=>JSON.parse(JSON.stringify(v));
const initial=E('JSON.stringify(captureGameProgress())');
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack?.slice(0,3500)});}}
function reset(){E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(initial)}));for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);playerDead=false;document.hidden=false;menuOpen=false;`);}
const rawState=()=>E('JSON.stringify({player:{...player},bag,equipment,magazine,magazineMax,quick:V013Inventory.items,combat:V010Combat.reloading})');
check('actors.oneLiveViewNoSecondPlayer',()=>{assert.equal(E('GameActors.list().length'),1);assert.equal(E('GameActors.local.entity===player&&GameActors.local.inventory===GameState.inventory&&GameActors.local.combat===GameState.combat'),true);assert.equal(E('GameActors.local.typeId'), 'player');assert.equal(E('GameActors.get("foreign")'),null);});
check('actors.identityIndependentOfDisplayName',()=>{const id=E('GameActors.localId');E('GameState.session.name="Any display name";player.instanceId="forged";');assert.equal(E('GameActors.localId'),id);});
check('actors.liveContainersAfterRestore',()=>{E('window.previousBag=GameActors.local.inventory.bag');reset();assert.equal(E('GameActors.local.inventory.bag===bag&&bag!==previousBag'),true);});
check('identity.factoryDoesNotConsumeExtraRandomNumbers',()=>{const old=setup('qa/pre-stage7/index.html');reset();for(const x of [old,r])x.eval('window.randomCalls=0;window.randomBefore=Math.random;Math.random=()=>{randomCalls++;return .5};makeZombie(200,200);Math.random=randomBefore;');assert.equal(E('randomCalls'),old.eval('randomCalls'));});
check('identity.immutableUniqueAndSeparateFromAISeed',()=>{reset();assert.equal(E('new Set(zombies.map(z=>z.instanceId)).size===zombies.length'),true);const id=E('zombies[0].instanceId');E('zombies[0].instanceId="enemy:999999";zombies[0].worldId="legacy-ai-seed";');assert.equal(E('zombies[0].instanceId'),id);assert.equal(E('zombies[0].typeId'),E('zombies[0].type'));});
check('identity.reorderRoundtripAndMonotonicSpawn',()=>{reset();E('zombies.reverse()');const ids=E('JSON.stringify(zombies.map(z=>z.instanceId))'),raw=E('JSON.stringify(captureGameProgress())');E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(raw)}))`);assert.equal(E('JSON.stringify(zombies.map(z=>z.instanceId))'),ids);assert.equal(E('zombies.includes(GameIdentity.enemy(zombies[3].instanceId))'),true);E('window.newEnemy=makeZombie(260,600);');assert.ok(!JSON.parse(ids).includes(E('newEnemy.instanceId')));});
function attackSetup(){reset();E("scene='surface';Object.assign(V014Robots.state,{scene:'surface',x:800,y:850,task:'follow',mode:'attack',combatMode:'attack',packed:false,battery:100,hp:100,ammo:30});window.targetEnemy=zombies[7];window.savedTargetId=targetEnemy.instanceId;");assert.equal(E('V014Robots.attack(targetEnemy)'),true);}
check('drone.targetSurvivesReorderAndIndexRemoval',()=>{attackSetup();E('zombies.reverse();zombies.splice(0,1);');assert.equal(E('GameIdentity.enemy(V014Robots.state.targetId)===targetEnemy'),true);assert.equal(E('V014Robots.state.targetIndex'),E('zombies.indexOf(targetEnemy)'));});
check('drone.targetSurvivesSaveRestart',()=>{attackSetup();E('zombies.reverse();saveGameProgress()');const again=setup('index.html',Object.fromEntries(r.storage));assert.equal(again.eval('V014Robots.state.targetId'),E('savedTargetId'));assert.equal(again.eval('GameIdentity.enemy(V014Robots.state.targetId)?.instanceId'),E('savedTargetId'));assert.deepEqual(again.errors,[]);});
check('drone.replacedArraySlotNeverRetargetsNewEnemy',()=>{attackSetup();E('window.targetSlot=zombies.indexOf(targetEnemy);zombies[targetSlot]=makeZombie(targetEnemy.x,targetEnemy.y);');assert.equal(E('GameIdentity.enemy(V014Robots.state.targetId)'),null);assert.equal(E('V014Robots.state.targetIndex'),null);E('V014Robots.tick(16.667)');assert.notEqual(E('V014Robots.state.task'),'attack');});
check('map.enemyMarkersUseStableIds',()=>{reset();E("scene='surface'");const before=json(E('V0105.markers().filter(m=>m.kind==="zombie").map(m=>m.id).sort()'));E('zombies.reverse()');assert.deepEqual(json(E('V0105.markers().filter(m=>m.kind==="zombie").map(m=>m.id).sort()')),before);assert.ok(before.every(id=>id.startsWith('enemy:')));});
for(const stage of ['stage0','stage1','stage2'])for(const name of ['fresh_game','day_x','rifle_ak74_37_60','drone_packed','damaged_base_turret'])check(`migration.${stage}.${name}.deterministicAndRoundtrip`,()=>{
 const raw=fs.readFileSync(`qa/${stage}/fixtures/${name}.json`,'utf8'),before=E('JSON.stringify(captureGameProgress())');
 const a=json(E(`decodeGameProgress(${JSON.stringify(raw)})`)),b=json(E(`decodeGameProgress(${JSON.stringify(raw)})`));assert.deepEqual(a.identity027,b.identity027);assert.equal(a.saveVersion,7);assert.equal(E('JSON.stringify(captureGameProgress())'),before);
 E(`restoreGameProgress(${JSON.stringify(a)})`);const saved=E('JSON.stringify(captureGameProgress())');E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(saved)}))`);assert.equal(E('JSON.stringify(captureGameProgress())'),saved);
});
for(let slot=1;slot<=5;slot++)check(`identity.slot.${slot}.independentRestart`,()=>{reset();E(`window.slotData=captureGameProgress();slotData.identity027.playerId='player:${slot+10}';restoreGameProgress(slotData);`);const raw=E('JSON.stringify(captureGameProgress())'),stored={['survival_base_v09_slot_'+slot]:raw};const x=setup('index.html',stored,{mainMenu:true});assert.equal(x.eval(`V09Saves.load(${slot})`),true);assert.equal(x.eval('GameActors.localId'),'player:'+(slot+10));assert.equal(x.eval('saveGameProgress()'),true);assert.equal(JSON.parse(x.storage.get('survival_base_v09_slot_'+slot)).identity027.playerId,'player:'+(slot+10));assert.deepEqual(x.errors,[]);});
for(const [id,change]of [
 ['missing',d=>delete d.identity027],['duplicate',d=>d.identity027.enemies[1]=d.identity027.enemies[0]],
 ['counterReuse',d=>d.identity027.nextEnemy=1],['invalidId',d=>d.identity027.enemies[0]='0'],
 ['missingEnemy',d=>d.identity027.enemies.pop()],['displayNameId',d=>d.identity027.playerId='Ali'],
 ['danglingDrone',d=>d.identity027.droneTargetId='enemy:999999'],
 ['shadowEnemyId',d=>{d.player.health=41;d.zombies[0].instanceId='enemy:999';}],
 ['shadowEnemyType',d=>{d.player.health=41;d.zombies[0].typeId='heavy';}],
 ['shadowPlayerId',d=>d.player.instanceId='player:999'],
 ['shadowDroneTarget',d=>d.robots014.targetId='enemy:999']
])check('migration.reject.'+id+'.beforeAnyMutation',()=>{reset();const d=json(E('captureGameProgress()'));change(d);const before=E('JSON.stringify(captureGameProgress())'),storage=Object.fromEntries(r.storage);assert.throws(()=>E(`restoreGameProgress(${JSON.stringify(d)})`));assert.equal(E('JSON.stringify(captureGameProgress())'),before);assert.deepEqual(Object.fromEntries(r.storage),storage);});
for(const mode of ['PC','MOBILE'])check('commands.'+mode+'.sameActorAndResults',()=>{reset();E(`GameInput.setMode('${mode}')`);assert.equal(E("GameActions.dispatch('MOVE',{kind:'vector',x:0,y:1,power:.5})"),true);assert.equal(E('movePower'),.5);assert.equal(E("GameSimulation.execute({actorId:GameActors.localId,type:'MOVE',payload:{kind:'vector',x:1,y:0,power:.8}})"),true);assert.equal(E('moveX'),1);assert.equal(E('movePower'),.8);});
for(const [type,payload]of [['MOVE',{kind:'vector',power:0}],['FIRE',{active:false}],['AIM',{active:false}],['SELECT_SLOT',{index:1}],['RELOAD',{}],['INTERACT',{nearest:true}]])check('commands.foreignActorCannot.'+type,()=>{reset();E('firing=true;rightAimActive=true;movePower=.8;');const before=E('JSON.stringify([firing,rightAimActive,movePower,activeHandSlot,captureGameProgress()])');assert.equal(E(`GameSimulation.execute(${JSON.stringify({actorId:'player:999',type,payload})})`),false);assert.equal(E('JSON.stringify([firing,rightAimActive,movePower,activeHandSlot,captureGameProgress()])'),before);});
check('commands.localModalGuardAndReleasePreserved',()=>{reset();E('openOverlay(el("inventoryOverlay"));movePower=.6;firing=true;');assert.equal(E("GameActions.dispatch('MOVE',{kind:'vector',x:1,y:0,power:1})"),false);assert.equal(E("GameActions.dispatch('FIRE',{active:false})"),true);assert.equal(E('firing'),false);});
check('commands.invalidDoesNotMutateState',()=>{reset();const before=rawState();for(const payload of [{kind:'vector',x:null,y:2,power:1},{kind:'point',x:'800',y:850}])assert.equal(E(`GameSimulation.execute({actorId:GameActors.localId,type:'MOVE',payload:${JSON.stringify(payload)}})`),false);assert.equal(E("GameSimulation.execute({actorId:GameActors.localId,type:'SELECT_SLOT',payload:{index:9}})"),false);assert.equal(rawState(),before);});
check('ui.equipmentRenderingCannotCalculateOrClampPlayerHP',()=>{reset();E('equipment.body={type:"vest5",qty:1,level:5};player.maxHealth=123;player.health=121;player.walkSpeed=9;player.runSpeed=12;');const before=rawState();E('renderEquipment();renderEquipment();V010Combat.equipmentSnapshot();');assert.equal(rawState(),before);});
check('ui.itemCardAndMagazinePickerDoNotInitializeItems',()=>{reset();E('bag[0]={type:"rifle_m4",qty:1};');const before=rawState();E('V011UI.details("bag",0);');assert.equal(rawState(),before);});
check('ui.defaultsViewMatchesInitializationWithoutAllocatingUid',()=>{reset();for(const type of ['rifle_ak74','rifle_m4','vest5','boots1']){const raw={type,qty:1,modules:{magazine:true}};r.context.viewProbe=raw;const before=JSON.stringify(raw),view=json(E('V010Combat.itemView(viewProbe)'));assert.equal(JSON.stringify(raw),before);assert.equal(view.uid,undefined);const initialized=json(E('V010Combat.ensure(JSON.parse(JSON.stringify(viewProbe)))'));delete initialized.uid;assert.deepEqual(view,initialized);}E('bag[0]={type:"rifle_m4",qty:1};V011UI.details("bag",0);');const text=r.doc.getElementById('v010ItemDetails').textContent;assert.ok(!text.includes('undefined'));assert.ok(text.includes('0/30'));});
check('ui.ammoHudIsReadOnly',()=>{reset();E('magazine=9;magazineMax=12;');const before=rawState();E('updateAmmoHud();updateAmmoHud();');assert.equal(rawState(),before);});
check('simulation.equipAndUnequipCommitWithoutRenderer',()=>{reset();E('window.savedRenderEquipment=renderEquipment;renderEquipment=()=>{};bag[0]={type:"vest5",qty:1,level:5};');try{assert.equal(E('V010Inventory.equip(0)'),true);assert.equal(E('player.maxHealth'),E('V010Combat.equipmentSnapshot().hp'));assert.ok(E('player.maxHealth')>100);assert.equal(E('V010Inventory.unequip("body")'),true);assert.equal(E('player.maxHealth'),E('V010Combat.equipmentSnapshot().hp'));}finally{E('renderEquipment=savedRenderEquipment');}});
check('world.eventsIndependentOfClientSceneCameraAndMode',()=>{reset();for(const scene of ['surface','bunker'])for(const mode of ['PC','MOBILE']){E(`scene='${scene}';GameInput.setMode('${mode}');camera.x=-900;camera.y=7000;WorldClock.restore({schema:1,day:100,minute:0});`);assert.equal(E("WorldEvents.isActive('day_x')"),true);E('WorldClock.restore({schema:1,day:100,minute:360})');assert.equal(E("WorldEvents.isActive('day_x')"),false);}});
check('world.currentClientSceneIsNotWorldAuthority',()=>{reset();assert.equal(E('Object.hasOwn(GameState.world,"scene")'),false);E("scene='bunker'");assert.equal(E('GameActors.local.scene'), 'bunker');assert.equal(E('GameState.render.scene'), 'bunker');assert.equal(E('GameState.world.identity===GameIdentity&&GameState.world.clock===WorldClock'),true);});
check('architecture.noNewNetworkOrLoopInNewModules',()=>{for(const f of ['state/identity.js','state/actors.js','simulation/commands.js']){const src=fs.readFileSync('src/'+f,'utf8');assert.ok(!/new WebSocket|fetch\(|setInterval\(|requestAnimationFrame\(/.test(src),f);}assert.equal(E('GameActors.list().length'),1);});
check('console.noErrors',()=>assert.deepEqual(r.errors,[]));
const result={version:require('../package.json').version,passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks};
fs.writeFileSync('qa/results/readiness.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(c=>c.status==='FAIL')}));if(result.failed)process.exitCode=1;
