const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
process.chdir(path.resolve(__dirname,'..'));process.env.LAST_BASE_ASSETS=process.cwd();process.env.LAST_BASE_TEST_LANGUAGE='ru';
const {boot}=require('./story-video-harness.cjs'),checks=[];
const drain=async()=>{for(let n=0;n<5;n++)await Promise.resolve();};
const test=async(id,fn)=>{try{await fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack});}};
function start(h){assert.equal(h.E('V09Saves.newGame(1)'),true);assert.equal(h.E('StoryPlayer.active'),true);assert.equal(h.videos.length,1);return h.videos[0];}
function disposed(v){assert.equal(v.paused,true);assert.equal(v.src,'');assert.equal(v.removed,true);assert.equal(v.loadCalls,1);assert.ok(Object.values(v.listeners).every(a=>a.length===0));}
function core(h){h.E("scene='bunker';player.x=1210;player.y=680;V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=1;for(const d of Object.values(V09Power.devices))d.enabled=d.id===GameCampaign.powerId;CommandCoreUI.show('archive');CommandCoreUI.tick()");}
const section=h=>h.doc.getElementById('coreSection_archive'),card=h=>section(h).querySelector('[data-archive-open="log.arrival"]');
(async()=>{
await test('official_video_exact_bytes_and_catalog',()=>{const asset=JSON.parse(fs.readFileSync('assets/manifest.json')).videos['story/intro'],b=fs.readFileSync(asset.path);assert.equal(b.length,18124094);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),'b5a6fca2bceb66546dce80d09523ec7acc1440d780326860b39650a782185790');assert.equal(asset.durationMs,21250);assert.equal(asset.sha256,crypto.createHash('sha256').update(b).digest('hex'));});
await test('boot_is_lazy_no_video_for_menu_or_continue',()=>{const h=boot();assert.equal(h.videos.length,0);h.E('V09Saves.newGame(1);StoryPlayer.skip()');const save=h.storage.get('survival_base_v09_slot_1'),c=boot({'survival_base_v09_slot_2':save});assert.equal(c.videos.length,0);assert.equal(c.E('MainMenu.continueGame()'),true);assert.equal(c.videos.length,0);assert.equal(c.E('StoryPlayer.active'),false);});
await test('new_game_plays_official_inline_media_and_freezes_world',async()=>{const h=boot(),v=start(h);await drain();assert.equal(v.src,'assets/video/last-base-intro.mp4');assert.equal(v.playsInline,true);assert.equal(v.loop,false);assert.equal(v.preload,'metadata');assert.equal(v.playCalls,1);assert.equal(h.E('GameFlow.paused'),true);assert.equal(h.E('StoryPlayer.inspect().media'),true);const before=h.J('captureGameProgress()');h.E('for(let t=0;t<3000;t+=100)gameLoop(t)');const after=h.J('captureGameProgress()');for(const key of Object.keys(before))if(key!=='savedAt')assert.deepEqual(after[key],before[key],key);assert.equal(h.E('StoryPlayer.inspect().elapsedMs'),0);h.E('StoryPlayer.skip()');disposed(v);assert.deepEqual(h.errors,[]);});
await test('completion_uses_ended_not_old_18s_timer_or_buffer_wait',async()=>{const h=boot(),v=start(h);await drain();v.currentTime=19;h.E('for(let t=0;t<30000;t+=250)StoryPlayer.tick(t)');assert.equal(h.E('StoryPlayer.active'),true);assert.equal(h.E('StoryPlayer.inspect().elapsedMs'),19000);v.currentTime=21.25;v.dispatchEvent({type:'ended'});assert.equal(h.E('StoryPlayer.active'),false);assert.equal(h.E('GameStory.view().intro'),'completed');assert.equal(h.E('GameFlow.paused'),false);assert.equal(h.E('captureGameProgress().campaign031.activeChapter'),'chapter_1');disposed(v);const rev=h.E('GameStory.revision');v.dispatchEvent({type:'ended'});assert.equal(h.E('GameStory.revision'),rev);});
for(const exit of ['skip','escape','close'])await test('video_exit_'+exit+'_frees_source_once_and_persists',async()=>{const h=boot(),v=start(h);await drain();if(exit==='skip')h.doc.getElementById('storySkip').click();if(exit==='escape')h.emit('keydown',h.doc.body,{key:'Escape',code:'Escape'});if(exit==='close')h.doc.getElementById('storyOverlay').querySelector('.v09Close').click();disposed(v);assert.equal(h.E('GameFlow.paused'),false);assert.equal(h.E('GameStory.view().intro'),'skipped');const c=boot(Object.fromEntries(h.storage));assert.equal(c.E('MainMenu.continueGame()'),true);assert.equal(c.videos.length,0);assert.equal(c.E('GameStory.view().intro'),'skipped');});
await test('native_play_policy_block_requires_explicit_resume',async()=>{const h=boot({}, {mode:'blocked'}),v=start(h);await drain();assert.equal(h.E('StoryPlayer.inspect().playing'),false);assert.equal(h.E('StoryPlayer.inspect().media'),true);assert.equal(v.playCalls,1);assert.equal(v.muted,false);h.E('for(let t=0;t<30000;t+=250)StoryPlayer.tick(t)');assert.equal(h.E('GameStory.view().intro'),'pending');h.doc.getElementById('storyPlayPause').click();await drain();assert.equal(v.playCalls,2);assert.equal(v.paused,false);assert.equal(h.E('StoryPlayer.inspect().playing'),true);h.E('StoryPlayer.skip()');disposed(v);});
await test('manual_pause_hidden_resume_preserves_pause_and_volume',async()=>{const h=boot(),v=start(h);await drain();h.E('StoryPlayer.pause();document.hidden=true');h.emit('visibilitychange',h.doc);h.E('document.hidden=false');h.emit('visibilitychange',h.doc);assert.equal(v.paused,true);assert.equal(v.playCalls,1);h.E('StoryPlayer.pause()');await drain();assert.equal(v.paused,false);h.E('masterVolume=0;StoryPlayer.tick(0)');assert.equal(v.muted,true);assert.equal(v.volume,0);h.E('masterVolume=.37;StoryPlayer.tick(100)');assert.equal(v.muted,false);assert.equal(v.volume,.37);h.E('document.hidden=true');h.emit('visibilitychange',h.doc);assert.equal(v.paused,true);h.E('document.hidden=false');h.emit('visibilitychange',h.doc);await drain();assert.equal(v.paused,false);h.E('StoryPlayer.skip()');disposed(v);});
for(const mode of ['error','pending'])await test('media_'+mode+'_fallback_and_skip_never_softlock',async()=>{const h=boot({}, {mode}),v=start(h);await drain();if(mode==='pending')h.flushTimers(15001);assert.equal(h.E('StoryPlayer.inspect().media'),false);assert.equal(h.E('StoryPlayer.active'),true);assert.equal(h.E('GameFlow.paused'),true);disposed(v);h.doc.getElementById('storySkip').click();assert.equal(h.E('StoryPlayer.active'),false);assert.equal(h.E('GameFlow.paused'),false);});
await test('late_play_promise_after_skip_cannot_restart_or_mutate',async()=>{const h=boot({}, {mode:'pending'}),v=start(h);h.E('StoryPlayer.skip()');const before=h.J('GameStory.capture()');v.pending[0].resolve();await drain();disposed(v);assert.deepEqual(h.J('GameStory.capture()'),before);});
await test('pending_intro_continue_and_live_load_do_not_replay',async()=>{const h=boot(),v=start(h);await drain();const raw=h.E('JSON.stringify(captureGameProgress())');h.storage.set('survival_base_v09_slot_2',raw);assert.equal(h.E('V09Saves.load(2)'),true);disposed(v);assert.equal(h.videos.length,1);assert.equal(h.E('GameStory.view().intro'),'interrupted');const c=boot({'survival_base_v09_slot_2':raw});assert.equal(c.E('MainMenu.continueGame()'),true);assert.equal(c.videos.length,0);assert.equal(c.E('GameStory.view().intro'),'interrupted');});
await test('native_error_after_play_falls_back_and_releases',async()=>{const h=boot(),v=start(h);await drain();v.currentTime=7;h.E('StoryPlayer.tick(100)');v.dispatchEvent({type:'error'});disposed(v);assert.equal(h.E('StoryPlayer.inspect().media'),false);assert.equal(h.E('StoryPlayer.inspect().elapsedMs'),0);h.E('StoryPlayer.skip()');});
for(const language of ['ru','en'])for(const size of [[1280,800],[390,844],[844,390]])await test('archive_reread_save_load_'+language+'_'+size.join('x'),async()=>{
 const h=boot({}, {width:size[0],height:size[1]});start(h);h.E(`StoryPlayer.skip();I18n.setLanguage('${language}')`);core(h);const count=section(h).querySelectorAll('.archiveCard').length;
 assert.ok(card(h).textContent.includes(h.E("I18n.t('story.unread')")));assert.equal(card(h).tagName,'BUTTON');assert.equal(card(h).disabled,false);
 // Native click on the title bubbles to the whole button, as on PC/touch.
 h.emit('click',card(h).querySelector('.archiveCardTitle'),{pointerType:'mouse'});h.E('CommandCoreUI.tick()');assert.ok(section(h).querySelector('.archiveDocument'));const marked=h.J('GameStory.capture()');
 for(let n=0;n<3;n++){h.doc.getElementById('coreBack').click();assert.equal(section(h).querySelectorAll('.archiveCard').length,count);assert.ok(!card(h).textContent.includes(h.E("I18n.t('story.unread')")));assert.equal(card(h).disabled,false);h.emit('click',card(h).querySelector('.archiveReadState'),{pointerType:'touch'});h.E('CommandCoreUI.tick()');assert.ok(section(h).querySelector('.archiveDocument'));assert.deepEqual(h.J('GameStory.capture()'),marked);}
 const raw=h.E('JSON.stringify(captureGameProgress())'),c=boot({'survival_base_v09_slot_3':raw},{language,width:size[0],height:size[1]});assert.equal(c.E('MainMenu.continueGame()'),true);assert.equal(c.videos.length,0);core(c);assert.equal(card(c).disabled,false);assert.ok(!card(c).textContent.includes(c.E("I18n.t('story.unread')")));card(c).click();c.E('CommandCoreUI.tick()');assert.ok(section(c).querySelector('.archiveDocument'));assert.deepEqual(c.J('GameStory.capture()'),marked);assert.deepEqual(h.errors,[]);assert.deepEqual(c.errors,[]);
});
await test('archive_manual_replay_ended_stays_read_and_clickable',async()=>{const h=boot();start(h);h.E('StoryPlayer.skip()');core(h);card(h).click();h.E('CommandCoreUI.tick()');section(h).querySelector('[data-archive-play]').click();await drain();assert.equal(h.videos.length,2);h.videos[1].dispatchEvent({type:'ended'});assert.equal(h.E("GameStory.view().watched.includes('log.arrival')"),true);assert.equal(h.E('GameStory.view().intro'),'skipped');h.doc.getElementById('coreBack').click();card(h).click();assert.ok(section(h).querySelector('.archiveDocument'));disposed(h.videos[1]);});
await test('0370_save_unchanged_owners_with_explicit_G_migration',()=>{const {setup}=require('./runtime.cjs'),old=setup('qa/stage-f-final-base/index.html');old.eval("restoreGameProgress(GameNewGame.create());GameStory.request('finish_intro',{outcome:'completed'});scene='bunker';player.x=1210;player.y=680;V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=1;for(const d of Object.values(V09Power.devices))d.enabled=d.id===GameCampaign.powerId;GameStory.request('read',{entryId:'log.arrival'});");const save=JSON.parse(old.eval('JSON.stringify(captureGameProgress())')),h=boot({'survival_base_v09_slot_2':JSON.stringify(save)});const decoded=h.J('decodeGameProgress('+JSON.stringify(JSON.stringify(save))+')');for(const key of Object.keys(save))if(!['gameVersion','saveVersion'].includes(key))assert.deepEqual(require('./stage-h-contract.cjs').project(decoded)[key],save[key],'decode '+key);old.eval('restoreGameProgress('+JSON.stringify(save)+')');const expected=JSON.parse(old.eval('JSON.stringify(captureGameProgress())'));h.E('restoreGameProgress('+JSON.stringify(save)+')');const actual=h.J('captureGameProgress()');assert.equal(actual.saveVersion,h.E("SaveFormat.version"));for(const key of Object.keys(save))if(!['gameVersion','saveVersion','savedAt','saveName'].includes(key))assert.deepEqual(require('./stage-h-contract.cjs').project(actual)[key],expected[key],key);assert.equal(h.E('MainMenu.continueGame()'),true);assert.equal(h.videos.length,0);assert.equal(h.E('GameStory.view().intro'),'completed');});
const report={version:require('../package.json').version,runtimeSha256:crypto.createHash('sha256').update(fs.readFileSync('js/game.js')).digest('hex'),passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks,limitations:['Modeled HTMLVideoElement lifecycle; native browser/Telegram playback and device audio require manual verification. Original MP4 is separately inspected/decoded without rewriting.']};fs.writeFileSync('qa/results/stage-f-final.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,failed:report.failed,failures:checks.filter(c=>c.status==='FAIL')}));if(report.failed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
