// Stage B gate. The 0.31.1 archive bundle is immutable; the second furnace is
// injected at world creation in this harness, never exposed as a game command.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
process.chdir(path.resolve(__dirname,'..'));process.env.LAST_BASE_TEST_LANGUAGE='ru';
const {setup}=require('./runtime.cjs'),copy=x=>JSON.parse(JSON.stringify(x)),checks=[];
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack.slice(0,3500)});}}
const r=setup('index.html'),old=setup('qa/stage-b-base/index.html'),E=s=>r.eval(s),J=s=>copy(E(s)),O=s=>old.eval(s),OJ=s=>copy(O(s));
const initial=J('captureGameProgress()'),oldInitial=OJ('captureGameProgress()');
const restore=(runtime,d)=>runtime.eval(`restoreGameProgress(decodeGameProgress(${JSON.stringify(JSON.stringify(d))}))`);
const clean=d=>{d=require('./stage-c1-contract.cjs').project(d);d=require('./stage-ab-contract.cjs').previousCampaign(require('./stage-ab-contract.cjs').previousLayout(d));delete d.equipment032;delete d.saveVersion;delete d.gameVersion;return d;};
function reset(){restore(r,initial);E("menuOpen=false;playerDead=false;document.hidden=false;GameFlow.resume();scene='bunker';player.x=430;player.y=18;V09Power.running=true;V09Power.fuel=50;V010Progression.tick(1000);");}
const issue=(action,payload={},extra={})=>J(`GameEquipmentRuntime.execute(${JSON.stringify({instanceId:'furnace',actorId:E('GameActors.localId'),requestId:'qa:'+E('GameEquipmentRuntime.revision'),expectedRevision:E('GameEquipmentRuntime.revision'),action,payload,...extra})})`);
check('baseline.sha256',()=>assert.equal(crypto.createHash('sha256').update(fs.readFileSync('qa/stage-b-base/js/game.js')).digest('hex'),require('./stage-b-source-reference.json').baselineBundleSha256));
check('default_world.has_only_existing_instances',()=>{assert.equal(J('GameEquipment.ids').length,18);assert.equal(new Set(J('GameEquipment.ids')).size,18);assert.deepEqual(J('GameEquipment.productionIds'),['furnace','craft_bench','feed_craft']);assert.equal(E('GameEquipment.add===undefined&&GameEquipment.move===undefined&&GameEquipment.remove===undefined'),true);});
check('migration.0311.additive_pure_repeatable',()=>{const before=J('captureGameProgress()'),storage=copy(Object.fromEntries(r.storage)),raw=JSON.stringify(oldInitial),d=J(`decodeGameProgress(${JSON.stringify(raw)})`);assert.equal(d.saveVersion,r.eval('SaveFormat.version'));assert.deepEqual(clean(d),clean(oldInitial));assert.deepEqual(J(`decodeGameProgress(${JSON.stringify(JSON.stringify(d))})`),d);assert.deepEqual(J('captureGameProgress()'),before);assert.deepEqual(Object.fromEntries(r.storage),storage);});
check('migration.0311.active_paused_queue_output_refund_feed_and_item',()=>{
 restore(old,oldInitial);O("scene='bunker';player.x=430;player.y=1018;bag=[];for(const c of storageChests)c.items=[];for(const t of ['iron_ore','copper_ore','iron','copper','wood','parts'])addItem(t,100);V09Power.running=true;V09Power.fuel=70;V09Craft.start('furnace','iron',5);V09Craft.start('furnace','copper',4);V09Craft.start('craft_bench','hammer',2);for(let i=0;i<31;i++)V09Craft.tick(100);V09Craft.craftQueue.setPaused('furnace',true);V09Craft.craftQueue.ready.craft_bench.iron=7;V09Craft.craftQueue.refunds.furnace.copper_ore=9;pendingFeedCraft={recipe:'feed',batches:4,totalMs:10000,remainingMs:4000,readyAt:AgricultureTime.now()+4000,completedBatches:2,outputQty:40,collectedQty:0,total:80,qty:80};V09Craft.craftQueue.paused.feed_craft=true;V09Craft.craftQueue.ready.feed_craft.animal_feed=20;V09Craft.craftQueue.refunds.feed_craft.grain=10;V0161Upgrade.slots[0]={type:'helmet1',qty:1,level:0};V010Progression.tick(1000);");
 const saved=OJ('captureGameProgress()');restore(r,saved);const after=J('captureGameProgress()');assert.deepEqual(clean(after),clean(saved));assert.ok(after.v09.crafting.jobs.furnace.outputQty>0);assert.ok(after.v09.crafting.jobs.craft_bench.remainingMs>0);assert.equal(after.v010.modules.craft.queues.furnace.length,1);assert.equal(after.v010.modules.craft.paused.furnace,true);assert.equal(after.upgrade0161.item.type,'helmet1');
 restore(r,after);assert.deepEqual(J('captureGameProgress()'),after);
});
for(const id of J('GameEquipment.ids'))check('transform.old_coordinates.'+id,()=>{const before=OJ(`BunkerLayout.fixture('${id}')`);if(before.room==='workshop')before.y-=1000;assert.deepEqual(J(`GameEquipment.fixture('${id}')`),before);});
check('geometry.preserved_shell_and_shared_new_physical_bodies',()=>{reset();for(const name of ['core','stairs','arrivals','bounds'])assert.deepEqual(J('BunkerLayout.'+name),OJ('BunkerLayout.'+name));assert.deepEqual(require('./stage-ab-contract.cjs').previousRooms(J('BunkerLayout.rooms')),OJ('BunkerLayout.rooms'));for(const id of J('GameEquipment.ids').filter(id=>!['feed_craft','chest8','chest9','robots014_dock'].includes(id)))assert.deepEqual(J(`solidObjects('bunker').find(o=>o.id==='${id}')`),J(`GameFootprints.body('${id}')`));});
check('geometry.collision_grid_and_routes',()=>{
 E("scene='bunker';for(const d of v09Doors)d.open=1;invalidateGeometry();");
 for(const [x,y]of [[600,30],[590,510],[650,1050],[1870,90],[1870,510],[1870,1010],[1260,1460],[2034,195]]){const a=J(`findWalkPath(1120,-120,{id:'ground',kind:'ground',x:${x},y:${y},r:0,range:1},'bunker',15)`);assert.ok(a?.length);let prev={x:1120,y:-120};for(const p of a){assert.equal(E(`lineClear(${prev.x},${prev.y},${p.x},${p.y},15,'bunker')`),true);prev=p;}}
});
check('container.live_refs_survive_restore',()=>{reset();E("window.__container=GameEquipmentRuntime.container('chest0');window.__cradle=GameEquipmentRuntime.container('upgrade0161');window.__job=GameEquipmentRuntime.job('furnace');");assert.equal(E("__container.slots===storageChests[0].items&&__cradle.slots===V0161Upgrade.slots&&V010Inventory.list({instanceId:'chest0'})===storageChests[0].items"),true);restore(r,initial);assert.equal(E("__container.slots===storageChests[0].items&&__cradle.slots===V0161Upgrade.slots&&__job.active===V09Craft.craftQueue.getJob('furnace')"),true);assert.equal(E("GameEquipmentRuntime.container('missing')"),null);});
check('commands.explicit_actor_instance_repeat_and_reload',()=>{
 reset();E("bag=[];addItem('iron_ore',30);");const command={instanceId:'furnace',actorId:E('GameActors.localId'),requestId:'stable-start',expectedRevision:0,action:'start',payload:{recipe:'iron',batches:3}},call=`GameEquipmentRuntime.execute(${JSON.stringify(command)})`;
 assert.equal(J(call).ok,true);const saved=J('captureGameProgress()');assert.equal(J(call).replayed,true);assert.deepEqual(J('captureGameProgress()'),saved);restore(r,saved);assert.equal(J(call).replayed,true);assert.deepEqual(J('captureGameProgress()'),saved);
 assert.equal(issue('start',{recipe:'iron',batches:4},{requestId:'stable-start',expectedRevision:0}).reason,'request_conflict');
 assert.equal(issue('start',{recipe:'iron',batches:3},{requestId:'another-client',expectedRevision:0}).reason,'stale_revision');
});
for(const [name,extra,prep]of [['foreign_actor',{actorId:'remote-not-configured'},''],['missing_instance',{instanceId:'missing'},''],['distance',{},'player.x=1210;player.y=510;'],['dead',{},'playerDead=true;'],['surface',{},"scene='surface';"],['inactive_feed',{instanceId:'feed_craft'},''],['pause',{},'GameFlow.pause();']])check('commands.denied_no_expense.'+name,()=>{reset();E("bag=[];addItem('iron_ore',30);"+prep);const before=J('captureGameProgress()');assert.equal(issue('start',{recipe:'iron',batches:1},extra).ok,false);assert.deepEqual(J('captureGameProgress()'),before);});
check('commands.atomic_materials_and_full_inventory_output',()=>{
 reset();E("bag=[];for(const c of storageChests)c.items=[];addItem('iron_ore',1);");const before=J('captureGameProgress()');assert.equal(issue('start',{recipe:'iron',batches:100}).ok,false);const after=J('captureGameProgress()');for(const key of ['bag','storage','v09','equipment032'])assert.deepEqual(after[key],before[key]);
 E("V09Craft.craftQueue.ready.furnace.iron=8;bag=Array.from({length:BAG_SLOTS},()=>({type:'hammer',qty:1}));");const output=J('V09Craft.craftQueue.readyItems("furnace")');assert.equal(issue('collect').ok,false);assert.deepEqual(J('V09Craft.craftQueue.readyItems("furnace")'),output);E('bag[0]=null;');assert.equal(issue('collect').value,8);assert.equal(E('bagCount("iron")'),8);
});
check('commands.cancel_refund_is_conserved_once',()=>{reset();E("bag=[];for(const c of storageChests)c.items=[];addItem('iron_ore',50);");assert.equal(issue('start',{recipe:'iron',batches:2}).ok,true);const paid=E('bagCount("iron_ore")');assert.equal(issue('cancelUnstarted').ok,true);assert.equal(E('bagCount("iron_ore")'),50);assert.ok(paid<50);assert.equal(issue('cancelUnstarted').ok,false);assert.equal(E('bagCount("iron_ore")'),50);});
check('power_off.roundtrip_and_no_free_progress',()=>{reset();E("bag=[];addItem('iron_ore',50);V09Craft.start('furnace','iron',3);V09Power.running=false;V010Energy.battery.charge=0;");const saved=J('captureGameProgress()'),job=J('V09Craft.capture()');for(let n=0;n<100;n++)E('V09Craft.tick(100)');assert.deepEqual(J('V09Craft.capture()'),job);restore(r,saved);for(let n=0;n<100;n++)E('V09Craft.tick(100)');assert.deepEqual(J('V09Craft.capture()'),job);assert.equal(E('GameEquipmentRuntime.power("furnace").powered'),false);});
check('upgrade.power_depends_on_shared_item_not_open_window',()=>{reset();E("player.x=620;player.y=920;V0161Upgrade.slots[0]=null;");assert.equal(E('V09Power.devices.upgrade0161.active()'),false);E('V0161Upgrade.open()');assert.equal(E('V09Power.devices.upgrade0161.active()'),false);E("V0161Upgrade.slots[0]={type:'helmet1',qty:1};");const open=J('({active:V09Power.devices.upgrade0161.active(),demand:V09Power.allocation().demand})');E("closeOverlay(document.getElementById('v0161UpgradePanel'))");assert.deepEqual(J('({active:V09Power.devices.upgrade0161.active(),demand:V09Power.allocation().demand})'),open);assert.equal(open.active,true);const saved=J('captureGameProgress()');restore(r,saved);assert.equal(E('V09Power.devices.upgrade0161.active()'),true);E('V09Power.devices.upgrade0161.enabled=false;');assert.equal(E('devicePowered("upgrade0161")'),false);});
for(const [name,change]of [
 ['missing',d=>delete d.equipment032],['schema',d=>d.equipment032.schema=999],['duplicate_id',d=>d.equipment032.instances[1].id='furnace'],['unknown_type',d=>d.equipment032.instances[0].typeId='future'],['protected_moved',d=>d.equipment032.instances.find(r=>r.id==='feed_craft').transform.x++],['rotation',d=>d.equipment032.instances[0].transform.rotation=1],['room',d=>d.equipment032.instances[0].transform.room='farm'],['job_ref',d=>d.equipment032.instances[0].refs.job='craft_bench'],['device_ref',d=>d.equipment032.instances[0].refs.device='unknown'],['container_ref',d=>d.equipment032.instances[8].refs.container='storage:999'],['extra_instance',d=>d.equipment032.instances.push(copy(d.equipment032.instances[0]))],['negative_revision',d=>d.equipment032.commands.revision=-1],['future',d=>d.saveVersion=r.eval('SaveFormat.version')+1]
])check('save.reject_without_world_or_slot_mutation.'+name,()=>{reset();const before=J('captureGameProgress()'),store=Object.fromEntries(r.storage),bad=copy(before);change(bad);assert.throws(()=>restore(r,bad));assert.deepEqual(J('captureGameProgress()'),before);assert.deepEqual(Object.fromEntries(r.storage),store);});
const two=setup('index.html',{}, {language:'ru',transformScript(code){return code.replace('const GameEquipment=EquipmentInstances.createRegistry(EquipmentInstances.defaults);',"const GameEquipment=EquipmentInstances.createRegistry([...EquipmentInstances.defaults,{id:'qa_furnace',typeId:'furnace',transform:{x:1900,y:300,rotation:0,scene:'bunker',room:'reserve_l1'},refs:{job:'qa_furnace',queue:'qa_furnace',output:'qa_furnace',refund:'qa_furnace',device:'qa_furnace'}}]);");}}),T=s=>two.eval(s),TJ=s=>copy(T(s));
check('two_instances.same_production_code_isolated_jobs_output_pause_power',()=>{
 T("menuOpen=false;playerDead=false;document.hidden=false;GameFlow.resume();scene='bunker';player.x=430;player.y=18;zombies=[];bag=[];for(const c of storageChests)c.items=[];addItem('iron_ore',100);addItem('copper_ore',100);V09Power.running=true;V09Power.supply=30;V09Power.fuel=50;V010Progression.tick(1000);");
 assert.equal(T("V09Craft.start('furnace','iron',4)"),true);assert.equal(T("V09Craft.start('qa_furnace','copper',3)"),true);assert.equal(T("V09Craft.start('qa_furnace','iron',2)"),true);T("V09Craft.craftQueue.setPaused('furnace',true);");
 const paused=T("V09Craft.craftQueue.getJob('furnace').remainingMs");T('for(let i=0;i<30;i++)V09Craft.tick(100);');assert.equal(T("V09Craft.craftQueue.getJob('furnace').remainingMs"),paused);assert.equal(T("V09Craft.craftQueue.readyItems('qa_furnace').copper"),1);assert.deepEqual(TJ("V09Craft.craftQueue.readyItems('furnace')"),{});
 T("V09Power.devices.qa_furnace.enabled=false;");const off=T("V09Craft.craftQueue.getJob('qa_furnace').remainingMs");T('for(let i=0;i<30;i++)V09Craft.tick(100);');assert.equal(T("V09Craft.craftQueue.getJob('qa_furnace').remainingMs"),off);
 const saved=TJ('captureGameProgress()');restore(two,saved);assert.deepEqual(TJ('captureGameProgress()'),saved);assert.equal(T("GameEquipmentRuntime.job('qa_furnace').active.recipe"),'copper');assert.equal(T("GameEquipmentRuntime.job('furnace').active.recipe"),'iron');
 assert.equal(T("V09Craft.collect('qa_furnace')"),1);assert.equal(T('bagCount("copper")'),1);assert.deepEqual(TJ("V09Craft.craftQueue.readyItems('furnace')"),{});
});
check('two_instances.renderer_collision_interaction_share_transform',()=>{
 const record=TJ("GameEquipment.fixture('qa_furnace')");assert.deepEqual(TJ("solidObjects('bunker').find(o=>o.id==='qa_furnace')"),TJ("GameFootprints.body('qa_furnace')"));assert.equal(T("interactionObjects('bunker').filter(o=>o.id==='qa_furnace').length"),1);
 const transformed=TJ("(()=>{let p;BunkerLayout.withArt('workshop',()=>GameEquipment.withArt('qa_furnace',()=>{const t=ctx.getTransform();p={x:t.a*154+t.c*794+t.e,y:t.b*154+t.d*794+t.f};}));return p;})()");assert.deepEqual(transformed,{x:record.x,y:record.y});T("BunkerLayout.withArt('workshop',()=>V011Rooms.workshop());");
 assert.deepEqual(TJ("GameEquipment.center('qa_furnace')"),{x:record.x+65,y:record.y+97.5});
});
check('pure_authority.two_actor_conflict_and_permission',()=>{
 const out=J("(()=>{const paid={a:0,b:0},actors={a:{id:'a'},b:{id:'b'},denied:{id:'denied'}};const gate=EquipmentCommands.create(GameEquipment,{actor:id=>actors[id],authorized:a=>a.id!=='denied',access:()=>true,perform:(c,a)=>{paid[a.id]++;return{ok:true,value:1};}});const a={instanceId:'furnace',actorId:'a',requestId:'same',expectedRevision:0,action:'test'},first=gate.execute(a),duplicate=gate.execute(a),stale=gate.execute({...a,actorId:'b'}),second=gate.execute({...a,actorId:'b',expectedRevision:1}),denied=gate.execute({...a,actorId:'denied',expectedRevision:2});return {first,duplicate,stale,second,denied,paid};})()");assert.equal(out.first.ok,true);assert.equal(out.duplicate.replayed,true);assert.equal(out.stale.reason,'stale_revision');assert.equal(out.second.ok,true);assert.equal(out.denied.reason,'actor_denied');assert.deepEqual(out.paid,{a:1,b:1});
});
check('two_instances.actual_renderer_and_audio_observer_anchors',()=>{
 const draw=TJ("(()=>{const original=V011Art.draw,seen=[];V011Art.draw=function(key,x,y,w,h){if(key==='furnace'){const t=ctx.getTransform();seen.push({x:t.a*x+t.c*y+t.e,y:t.b*x+t.d*y+t.f});}return original(key,x,y,w,h);};ctx.save();ctx.resetTransform();try{BunkerLayout.withArt('workshop',()=>V011Rooms.workshop());}finally{ctx.restore();V011Art.draw=original;}return seen;})()");assert.deepEqual(draw,[{x:354,y:-206},{x:1900,y:300}]);
 const audio=TJ("(()=>{const originalLoop=GameAudio.loop,originalSync=GameAudio.sync,seen=[];V09Power.devices.qa_furnace.enabled=true;GameAudio.loop=(channel,name,opts)=>{seen.push({channel,name,...opts});return true;};GameAudio.sync=()=>true;try{GameAudioWorld.tick(true);}finally{GameAudio.loop=originalLoop;GameAudio.sync=originalSync;}return seen;})()");const machine=audio.find(x=>x.channel==='machine');assert.equal(machine.name,'machine');assert.equal(machine.x,1965);assert.equal(machine.y,397.5);const generator=audio.find(x=>x.channel==='generator');assert.equal(generator.x,1887);assert.equal(generator.y,-87.5);
});
check('receipts.bounded_and_evicted_request_stays_stale',()=>{const state=J("(()=>{let writes=0;const gate=EquipmentCommands.create(GameEquipment,{actor:id=>({id}),authorized:()=>true,access:()=>true,perform:()=>{writes++;return {ok:true,value:1};}});for(let i=0;i<132;i++)gate.execute({instanceId:'furnace',actorId:'a',requestId:'r'+i,expectedRevision:i,action:'test'});const capture=gate.capture();gate.restore(capture);const retry=gate.execute({instanceId:'furnace',actorId:'a',requestId:'r0',expectedRevision:0,action:'test'});return {capture,retry,writes};})()");assert.equal(state.capture.receipts.length,128);assert.equal(state.retry.reason,'stale_revision');assert.equal(state.writes,132);});
check('UI.production_uses_instance_command_and_remains_localized',()=>{reset();E("bag=[];addItem('iron_ore',20);V09Craft.open('furnace');");const button=r.doc.querySelector('[data-craft-control="make"]');assert.ok(button);button.click();assert.equal(E('GameEquipmentRuntime.revision'),1);assert.equal(E('V09Craft.craftQueue.getJob("furnace").recipe'),'iron');const receipt=J('GameEquipmentRuntime.capture().commands.receipts[0]');assert.equal(receipt.actorId,E('GameActors.localId'));assert.equal(JSON.parse(receipt.signature)[0],'furnace');});
check('stage_A_and_content_files_unchanged',()=>{const ref=require('./stage-b-source-reference.json');for(const name of ['src/campaign/definitions.js','src/campaign/domain.js','src/campaign/runtime.js','src/campaign/base-overview.js','src/ui/command-core.js','src/base/level1.js','src/base/construction.js','src/base/structures.js'])assert.ok(!ref.changes[name],name);assert.ok(!Object.keys(ref.changes).some(n=>n.startsWith('assets/')));});
check('console.clean',()=>{assert.deepEqual(r.errors,[]);assert.deepEqual(old.errors,[]);assert.deepEqual(two.errors,[]);});
const result={version:require('../package.json').version,passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks};fs.writeFileSync('qa/results/stage-b.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(c=>c.status==='FAIL')}));if(result.failed)process.exitCode=1;
