const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');process.chdir(path.resolve(__dirname,'..'));process.env.LAST_BASE_ASSETS=process.cwd();process.env.LAST_BASE_TEST_LANGUAGE='ru';
const {setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),J=s=>JSON.parse(E('JSON.stringify('+s+')')),checks=[];
function test(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack.slice(0,3400)});}console.log(id,checks.at(-1).status);}
function clean(){E("StoryPlayer.cancel();for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);for(const reason of GameFlow.reasons)GameFlow.resume(reason);GamePickup.cancel();menuOpen=false;playerDead=false;document.hidden=false;stopControls(true);zombies=[]");}
function reset(){E("restoreGameProgress(GameNewGame.create());GameStory.request('finish_intro',{outcome:'skipped'})");clean();E("for(const c of storageChests)c.items=[];bag=[];for(const t of ['iron','parts','copper','wood','concrete','ammo','advanced_parts'])addItem(t,300);addItem('hammer',1);scene='bunker';player.x=1210;player.y=680");}
function craft(type){E("scene='bunker';player.x=1210;player.y=680");const x=J(`GamePlacement.request('${type}','craft')`);assert.equal(x.ok,true,JSON.stringify(x));return x.instanceId;}
function place(id,x=450,y=350,turn=0,room='yard'){E(`scene='${room==='yard'?'surface':'bunker'}';player.x=${room==='yard'?800:1210};player.y=${room==='yard'?850:680};`);const q=J(`GamePlacement.request('${id}','place',GamePlacement.centered(GameEquipment.get('${id}').typeId,'${room}',${x},${y},${turn}))`);assert.equal(q.ok,true,JSON.stringify(q));return q;}
function near(id){r.context.did=id;assert.equal(E("(()=>{const r=GameEquipment.get(did),b=GameFootprints.forRecord(r);scene=r.transform.scene;for(const p of [{x:b.x+b.w/2,y:b.y+b.h+24},{x:b.x-24,y:b.y+b.h/2},{x:b.x+b.w+24,y:b.y+b.h/2},{x:b.x+b.w/2,y:b.y-24}]){Object.assign(player,p);if(GameDefense.reachable(GameActors.local,r)&&!worldCollision(p.x,p.y,player.radius,scene))return true;}return false;})()"),true);}
function power(id){E(`V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=1;for(const d of Object.values(V09Power.devices))d.enabled=d.id==='${id}';`);}
function save(){const d=J('captureGameProgress()');r.context.hsave=d;E('restoreGameProgress(decodeGameProgress(JSON.stringify(hsave)))');assert.deepEqual(J('GameEquipment.capture()'),d.equipment032.instances);assert.deepEqual(J('GameDefense.capture()'),d.defense039);assert.deepEqual(J('captureGameProgress().v09.power.deviceEnabled'),d.v09.power.deviceEnabled);clean();}
function pack(id){near(id);clean();near(id);const h=J(`GamePlacement.beginPickup('${id}')`);assert.equal(h.ok,true,JSON.stringify(h));r.context.ticket=h;assert.equal(J("GamePlacement.request(ticket.id,'pack',null,ticket.token)").reason,'holdRequired');r.advance(3001);const result=J("GamePlacement.request(ticket.id,'pack',null,ticket.token)");assert.equal(result.ok,true,JSON.stringify(result));}
function issue(id,action,payload={}){return J(`GameDefense.request('${id}','${action}',${JSON.stringify(payload)})`);}

function loadSave(){E('window.roundtrip=captureGameProgress();restoreGameProgress(decodeGameProgress(JSON.stringify(roundtrip)))');}
function frame(ms=16.667){r.advance(Math.round(ms));E(`frameScale=${ms/16.667};update()`);}
function enemy(x,y,type='normal'){E(`window.z=makeZombie(${x},${y});z.type='${type}';zombies=[z];V017Monsters.prepare(z);z.lastAttack=GameActivity.now()-20000;`);return E('z.instanceId');}
function gun(){reset();const id=craft('automatic_turret');place(id);near(id);power(id);assert.equal(issue(id,'load',{units:100}).ok,true);return id;}
function neutralPlayer(where){E(`scene='${where==='bunker'?'bunker':'surface'}';player.wallLevel=false;player.x=${where==='sector'?3500:where==='bunker'?1210:800};player.y=${where==='sector'?5500:where==='bunker'?680:850};stopControls(true)`);}
for(const where of ['surface','bunker','sector'])test('real_update_defense_'+where,()=>{const id=gun();enemy(520,350);neutralPlayer(where);const start=E("V09Power.fuel");for(let i=0;i<180&&E('z.alive');i++)frame();assert.equal(E('z.alive'),false);assert.equal(E(`GameEquipment.get('${id}').state.settings.ammo`),97);assert.ok(E('V09Power.fuel')<start);const n=E(`GameEquipment.get('${id}').state.settings.ammo`);for(let i=0;i<10;i++)frame();assert.equal(E(`GameEquipment.get('${id}').state.settings.ammo`),n);});
for(const where of ['surface','bunker','sector'])test('raid_wall_damage_'+where,()=>{reset();E("WorldClock.restore({schema:1,day:10,minute:120});window.w=V015Base.sections.find(w=>w.group==='outer'&&w.side==='W'&&!w.corner&&w.y<500);w.hp=w.maxHp;invalidateGeometry()");enemy(E('w.x-28'),E('w.y+w.h/2'),'heavy');neutralPlayer(where);E("V017Monsters.state(z).side='W'");const before=E('w.hp');for(let i=0;i<3;i++)frame();assert.ok(E('w.hp')<before);const once=E('w.hp');loadSave();for(let i=0;i<20;i++)frame();assert.equal(E('V015Base.byId.get(w.id).hp'),once);});
test('transition_mid_shot_has_no_extra_damage_or_ammo',()=>{const id=gun();enemy(520,350,'heavy');E(`GameDefense.transient('${id}').angle=0;GameDefense.tick(1)`);const hp=E('z.health'),ammo=E(`GameEquipment.get('${id}').state.settings.ammo`);assert.equal(ammo,99);neutralPlayer('bunker');E('GameDefense.tick(1)');neutralPlayer('sector');E('GameDefense.tick(1)');assert.equal(E('z.health'),hp);assert.equal(E(`GameEquipment.get('${id}').state.settings.ammo`),ammo);loadSave();for(let i=0;i<12;i++)E('GameDefense.tick(16.667)');assert.equal(E(`GameEquipment.get('${id}').state.settings.ammo`),ammo);for(let i=0;i<6;i++)E('GameDefense.tick(16.667)');assert.equal(E(`GameEquipment.get('${id}').state.settings.ammo`),ammo-1);});
test('offzone_equipment_damage_and_recovery',()=>{const id=gun();enemy(478,350,'heavy');neutralPlayer('bunker');const hp=E(`GameEquipment.get('${id}').state.condition.hp`);E('GameDefense.breachTarget(z,GameActivity.now(),V017Monsters.stats(z))');assert.ok(E(`GameEquipment.get('${id}').state.condition.hp`)<hp);loadSave();const damaged=E(`GameEquipment.get('${id}').state.condition.hp`);E('GameDefense.breachTarget(zombies[0],GameActivity.now(),V017Monsters.stats(zombies[0]))');assert.equal(E(`GameEquipment.get('${id}').state.condition.hp`),damaged);E('zombies=[]');near(id);E("V013Inventory.equip('hammer')");assert.equal(issue(id,'repair').ok,true);assert.equal(E(`GameEquipment.get('${id}').state.condition.hp`),hp);});
test('offzone_explosion_once_and_fuse_survives_save',()=>{const id=gun();enemy(490,350,'bloater');neutralPlayer('bunker');E("WorldClock.restore({schema:1,day:10,minute:120});V017Monsters.prepare(z);V017Monsters.armFuse(V017Monsters.state(z),GameActivity.now(),600)");const hp=E(`GameEquipment.get('${id}').state.condition.hp`);r.advance(250);loadSave();const saved=J('GameActivitySave.capture()');assert.equal(saved.actors[0].fuse.remaining,350);E(`V09Power.devices['${id}'].enabled=false`);r.advance(300);E('V017Monsters.update()');assert.equal(E('zombies[0].alive'),true);r.advance(60);E('V017Monsters.update()');assert.equal(E('zombies[0].alive'),false);assert.ok(E(`GameEquipment.get('${id}').state.condition.hp`)<hp);const after=E(`GameEquipment.get('${id}').state.condition.hp`);loadSave();r.advance(1000);E('V017Monsters.update()');assert.equal(E(`GameEquipment.get('${id}').state.condition.hp`),after);});
test('leaper_pending_jump_resumes_without_relaunch',()=>{reset();enemy(1800,1500,'leaper');E("window.jr=V017Monsters.state(z);jr.jump={start:GameActivity.now(),windup:255,duration:1000,speed:4,angle:0}");r.advance(400);loadSave();assert.equal(E('GameActivity.now()-V017Monsters.state(zombies[0]).jump.start'),400);neutralPlayer('bunker');const x=E('zombies[0].x');frame();assert.ok(E('zombies[0].x')>x);});
test('cached_player_sense_cannot_attack_bunker_coordinates',()=>{reset();enemy(1210,680);E('V017Monsters.state(z).sees=true;V017Monsters.state(z).nextSense=GameActivity.now()+1000');neutralPlayer('bunker');const hp=E('player.health');frame();assert.equal(E('V017Monsters.state(z).sees'),false);assert.equal(E('player.health'),hp);});
test('bounded_idle_cadence_and_active_budget',()=>{reset();E("zombies=Array.from({length:120},(_,i)=>makeZombie(2400+i%12*50,5600+Math.floor(i/12)*50));GameActivity.reset();scene='bunker';window.m0=GameActivity.metrics()");for(let i=0;i<60;i++){r.advance(16.667);E('frameScale=1;V017Monsters.update()');}const m=J('GameActivity.metrics()'),before=J('m0');assert.ok(m.skipped-before.skipped>5000);assert.ok(m.coarse-before.coarse>100);assert.ok(m.full-before.full<400);assert.ok(E('zombies.length')<=144);});
test('UI_capture_keeps_world_active_explicit_pause_and_hidden_stop',()=>{const id=gun();enemy(520,350,'heavy');neutralPlayer('bunker');E("openOverlay(el('inventoryOverlay'))");const n=E(`GameEquipment.get('${id}').state.settings.ammo`);for(let i=0;i<25;i++)frame();assert.ok(E(`GameEquipment.get('${id}').state.settings.ammo`)<n);E("GameFlow.pause('test');window.pauseState=captureGameProgress()");frame(100);assert.deepEqual(J('captureGameProgress().equipment032'),J('pauseState.equipment032'));E("GameFlow.resume('test');document.hidden=true");frame(100);assert.deepEqual(J('captureGameProgress().equipment032'),J('pauseState.equipment032'));E('document.hidden=false');});
test('power_consumers_not_double_ticked_offzone',()=>{const states=[];for(const where of ['surface','bunker','sector']){gun();neutralPlayer(where);const fuel=E('V09Power.fuel');for(let i=0;i<60;i++)frame();states.push(fuel-E('V09Power.fuel'));}assert.ok(states[0]>0);assert.ok(Math.abs(states[1]-states[0])<1e-8);assert.ok(Math.abs(states[2]-states[0])<1e-8);});
test('empty_disabled_destroyed_packed_defense_cannot_fire',()=>{for(const mode of ['empty','disabled','destroyed','packed']){const id=gun();enemy(520,350);E(`window.q=clone(GameEquipment.get('${id}'));`);if(mode==='empty')E('q.state.settings.ammo=0;GameEquipment.change(q)');if(mode==='disabled')E(`V09Power.devices['${id}'].enabled=false`);if(mode==='destroyed')E(`GameDefense.damage('${id}',10000)`);if(mode==='packed'){E('zombies=[]');pack(id);enemy(520,350);}neutralPlayer('bunker');const hp=E('z.health');for(let i=0;i<20;i++)frame();assert.equal(E('z.health'),hp,mode);}});
test('same_ground_geometry_when_player_changes_elevation',()=>{reset();const ground=J("GameActivity.ground(()=>geometryFor('surface').objects.map(o=>({id:o.id,x:o.x,y:o.y})))");E("scene='surface';player.wallLevel=true;V013City.setFloor(1)");assert.deepEqual(J("GameActivity.ground(()=>geometryFor('surface').objects.map(o=>({id:o.id,x:o.x,y:o.y})))"),ground);assert.ok(E("geometryFor('surface').objects.some(o=>o.id==='mall013_upwall')"));E('V013City.setFloor(0);player.wallLevel=false');});
test('legacy_0390_all_owners_preserved',()=>{const old=setup('qa/stage-i1-base/index.html');const d=JSON.parse(old.eval('JSON.stringify(captureGameProgress())'));r.context.baseline=d;const n=J('decodeGameProgress(JSON.stringify(baseline))');assert.equal(n.saveVersion,20);for(const key of Object.keys(d))if(!['gameVersion','saveVersion','control0353'].includes(key))assert.deepEqual(n[key],d[key],key);assert.equal(n.activity040.actors.length,d.zombies.length);assert.ok(n.activity040.turrets.every(t=>t.shot===0));E('restoreGameProgress(decodeGameProgress(JSON.stringify(baseline)))');loadSave();});
for(const [name,mutation]of [['missing',"delete d.activity040"],['duplicate',"d.activity040.actors[1]=d.activity040.actors[0]"],['foreign',"d.activity040.actors[0].id='enemy:999999'"],['fuse',"d.activity040.actors[0].fuse={remaining:999999,duration:650}"],['negative',"d.activity040.actors[0].attackAgo=-1"],['shot',"d.activity040.turrets[0].shot=8"],['extra',"d.activity040.threat=5"]])test('atomic_save_rejection_'+name,()=>{reset();E('restoreGameProgress(GameNewGame.create());GameStory.request("finish_intro",{outcome:"skipped"});window.d=captureGameProgress()');const before=J('captureGameProgress()');E(mutation);assert.throws(()=>E('restoreGameProgress(d)'));assert.deepEqual(J('captureGameProgress()'),before);});
test('explicit_pause_freezes_pending_fuse_and_save_timers',()=>{gun();enemy(490,350,'bloater');neutralPlayer('bunker');E("V017Monsters.armFuse(V017Monsters.state(z),GameActivity.now(),650);GameFlow.pause('test')");const saved=J('GameActivitySave.capture()');r.advance(30000);assert.deepEqual(J('GameActivitySave.capture()'),saved);E("GameFlow.resume('test')");assert.equal(J('GameActivitySave.capture()').actors[0].fuse.remaining,650);});
test('invalid_legacy_door_preference_rejected_before_mutation',()=>{const old=setup('qa/stage-i1-base/index.html');r.context.badOld=JSON.parse(old.eval('JSON.stringify(captureGameProgress())'));r.context.badOld.control0353.doorModes.v09door_workshop='unexpected';const before=J('captureGameProgress()');assert.throws(()=>E('restoreGameProgress(badOld)'));assert.deepEqual(J('captureGameProgress()'),before);});
test('far_raid_travel_coarse_but_continuous',()=>{reset();E("WorldClock.restore({schema:1,day:10,minute:120});zombies=Array.from({length:54},(_,i)=>makeZombie(2400+i%9*45,5600+Math.floor(i/9)*45));GameActivity.reset();scene='bunker';window.m0=GameActivity.metrics();window.zx=zombies[0].x;window.zy=zombies[0].y");for(let i=0;i<60;i++){r.advance(17);E('frameScale=1;V017Monsters.update()');}const a=J('GameActivity.metrics()'),b=J('m0');assert.ok(a.skipped-b.skipped>2500);assert.ok(a.coarse-b.coarse>100);assert.ok(E('Math.hypot(zombies[0].x-zx,zombies[0].y-zy)')>0);});
test('no_console_errors',()=>assert.deepEqual(r.errors,[]));
const report={version:require('../package.json').version,runtimeSha256:crypto.createHash('sha256').update(fs.readFileSync('js/game.js')).digest('hex'),passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks};fs.writeFileSync('qa/results/stage-i1.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,failed:report.failed,failures:checks.filter(c=>c.status==='FAIL')}));if(report.failed)process.exitCode=1;
