// Fresh Stage D gate. Baseline bytes come only from the accepted 0.34.0 ZIP.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
process.chdir(path.resolve(__dirname,'..'));process.env.LAST_BASE_TEST_LANGUAGE='ru';
const {setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),J=s=>JSON.parse(E('JSON.stringify('+s+')')),copy=v=>JSON.parse(JSON.stringify(v)),checks=[];
const check=(id,fn)=>{try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack});}};
const initial=J('captureGameProgress()');
function clean(){E("for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);menuOpen=false;playerDead=false;document.hidden=false;GameFlow.resume();stopControls(true);el('fade').classList.remove('show');scene='bunker';player.x=1210;player.y=675;V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=1.5;for(const d of v09Doors)d.open=1;invalidateGeometry();");}
function reset(materials=true){E(`restoreGameProgress(${JSON.stringify(initial)})`);clean();E("bag=[];for(const c of storageChests)c.items=[];");if(materials)E("for(const type of ['iron','wood','parts','concrete','stone','iron_ore','copper_ore'])addItem(type,100)");}
const transform=(type='furnace',x=1950,y=400,turn=1)=>J(`GamePlacement.centered('${type}','reserve_l1',${x},${y},${turn})`);
const request=(id,action,t)=>J(`GamePlacement.request(${JSON.stringify(id)},${JSON.stringify(action)},${JSON.stringify(t)})`);
function place(type='furnace',x=1950,y=400,turn=1){const out=request('catalog:'+type,'place',transform(type,x,y,turn));assert.equal(out.ok,true,JSON.stringify(out));return out.instanceId;}
function roundtrip(){E('V010Progression.tick(1000);V010Camera.reveal();GameCampaign.refresh(true)');const d=J('captureGameProgress()');E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(JSON.stringify(d))}))`);assert.deepEqual(J('captureGameProgress()'),d);clean();return d;}
const command=(id,action,payload={})=>({instanceId:id,action,payload:{geometry:E('geometryRevision'),...payload},actorId:E('GameActors.localId'),requestId:'test:'+E('GamePlacement.revision'),expectedRevision:E('GamePlacement.revision')});
const execute=c=>J(`GamePlacement.execute(${JSON.stringify(c)})`);
check('fresh_base.archive_and_manifest_provenance',()=>{const p=require('./stage-d-base/PROVENANCE.json');assert.equal(p.sha256,'11a1742cf3887b29036f7a9d3168942bf86829db9c1fdee9c32bbb1a49cb2b60');const m=require('./stage-d-base/release_manifest.json');for(const f of ['index.html','package.json','js/game.js','js/game.js.map'])assert.equal(crypto.createHash('sha256').update(fs.readFileSync('qa/stage-d-base/'+f)).digest('hex'),m.files.find(r=>r.file===f).sha256);});
check('default.identity_and_layout_unchanged',()=>{assert.equal(J('GameEquipment.ids').length,18);assert.equal(E('BunkerLayout.revision'),3);for(const instance of J('GameEquipment.capture()'))assert.deepEqual(instance,{...J(`EquipmentInstances.defaults.find(r=>r.id==='${instance.id}')`),placement:'installed'});assert.equal(E('AgricultureTime.available'),false);assert.equal(E('GameEquipment.get("generator").typeId'),'generator');});
check('build.atomic_cost_and_second_instance_owners',()=>{reset();const before=J('({iron:bagCount("iron"),parts:bagCount("parts"),concrete:bagCount("concrete")})'),id=place();assert.equal(id,'build:furnace:1');assert.deepEqual(J('({iron:bagCount("iron"),parts:bagCount("parts"),concrete:bagCount("concrete")})'),{iron:before.iron-20,parts:before.parts-6,concrete:before.concrete-8});assert.equal(E(`GameEquipmentRuntime.job('${id}').active`),null);assert.equal(E(`V09Power.devices['${id}'].room`),'reserve_l1');assert.equal(J(`interactionObjects('bunker').filter(r=>r.id==='${id}')`).length,1);assert.deepEqual(J(`solidObjects('bunker').find(r=>r.id==='${id}')`),J(`GameFootprints.body('${id}')`));roundtrip();});
for(const [name,prep,reason]of [['materials',"bag=[];for(const c of storageChests)c.items=[]",'materials'],['surface',"scene='surface'",'out_of_reach'],['floor2','player.floor=2','out_of_reach'],['distance','player.x=1120;player.y=-120','out_of_reach'],['dead','playerDead=true','world_paused'],['paused',"GameFlow.pause('test')",'world_paused']])check('authority.no_mutation.'+name,()=>{reset();E(prep);const before=J('captureGameProgress()'),out=request('catalog:furnace','place',transform());assert.equal(out.reason,reason);assert.deepEqual(J('captureGameProgress()'),before);E("delete player.floor;GameFlow.resume('test')");});
check('authority.foreign_actor_duplicate_stale_conflict_reload',()=>{reset();const c=command('catalog:furnace','place',{transform:transform()});assert.equal(execute({...c,actorId:'remote'}).reason,'actor_denied');assert.equal(execute(c).ok,true);const saved=J('captureGameProgress()');assert.equal(execute(c).replayed,true);assert.deepEqual(J('captureGameProgress()'),saved);assert.equal(execute({...c,payload:{...c.payload,transform:transform('furnace',1950,650)}}).reason,'request_conflict');assert.equal(execute({...c,requestId:'other'}).reason,'stale_revision');roundtrip();assert.equal(execute(c).replayed,true);});
check('authority.world_revision_rechecked_at_commit',()=>{reset();const c=command('catalog:furnace','place',{transform:transform()});E('invalidateGeometry()');const before=J('captureGameProgress()');assert.equal(execute(c).reason,'world_changed');assert.deepEqual(J('captureGameProgress()'),before);});
for(const [name,mutate,reason]of [['wrong-scene',t=>t.scene='surface','room'],['future-room',t=>t.room='farm','room'],['corridor',t=>t.room='corridor','room'],['wall',t=>t.x=2200,'bounds'],['rotation',t=>t.rotation=.2,'room'],['NaN',t=>t.x=null,'room'],['door',t=>Object.assign(t,{x:1680,y:460,rotation:0}),'door']])check('validation.'+name,()=>{reset();const t=transform();mutate(t);const before=J('captureGameProgress()');assert.equal(request('catalog:furnace','place',t).reason,reason);assert.deepEqual(J('captureGameProgress()'),before);});
check('validation.overlap_actors_drone_and_limit',()=>{reset();place();assert.equal(request('catalog:furnace','place',transform()).reason,'limitReached');assert.equal(request('catalog:craft_bench','place',transform('craft_bench',1950,400,0)).reason,'overlap');reset();E("Object.assign(V014Robots.state,{packed:false,scene:'bunker',x:1950,y:400})");assert.equal(request('catalog:furnace','place',transform()).reason,'occupied');E('V014Robots.state.packed=true');const good=place();assert.equal(request(good,'pack').ok,true);assert.equal(request('catalog:furnace','place',transform()).reason,'limitReached');});
check('pack.preserves_identity_state_no_collision_interactions_or_power',()=>{reset();const id=place();E(`V09Craft.craftQueue.paused['${id}']=true;V09Power.devices['${id}'].enabled=false;V010Energy.setDevicePriority('${id}',3)`);const record=J(`GameEquipment.get('${id}')`),job=J(`V09Craft.craftQueue.capture()`),before=J('({bag,storage:storageChests})');assert.equal(request(id,'pack').ok,true);assert.deepEqual(J(`GameEquipment.get('${id}')`),{...record,placement:'packed'});assert.deepEqual(J('V09Craft.craftQueue.capture()'),job);assert.deepEqual(J('({bag,storage:storageChests})'),before);assert.equal(E(`solidObjects('bunker').some(o=>o.id==='${id}')`),false);assert.equal(E(`interactionObjects('bunker').some(o=>o.id==='${id}')`),false);assert.equal(E(`devicePowered('${id}')`),false);assert.equal(E(`V09Craft.start('${id}','iron',1)`),false);roundtrip();assert.equal(request(id,'place',transform('furnace',1950,650,3)).ok,true);assert.equal(E(`V09Craft.craftQueue.paused['${id}']`),true);assert.equal(E(`V09Power.devices['${id}'].enabled`),false);assert.equal(E(`V010Energy.devicePriority('${id}')`),3);assert.deepEqual(J('({bag,storage:storageChests})'),before);roundtrip();});
for(const [kind,prep]of [['active',"V09Craft.start('furnace','iron',2)"],['paused',"V09Craft.start('furnace','iron',2);V09Craft.craftQueue.setPaused('furnace',true)"],['queued',"V09Craft.start('furnace','iron',2);V09Craft.start('furnace','copper',2)"],['output',"V09Craft.craftQueue.ready.furnace.iron=4"],['refund',"V09Craft.craftQueue.refunds.furnace.iron_ore=4"]])check('pack.busy_guard.'+kind,()=>{reset();E(prep);const before=J('captureGameProgress()');assert.equal(request('furnace','pack').reason,'busy');assert.deepEqual(J('captureGameProgress()'),before);roundtrip();assert.equal(request('furnace','pack').reason,'busy');});
check('pack.authored_furnace_free_reinstall_and_protected_devices',()=>{reset(false);assert.equal(request('generator','pack').reason,'protected');assert.equal(request('furnace','pack').ok,true);roundtrip();assert.equal(request('furnace','place',transform()).ok,true);assert.equal(E('GameEquipment.ids.length'),18);assert.equal(E("GameEquipment.get('furnace').id"),'furnace');roundtrip();});
check('production.two_queues_power_loss_output_refunds_save_load',()=>{reset();const id=place();E(`V09Power.supply=30;V09Craft.start('furnace','iron',3);V09Craft.start('${id}','copper',4);V09Craft.start('${id}','iron',2);V09Craft.craftQueue.setPaused('furnace',true);for(let i=0;i<31;i++)V09Craft.tick(100);V09Power.devices['${id}'].enabled=false`);assert.equal(E(`V09Craft.craftQueue.readyItems('${id}').copper`),1);const jobs=J('V09Craft.capture()');roundtrip();E('for(let n=0;n<30;n++)V09Craft.tick(100)');assert.deepEqual(J('V09Craft.capture()'),jobs);assert.equal(request(id,'pack').reason,'busy');E(`V09Craft.craftQueue.cancelQueued('${id}',0);V09Craft.craftQueue.cancelUnstarted('${id}');V09Power.devices['${id}'].enabled=true;for(let i=0;i<30;i++)V09Craft.tick(100);V09Craft.collect('${id}');V09Craft.craftQueue.collectRefund('${id}')`);assert.equal(request(id,'pack').ok,true);assert.ok(E('V09Craft.craftQueue.getJob("furnace")'));roundtrip();});
check('navigation.player_and_drone_critical_routes_after_two_builds',()=>{reset();place();place('craft_bench',1950,650,0);for(const radius of [10,14,18])for(const [x,y]of [[1120,-300],[590,30],[590,510],[650,1050],[1870,90],[1800,510],[1870,1010],[1260,1460],[2034,195],[1210,680]]){const p=J(`findWalkPath(1120,-120,{id:'ground',kind:'ground',x:${x},y:${y},r:0,range:1},'bunker',${radius})`);assert.ok(p?.length,`${radius}: ${x},${y}`);}assert.equal(E("GamePlacement.reachable('reserve_l1',GameEquipment.capture())"),true);roundtrip();});
check('save.old_C2_pure_migration_and_developed_world',()=>{const old=setup('qa/stage-d-base/index.html');old.eval("V09Power.fuel=56;V09Power.running=true;V010Energy.battery.charge=.7;V09Craft.start('furnace','iron',2);V09Craft.craftQueue.paused.furnace=true");const raw=old.eval('JSON.stringify(captureGameProgress())'),d=JSON.parse(raw);reset();const live=J('captureGameProgress()');r.context.raw034=raw;const next=J('decodeGameProgress(raw034)');assert.deepEqual(J('captureGameProgress()'),live);for(const key of ['bag','storage','equipment','headModules033','campaign031','chapter034','v09','v010','base015','building018','gathering','farm','livestock'])assert.deepEqual(next[key],d[key],key);assert.deepEqual(next.equipment032.instances,d.equipment032.instances.map(r=>({...r,placement:'installed'})));assert.equal(next.equipment032.schema,2);assert.equal(next.saveVersion,13);E('restoreGameProgress(decodeGameProgress(raw034))');roundtrip();});
check('save.JSON_key_order_is_not_gameplay_state',()=>{reset();const d=J('captureGameProgress()');for(const r of d.equipment032.instances){r.transform=Object.fromEntries(Object.entries(r.transform).reverse());r.refs=Object.fromEntries(Object.entries(r.refs).reverse());}E(`restoreGameProgress(${JSON.stringify(d)})`);assert.equal(E('GameEquipment.ids.length'),18);roundtrip();});
check('save.legacy_C2_JSON_key_order_migrates',()=>{reset();const d=J('captureGameProgress()');d.gameVersion='0.34.0';d.saveVersion=12;d.equipment032.schema=1;delete d.placement035;d.equipment032.instances=d.equipment032.instances.map(r=>{delete r.placement;r.transform=Object.fromEntries(Object.entries(r.transform).reverse());r.refs=Object.fromEntries(Object.entries(r.refs).reverse());return Object.fromEntries(Object.entries(r).reverse());});E(`restoreGameProgress(${JSON.stringify(d)})`);assert.equal(E('GameEquipment.ids.length'),18);roundtrip();});
for(const [name,mutate]of [['missing-state',d=>delete d.placement035],['future-schema',d=>d.placement035.schema=2],['protected-packed',d=>d.equipment032.instances.find(r=>r.id==='generator').placement='packed'],['unknown-presence',d=>d.equipment032.instances[0].placement='missing'],['bad-position',d=>d.equipment032.instances.find(r=>r.id==='build:furnace:1').transform.x=9999],['missing-owner',d=>delete d.v09.crafting.jobs['build:furnace:1']],['mixed-type',d=>d.equipment032.instances.find(r=>r.id==='build:furnace:1').typeId='craft_bench'],['packed-job',d=>{d.equipment032.instances[0].placement='packed';d.v010.modules.craft.ready.furnace.iron=1}],['device-ref',d=>d.equipment032.instances.find(r=>r.id==='build:furnace:1').refs.device='furnace']])check('save.atomic_rejection.'+name,()=>{reset();place();const before=J('captureGameProgress()'),bad=copy(before),slots=Object.fromEntries(r.storage);mutate(bad);assert.throws(()=>E(`restoreGameProgress(${JSON.stringify(bad)})`));assert.deepEqual(J('captureGameProgress()'),before);assert.deepEqual(Object.fromEntries(r.storage),slots);});
check('save.new_game_after_dynamic_world_cleans_all_owners',()=>{reset();place();place('craft_bench',1950,650,0);E('restoreGameProgress(GameNewGame.create())');assert.equal(E('GameEquipment.ids.length'),18);assert.equal(E("Object.keys(V09Power.devices).some(id=>id.startsWith('build:'))"),false);assert.equal(E("Object.keys(V09Craft.capture().jobs).length"),2);assert.equal(E('GameChapterOne.active'),true);roundtrip();});
for(const [lang,w,h]of [['ru',390,844],['en',844,390]])check('UI.preview_explicit_confirm_session_layout.'+lang,()=>{reset();E(`I18n.setLanguage('${lang}');window.innerWidth=${w};window.innerHeight=${h};resizeCanvas();CommandCoreUI.show('construction')`);const saved=J('captureGameProgress()');assert.equal(E("GamePlacementUI.choose('catalog:furnace')"),true);E('GamePlacementUI.move(1950,400);GamePlacementUI.rotate()');assert.deepEqual(J('captureGameProgress()'),saved);assert.equal(E('GamePlacementUI.preview.turn'),1);assert.equal(E('GamePlacementUI.commit().ok'),true);assert.equal(E('GamePlacementUI.preview'),null);E("closeOverlay(el('commandCoreOverlay'));CommandCoreUI.show()");assert.equal(r.doc.getElementById('coreSection_construction').hidden,false);const css=fs.readFileSync('src/ui/command-core.js','utf8');for(const rule of ['height:min(760px','overflow-y:scroll','position:absolute;inset:0'])assert.ok(css.includes(rule));const text=r.doc.getElementById('commandCoreOverlay').textContent;assert.ok(!text.includes('build:furnace'));if(lang==='en')assert.ok(!/[А-Яа-яЁё]/.test(text),text);E("scene='surface';CommandCoreUI.tick();scene='bunker';CommandCoreUI.show()");assert.equal(r.doc.getElementById('coreSection_base').hidden,false);});
check('UI.touch_long_hold_cancel_and_no_world_movement',()=>{reset();E("GameInput.setMode('MOBILE');CommandCoreUI.show('construction');GamePlacementUI.choose('catalog:furnace')");const node=r.doc.getElementById('placementPlan');node.getBoundingClientRect=()=>({left:0,top:0,width:520,height:500});const before=J('captureGameProgress()');r.emit('pointerdown',node,{pointerId:20,pointerType:'touch',clientX:340,clientY:140,button:0});r.advance(5000);r.emit('pointermove',node,{pointerId:20,pointerType:'touch',clientX:350,clientY:160,buttons:1});r.emit('pointerup',node,{pointerId:20,pointerType:'touch',clientX:350,clientY:160,button:0});assert.deepEqual(J('captureGameProgress()'),{...before,savedAt:E('Date.now()')});assert.equal(E('navigation'),null);assert.equal(E('GameEquipment.ids.length'),18);r.emit('keydown',r.doc,{key:'Escape',code:'Escape'});assert.equal(E('GamePlacementUI.preview'),null);assert.equal(r.doc.getElementById('commandCoreOverlay').classList.contains('open'),true);});
check('UI.preview_does_not_survive_close_load_or_section_change',()=>{reset();E("CommandCoreUI.show('construction');GamePlacementUI.choose('catalog:furnace');closeOverlay(el('commandCoreOverlay'));CommandCoreUI.tick()");assert.equal(E('GamePlacementUI.preview'),null);E("CommandCoreUI.show('construction');GamePlacementUI.choose('catalog:furnace')");roundtrip();assert.equal(E('GamePlacementUI.preview'),null);E("CommandCoreUI.show('construction');GamePlacementUI.choose('catalog:furnace');CommandCoreUI.show('base');CommandCoreUI.tick()");assert.equal(E('GamePlacementUI.preview'),null);});
check('rotation.all_quarter_turns_and_free_pack_reinstall',()=>{reset();place();for(const turn of [0,1,2,3]){assert.equal(request('build:furnace:1','pack').ok,true);const t=transform('furnace',1950,400,turn);assert.equal(request('build:furnace:1','place',t).ok,true);const b=J("GameFootprints.body('build:furnace:1')"),p=J("GameEquipment.center('build:furnace:1')");assert.equal(E(`worldCollision(${p.x},${p.y},10,'bunker')`),true);assert.equal(J("interactionObjects('bunker').find(o=>o.id==='build:furnace:1')").w,b.w);assert.equal(E("GameRecovery.classify('build:furnace:1').mode"),'protected');roundtrip();}});
check('malformed_commands_do_not_mutate_world',()=>{reset();for(const [id,transform]of [['catalog:furnace',null],['catalog:furnace',{}],['catalog:__proto__',{}],['catalog:constructor',{}]]){const before=J('captureGameProgress()');assert.equal(execute(command(id,'place',{transform})).ok,false);assert.deepEqual(J('captureGameProgress()'),before);}});
check('UI.room_page_uses_generic_Core_route_reset',()=>{reset();E("CommandCoreUI.show('construction')");r.doc.querySelectorAll('#coreSection_construction .placementRooms button')[0].click();assert.equal(E('GamePlacementUI.room'),'workshop');E("closeOverlay(el('commandCoreOverlay'));CommandCoreUI.show()");assert.equal(E('GamePlacementUI.room'),'workshop');E("scene='surface';CommandCoreUI.tick();scene='bunker';CommandCoreUI.show('construction')");assert.equal(E('GamePlacementUI.room'),'reserve_l1');});
check('performance.no_idle_validation_or_preview_in_save',()=>{reset();const before=E('GamePlacement.metrics().checks');for(let n=0;n<50;n++){r.advance(17);E('update();GamePlacementUI.tick()');}assert.equal(E('GamePlacement.metrics().checks'),before);assert.ok(!JSON.stringify(J('captureGameProgress()')).includes('preview'));assert.deepEqual(r.errors,[]);});
const report={version:require('../package.json').version,passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks};fs.writeFileSync('qa/results/stage-d.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,failed:report.failed,failures:checks.filter(c=>c.status==='FAIL')}));if(report.failed)process.exitCode=1;
