// Stage D preservation gate. The expanded current lifecycle is exercised by
// stage-d-corrective.cjs; these cases migrate real delivered 0.35.1 worlds.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');process.chdir(path.resolve(__dirname,'..'));process.env.LAST_BASE_TEST_LANGUAGE='ru';
const {setup}=require('./runtime.cjs'),r=setup('index.html'),old=setup('qa/stage-d-corrective-base/index.html'),E=s=>r.eval(s),O=s=>old.eval(s),J=s=>JSON.parse(E('JSON.stringify('+s+')')),checks=[];
const test=(id,fn)=>{try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack});}};
const original=O('JSON.stringify(captureGameProgress())');
function reset(){old.context.oldRaw=original;O("restoreGameProgress(decodeGameProgress(oldRaw));menuOpen=false;playerDead=false;GameFlow.resume();scene='bunker';player.x=1210;player.y=675;V09Power.running=true;V09Power.fuel=100;for(const c of storageChests)c.items=[];bag=[];for(const t of ['wood','iron','copper','parts','concrete','iron_ore','copper_ore'])addItem(t,100)");}
function project(value){const d=JSON.parse(JSON.stringify(value));delete d.research036;delete d.story037;delete d.carry0353;delete d.control0353;d.bag=d.bag.filter(s=>s?.type!=='equipment_case');delete d.saveVersion;delete d.gameVersion;d.equipment032.schema=2;for(const r of d.equipment032.instances){delete r.ownerId;delete r.state;}d.placement035.schema=1;delete d.placement035.roomNames;d.chapter034.schema=1;delete d.chapter034.recovered;for(const k of ['storage','supplies','workbenchCrafted','workbenchPlaced','hammer','pickaxe','axe'])delete d.chapter034.seen[k];for(const j of [...Object.values(d.v09.crafting.jobs),...Object.values(d.v010.modules.craft.queues).flat()])if(j)delete j.legacy0351;return d;}
function migrate(){O('V010Progression.tick(1000);V010Camera.reveal();GameCampaign.refresh(true)');const raw=O('JSON.stringify(captureGameProgress())'),prior=JSON.parse(raw),before=J('captureGameProgress()');r.context.raw=raw;const decoded=J('decodeGameProgress(raw)');assert.deepEqual(J('captureGameProgress()'),before,'decode must be pure');assert.deepEqual(project(decoded),project(prior));E('restoreGameProgress(decodeGameProgress(raw))');E('V010Progression.tick(1000);V010Camera.reveal();GameCampaign.refresh(true)');const saved=J('captureGameProgress()');r.context.saved=saved;E('restoreGameProgress(decodeGameProgress(JSON.stringify(saved)))');assert.deepEqual(J('captureGameProgress()'),saved);return saved;}
test('baseline.delivered_0351_immutable',()=>assert.equal(crypto.createHash('sha256').update(fs.readFileSync('qa/stage-d-corrective-base/js/game.js')).digest('hex'),'7f47d8b939c1c0e522a984e6f8a88b217ab057a52e6e78d2c724349f04132a38'));
test('defaults.identity_layout_and_farm_pause',()=>{assert.equal(E('GameEquipment.ids.length'),18);assert.equal(E('BunkerLayout.revision'),3);assert.equal(E('AgricultureTime.available'),false);for(const record of J('GameEquipment.capture()'))assert.deepEqual(record,{...J(`EquipmentInstances.defaults.find(r=>r.id==='${record.id}')`),placement:'installed',ownerId:null,state:J('EquipmentInstances.state()')});});
for(const type of ['furnace','craft_bench'])for(const packed of [false,true])test('migration.delivered_dynamic_'+type+'_'+(packed?'packed':'installed'),()=>{reset();assert.equal(O(`GamePlacement.request('catalog:${type}','place',GamePlacement.centered('${type}','reserve_l1',1950,${type==='craft_bench'?650:400},${type==='craft_bench'?0:1})).ok`),true);const id='build:'+type+':1';O(`V09Craft.craftQueue.paused['${id}']=true;V09Power.devices['${id}'].enabled=false;V010Energy.setDevicePriority('${id}',3)`);if(packed)assert.equal(O(`GamePlacement.request('${id}','pack').ok`),true);const d=migrate(),rec=d.equipment032.instances.find(r=>r.id===id);assert.equal(rec.ownerId,packed?'player:1':null);assert.equal(E(`GameEquipmentRuntime.job('${id}').active`),null);assert.equal(E(`V09Craft.craftQueue.paused['${id}']`),true);if(packed){assert.equal(E(`solidObjects('bunker').some(o=>o.id==='${id}')`),false);E("menuOpen=false;GameFlow.resume();scene='bunker';player.x=1210;player.y=675");assert.equal(E(`GamePlacement.request('${id}','place',GamePlacement.centered('${type}','reserve_l1',1950,${type==='craft_bench'?650:400},${type==='craft_bench'?0:1})).ok`),true);}});
for(const kind of ['job','queue','output','refund'])test('migration.production_'+kind,()=>{reset();assert.equal(O("GamePlacement.request('catalog:furnace','place',GamePlacement.centered('furnace','reserve_l1',1950,400,1)).ok"),true);if(kind==='job'||kind==='queue')assert.equal(O("V09Craft.start('build:furnace:1','iron',3)"),true);if(kind==='queue')assert.equal(O("V09Craft.start('build:furnace:1','copper',2)"),true);if(kind==='output')O("V09Craft.craftQueue.ready['build:furnace:1'].iron=4");if(kind==='refund')O("V09Craft.craftQueue.refunds['build:furnace:1'].iron_ore=4");migrate();E("menuOpen=false;GameFlow.resume();scene='bunker';player.x=1950;player.y=470");assert.equal(E("GamePlacement.request('build:furnace:1','pack').reason"),'busy');});
for(const recipe of ['hammer','fishing_rod','flashlight','head_mount'])test('migration.historical_recipe_owner_'+recipe,()=>{reset();assert.equal(O(`V09Craft.start('craft_bench','${recipe}',1)`),true);const d=migrate();assert.equal(d.v09.crafting.jobs.craft_bench.legacy0351,true);assert.equal(E(`V09Craft.recipes['${recipe}'].station`),'utility_workbench');E("menuOpen=false;GameFlow.resume();V09Power.running=true;V09Power.fuel=100;for(let i=0;i<700;i++)V09Craft.tick(100)");assert.equal(E(`V09Craft.craftQueue.readyItems('craft_bench')['${recipe}']`),1);assert.equal(E("V09Craft.collect('craft_bench')"),1);assert.equal(E(`bagCount('${recipe}')`),1);});
test('scope.fixed_infrastructure_cannot_be_packed',()=>{E("scene='bunker';player.x=1210;player.y=675;menuOpen=false;GameFlow.resume()");for(const id of ['command_core_l1','exit','v09door_storage','v091wall020_N_0','feed_craft'])assert.equal(E(`GamePlacement.request('${id}','pack').ok`),false);assert.equal(E('AgricultureTime.available'),false);assert.equal(E('ChapterOneDefinitions.chapters.length'),2);});
test('runtime.clean',()=>assert.deepEqual([...r.errors,...old.errors],[]));
const report={version:require('../package.json').version,runtimeSha256:crypto.createHash('sha256').update(fs.readFileSync('js/game.js')).digest('hex'),passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks};fs.writeFileSync('qa/results/stage-d.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));if(report.failed)process.exitCode=1;
