// Real bundled game and saves; modeled DOM/authority ports. No network transport.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
process.chdir(path.resolve(__dirname,'..'));process.env.LAST_BASE_ASSETS=process.cwd();process.env.LAST_BASE_TEST_LANGUAGE='ru';
const {setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),J=s=>JSON.parse(E('JSON.stringify('+s+')')),checks=[];
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
function test(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack.slice(0,2800)});}console.log(id+' '+checks.at(-1).status);}
function reset(){E("StoryPlayer.cancel();restoreGameProgress(GameNewGame.create());GameStory.request('finish_intro',{outcome:'skipped'});for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);for(const reason of GameFlow.reasons)GameFlow.resume(reason);menuOpen=false;playerDead=false;document.hidden=false;stopControls(true);scene='surface';player.x=800;player.y=1150");}
function at(id){E(`window.gs=GameExploration.sites.find(s=>s.id==='${id}');player.x=gs.x;player.y=gs.y+30;scene='surface';`);}
function collect(id){at(id);return J(`GameExploration.collect('${id}')`);}
function core(){E("scene='bunker';player.x=1210;player.y=680;V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=1;for(const d of Object.values(V09Power.devices))d.enabled=d.id===GameCampaign.powerId;");}
function boundary(){const before=J('GameExploration.capture()'),research=J('GameResearch.capture()');E('restoreGameProgress(decodeGameProgress(JSON.stringify(captureGameProgress())))');assert.deepEqual(J('GameExploration.capture()'),before);assert.deepEqual(J('GameResearch.capture()'),research);}
test('baseline_exact_0371',()=>assert.equal(hash('qa/stage-g-base/js/game.js'),'f150417f1d5fa1899eb91fd2a2575d180848cd0322bcc41676f8306b27aee952'));
test('only_existing_world_and_original_assets',()=>{const base=require('./stage-g-base/release_manifest.json');for(const f of base.files.filter(f=>f.file.startsWith('assets/')))assert.equal(crypto.createHash('sha256').update(require('./stage-h-contract.cjs').assetBytes(f.file)).digest('hex'),f.sha256,f.file);assert.deepEqual(J('V012Expansion.bounds'),{x:-2800,y:-2400,w:7200,h:12000});assert.equal(E('GameExploration.sectors.length'),12);assert.equal(E('GameExploration.sites.length'),3);});
test('new_game_preserves_C1_and_separates_unknown_from_access',()=>{reset();assert.equal(E('captureGameProgress().campaign031.contentRevision'),6);assert.equal(E('captureGameProgress().saveVersion'),E('SaveFormat.version'));assert.equal(E("GameExploration.known('sector.station')"),false);assert.equal(E("GameExploration.allowed('sector.station')"),true);assert.equal(E("GameExploration.allowed('sector.annex')"),false);assert.equal(E('GameResearch.capture().data'),0);assert.deepEqual(J('GameResearch.capture().packets'),[]);});
test('opening_or_drawing_map_never_discovers_or_grants_access',()=>{reset();const before=J('GameExploration.capture()'),fog=J('V010Camera.capture()');E("player.x=3050;player.y=6600;V010Camera.showMap();V010Camera.drawFull();draw()");assert.deepEqual(J('GameExploration.capture()'),before);assert.deepEqual(J('V010Camera.capture().discovered'),fog.discovered);assert.deepEqual(J('V010Camera.capture().known'),fog.known);});
test('survey_uses_simulation_actor_and_existing_fog',()=>{reset();E("player.x=3050;player.y=6600;GameExploration.tick(250)");assert.equal(E('V010Camera.seen(player.x,player.y)'),true);assert.equal(E("GameExploration.known('sector.station')"),true);assert.equal(E("GameExploration.visited('sector.southeast')"),true);assert.equal(E("GameExploration.allowed('sector.annex')"),false);boundary();});
test('survey_does_not_duplicate_discoveries_or_receipts',()=>{reset();E('GameExploration.tick(250)');const before=J('GameExploration.capture()');E('for(let n=0;n<80;n++)GameExploration.tick(250)');assert.deepEqual(J('GameExploration.capture()'),before);});
for(const mode of ['hidden','dead','explicit'])test('survey_paused_'+mode,()=>{reset();const before=J('GameExploration.capture()');E("player.x=3050;player.y=6600;"+(mode==='hidden'?'document.hidden=true':mode==='dead'?'playerDead=true':mode==='explicit'?"GameFlow.pause('qa')":"GameFlow.pause('qa-restore')"));E('GameExploration.tick(250)');assert.deepEqual(J('GameExploration.capture()'),before);});
test('known_gate_does_not_bypass_physical_gate',()=>{reset();E("player.x=3610;player.y=2570;GameExploration.tick(250)");assert.equal(E("GameExploration.known('sector.annex')"),true);assert.equal(E("GameExploration.allowed('sector.annex')"),false);for(const [x,y]of [[3610,2500],[3410,2300],[3810,2300],[3610,2200]])assert.equal(E(`worldCollision(${x},${y},15,'surface')`),true);E("V011World.buildings.find(b=>b.id==='ex12_east_1').doorOpen=true;V011World.buildings.find(b=>b.id==='ex12_east_1').doorProgress=1;invalidateGeometry()");assert.equal(E("worldCollision(3610,2500,15,'surface')"),true);assert.equal(collect('site.service_cache').ok,false);assert.deepEqual(J('GameResearch.capture().packets'),[]);});
test('field_collection_rejected_from_core_and_through_wall',()=>{reset();core();assert.equal(J("GameResearch.request('obtain',{sourceId:'source.field_notes'})").ok,false);at('site.field_notes');E('player.y=gs.y+80');const before=J('GameResearch.capture()');assert.equal(J("GameExploration.collect('site.field_notes')").ok,false);assert.deepEqual(J('GameResearch.capture()'),before);});
test('collect_is_available_without_base_power_or_inventory_space',()=>{reset();E("bag=Array.from({length:BAG_SLOTS},()=>({type:'wood',qty:100}));V09Power.running=false;V010Energy.battery.charge=0");assert.equal(collect('site.field_notes').ok,true);assert.equal(E('GameResearch.capture().data'),0);assert.equal(E('bag.length'),E('BAG_SLOTS'));assert.equal(E("GameExploration.allowed('sector.annex')"),true);boundary();});
test('field_notes_unlock_only_code_and_small_archive_entry',()=>{reset();const items=J('[bag,equipment,GameEquipment.capture()]');assert.equal(collect('site.field_notes').ok,true);assert.deepEqual(J('[bag,equipment,GameEquipment.capture()]'),items);assert.equal(E("GameStory.view().unlocked.includes('log.field_notes')"),true);assert.deepEqual(J('GameResearch.capture().technologies'),[]);assert.deepEqual(J('GameResearch.capture().blueprints'),[]);assert.equal(E('GameCampaign.view().completed.length'),0);});
test('new_field_archive_remains_reopenable_after_read_and_save_load',()=>{reset();collect('site.field_notes');core();assert.equal(J("GameStory.request('read',{entryId:'log.field_notes'})").ok,true);boundary();assert.equal(E("GameStory.view().read.includes('log.field_notes')"),true);E("CommandCoreUI.show('archive');CommandCoreUI.tick()");const card=r.doc.getElementById('coreSection_archive').querySelector('[data-archive-entry="log.field_notes"]');assert.ok(card);assert.equal(card.disabled,false);card.click();assert.ok(r.doc.getElementById('coreSection_archive').textContent.includes(E("I18n.t('story.field.1')")));});
test('partial_exploration_save_load_continues_and_gate_stays_open',()=>{reset();collect('site.field_notes');boundary();assert.equal(E("GameExploration.allowed('sector.annex')"),true);assert.equal(collect('site.service_cache').ok,true);boundary();assert.equal(collect('site.station_records').ok,true);boundary();});
test('real_interaction_dispatch_collects_document_once',()=>{reset();at('site.field_notes');const before=E('GameResearch.revision');E("executeInteraction(interactionObjects('surface').find(o=>o.id==='site.field_notes'))");assert.equal(E('GameResearch.revision'),before+1);E("executeInteraction(interactionObjects('surface').find(o=>o.id==='site.field_notes'))");assert.equal(E('GameResearch.revision'),before+1);boundary();});
test('field_research_duplicate_request_and_conflict_survive_save',()=>{reset();at('site.field_notes');E('GameExploration.survey()');r.context.gcmd={actorId:E('GameActors.localId'),instanceId:'source.field_notes',requestId:'qa.field.stable',expectedRevision:E('GameResearch.revision'),action:'obtain',payload:{sourceId:'source.field_notes'}};assert.equal(J('GameResearch.execute(gcmd)').ok,true);boundary();const before=J('GameResearch.capture()');assert.equal(J('GameResearch.execute(gcmd)').replayed,true);assert.deepEqual(J('GameResearch.capture()'),before);assert.equal(J("GameResearch.execute({...gcmd,payload:{sourceId:'source.service_cache'}})").ok,false);});
test('field_command_wrong_target_distance_actor_and_stale_rejected',()=>{reset();at('site.field_notes');E('GameExploration.survey()');const c={actorId:E('GameActors.localId'),instanceId:'source.field_notes',requestId:'qa.field',expectedRevision:E('GameResearch.revision'),action:'obtain',payload:{sourceId:'source.field_notes'}};for(const change of [{actorId:'player:999'},{instanceId:E('BunkerLayout.core.id')},{expectedRevision:99},{action:'submit'}]){r.context.gcmd={...c,...change};const before=J('GameResearch.capture()');assert.equal(J('GameResearch.execute(gcmd)').ok,false);assert.deepEqual(J('GameResearch.capture()'),before);}});
test('explore_submit_research_craft_inventory_place_save_load',()=>{reset();for(const id of ['site.field_notes','site.service_cache','site.station_records'])assert.equal(collect(id).ok,true);core();for(const sourceId of ['source.field_notes','source.service_cache','source.station_records'])assert.equal(J(`GameResearch.request('submit',{sourceId:'${sourceId}'})`).ok,true);assert.equal(E('GameResearch.capture().data'),36);const before=J('GameEquipment.capture()');assert.equal(J("GameResearch.request('research',{researchId:'research.station_fabrication'})").ok,true);assert.deepEqual(J('GameEquipment.capture()'),before);E("for(const [type,qty]of [['iron',100],['wood',100],['parts',100],['concrete',100]])addItem(type,qty)");const crafted=J("GamePlacement.request('furnace','craft')");assert.equal(crafted.ok,true);r.context.createdId=crafted.instanceId;assert.equal(E('GameEquipment.get(createdId).placement'),'packed');assert.equal(E('GameEquipment.inventory(GameActors.localId).some(r=>r.id===createdId)'),true);E("window.target=GamePlacement.centered('furnace','reserve_l1',1950,400,1)");assert.equal(J("GamePlacement.request(createdId,'place',target)").ok,true);boundary();assert.equal(E('GameEquipment.get(createdId).placement'),'installed');assert.equal(E('GameEquipment.get(createdId).transform.rotation'),Math.PI/2);assert.ok(J('GameResearch.capture().blueprints').includes('blueprint.scout_service'));const balance=E('GameResearch.capture().data');assert.equal(J("GameResearch.request('submit',{sourceId:'source.field_notes'})").ok,false);assert.equal(E('GameResearch.capture().data'),balance);});
let legacy;
test('migration_0371_preserves_every_old_save_owner',()=>{const old=setup('qa/stage-g-base/index.html');old.eval("restoreGameProgress(GameNewGame.create());GameStory.request('finish_intro',{outcome:'skipped'});scene='surface';player.x=3610;player.y=2445;Object.assign(V014Robots.state,{scene:'surface',x:3450,y:2300,packed:false,task:'guard',guard:{scene:'surface',x:3450,y:2300},autoReturn:false,battery:100});V010Camera.reveal();");legacy=JSON.parse(old.eval('JSON.stringify(captureGameProgress())'));assert.equal(legacy.saveVersion,17);const before=J('captureGameProgress()');r.context.oldData=legacy;const result=J('decodeGameProgress(JSON.stringify(oldData))');for(const key of Object.keys(legacy))if(!['gameVersion','saveVersion'].includes(key))assert.deepEqual(require('./stage-h-contract.cjs').project(result)[key],legacy[key],key);assert.deepEqual(J('captureGameProgress()'),before);assert.equal(result.saveVersion,E('SaveFormat.version'));assert.equal(result.sectors038.profile,'legacy');assert.equal(result.sectors038.access.length,12);assert.deepEqual(result.sectors038.sites,[]);assert.deepEqual(result.research036.packets,legacy.research036.packets);E('restoreGameProgress(decodeGameProgress(JSON.stringify(oldData)))');assert.equal(E("GameExploration.allowed('sector.annex')"),true);assert.equal(E('player.x'),legacy.player.x);assert.equal(E('V014Robots.state.x'),legacy.robots014.x);});
test('migration_idempotent_and_no_intro_replay',()=>{r.context.oldData=legacy;const a=J('decodeGameProgress(JSON.stringify(oldData))');r.context.once=a;assert.deepEqual(J('decodeGameProgress(JSON.stringify(once))'),a);const c=setup('index.html',{'survival_base_v09_slot_2':JSON.stringify(legacy)},{mainMenu:true,storyIntro:true});assert.equal(c.eval('MainMenu.continueGame()'),true);assert.equal(c.eval('StoryPlayer.active'),false);assert.deepEqual(c.errors,[]);});
for(const [name,edit]of [ ['missing',d=>delete d.sectors038],['unknown_sector',d=>d.sectors038.known.push('sector.future')],['duplicate',d=>d.sectors038.known.push(d.sectors038.known[0])],['gate_without_code',d=>d.sectors038.access.push('sector.annex')],['unknown_site',d=>d.sectors038.sites.push('site.future')],['bad_receipt',d=>d.sectors038.commands.revision++],['future_schema',d=>d.sectors038.schema++],['future_format',d=>d.saveVersion=E('SaveFormat.version')+1]])test('save_atomic_reject_'+name,()=>{reset();const before=J('captureGameProgress()'),bad=JSON.parse(JSON.stringify(before));edit(bad);r.context.bad=bad;assert.throws(()=>E('restoreGameProgress(bad)'));assert.deepEqual(J('captureGameProgress()'),before);});
test('research_packet_requires_persisted_site_evidence',()=>{reset();collect('site.field_notes');const before=J('captureGameProgress()'),bad=JSON.parse(JSON.stringify(before));bad.sectors038.sites=[];r.context.bad=bad;assert.throws(()=>E('decodeGameProgress(JSON.stringify(bad))'));assert.deepEqual(J('captureGameProgress()'),before);});
for(const [width,height]of [[1280,800],[390,844],[844,390],[320,568]])for(const language of ['ru','en'])test('shared_core_and_map_navigation_'+language+'_'+width+'x'+height,()=>{reset();core();E(`innerWidth=${width};innerHeight=${height};I18n.setLanguage('${language}');CommandCoreUI.show('map-signals');CommandCoreUI.tick()`);const host=r.doc.getElementById('coreSection_map-signals');assert.ok(host.querySelector('[data-sector="sector.woodland"]'));host.querySelector('[data-sector="sector.woodland"]').click();assert.ok(host.querySelector('[data-sector-locate="sector.woodland"]'));r.doc.getElementById('coreBack').click();assert.ok(host.querySelector('[data-sector="sector.woodland"]'));const before=J('captureGameProgress()');E("V010Camera.showMap('surface');V010Camera.drawFull()");assert.equal(E('scene'),'bunker');assert.equal(E('V010Camera.mapScene'),'surface');r.doc.getElementById('explorationMapSectors').click();assert.equal(r.doc.getElementById('explorationDrawer').hidden,false);const text=r.doc.getElementById('explorationDrawer').textContent;assert.ok(!/exploration\.|sector\.|site\.|undefined/.test(text));if(language==='ru')assert.ok(!/[a-zA-Z]{2,}/.test(text.replaceAll('LAST BASE','')),text);else assert.ok(!/[А-Яа-яЁё]/.test(text));assert.deepEqual(J('captureGameProgress().sectors038'),before.sectors038);});
test('home_goal_uses_surface_coordinates_without_changing_scene',()=>{reset();core();E("V010Camera.showMap('surface')");r.doc.getElementById('explorationMapHome').click();assert.deepEqual(J('V010Camera.goal'),{scene:'surface',x:800,y:690});assert.equal(E('scene'),'bunker');assert.equal(E('V010Camera.selected.scene'),'surface');const before=J('[player.x,player.y]');r.doc.getElementById('v014MapGo').click();assert.deepEqual(J('[player.x,player.y]'),before);assert.equal(E('V014Controls.route'),null);assert.equal(E("GameExploration.capture().goal"),undefined);});
test('surface_map_click_cannot_move_bunker_player',()=>{reset();core();E("V010Camera.showMap('surface')");const cv=r.doc.getElementById('v010WorldMap');for(const type of ['pointerdown','pointerup'])cv.dispatchEvent({type,pointerId:1,clientX:50,clientY:50});assert.equal(E('V010Camera.selected.scene'),'surface');const before=J('[player.x,player.y,scene]');r.doc.getElementById('v014MapGo').click();assert.deepEqual(J('[player.x,player.y,scene]'),before);assert.equal(E('V014Controls.route'),null);});
test('map_pins_and_camera_remain_outside_team_sector_owner',()=>{reset();E("V010Camera.setGoal({x:500,y:1500,scene:'surface'})");assert.deepEqual(J('V010Camera.goal'),{x:500,y:1500,scene:'surface'});assert.ok(!('goal' in J('GameExploration.capture()')));boundary();assert.equal(E('V010Camera.goal.x'),500);});
test('simulation_budget_and_idle_map_do_not_rebuild',()=>{reset();core();E("CommandCoreUI.show('map-signals');CommandCoreUI.tick()");const builds=E('GameExplorationUI.metrics().renders'),polls=E('GameExploration.metrics().polls');E('for(let n=0;n<240;n++){GameExploration.tick(16.667);CommandCoreUI.tick()}');assert.equal(E('GameExplorationUI.metrics().renders'),builds);assert.ok(E('GameExploration.metrics().polls')-polls<=17);});
test('two_actor_domain_shared_access_and_duplicate_guards',()=>{E("window.gf={'world.open':true,'expedition.field_notes':false};window.actors={a:{id:'a'},b:{id:'b'}};window.observations={a:{known:['sector.annex'],visited:[],sites:[]},b:{known:['sector.woodland'],visited:['sector.woodland'],sites:['site.field_notes']}};window.gd=ExplorationDomain.create(ExplorationDefinitions,{initialProfile:'new',facts:()=>gf,actor:id=>actors[id],authorized:()=>true,observe:a=>observations[a.id]});");const cmd={actorId:'a',instanceId:'world:surface',action:'survey',payload:{},requestId:'shared.a',expectedRevision:0};r.context.gcmd=cmd;assert.equal(J('gd.execute(gcmd)').ok,true);assert.equal(J('gd.execute(gcmd)').replayed,true);r.context.gcmd={...cmd,actorId:'b',requestId:'shared.b'};assert.equal(J('gd.execute(gcmd)').reason,'stale_revision');r.context.gcmd.expectedRevision=1;assert.equal(J('gd.execute(gcmd)').ok,true);E("gf['expedition.field_notes']=true");r.context.gcmd={...cmd,expectedRevision:2,requestId:'shared.c'};assert.equal(J('gd.execute(gcmd)').ok,true);assert.equal(E("gd.allowed('sector.annex')"),true);const before=J('gd.capture()');E('gd.restore(gd.capture())');assert.deepEqual(J('gd.capture()'),before);});
test('two_actors_cannot_claim_same_research_source',()=>{E("window.rd=ResearchDomain.create(ResearchDefinitions,{coreId:'core:test',facts:()=>Object.fromEntries(ResearchDefinitions.facts.map(id=>[id,true])),actor:id=>({id}),authorized:()=>true,access:()=>({available:true}),sourceAccess:()=>({available:true})});");const c={actorId:'a',instanceId:'source.field_notes',requestId:'a',expectedRevision:0,action:'obtain',payload:{sourceId:'source.field_notes'}};r.context.gcmd=c;assert.equal(J('rd.execute(gcmd)').ok,true);r.context.gcmd={...c,actorId:'b',requestId:'b',expectedRevision:1};assert.equal(J('rd.execute(gcmd)').reason,'research.error.source_claimed');assert.equal(E('rd.capture().packets.length'),1);});
test('no_console_errors',()=>assert.deepEqual(r.errors,[]));
const report={version:require('../package.json').version,runtimeSha256:hash('js/game.js'),passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks,limitations:['Modeled DOM/WebAudio/HTMLVideoElement; physical PC/mobile/Telegram rendering and audio remain manual.']};fs.writeFileSync('qa/results/stage-g.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,failed:report.failed,failures:checks.filter(c=>c.status==='FAIL')}));if(report.failed)process.exitCode=1;
