const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');process.chdir(path.resolve(__dirname,'..'));process.env.LAST_BASE_ASSETS=process.cwd();
const {setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),J=s=>JSON.parse(E('JSON.stringify('+s+')')),checks=[];
function test(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack});}console.log(id,checks.at(-1).status);}
function clean(){E("StoryPlayer.cancel();for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);for(const reason of GameFlow.reasons)GameFlow.resume(reason);menuOpen=false;playerDead=false;document.hidden=false;stopControls(true)");}
function base(){E('GameDevQA.disable();restoreGameProgress(GameNewGame.create());GameStory.request("finish_intro",{outcome:"skipped"})');clean();}
function at(day,minute){E(`WorldClock.restore({schema:1,day:${day},minute:${minute}})`);}
function frame(ms=17){r.advance(ms);E('frameScale=1;update()');}
function save(){E('window.savedI2=decodeGameProgress(JSON.stringify(captureGameProgress()));restoreGameProgress(savedI2)');clean();}
function enable(){base();E("for(let i=1;i<=5;i++){localStorage.removeItem(v09SlotKey(i));localStorage.removeItem(v09BackupKey(i));}GameState.session.activeSlot=1;GameState.session.lastVerified=null;saveGameProgress();");assert.equal(E('GameDevQA.enable().ok'),true);clean();}
const cmd=p=>J(`GameDevQA.request('time',${JSON.stringify(p)})`);
function complete(){for(let i=0;i<12000&&E('GameDevQA.metrics().target!==null');i++){r.advance(17);E('frameScale=1;GameDevQA.runFrame(update)');}assert.equal(E('GameDevQA.metrics().target'),null);}
test('new_game_quiet_and_onboarding_unchanged',()=>{base();assert.equal(E('GameSignal.view().phase'),'quiet');assert.equal(E('GameSignal.view().threat'),0);assert.equal(E('GameCampaign.view().chapter'),'chapter_1');assert.equal(E('SaveFormat.version'),21);save();});
test('signal_48h_warning24h_imminent6h',()=>{base();at(8,0);assert.equal(E('GameSignal.view().phase'),'detected');at(9,0);assert.equal(E('GameSignal.view().phase'),'warning');at(9,1080);assert.equal(E('GameSignal.view().phase'),'imminent');assert.equal(E('GameSignal.view().left'),360);save();assert.equal(E('GameSignal.capture().imminentDay'),10);});
test('archive_log_unlocked_after_observation',()=>{base();at(8,1);assert.equal(E("GameStory.capture().unlocked.includes('log.signal_observation')"),true);save();});
test('midnight_starts_once_and_multipliers_do_not_stack',()=>{base();at(9,1439.999);frame();assert.equal(E('WorldClock.day'),10);assert.equal(E('GameSignal.capture().wave.day'),10);let before=J('GameSignal.capture()');for(let i=0;i<10;i++)E('GameSignal.observe()');assert.deepEqual(J('GameSignal.capture()'),before);assert.equal(E("WorldEvents.value('enemy.hp')"),1.5);save();assert.deepEqual(J('GameSignal.capture()'),before);});
test('composition_directions_bounded_and_no_refill_exploit',()=>{base();E('zombies=[]');at(10,0);const p=J('GameSignal.view().profile');for(let i=0;i<160;i++){E(`var zz=V017Monsters.spawn(${i});if(zz){zombies.push(zz);zz.alive=false;zz.health=0;}`);}const w=J('GameSignal.capture().wave');assert.equal(w.admitted.length,w.limit);assert.ok(w.limit<=144);assert.equal(E('V017Monsters.spawn(999)'),null);assert.ok(J('zombies.map(z=>z.type)').every(t=>p.types.includes(t)));save();assert.equal(E('V017Monsters.spawn(1000)'),null);});
test('death_receipt_is_idempotent',()=>{base();E('zombies=[]');at(10,0);E('var victim=V017Monsters.spawn(0);zombies.push(victim);hitZombie(victim,9999,{fixedDamage:true});GameSignal.killed(victim);');assert.equal(E('GameSignal.capture().wave.killed.length'),1);save();assert.equal(E('GameSignal.capture().wave.killed.length'),1);});
test('0559_0600_results_and_no_replay',()=>{base();at(10,359);E("V018Build.damage(V015Base.sections.find(w=>w.group==='outer').id,100)");at(10,360);assert.equal(E('GameSignal.capture().wave'),null);assert.equal(E('GameSignal.capture().history.length'),1);assert.equal(E('GameSignal.view().last.outcome'),'damaged');const before=J('GameSignal.capture()');save();E('GameSignal.observe()');assert.deepEqual(J('GameSignal.capture()'),before);assert.equal(E("WorldEvents.value('enemy.hp')"),1);});
test('next_cycle_has_new_composition_bounded_threat',()=>{base();at(10,0);let p=E('GameSignal.view().profile.id');at(10,360);at(20,0);assert.notEqual(E('GameSignal.view().profile.id'),p);assert.equal(E('GameSignal.view().threat'),100);at(500,0);assert.ok(E('GameSignal.view().threat')<=100);});
test('save20_migration_midraid_keeps_existing_enemies_without_wave_spawn',()=>{base();const old=setup('qa/stage-i2-base/index.html');old.eval('WorldClock.restore({schema:1,day:10,minute:100})');r.context.legacyI2=JSON.parse(old.eval('JSON.stringify(captureGameProgress())'));E('window.oldIds=legacyI2.identity027.enemies.slice();restoreGameProgress(decodeGameProgress(JSON.stringify(legacyI2)))');assert.deepEqual(J('captureGameProgress().identity027.enemies'),J('oldIds'));assert.equal(E('GameSignal.capture().wave.legacy'),true);assert.equal(E('GameSignal.spawnPlan(0).allowed'),false);for(const k of ['bag','equipment032','research036','campaign031','story037','control0353','carry0353'])assert.deepEqual(J('captureGameProgress().'+k),J('legacyI2.'+k));save();});
test('invalid_ledger_rejected_before_mutation',()=>{base();const before=J('GameSignal.capture()');assert.throws(()=>E('var bad=captureGameProgress();bad.signal041.resolvedDay=11;restoreGameProgress(bad)'));assert.deepEqual(J('GameSignal.capture()'),before);});
test('restoring_other_slot_during_attack_cannot_use_previous_wave_budget',()=>{base();at(10,0);E('var nextSlotI2=GameNewGame.create();restoreGameProgress(nextSlotI2)');assert.equal(E('GameSignal.capture().wave'),null);assert.equal(E('GameSignal.capture().observed'),false);assert.deepEqual(J('captureGameProgress().monsters017.types'),J('nextSlotI2.monsters017.types'));save();});
for(const minutes of [60,360,1440])test('DEV_exact_'+minutes+'_minutes_and_save',()=>{enable();E("scene='bunker';window.startI2=WorldClock.day*1440+WorldClock.minute;window.fuelI2=V09Power.fuel;zombies=[];");assert.equal(cmd({minutes}).ok,true);complete();assert.ok(Math.abs(E('WorldClock.day*1440+WorldClock.minute-startI2')-minutes)<1e-5);assert.equal(E('GameDevQA.metrics().rate'),1);save();});
test('DEV_to_day_crosses_signal_and_midnight',()=>{enable();at(9,1439);assert.equal(cmd({day:10}).ok,true);complete();assert.equal(E('WorldClock.day'),10);assert.ok(E('WorldClock.minute')<1e-5);assert.equal(E('GameSignal.capture().wave.day'),10);save();});
test('DEV_duplicate_time_packet_no_second_target',()=>{enable();E("var packetI2={actorId:GameActors.localId,instanceId:'qa',requestId:'I2time',expectedRevision:GameDevQA.revision,action:'time',payload:{minutes:60}};GameDevQA.execute(packetI2)");let target=E('GameDevQA.metrics().target');assert.equal(E('GameDevQA.execute(packetI2).replayed'),true);assert.equal(E('GameDevQA.metrics().target'),target);E("GameDevQA.request('stop')");});
test('DEV_disabled_no_commands_or_time_override',()=>{base();let before=J('WorldClock.capture()');assert.equal(cmd({minutes:1440}).ok,false);assert.deepEqual(J('WorldClock.capture()'),before);});
test('UI_RU_EN_and_map_route',()=>{base();for(const lang of ['ru','en']){E(`I18n.setLanguage('${lang}');GameSignalUI.refresh();`);assert.ok(!E("el('signalChip').textContent").includes('signal.'));}E("scene='bunker';player.x=1210;player.y=675;V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=1;CommandCoreUI.show('map-signals');CommandCoreUI.tick()");assert.ok(E("el('coreSection_map-signals').textContent.includes(I18n.t('signal.title'))"));});
test('no_console_errors',()=>assert.deepEqual(r.errors,[]));
const result={version:'0.41.0',runtimeSha256:crypto.createHash('sha256').update(fs.readFileSync('js/game.js')).digest('hex'),passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks};fs.writeFileSync('qa/results/stage-i2.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(checks.filter(c=>c.status==='FAIL')));if(result.failed)process.exitCode=1;
