const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');process.chdir(path.resolve(__dirname,'..'));process.env.LAST_BASE_ASSETS=process.cwd();process.env.LAST_BASE_TEST_LANGUAGE='ru';
const {setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),J=s=>JSON.parse(E('JSON.stringify('+s+')')),checks=[];
function test(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack.slice(0,3400)});}console.log(id,checks.at(-1).status);}
function clean(){E("StoryPlayer.cancel();for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);for(const reason of GameFlow.reasons)GameFlow.resume(reason);GamePickup.cancel();menuOpen=false;playerDead=false;document.hidden=false;stopControls(true);zombies=[]");}
function reset(){E("restoreGameProgress(GameNewGame.create());GameStory.request('finish_intro',{outcome:'skipped'})");clean();E("for(const c of storageChests)c.items=[];bag=[];for(const t of ['iron','parts','copper','wood','concrete','ammo','advanced_parts'])addItem(t,300);addItem('hammer',1);scene='bunker';player.x=1210;player.y=680");}
function craft(type){E("scene='bunker';player.x=1210;player.y=680");const x=J(`GamePlacement.request('${type}','craft')`);assert.equal(x.ok,true,JSON.stringify(x));return x.instanceId;}
function place(id,x=450,y=350,turn=0,room='yard'){E(`scene='${room==='yard'?'surface':'bunker'}';player.x=${room==='yard'?800:1210};player.y=${room==='yard'?850:680};`);const q=J(`GamePlacement.request('${id}','place',GamePlacement.centered(GameEquipment.get('${id}').typeId,'${room}',${x},${y},${turn}))`);assert.equal(q.ok,true,JSON.stringify(q));return q;}
function near(id){r.context.did=id;assert.equal(E("(()=>{const r=GameEquipment.get(did),b=GameFootprints.forRecord(r);scene=r.transform.scene;for(const p of [{x:b.x+b.w/2,y:b.y+b.h+24},{x:b.x-24,y:b.y+b.h/2},{x:b.x+b.w+24,y:b.y+b.h/2},{x:b.x+b.w/2,y:b.y-24}]){Object.assign(player,p);if(GameDefense.reachable(GameActors.local,r)&&!worldCollision(p.x,p.y,player.radius,scene))return true;}return false;})()"),true);}
function power(id){E(`V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=1;for(const d of Object.values(V09Power.devices))d.enabled=d.id==='${id}';`);}
function save(){const d=J('captureGameProgress()');r.context.hsave=d;E('restoreGameProgress(decodeGameProgress(JSON.stringify(hsave)))');assert.deepEqual(J('GameEquipment.capture()'),d.equipment032.instances);assert.deepEqual(J('GameDefense.capture()'),d.defense039);assert.deepEqual(J('captureGameProgress().v09.power.deviceEnabled'),d.v09.power.deviceEnabled);clean();}
function pack(id){near(id);clean();near(id);const h=J(`GamePlacement.beginPickup('${id}')`);assert.equal(h.ok,true,JSON.stringify(h));r.context.ticket=h;assert.equal(J("GamePlacement.request(ticket.id,'pack',null,ticket.token)").reason,'holdRequired');r.advance(3001);const result=J("GamePlacement.request(ticket.id,'pack',null,ticket.token)");assert.equal(result.ok,true,JSON.stringify(result));}
function issue(id,action,payload={}){return J(`GameDefense.request('${id}','${action}',${JSON.stringify(payload)})`);}

test('baseline_0380_exact',()=>assert.equal(crypto.createHash('sha256').update(fs.readFileSync('qa/stage-h-base/js/game.js')).digest('hex'),'8a11f64155170b3fe887bbd69285641491bff9ae334db044ab46765efeaac3c1'));
test('definitions_power_cost_DPS_and_no_gate',()=>{reset();const d=J('DefenseDefinitions.types');assert.ok(Math.abs((d.automatic_turret.damage/d.automatic_turret.intervalMs)/(d.heavy_turret.damage/d.heavy_turret.intervalMs)-.5)<.01);assert.equal(d.heavy_turret.damage,65);assert.equal(d.heavy_turret.intervalMs,190);for(const k of Object.keys(d.automatic_turret.cost))assert.equal(d.heavy_turret.cost[k],3*d.automatic_turret.cost[k]);for(const type of Object.keys(d))assert.equal(E(`GameAvailability.buildable('${type}').available`),true);});
for(const type of ['automatic_turret','heavy_turret','searchlight'])test(type+'_craft_inventory_place_pickup_same_instance_save',()=>{reset();const id=craft(type);assert.equal(E(`bag.filter(s=>s?.instanceId==='${id}').length`),1);assert.equal(E(`interactionObjects('surface').some(o=>o.id==='${id}')`),false);assert.equal(E(`V09Power.allocation().served.has('${id}')`),false);save();place(id);near(id);power(id);assert.equal(E(`devicePowered('${id}')`),true);if(type!=='searchlight'){assert.equal(issue(id,'load',{units:100}).units,100);}else assert.equal(issue(id,'aim',{angle:1.2}).ok,true);const state=J(`GameEquipment.get('${id}').state`);save();pack(id);assert.equal(E(`interactionObjects('surface').some(o=>o.id==='${id}')`),false);assert.equal(E(`solidObjects('surface').some(o=>o.id==='${id}')`),false);assert.equal(E(`devicePowered('${id}')`),false);save();place(id,550,370,1);assert.deepEqual(J(`GameEquipment.get('${id}').state`),state);save();});
test('damage_destroy_rebuild_keeps_identity_ammo_upgrade',()=>{reset();const id=craft('automatic_turret');place(id);near(id);assert.equal(issue(id,'load',{units:80}).ok,true);assert.equal(issue(id,'upgrade').ok,true);power(id);E(`GameDefense.damage('${id}',500)`);save();near(id);E("V013Inventory.equip('hammer')");assert.equal(issue(id,'repair').ok,true);E(`GameDefense.damage('${id}',100000)`);assert.equal(E(`devicePowered('${id}')`),false);assert.equal(E(`solidObjects('surface').some(o=>o.id==='${id}')`),false);save();near(id);E("V013Inventory.equip('hammer')");assert.equal(issue(id,'repair').ok,true);assert.equal(E(`GameEquipment.get('${id}').state.settings.ammo`),80);assert.equal(E(`GameEquipment.get('${id}').state.level`),1);save();});
test('rebuild_occupied_no_spend_and_critical_routes',()=>{reset();const id=craft('searchlight');place(id);E(`GameDefense.damage('${id}',100000)`);near(id);E("V013Inventory.equip('hammer')");E(`const p=GameEquipment.center('${id}');zombies=[makeZombie(p.x,p.y)]`);const before=E("V010Inventory.materialCount('iron')");assert.equal(issue(id,'repair').reason,'occupied');assert.equal(E("V010Inventory.materialCount('iron')"),before);for(const [x,y]of [[800,350],[450,600],[800,700],[150,150]]){const token=craft('automatic_turret');E("scene='surface'");const check=J(`GamePlacement.check('${token}',GamePlacement.centered('automatic_turret','yard',${x},${y}))`);assert.equal(check.ok,false);}});
test('no_remote_scene_placement_and_no_overlap',()=>{reset();const a=craft('automatic_turret'),b=craft('searchlight');assert.equal(J(`GamePlacement.request('${a}','place',GamePlacement.centered('automatic_turret','yard',450,350))`).reason,'room');place(a);assert.equal(J(`GamePlacement.check('${b}',GamePlacement.centered('searchlight','yard',450,350))`).reason,'overlap');});
test('repair_material_shortage_and_missing_hammer_atomic',()=>{reset();const id=craft('automatic_turret');place(id);near(id);E(`GameDefense.damage('${id}',600)`);assert.equal(issue(id,'repair').reason,'hammer');E("V013Inventory.equip('hammer');bag=bag.filter(s=>s?.type!=='iron')");const before=J(`GameEquipment.get('${id}')`);assert.equal(issue(id,'repair').reason,'materials');assert.deepEqual(J(`GameEquipment.get('${id}')`),before);});
test('duplicate_conflict_stale_remote_actor_and_save_receipts',()=>{reset();const id=craft('searchlight');place(id);near(id);r.context.cmd=J(`({actorId:GameActors.localId,instanceId:'${id}',action:'aim',payload:{angle:.5,state:JSON.stringify(GameEquipment.get('${id}').state)},requestId:'h:aim',expectedRevision:GameDefense.revision})`);assert.equal(J('GameDefense.execute(cmd)').ok,true);assert.equal(J('GameDefense.execute(cmd)').replayed,true);save();assert.equal(J('GameDefense.execute(cmd)').replayed,true);assert.equal(J('GameDefense.execute({...cmd,payload:{...cmd.payload,angle:.4}})').reason,'request_conflict');assert.equal(J("GameDefense.execute({...cmd,requestId:'stale'})").reason,'stale_revision');assert.equal(J("GameDefense.execute({...cmd,actorId:'player:2'})").reason,'actor_denied');});
test('local_Core_Remote_share_switch_state_and_saved_direction',()=>{reset();const id=craft('searchlight');place(id);near(id);power(id);assert.equal(J(`GameBaseControl.request('${id}','power',{value:false})`).ok,true);E("scene='bunker';player.x=1210;player.y=680");assert.equal(J(`GameBaseControl.request('${id}','power',{value:true})`).ok,true);E("scene='surface';player.x=1800;player.y=1500;addItem('remote',1)");assert.equal(J(`GameBaseControl.request('${id}','power',{value:false})`).ok,true);save();assert.equal(E(`V09Power.devices['${id}'].enabled`),false);});
test('searchlight_rotated_bunker_power_aim_and_shadow_geometry',()=>{reset();const id=craft('searchlight');place(id,1880,400,1,'reserve_l1');near(id);power(id);assert.equal(issue(id,'aim',{angle:0}).ok,true);let s=J('V016Lighting.searchlights()');assert.equal(s.length,1);assert.equal(s[0].range,1100);assert.equal(s[0].angle,0);const shape=J('V016Lighting.lightShape(V016Lighting.searchlights()[0])');assert.equal(shape.points.length,57);assert.ok(shape.points.every(p=>p.x<=2130));const t=J(`GameEquipment.get('${id}').transform`);assert.equal(issue(id,'aim',{angle:Math.PI}).ok,true);assert.deepEqual(J(`GameEquipment.get('${id}').transform`),t);assert.equal(J('V016Lighting.searchlights()')[0].angle,Math.PI);save();});
test('turret_damage_real_power_ammo_LOS_and_disabled',()=>{reset();const id=craft('automatic_turret');place(id);near(id);issue(id,'load',{units:10});power(id);E("zombies=[makeZombie(600,350)];V017Monsters.prepare(zombies[0]);zombies[0].health=120;zombies[0].alive=true");assert.equal(E(`GameDefense.shoot(GameEquipment.get('${id}'),zombies[0])`),true);assert.equal(E(`GameEquipment.get('${id}').state.settings.ammo`),9);assert.equal(E('zombies[0].health'),75);E(`V09Power.devices['${id}'].enabled=false`);assert.equal(E(`GameDefense.shoot(GameEquipment.get('${id}'),zombies[0])`),false);E(`V09Power.devices['${id}'].enabled=true;zombies[0].x=800;zombies[0].y=590`);assert.equal(E(`GameDefense.shoot(GameEquipment.get('${id}'),zombies[0])`),false);save();});
test('breach_actual_enemy_attack_and_destroyed_recoverable',()=>{reset();const id=craft('searchlight');place(id);E(`const b=GameFootprints.body('${id}');window.hz=makeZombie(b.x-25,b.y+b.h/2);hz.lastAttack=-100000;zombies=[hz]`);const before=E(`GameEquipment.get('${id}').state.condition.hp`);E('GameDefense.breachTarget(hz,performance.now(),V017Monsters.stats(hz))');assert.ok(E(`GameEquipment.get('${id}').state.condition.hp`)<before);E(`GameDefense.damage('${id}',100000)`);assert.equal(E(`interactionObjects('surface').some(o=>o.id==='${id}')`),true);save();});
test('legacy_wall_support_loss_and_same_id_replacement',()=>{reset();E("scene='surface';V015Base.byId.get('v091wall020_corner_SE').hp=0;GameDefense.settle()");assert.equal(E("GameEquipment.get('hmg016_1').state.settings.fallen"),true);save();pack('hmg016_1');place('hmg016_1',550,350);assert.equal(E("GameEquipment.get('hmg016_1').state.settings.fallen"),false);save();});
let legacy;
test('migration_0380_all_old_owners_intact_and_identity_ammo_level',()=>{const old=setup('qa/stage-h-base/index.html');old.eval("restoreGameProgress(GameNewGame.create());GameStory.request('finish_intro',{outcome:'skipped'});V016Turret.guns[0].ammo=77;V016Turret.guns[0].level=3;V016Turret.guns[0].enabled=false;addItem('hmg016',1);bag.find(s=>s?.type==='hmg016').turretData.ammo=26;");legacy=JSON.parse(old.eval('JSON.stringify(captureGameProgress())'));r.context.legacy=legacy;const migrated=J('decodeGameProgress(JSON.stringify(legacy))');assert.equal(migrated.saveVersion,E('SaveFormat.version'));assert.equal(migrated.turret016.guns.length,0);for(const key of ['research036','story037','sectors038','campaign031','chapter034','head033','v091','quick013','storage','equipment'])assert.deepEqual(migrated[key],legacy[key],key);for(const record of legacy.equipment032.instances)assert.deepEqual(migrated.equipment032.instances.find(r=>r.id===record.id),record);assert.equal(migrated.equipment032.instances.find(r=>r.id==='hmg016_1').state.level,3);assert.equal(migrated.equipment032.instances.find(r=>r.id==='hmg016_1').state.settings.ammo,77);assert.equal(migrated.v09.power.deviceEnabled.hmg016_1,false);const token=migrated.bag.find(s=>s?.type==='equipment_case');assert.equal(migrated.equipment032.instances.find(r=>r.id===token.instanceId).state.settings.ammo,26);E('restoreGameProgress(decodeGameProgress(JSON.stringify(legacy)))');save();});
for(const [name,mutation]of [['hp',"s.state.condition.hp=-1"],['ammo',"s.state.settings.ammo=99999"],['angle',"s.state.settings.angle=9"],['duplicate',"d.equipment032.instances.push(s)"],['missing_receipts',"delete d.defense039"],['unknown_type',"s.typeId='bad_type'"]])test('atomic_save_reject_'+name,()=>{reset();const before=J('GameEquipment.capture()');E(`window.d=captureGameProgress();window.s=d.equipment032.instances.find(r=>r.typeId==='heavy_turret');${mutation}`);assert.throws(()=>E('restoreGameProgress(d)'));assert.deepEqual(J('GameEquipment.capture()'),before);});
for(const lang of ['ru','en'])for(const [w,h]of [[1280,800],[390,844],[844,390]])test('UI_'+lang+'_'+w,()=>{reset();const id=craft('searchlight');place(id);near(id);E(`innerWidth=${w};innerHeight=${h};I18n.setLanguage('${lang}');GameDefenseUI.open('${id}')`);const n=r.doc.getElementById('defenseOverlay'),text=n.textContent;assert.ok(!/defense\.|build\.type\.|undefined/.test(text),text);assert.ok(n.querySelector('[data-defense-action="aim"]'));assert.ok(n.querySelector('[data-defense-action="repair"]'));r.doc.getElementById('searchlightDirection').value='90';r.doc.getElementById('searchlightDirection').oninput();n.querySelector('[data-defense-action="aim"]').click();assert.equal(E(`GameEquipment.get('${id}').state.settings.angle`),Math.PI/2);});
test('legacy_wall_deck_click_opens_without_forced_descent',()=>{reset();E("scene='surface';player.wallLevel=true;window.wallGun=interactionObjects().find(o=>o.id==='hmg016_1');player.x=wallGun.x;player.y=wallGun.y+22;approachObject(wallGun)");assert.equal(E("el('defenseOverlay').classList.contains('open')"),true);assert.equal(E('player.wallLevel'),true);});
test('navigation_checks_candidate_position_not_current_player',()=>{reset();const id=craft('automatic_turret');place(id);near(id);const p=J('({x:player.x,y:player.y})');E("player.x=1600;player.y=1700");assert.equal(E(`canInteract(interactionObjects('surface').find(o=>o.id==='${id}'),${p.x},${p.y})`),true);assert.equal(E(`canInteract(interactionObjects('surface').find(o=>o.id==='${id}'),1600,1700)`),false);});
test('legacy_paid_output_collects_once_as_same_instance_token',()=>{reset();E("V09Craft.craftQueue.ready.craft_bench.hmg016=1");save();const before=E('GameEquipment.ids.length');assert.equal(E("V09Craft.collect('craft_bench')"),1);assert.equal(E('GameEquipment.ids.length'),before+1);assert.equal(E("bag.filter(s=>s?.type==='equipment_case').length"),1);assert.equal(E("V09Craft.collect('craft_bench')"),0);assert.equal(E("V09Craft.start('craft_bench','hmg016',1)"),false);save();});
test('legacy_stored_turret_migrates_without_loss_with_full_backpack',()=>{const old=setup('qa/stage-h-base/index.html');old.eval("restoreGameProgress(GameNewGame.create());GameStory.request('finish_intro',{outcome:'skipped'});bag=[];addItem('hmg016',1);bag[0].turretData.ammo=41;bag[0].turretData.level=2;storageChests[0].items=[bag[0]];bag=[];addItem('iron',99999)");const raw=JSON.parse(old.eval('JSON.stringify(captureGameProgress())'));r.context.fullOld=raw;const d=J('decodeGameProgress(JSON.stringify(fullOld))');const id=raw.storage[0].items[0].turretData.id;assert.ok(d.carry0353.legacyOverflow.includes(id));assert.equal(d.equipment032.instances.find(r=>r.id===id).state.settings.ammo,41);assert.deepEqual(d.bag,raw.bag);E('restoreGameProgress(decodeGameProgress(JSON.stringify(fullOld)))');save();});
test('no_console_errors',()=>assert.deepEqual(r.errors,[]));
const report={version:require('../package.json').version,runtimeSha256:crypto.createHash('sha256').update(fs.readFileSync('js/game.js')).digest('hex'),passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks,limitations:['UI uses modeled DOM; native Canvas checks are separate. Physical PC/mobile/Telegram acceptance remains manual.']};fs.writeFileSync('qa/results/stage-h.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,failed:report.failed,failures:checks.filter(c=>c.status==='FAIL')}));if(report.failed)process.exitCode=1;
