const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
process.chdir(path.resolve(__dirname,'..'));process.env.LAST_BASE_TEST_LANGUAGE='ru';process.env.LAST_BASE_ASSETS=process.cwd();
const {setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),J=s=>JSON.parse(E('JSON.stringify('+s+')')),checks=[],boundaries=[];
const test=(id,fn)=>{try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack});}};
function clean(){E("for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);menuOpen=false;playerDead=false;document.hidden=false;GameFlow.resume();stopControls(true);el('fade').classList.remove('show');");}
function core(){clean();E("scene='bunker';player.x=1210;player.y=680;");}
function power(){E("V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=1;for(const d of Object.values(V09Power.devices))d.enabled=d.id===GameCampaign.powerId;");}
function reset(resources=false){E('restoreGameProgress(GameNewGame.create())');core();power();if(resources)E("bag=[];for(const c of storageChests)c.items=[];for(const t of ['wood','iron','copper','parts','concrete','stone','fuel','advanced_parts'])addItem(t,200)");}
const request=(action,payload)=>J(`GameResearch.request(${JSON.stringify(action)},${JSON.stringify(payload)})`);
function accept(id){const a=request('obtain',{sourceId:id});assert.equal(a.ok,true,JSON.stringify(a));const b=request('submit',{sourceId:id});assert.equal(b.ok,true,JSON.stringify(b));return b;}
function research(id){const a=request('research',{researchId:id});assert.equal(a.ok,true,JSON.stringify(a));return a;}
function boundary(id){const d=J('captureGameProgress()');r.context.saved=d;E('restoreGameProgress(decodeGameProgress(JSON.stringify(saved)))');assert.deepEqual(J('GameResearch.capture()'),d.research036);assert.deepEqual(J('GameEquipment.capture()'),d.equipment032.instances);assert.deepEqual(J('captureGameProgress().carry0353'),d.carry0353);boundaries.push(id);clean();return d;}
function near(id){r.context.nearId=id;assert.equal(E(`(()=>{const rec=V018Build.record(nearId),instance=GameEquipment.get(nearId),b=rec?.object||GameFootprints.body(nearId);scene=rec?.scene||instance?.transform.scene||'bunker';for(const p of [{x:b.x+b.w/2,y:b.y+b.h+22},{x:b.x+b.w/2,y:b.y-22},{x:b.x-22,y:b.y+b.h/2},{x:b.x+b.w+22,y:b.y+b.h/2}]){Object.assign(player,p);if(!worldCollision(p.x,p.y,player.radius,scene)&&(instance?GameEquipmentRuntime.access(GameActors.local,instance):GameRecovery.access(GameActors.local,GameRecovery.instance(nearId))))return true;}return false;})()`),true,'approach '+id);}
function craft(type='utility_workbench'){core();const a=J(`GamePlacement.request('${type}','craft')`);assert.equal(a.ok,true,JSON.stringify(a));return a.instanceId;}
function place(id,x=1870,y=450,turn=0){r.context.objectId=id;const a=J(`GamePlacement.request(objectId,'place',GamePlacement.centered(GameEquipment.get(objectId).typeId,'reserve_l1',${x},${y},${turn}))`);assert.equal(a.ok,true,JSON.stringify(a));}
function equipment(id,action,p={}){return J(`GameEquipmentRuntime.request('${id}','${action}',${JSON.stringify(p)})`);}
function tool(id,type){near(id);assert.equal(equipment(id,'start',{recipe:type,batches:1}).ok,true);E('for(let n=0;n<31;n++)V09Craft.tick(100)');assert.equal(equipment(id,'collect').ok,true);assert.equal(E(`bagCount('${type}')`),1);}
function seedPure(){E(`window.researchWorld={'base.core_powered':true,'base.drone_station':true,'campaign.chapter_one_complete':true};window.researchActors={'player:1':{id:'player:1'},'player:2':{id:'player:2'}};window.researchPermission=true;window.researchReach=true;window.rd=ResearchDomain.create(ResearchDefinitions,{coreId:'core:test',facts:()=>researchWorld,actor:id=>researchActors[id],authorized:()=>researchPermission,access:()=>({available:researchReach&&researchWorld['base.core_powered'],reason:'campaign.reason.power'})});`);}
function pure(action,payload,actor='player:1',extra={}){const command={actorId:actor,instanceId:'core:test',action,payload,expectedRevision:E('rd.revision'),requestId:'test:'+E('rd.revision'),...extra};r.context.command=command;return J('rd.execute(command)');}

test('baseline.authoritative_0353_immutable',()=>assert.equal(crypto.createHash('sha256').update(fs.readFileSync('qa/stage-e-base/js/game.js')).digest('hex'),'ab1eb8124249f52ae9c8c8e2f30e2bacde7bfe68af99234c8d1e9486eac37505'));
test('new_game.no_research_grants_and_revision6_retained',()=>{reset();const d=J('captureGameProgress()');assert.equal(d.saveVersion,E('SaveFormat.version'));assert.equal(d.campaign031.contentRevision,6);assert.equal(d.research036.data,0);assert.deepEqual(d.research036.completed,[]);assert.deepEqual(d.research036.blueprints,[]);assert.deepEqual(d.research036.legacyEntitlements,[]);assert.ok(![...d.bag,...d.quick013.items].some(s=>s&&['axe','hammer','pickaxe'].includes(s.type)));boundary('fresh');});
test('sources.held_actor_packet_then_submission_blueprint_once',()=>{reset();assert.equal(request('obtain',{sourceId:'source.scout_service'}).ok,true);assert.equal(E('GameResearch.capture().data'),0);assert.equal(E('GameResearch.capture().blueprints.length'),0);boundary('held-packet');core();const a=request('submit',{sourceId:'source.scout_service'});assert.equal(a.ok,true);assert.equal(E('GameResearch.capture().data'),20);assert.deepEqual(J('GameResearch.capture().blueprints'),['blueprint.scout_service']);const before=J('GameResearch.capture()');assert.equal(request('submit',{sourceId:'source.scout_service'}).ok,false);assert.equal(request('obtain',{sourceId:'source.scout_service'}).ok,false);assert.deepEqual(J('GameResearch.capture()'),before);boundary('submitted-packet');});
test('sources.full_bag_never_loses_or_duplicates_progression',()=>{reset();E("bag=Array.from({length:BAG_SLOTS},()=>({type:'wood',qty:100}))");const bag=J('bag');accept('source.scout_service');research('research.scout_service');assert.deepEqual(J('bag'),bag);assert.equal(E('GameResearch.capture().data'),5);assert.equal(E('GameResearch.capture().blueprints.length'),1);boundary('full-bag-unlock');});
test('availability.data_blueprint_prerequisite_rejected_without_debit',()=>{reset();const before=J('GameResearch.capture()');assert.equal(request('research',{researchId:'research.station_fabrication'}).reason,'research.error.data');assert.deepEqual(J('GameResearch.capture()'),before);accept('source.core_diagnostics');assert.equal(request('research',{researchId:'research.scout_service'}).reason,'research.error.blueprint');research('research.station_fabrication');accept('source.scout_service');const middle=J('GameResearch.capture()');assert.equal(request('research',{researchId:'research.precision_weapons'}).reason,'research.error.blueprint');assert.equal(request('obtain',{sourceId:'source.recovery_report'}).reason,'research.error.chapter_one');assert.deepEqual(J('GameResearch.capture()'),middle);});
test('unlock.not_free_item_and_duplicate_after_load',()=>{reset();accept('source.core_diagnostics');const before=J('({bag,storage:storageChests,equipment:GameEquipment.capture()})');const revision=E('GameResearch.revision');r.context.command={actorId:'player:1',instanceId:'command_core_l1',action:'research',payload:{researchId:'research.station_fabrication'},expectedRevision:revision,requestId:'permanent-unlock'};assert.equal(J('GameResearch.execute(command)').ok,true);assert.deepEqual(J('({bag,storage:storageChests,equipment:GameEquipment.capture()})'),before);assert.equal(E('GameResearch.capture().data'),8);assert.equal(J('GameResearch.execute(command)').replayed,true);boundary('unlock-receipt');assert.equal(J('GameResearch.execute(command)').replayed,true);core();assert.equal(request('research',{researchId:'research.station_fabrication'}).reason,'research.completed');assert.equal(E('GameResearch.capture().data'),8);});
test('availability.locked_buildable_direct_command_and_recipe',()=>{reset(true);const before=J('({bag,storage:storageChests,equipment:GameEquipment.capture()})');assert.equal(J("GamePlacement.request('furnace','craft')").reason,'researchLocked');assert.deepEqual(J('({bag,storage:storageChests,equipment:GameEquipment.capture()})'),before);near('craft_bench');E("V09Power.devices.craft_bench.enabled=true");const materials=J('bag');assert.equal(equipment('craft_bench','start',{recipe:'rifle_m4',batches:1}).ok,false);assert.equal(E("V09Craft.start('craft_bench','rifle_m4',1)"),false);assert.deepEqual(J('bag'),materials);assert.equal(E("GameAvailability.recipe(V09Craft.recipes.rifle_ak74).available"),true);});
test('research_full_building_cycle_no_new_craft_route',()=>{reset(true);accept('source.core_diagnostics');accept('source.scout_service');research('research.scout_service');research('research.station_fabrication');const before=E('GameEquipment.ids.length'),id=craft('furnace');assert.equal(E('GameEquipment.ids.length'),before+1);assert.equal(E(`bag.filter(s=>s?.instanceId==='${id}').length`),1);boundary('researched-buildable-carried');place(id,1930,450,1);near(id);E(`V09Power.devices['${id}'].enabled=true`);assert.equal(equipment(id,'start',{recipe:'concrete',batches:1}).ok,true);E('for(let n=0;n<21;n++){V09Power.tick(.1);V09Craft.tick(100)}');assert.equal(equipment(id,'collect').ok,true);boundary('researched-buildable-used');near(id);const ticket=J(`GamePlacement.beginPickup('${id}')`);assert.equal(ticket.ok,true);r.context.ticket=ticket;r.advance(3001);assert.equal(J("GamePlacement.request(ticket.id,'pack',null,ticket.token)").ok,true);boundary('researched-buildable-picked-up');place(id,1930,660,3);boundary('researched-buildable-replaced');assert.equal(E('GameEquipment.ids.length'),before+1);});
test('drone_existing_effects_gated_then_paid_upgrade_only',()=>{reset(true);assert.equal(E("GameAvailability.droneModule('body').available"),false);assert.equal(E("GameAvailability.droneModule('engine').available"),true);const modules=J('V014Robots.state.modules');accept('source.scout_service');research('research.scout_service');assert.deepEqual(J('V014Robots.state.modules'),modules);assert.equal(E('V014Robots.combat.capacity'),600);assert.equal(E('V014Robots.pack()'),true);near('upgrade0161');E('V09Power.devices.upgrade0161.enabled=true');const i=E('bag.findIndex(V014Robots.ownsToken)');assert.equal(equipment('upgrade0161','deposit',{from:'bag',index:i}).ok,true);const iron=E("V010Inventory.materialCount('iron')");assert.equal(equipment('upgrade0161','upgrade',{key:'body'}).ok,true);assert.equal(E('V014Robots.state.modules.body'),modules.body+1);assert.ok(E("V010Inventory.materialCount('iron')")<iron);boundary('paid-drone-upgrade');});
test('basic_chapter1_recipes_never_research_gated',()=>{reset();for(const id of ['hammer','axe','pickaxe','concrete','iron','copper','ammo','flashlight','head_mount'])assert.equal(E(`GameAvailability.recipe(V09Craft.recipes['${id}']).available`),true,id);for(const type of ['utility_workbench','storage_crate'])assert.equal(E(`GameAvailability.buildable('${type}').available`),true,type);assert.equal(E('GameGathering.stats({type:"pickaxe",level:5}).yield'),40);});
for(const reason of ['distance','power','dead','paused','foreign','target','unknown','payload'])test('authority.reject_'+reason,()=>{reset();accept('source.core_diagnostics');const snapshot=J('GameResearch.capture()'),command={actorId:'player:1',instanceId:'command_core_l1',action:'research',payload:{researchId:'research.station_fabrication'},expectedRevision:E('GameResearch.revision'),requestId:'invalid-'+reason};if(reason==='distance')E("scene='surface'");if(reason==='power')E('V09Power.running=false;V010Energy.battery.charge=0');if(reason==='dead')E('playerDead=true');if(reason==='paused')E("GameFlow.pause('qa')");if(reason==='foreign')command.actorId='player:other';if(reason==='target')command.instanceId='tank';if(reason==='unknown')command.payload.researchId='research.missing';if(reason==='payload')command.payload.free=true;r.context.command=command;assert.equal(J('GameResearch.execute(command)').ok,false);assert.deepEqual(J('GameResearch.capture()'),snapshot);E("GameFlow.resume('qa')");clean();});
test('authority.pure_two_actors_shared_progress_personal_packet',()=>{seedPure();assert.equal(pure('obtain',{sourceId:'source.scout_service'}).ok,true);assert.equal(pure('submit',{sourceId:'source.scout_service'},'player:2').reason,'research.error.packet_owner');assert.equal(pure('submit',{sourceId:'source.scout_service'}).ok,true);assert.equal(pure('research',{researchId:'research.scout_service'},'player:2').ok,true);assert.equal(E("rd.hasTechnology('technology.scout_service')"),true);assert.equal(E('rd.capture().data'),5);});
test('authority.stale_and_conflicting_request_no_double_spend',()=>{seedPure();assert.equal(pure('obtain',{sourceId:'source.core_diagnostics'}).ok,true);assert.equal(pure('submit',{sourceId:'source.core_diagnostics'}).ok,true);const revision=E('rd.revision'),id='same';assert.equal(pure('research',{researchId:'research.station_fabrication'},'player:1',{expectedRevision:revision,requestId:id}).ok,true);const before=J('rd.capture()');assert.equal(pure('research',{researchId:'research.station_fabrication'},'player:2',{expectedRevision:revision,requestId:'other'}).reason,'stale_revision');assert.equal(pure('research',{researchId:'research.workshop_efficiency'},'player:1',{expectedRevision:revision,requestId:id}).reason,'request_conflict');assert.deepEqual(J('rd.capture()'),before);});
test('authority.permission_and_power_rechecked_after_preview',()=>{seedPure();pure('obtain',{sourceId:'source.core_diagnostics'});pure('submit',{sourceId:'source.core_diagnostics'});assert.equal(E("rd.availability('research.station_fabrication').available"),true);E('researchPermission=false');assert.equal(pure('research',{researchId:'research.station_fabrication'}).reason,'actor_denied');E("researchPermission=true;researchWorld['base.core_powered']=false");assert.equal(pure('research',{researchId:'research.station_fabrication'}).reason,'campaign.reason.power');assert.equal(E('rd.capture().data'),20);});
test('definitions.AND_OR_and_no_unreachable_or_cyclic_content',()=>{seedPure();E("window.df=JSON.parse(JSON.stringify(ResearchDefinitions));df.research[0].requires={all:[{fact:'base.core_powered',equals:true},{any:[{fact:'base.drone_station',equals:true},{fact:'legacy.precision_blueprint',equals:true}]}]}");assert.equal(E('ResearchDomain.validateDefinitions(df)'),true);for(const edit of ["df.research[0].requires={fact:'unknown',equals:true}","df.research[0].requires={fact:'research.station_fabrication',equals:true}","df.research[0].blueprints=['blueprint.missing']","df.research[0].technologies=['technology.missing']","df.research[1].id=df.research[0].id","df.sources=df.sources.filter(s=>!s.blueprints.includes('blueprint.scout_service'))"]){E('df=JSON.parse(JSON.stringify(ResearchDefinitions))');E(edit);assert.throws(()=>E('ResearchDomain.validateDefinitions(df)'),edit);}});
test('save.validation_conservation_and_receipts_atomic',()=>{reset();accept('source.core_diagnostics');research('research.station_fabrication');const base=J('captureGameProgress()'),before=J('captureGameProgress()');for(const mutate of [d=>delete d.research036,d=>d.research036.data++,d=>d.research036.completed.push('research.unknown'),d=>d.research036.completed.push('research.station_fabrication'),d=>d.research036.blueprints.push('blueprint.scout_service'),d=>d.research036.technologies=[],d=>d.research036.unlocks.buildables=[],d=>d.research036.legacyEntitlements.push('technology.scout_service'),d=>d.research036.packets[0].actorId='',d=>d.research036.commands.receipts=[],d=>d.research036.contentRevision++,d=>d.research036.schema++,d=>d.research036.extra=true]){const bad=structuredClone(base);mutate(bad);r.context.bad=bad;assert.throws(()=>E('restoreGameProgress(bad)'));assert.deepEqual(J('captureGameProgress()'),before);}});
test('save.capture_is_pure_and_new_game_resets_only_research',()=>{reset();accept('source.scout_service');research('research.scout_service');const current=J('GameResearch.capture()');for(let n=0;n<50;n++)E('GameResearch.capture();GameResearch.facts()');assert.deepEqual(J('GameResearch.capture()'),current);E('restoreGameProgress(GameNewGame.create())');assert.equal(E('GameResearch.capture().data'),0);assert.deepEqual(J('GameResearch.capture().completed'),[]);assert.deepEqual(J('GameResearch.capture().packets'),[]);});

let legacySave;
test('migration.0353_preserves_every_existing_owner_and_paid_jobs',()=>{const old=setup('qa/stage-e-base/index.html');old.eval("restoreGameProgress(GameNewGame.create());menuOpen=false;GameFlow.resume();scene='bunker';player.x=1210;player.y=680;bag=[];for(const c of storageChests)c.items=[];for(const t of ['wood','iron','parts','concrete','copper'])addItem(t,200);GamePlacement.request('utility_workbench','craft');GamePlacement.rename('reserve_l1',{preset:null,custom:'Ali Workshop'});V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=1;V09Craft.start('craft_bench','rifle_m4',2);V09Power.devices.light_workshop.enabled=false;addItem('pickaxe',1);V010Combat.ensure(bag.find(s=>s?.type==='pickaxe'));bag.find(s=>s?.type==='pickaxe').level=5;V014Robots.state.modules.weapon=3;");legacySave=JSON.parse(old.eval('JSON.stringify(captureGameProgress())'));r.context.legacy=legacySave;const before=J('captureGameProgress()'),decoded=J('decodeGameProgress(JSON.stringify(legacy))');assert.deepEqual(J('captureGameProgress()'),before);assert.equal(decoded.research036.profile,'legacy');assert.equal(decoded.research036.data,0);assert.deepEqual(decoded.research036.completed,[]);assert.deepEqual(decoded.research036.blueprints,[]);for(const key of Object.keys(legacySave))if(!['gameVersion','saveVersion'].includes(key))assert.deepEqual(require('./stage-h-contract.cjs').project(decoded)[key],legacySave[key],key);E('restoreGameProgress(decoded=decodeGameProgress(JSON.stringify(legacy)))');assert.equal(E("GameAvailability.recipe(V09Craft.recipes.rifle_m4).available"),true);assert.equal(E("GameAvailability.buildable('furnace').available"),true);assert.equal(E("GameAvailability.droneModule('weapon').available"),true);assert.equal(E("V010Progression.isUnlocked('workshop_efficiency')"),false);boundary('migrated-0353-all-owners');});
test('migration.entitlement_prerequisites_do_not_softlock_research',()=>{r.context.legacy=legacySave;E('restoreGameProgress(decodeGameProgress(JSON.stringify(legacy)))');core();power();accept('source.core_diagnostics');assert.equal(request('research',{researchId:'research.station_fabrication'}).reason,'research.legacyAvailable');research('research.workshop_efficiency');assert.equal(E("V010Progression.isUnlocked('workshop_efficiency')"),true);assert.equal(E('V09Craft.craftQueue.upgrades.workshop'),false);boundary('legacy-new-research');});
test('legacy_four_TECH_preserved_and_single_availability_policy',()=>{reset();for(const id of ['precision_blueprint','elite_weapon','workshop_efficiency','tools_upgrade']){E(`V010Progression.unlock('${id}',true)`);assert.equal(E(`V010Progression.isLegacyUnlocked('${id}')`),true);assert.equal(E(`GameAvailability.legacy('${id}')`),true);}assert.equal(E('GameAvailability.recipe(V09Craft.recipes.rifle_m4).available'),true);boundary('legacy-tech-rights');});

for(const mode of ['PC','MOBILE'])for(const lang of ['ru','en'])test('UI.physical_core_localized_and_fixed_shell_'+mode+'_'+lang,()=>{reset();E(`GameInput.setMode('${mode}');I18n.setLanguage('${lang}');window.innerWidth=${mode==='MOBILE'?390:1280};window.innerHeight=${mode==='MOBILE'?844:800};CommandCoreUI.show('research');CommandCoreUI.tick()`);const section=r.doc.getElementById('coreSection_research'),coreEl=r.doc.getElementById('commandCoreOverlay');assert.equal(section.hidden,false);assert.equal(coreEl.querySelector('.v09Panel').style.height||'','');let text=section.textContent;assert.ok(!/(?:research|source|technology|blueprint)\.[a-z_]+|undefined|NaN/.test(text),text);if(lang==='en'){assert.ok(!/[А-Яа-яЁё]/.test(text),text);for(const el of section.querySelectorAll('*'))for(const key of ['title','placeholder','aria-label','alt'])assert.ok(!/[А-Яа-яЁё]/.test(el.getAttribute(key)||''),key+': '+el.getAttribute(key));}section.querySelector('[data-research-page="sources"]').click();const source=section.querySelector('[data-research-source="source.core_diagnostics"]');source.querySelector('button').click();section.querySelector('[data-research-source="source.core_diagnostics"]').querySelector('button').click();assert.equal(E('GameResearch.capture().data'),20);section.querySelector('[data-research-page="projects"]').click();const project=section.querySelector('[data-research-id="research.station_fabrication"]');project.querySelector('[data-research-action="research"]').click();assert.equal(E("GameResearch.hasTechnology('technology.station_fabrication')"),true);E("closeOverlay(el('commandCoreOverlay'));CommandCoreUI.show()");assert.equal(section.hidden,false);const styles=r.doc.head.textContent;assert.ok(styles.includes('height:min(760px'));assert.ok(styles.includes('overflow-x:auto'));assert.ok(styles.includes('--tg-content-safe-area-inset-top'));boundary('UI-'+mode+'-'+lang);});
test('UI.route_detail_restores_and_resets_on_departure_load',()=>{reset();E("CommandCoreUI.show('research')");let section=r.doc.getElementById('coreSection_research');section.querySelector('[data-research-id="research.scout_service"]').querySelector('.researchDetailsButton').click();assert.equal(section.querySelectorAll('[data-research-id]').length,1);E("closeOverlay(el('commandCoreOverlay'));CommandCoreUI.show()");assert.equal(section.querySelectorAll('[data-research-id]').length,1);E("scene='surface';CommandCoreUI.tick();scene='bunker';player.x=1210;player.y=680;CommandCoreUI.show()");assert.equal(section.hidden,true);E("CommandCoreUI.show('research')");assert.equal(section.querySelectorAll('[data-research-id]').length,4);boundary('UI-route-transient');core();E('CommandCoreUI.show()');assert.equal(section.hidden,true);});
test('UI.remote_and_tracker_never_expose_research_commands',()=>{reset();E("addItem('remote',1);GameBaseControlUI.show()");assert.equal(r.doc.getElementById('v09PowerOverlay').querySelector('[data-research-action]'),null);E('CommandCoreUI.showJournal()');assert.equal(r.doc.getElementById('campaignJournalOverlay').querySelector('[data-research-action]'),null);E("scene='surface';player.x=1000;player.y=800");assert.equal(E("CommandCoreUI.show('research')"),false);assert.equal(request('obtain',{sourceId:'source.core_diagnostics'}).ok,false);});
test('UI.idle_research_does_not_rebuild_graph_or_modify_progress',()=>{reset();E("CommandCoreUI.show('research');CommandCoreUI.tick()");const renders=E('GameResearchUI.metrics().renders'),before=J('GameResearch.capture()');E('for(let n=0;n<120;n++)CommandCoreUI.tick()');assert.equal(E('GameResearchUI.metrics().renders'),renders);assert.deepEqual(J('GameResearch.capture()'),before);});

test('chapter1_real_new_game_then_blueprint_research_M4_craft_load',()=>{
 E('restoreGameProgress(GameNewGame.create())');core();near('chest0');E("openStorage(0);V010Inventory.bulk('take')");clean();const workbench=craft();place(workbench);for(const name of ['hammer','pickaxe','axe'])tool(workbench,name);boundary('chapter-tools-no-research');
 E("scene='surface';V013Inventory.equip('pickaxe');window.mineTarget=V09World.ores.find(o=>o.type==='stone');player.x=mineTarget.x+mineTarget.r+25;player.y=mineTarget.y;executeInteraction(interactionObjects('surface').find(o=>o.id===mineTarget.id))");assert.ok(E('V09World.miningState()'));const stone=E("bagCount('stone')"),impact=E("GameGathering.stats(V010Inventory.selectedItem('pickaxe')).duration*GameGathering.phase('pickaxe')");r.advance(Math.ceil(impact));E('V09World.tickMining();GameCampaign.refresh(true)');assert.equal(E("bagCount('stone')"),stone+15);clean();
 near('tank');assert.equal(E("GameRecovery.request('tank','refuel',{units:4}).ok"),true);near('generator');assert.equal(E("GameRecovery.request('generator','generator',{value:true}).ok"),true);core();E('CommandCoreUI.show()');clean();near('furnace');assert.equal(equipment('furnace','start',{recipe:'concrete',batches:5}).ok,true);E('for(let n=0;n<101;n++){V09Power.tick(.1);V09Craft.tick(100)}');assert.equal(equipment('furnace','collect').value,5);
 for(const id of J('ChapterOnePreset.criticalRepairs')){E("V013Inventory.equip('hammer')");near(id);assert.equal(E(`GameRecovery.request('${id}','repair').ok`),true);E('V018Build.repairStep(20);V018Build.stop()');}E('GameCampaign.refresh(true)');assert.equal(E('GameCampaign.view().objectives.c1_repairs.done'),true);boundary('chapter-functional-repairs');
 E("scene='bunker';player.x=1120;player.y=-120");for(const [day,minute]of [[1,1201],[2,361]]){let n=0;while(E('WorldClock.day*1440+WorldClock.minute')<day*1440+minute-1e-6&&n++<1600){r.advance(1000);E('V016Lighting.tick(1000);for(let i=0;i<10;i++)V09Power.tick(.1);GameCampaign.tick(1000)');}assert.ok(n<1600);}
 assert.equal(E('GameCampaign.view().ready'),true);core();assert.equal(E("GameCampaign.execute({type:'ADVANCE_CHAPTER',actorId:'player:1',targetId:'command_core_l1',chapterId:'chapter_1',expectedRevision:GameCampaign.view().revision,requestId:'stage-e-chapter-finish'}).ok"),true);assert.equal(E('GameResearch.capture().completed.length'),0);boundary('chapter-finished-without-research');core();power();
 accept('source.core_diagnostics');research('research.station_fabrication');accept('source.recovery_report');boundary('precision-blueprint-discovered');core();research('research.precision_weapons');boundary('precision-unlocked');E("for(const t of ['iron','copper','parts','wood'])addItem(t,100)");near('craft_bench');E('V09Power.devices.craft_bench.enabled=true');const before=E("V010Inventory.materialCount('iron')");assert.equal(equipment('craft_bench','start',{recipe:'rifle_m4',batches:1}).ok,true);assert.equal(E("V010Inventory.materialCount('iron')"),before-18);boundary('M4-paid-job');near('craft_bench');E('for(let n=0;n<601;n++){V09Power.tick(.1);V09Craft.tick(100)}');assert.equal(equipment('craft_bench','collect').value,1);E("V013Inventory.equip('rifle_m4')");assert.equal(E('heldItem()'),'rifle_m4');boundary('M4-equipped');assert.equal(E("GameResearch.capture().blueprints.includes('blueprint.precision_weapons')"),true);
});

test('source.held_packet_survives_station_pack_and_resume',()=>{reset();assert.equal(request('obtain',{sourceId:'source.scout_service'}).ok,true);assert.equal(E('V014Robots.pack()'),true);near('robots014_dock');const hold=J("GamePlacement.beginPickup('robots014_dock')");assert.equal(hold.ok,true,JSON.stringify(hold));r.context.hold=hold;r.advance(3001);assert.equal(J("GamePlacement.request(hold.id,'pack',null,hold.token)").ok,true);boundary('source-station-carried');core();assert.equal(request('submit',{sourceId:'source.scout_service'}).ok,true);assert.equal(request('research',{researchId:'research.scout_service'}).reason,'research.error.drone_station');const rec=J("GameEquipment.get('robots014_dock')");assert.equal(J(`GamePlacement.request('robots014_dock','place',${JSON.stringify(rec.transform)})`).ok,true);core();research('research.scout_service');boundary('source-station-reinstalled');});
test('authority.malformed_and_cyclic_payload_rejected_atomically',()=>{seedPure();const before=J('rd.capture()');for(const body of ['null','[]','{researchId:4}','{researchId:{}}','(()=>{const p={};p.sourceId=p;return p})()']){E(`command={actorId:'player:1',instanceId:'core:test',action:'research',payload:${body},expectedRevision:0,requestId:'invalid'}`);assert.equal(J('rd.execute(command)').ok,false);assert.deepEqual(J('rd.capture()'),before);}});
test('authority.receipt_eviction_cannot_reclaim_data_after_load',()=>{seedPure();E("df=JSON.parse(JSON.stringify(ResearchDefinitions));for(let n=0;n<70;n++)df.sources.push({id:'source.test_'+n,data:1,blueprints:[],requires:{fact:'base.core_powered',equals:true}});rd=ResearchDomain.create(df,{coreId:'core:test',facts:()=>researchWorld,actor:id=>researchActors[id],authorized:()=>true,access:()=>({available:true})})");for(let n=0;n<70;n++){assert.equal(pure('obtain',{sourceId:'source.test_'+n}).ok,true);assert.equal(pure('submit',{sourceId:'source.test_'+n}).ok,true);}assert.equal(E('rd.capture().commands.receipts.length'),128);const state=J('rd.capture()');r.context.researchSaved=state;E('rd.restore(researchSaved)');assert.equal(pure('obtain',{sourceId:'source.test_0'},'player:1',{requestId:'test:0',expectedRevision:0}).reason,'stale_revision');assert.equal(pure('obtain',{sourceId:'source.test_0'}).reason,'research.error.source_claimed');assert.equal(pure('submit',{sourceId:'source.test_0'}).ok,false);assert.deepEqual(J('rd.capture()'),state);});
test('save.corrupt_receipt_payload_result_and_revision_rejected',()=>{reset();accept('source.core_diagnostics');research('research.station_fabrication');const base=J('captureGameProgress()');for(const edit of [s=>s.commands.receipts[1].result.data++,s=>s.commands.receipts[1].result.blueprints.push('blueprint.scout_service'),s=>s.commands.receipts[0].result.status='submitted',s=>{const sig=JSON.parse(s.commands.receipts[2].signature);sig[2].extra=true;s.commands.receipts[2].signature=JSON.stringify(sig)},s=>s.commands.extra=true]){const bad=structuredClone(base);edit(bad.research036);r.context.bad=bad;assert.throws(()=>E('restoreGameProgress(bad)'));assert.deepEqual(J('captureGameProgress()'),base);}});

test('runtime.no_console_errors',()=>assert.deepEqual(r.errors,[]));
const report={version:require('../package.json').version,runtimeSha256:crypto.createHash('sha256').update(fs.readFileSync('js/game.js')).digest('hex'),passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,boundaries,checks,limitations:['Modeled DOM and native Canvas2D; no native browser/Telegram/phone claim.','Full Chapter 1 uses real tool impact, crafting, repair and campaign commands; movement/time are controlled by the harness. Additional M4 materials are test supplies.']};
fs.writeFileSync('qa/results/stage-e.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,failed:report.failed,failures:checks.filter(c=>c.status==='FAIL')},null,2));if(report.failed)process.exitCode=1;
