// Real bundled runtime + deterministic DOM/audio ports. Not browser visual QA.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
process.chdir(path.resolve(__dirname,'..'));process.env.LAST_BASE_TEST_LANGUAGE='ru';process.env.LAST_BASE_ASSETS=process.cwd();
const {setup}=require('./runtime.cjs'),r=setup('index.html',{}, {mainMenu:true,storyIntro:true}),E=s=>r.eval(s),J=s=>JSON.parse(E('JSON.stringify('+s+')')),checks=[];
function test(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack});}}
function reset(){E("StoryPlayer.cancel();restoreGameProgress(GameNewGame.create());for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);menuOpen=false;for(const reason of GameFlow.reasons)GameFlow.resume(reason);playerDead=false;document.hidden=false;");}
function core(){E("scene='bunker';player.x=1210;player.y=680;V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=1;for(const d of Object.values(V09Power.devices))d.enabled=d.id===GameCampaign.powerId;");}
function boundary(){E('window.boundarySave=captureGameProgress();restoreGameProgress(decodeGameProgress(JSON.stringify(boundarySave)))');assert.deepEqual(J('GameStory.capture()'),J('boundarySave.story037'));}
function seed(){E("window.sf={'story.context':true,'story.core_visited':false,'story.research_count':0,'story.chapter_one_complete':false};window.sa={'player:1':{id:'player:1'},'player:2':{id:'player:2'}};window.permitted=true;window.reached=true;window.sd=StoryDomain.create(StoryDefinitions,{coreId:'core:test',facts:()=>sf,actor:id=>sa[id],authorized:()=>permitted,access:()=>({available:reached,reason:'distance'})});sd.restore(sd.fresh('new','player:1',sf),sf)");}
function cmd(action,payload,actorId='player:1',extra={}){r.context.sc={actorId,instanceId:'core:test',action,payload,expectedRevision:E('sd.revision'),requestId:'test:'+E('sd.revision'),...extra};return J('sd.execute(sc)');}
const runIntro=()=>E('for(let t=0;t<=21500;t+=100)StoryPlayer.tick(t)');

test('baseline.exact_accepted_0361',()=>assert.equal(crypto.createHash('sha256').update(fs.readFileSync('qa/stage-f-base/js/game.js')).digest('hex'),'016d446011c4dfe3b6939fde050e2d1b27dc0614dea6316b8dff250edb86f3f4'));
test('boot.no_intro_or_world_start_before_new_game',()=>{assert.equal(E('StoryPlayer.active'),false);assert.equal(E('MainMenu.active'),true);assert.equal(r.scheduler.rafRequests,0);assert.equal(E('GameStory.view().intro'),'legacy');});
test('new_game.selected_slot_starts_intro_and_existing_chapter',()=>{assert.equal(E('V09Saves.newGame(1)'),true);assert.equal(E('StoryPlayer.active'),true);assert.equal(E('GameFlow.paused'),true);assert.equal(E('MainMenu.active'),false);assert.equal(r.scheduler.rafRequests,1);assert.equal(E('GameStory.view().intro'),'pending');assert.equal(E('captureGameProgress().campaign031.contentRevision'),6);assert.equal(E('GameResearch.capture().data'),0);assert.equal(E('scene'),'bunker');const d=J('captureGameProgress()');assert.ok(![...d.bag,...d.quick013.items].some(s=>s&&['hammer','axe','pickaxe'].includes(s.type)));});
test('intro.world_resources_and_time_remain_frozen',()=>{const before=J('captureGameProgress()');E('for(let t=100;t<1100;t+=100)gameLoop(t)');const after=J('captureGameProgress()');for(const key of Object.keys(before))if(!['savedAt'].includes(key))assert.deepEqual(after[key],before[key],key);});
test('intro.pause_resume_and_visibility_do_not_fast_forward',()=>{E('StoryPlayer.pause()');const time=E('StoryPlayer.inspect().elapsedMs');E('StoryPlayer.tick(10000);StoryPlayer.tick(10200)');assert.equal(E('StoryPlayer.inspect().elapsedMs'),time);E('document.hidden=true');r.emit('visibilitychange',r.doc);E('StoryPlayer.tick(12000);document.hidden=false');r.emit('visibilitychange',r.doc);E('StoryPlayer.tick(13000)');assert.equal(E('StoryPlayer.inspect().elapsedMs'),time);E('StoryPlayer.pause();StoryPlayer.tick(13200);StoryPlayer.tick(13400)');assert.equal(E('StoryPlayer.inspect().elapsedMs'),time+200);});
test('intro.button_skip_commits_once_resumes_and_saves',()=>{r.doc.getElementById('storySkip').click();assert.equal(E('StoryPlayer.active'),false);assert.equal(E('GameFlow.paused'),false);assert.equal(E('GameStory.view().intro'),'skipped');const before=J('GameStory.capture()');assert.equal(E('StoryPlayer.skip()'),false);assert.deepEqual(J('GameStory.capture()'),before);boundary();assert.equal(E('StoryPlayer.startIntro()'),false);});
for(const way of ['escape','close','natural'])test('intro.'+way+'_completion',()=>{reset();assert.equal(E('StoryPlayer.startIntro()'),true);if(way==='escape')r.emit('keydown',r.doc.body,{key:'Escape',code:'Escape'});else if(way==='close')r.doc.getElementById('storyOverlay').querySelector('.v09Close').click();else runIntro();assert.equal(E('StoryPlayer.active'),false);assert.equal(E('GameStory.view().intro'),way==='natural'?'completed':'skipped');assert.equal(E('GameFlow.paused'),false);boundary();});
test('intro.skip_preserves_other_pause_reason',()=>{reset();E("GameFlow.pause('qa:independent');StoryPlayer.startIntro();StoryPlayer.skip()");assert.equal(E('GameFlow.paused'),true);assert.ok(J('GameFlow.reasons').includes('qa:independent'));E("GameFlow.resume('qa:independent')");});
test('continue.pending_intro_is_interrupted_not_replayed',()=>{reset();const pending=J('captureGameProgress()'),h=setup('index.html',{'survival_base_v09_slot_2':JSON.stringify(pending)},{mainMenu:true,storyIntro:true});assert.equal(h.eval('MainMenu.continueGame()'),true);assert.equal(h.eval('StoryPlayer.active'),false);assert.equal(h.eval('GameStory.view().intro'),'interrupted');assert.equal(h.eval('GameFlow.paused'),false);assert.deepEqual(h.errors,[]);});
test('load_in_game_cancels_intro_and_settles_pending',()=>{reset();r.storage.set('survival_base_v09_slot_2',JSON.stringify(J('captureGameProgress()')));E('StoryPlayer.startIntro()');assert.equal(E('V09Saves.load(2)'),true);assert.equal(E('StoryPlayer.active'),false);assert.equal(E('GameStory.view().intro'),'interrupted');assert.equal(E('GameFlow.paused'),false);});
test('failed_decode_during_intro_does_not_cancel_live_intro',()=>{reset();E('StoryPlayer.startIntro()');const before=J('GameStory.capture()');assert.throws(()=>E('restoreGameProgress({saveVersion:999})'));assert.equal(E('StoryPlayer.active'),true);assert.deepEqual(J('GameStory.capture()'),before);E('StoryPlayer.skip()');});
let legacy;
test('migration.0361_preserves_every_accepted_owner',()=>{const old=setup('qa/stage-f-base/index.html');old.eval("restoreGameProgress(GameNewGame.create());scene='bunker';player.x=1210;player.y=680;V09Power.running=true;V09Power.fuel=100;V010Energy.battery.charge=1;for(const d of Object.values(V09Power.devices))d.enabled=d.id===GameCampaign.powerId;GameResearch.request('obtain',{sourceId:'source.scout_service'});GameResearch.request('submit',{sourceId:'source.scout_service'});GameResearch.request('research',{researchId:'research.scout_service'});GamePlacement.rename('reserve_l1',{preset:null,custom:'Моя комната'});");legacy=JSON.parse(old.eval('JSON.stringify(captureGameProgress())'));assert.equal(legacy.saveVersion,16);r.context.legacy=legacy;const before=J('captureGameProgress()'),d=J('decodeGameProgress(JSON.stringify(legacy))');assert.deepEqual(J('captureGameProgress()'),before);for(const key of Object.keys(legacy))if(!['gameVersion','saveVersion'].includes(key))assert.deepEqual(d[key],legacy[key],key);assert.equal(d.saveVersion,17);assert.equal(d.story037.players[0].intro,'legacy');assert.deepEqual(d.story037.players[0].read,[]);assert.ok(d.story037.unlocked.includes('log.research_01'));assert.ok(!d.story037.unlocked.includes('log.base_recovered'));E('restoreGameProgress(decodeGameProgress(JSON.stringify(legacy)))');assert.equal(E('StoryPlayer.startIntro()'),false);boundary();});
test('continue.0361_never_auto_plays',()=>{const h=setup('index.html',{'survival_base_v09_slot_1':JSON.stringify(legacy)},{mainMenu:true,storyIntro:true});assert.equal(h.eval('MainMenu.continueGame()'),true);assert.equal(h.eval('StoryPlayer.active'),false);assert.equal(h.eval('GameStory.view().intro'),'legacy');assert.deepEqual(h.errors,[]);});
test('migration.0353_chain_keeps_research_entitlements',()=>{const old=setup('qa/stage-e-base/index.html');r.context.old15=JSON.parse(old.eval('JSON.stringify(captureGameProgress())'));const d=J('decodeGameProgress(JSON.stringify(old15))');assert.equal(d.saveVersion,17);assert.equal(d.research036.profile,'legacy');assert.equal(d.story037.players[0].intro,'legacy');assert.deepEqual(d.story037.players[0].watched,[]);assert.deepEqual(d.research036.completed,[]);});
test('research_first_unlock_is_free_to_read_no_extra_items_data_or_recipe',()=>{reset();core();assert.deepEqual(J('GameStory.view().unlocked'),['log.arrival']);for(const action of ['obtain','submit'])assert.equal(E(`GameResearch.request('${action}',{sourceId:'source.core_diagnostics'}).ok`),true);assert.ok(!J('GameStory.view().unlocked').includes('log.research_01'));assert.equal(E("GameResearch.request('research',{researchId:'research.station_fabrication'}).ok"),true);assert.ok(J('GameStory.view().unlocked').includes('log.research_01'));assert.equal(E('GameResearch.capture().data'),8);const before=J('({bag,equipment:GameEquipment.capture(),research:GameResearch.capture()})');assert.equal(E("GameStory.request('read',{entryId:'log.research_01'}).ok"),true);assert.deepEqual(J('({bag,equipment:GameEquipment.capture(),research:GameResearch.capture()})'),before);boundary();});
test('discovery.monotonic_authoritative_facts',()=>{seed();E("sf['story.core_visited']=true;sd.refresh()");assert.ok(J("sd.view('player:1').unlocked").includes('log.core_restart'));E("sf['story.research_count']=1;sd.refresh();sf['story.chapter_one_complete']=true;sd.refresh()");assert.equal(E("sd.view('player:1').unlocked.length"),4);assert.equal(E('sd.revision'),0);const before=J('sd.capture()');E('sd.refresh()');assert.deepEqual(J('sd.capture()'),before);});
test('authority.shared_unlocks_personal_read_watched_late_join',()=>{seed();E("sf['story.research_count']=1;sd.refresh()");assert.equal(cmd('read',{entryId:'log.research_01'}).ok,true);assert.deepEqual(J("sd.view('player:2').read"),[]);assert.equal(cmd('read',{entryId:'log.research_01'},'player:2').ok,true);assert.equal(cmd('watch',{entryId:'log.arrival'},'player:2').ok,true);assert.deepEqual(J("sd.view('player:1').watched"),[]);assert.equal(E("sd.view('player:2').intro"),'legacy');E('sd.restore(sd.capture(),sf)');});
test('authority.duplicate_after_save_conflict_and_stale',()=>{seed();const c={requestId:'stable',expectedRevision:0};assert.equal(cmd('finish_intro',{outcome:'skipped'},'player:1',c).ok,true);const before=J('sd.capture()');E('sd.restore(sd.capture(),sf)');assert.equal(cmd('finish_intro',{outcome:'skipped'},'player:1',c).replayed,true);assert.equal(cmd('finish_intro',{outcome:'completed'},'player:1',c).reason,'request_conflict');assert.equal(cmd('read',{entryId:'log.arrival'},'player:1',{expectedRevision:0,requestId:'stale'}).reason,'stale_revision');assert.equal(cmd('finish_intro',{outcome:'completed'}).ok,false);assert.deepEqual(J('sd.capture()'),before);});
for(const reason of ['locked','foreign','unauthorized','distance','target','malformed','non_playable'])test('authority.reject_'+reason,()=>{seed();let action='read',payload={entryId:'log.arrival'},actor='player:1',extra={};if(reason==='locked')payload.entryId='log.base_recovered';if(reason==='foreign')actor='player:9';if(reason==='unauthorized')E('permitted=false');if(reason==='distance')E('reached=false');if(reason==='target')extra.instanceId='other';if(reason==='malformed')payload.extra=true;if(reason==='non_playable'){E("sf['story.core_visited']=true;sd.refresh()");action='watch';payload.entryId='log.core_restart';}const before=J('sd.capture()');assert.equal(cmd(action,payload,actor,extra).ok,false);assert.deepEqual(J('sd.capture()'),before);});
for(const reason of ['power','surface','dead','paused'])test('runtime_access_'+reason,()=>{reset();core();if(reason==='power')E('V09Power.running=false;V010Energy.battery.charge=0');if(reason==='surface')E("scene='surface'");if(reason==='dead')E('playerDead=true');if(reason==='paused')E("GameFlow.pause('qa')");const before=J('GameStory.capture()');assert.equal(E("GameStory.request('read',{entryId:'log.arrival'}).ok"),false);assert.equal(E("StoryPlayer.open('log.arrival')"),false);assert.deepEqual(J('GameStory.capture()'),before);});
test('save.strict_validation_atomic_and_no_media_bytes',()=>{reset();core();E("GameStory.request('finish_intro',{outcome:'skipped'});GameStory.request('read',{entryId:'log.arrival'})");const before=J('captureGameProgress()');for(const edit of [d=>delete d.story037,d=>d.story037.schema++,d=>d.story037.contentRevision++,d=>d.story037.extra=true,d=>d.story037.unlocked.push('log.missing'),d=>d.story037.unlocked.push('log.base_recovered'),d=>d.story037.unlocked.push('log.arrival'),d=>d.story037.players[0].read.push('log.research_01'),d=>d.story037.players[0].actorId='equipment:1',d=>d.story037.players[0].intro='pending',d=>d.story037.commands.revision++,d=>d.story037.commands.receipts=[],d=>d.story037.commands.receipts[0].result.outcome='completed',d=>d.story037.commands.receipts[1].signature='[]']){const bad=structuredClone(before);edit(bad);r.context.bad=bad;assert.throws(()=>E('restoreGameProgress(bad)'));assert.deepEqual(J('captureGameProgress()'),before);}assert.ok(JSON.stringify(before.story037).length<2000);boundary();});
test('receipt_window_bounded_and_eviction_does_not_repeat_marks',()=>{seed();E("window.df=JSON.parse(JSON.stringify(StoryDefinitions));for(let n=0;n<140;n++)df.entries.push({...df.entries[1],id:'log.qa_'+n,requires:{fact:'story.context',equals:true}});sd=StoryDomain.create(df,{coreId:'core:test',facts:()=>sf,actor:id=>sa[id],authorized:()=>true,access:()=>({available:true})})");for(let n=0;n<140;n++)assert.equal(cmd('read',{entryId:'log.qa_'+n}).ok,true);assert.equal(E('sd.capture().commands.receipts.length'),128);E('sd.restore(sd.capture(),sf)');const before=J('sd.capture()');assert.equal(cmd('read',{entryId:'log.qa_0'}).ok,false);assert.deepEqual(J('sd.capture()'),before);});
for(const [name,width,height]of [['desktop',1280,800],['portrait',390,844],['small',320,568],['landscape',844,390]])for(const lang of ['ru','en'])test('archive.shared_navigation_'+name+'_'+lang,()=>{reset();core();E(`I18n.setLanguage('${lang}');innerWidth=${width};innerHeight=${height};CommandCoreUI.show('archive');CommandCoreUI.tick()`);const root=r.doc.getElementById('coreSection_archive'),panel=r.doc.getElementById('commandCoreOverlay').querySelector('.v09Panel');assert.equal(r.doc.getElementById('coreTab_archive').hidden,false);assert.equal(root.querySelectorAll('.archiveCard').length,2);const select=root.querySelector('select');select.value='research';select.onchange();E('CommandCoreUI.tick()');assert.equal(root.querySelectorAll('.archiveCard').length,0);r.doc.getElementById('coreBack').click();root.querySelector('[data-archive-open="log.arrival"]').click();E('CommandCoreUI.tick()');assert.ok(root.querySelector('.archiveDocument'));assert.equal(E("GameStory.view().read.includes('log.arrival')"),true);assert.equal(r.doc.getElementById('coreBack').disabled,false);const text=root.textContent;if(lang==='ru')assert.ok(!/[a-zA-Z]{2,}/.test(text.replaceAll('LAST BASE','')),text);else assert.ok(!/[А-Яа-яЁё]/.test(text));assert.ok(!/log\.|story\.|undefined|NaN/.test(text));root.querySelector('[data-archive-play]').click();assert.equal(E('StoryPlayer.active'),true);E('StoryPlayer.skip()');assert.equal(E('GameStory.view().watched.length'),0);assert.strictEqual(r.doc.getElementById('commandCoreOverlay').querySelector('.v09Panel'),panel);r.doc.getElementById('coreBack').click();assert.equal(root.querySelectorAll('.archiveCard').length,2);});
test('archive.replay_completed_personal_watched_saved',()=>{reset();core();E("CommandCoreUI.show('archive');StoryPlayer.open('log.arrival')");runIntro();assert.ok(J('GameStory.view().watched').includes('log.arrival'));assert.equal(E('GameStory.view().intro'),'pending');boundary();});
test('archive.idle_no_DOM_rebuild_no_progress_mutation',()=>{reset();core();E("CommandCoreUI.show('archive');CommandCoreUI.tick()");const builds=E('GameArchiveUI.inspect().builds'),before=J('GameStory.capture()');E('for(let n=0;n<500;n++)CommandCoreUI.tick()');assert.equal(E('GameArchiveUI.inspect().builds'),builds);assert.deepEqual(J('GameStory.capture()'),before);});
test('archive.session_back_and_reset_on_leaving_bunker',()=>{reset();core();E("CommandCoreUI.show('archive')");r.doc.getElementById('coreSection_archive').querySelector('[data-archive-open="log.arrival"]').click();E("closeOverlay(el('commandCoreOverlay'));CommandCoreUI.show()");assert.ok(r.doc.getElementById('coreSection_archive').querySelector('.archiveDocument'));E("scene='surface';CommandCoreUI.tick();scene='bunker';CommandCoreUI.show()");assert.equal(r.doc.getElementById('coreSection_archive').hidden,true);});
test('intro.locales_all_subtitles_and_controls',()=>{for(const lang of ['ru','en']){reset();E(`I18n.setLanguage('${lang}');StoryPlayer.startIntro()`);for(let t=0;t<18000;t+=250){E(`StoryPlayer.tick(${t})`);const text=r.doc.getElementById('storyOverlay').textContent;assert.ok(!/story\.|undefined/.test(text));if(lang==='ru')assert.ok(!/[a-zA-Z]{2,}/.test(text.replaceAll('LAST BASE','')),text);else assert.ok(!/[А-Яа-яЁё]/.test(text));}E('StoryPlayer.skip()');}});
test('definitions.no_generated_or_mandatory_media_and_localized_keys',()=>{const defs=J('StoryDefinitions');assert.equal(defs.entries.length,4);for(const e of defs.entries){if(e.id==='log.arrival')assert.equal(e.media.kind,'video');else assert.equal(e.media,null);for(const key of [e.title,e.summary,...e.body,...e.subtitles.map(c=>c.text)])for(const lang of ['ru','en'])assert.ok(JSON.parse(fs.readFileSync('locales/'+lang+'.json'))[key],key);}assert.ok(!JSON.stringify(defs).includes('level2'));});
test('definitions.reject_malformed_data',()=>{for(const edit of [d=>d.entries.push(d.entries[0]),d=>d.entries[0].id='research.same',d=>d.entries[0].subtitles[1].startMs=0,d=>d.entries[0].requires={fact:'unknown',equals:true},d=>d.entries[0].media={kind:'invalid',assetId:'x'},d=>d.introId='log.missing']){const d=J('StoryDefinitions');edit(d);r.context.badDef=d;assert.throws(()=>E('StoryDomain.validateDefinitions(badDef)'));}});
// Replace only the official video descriptor in this test copy to exercise
// the separate future audio-adapter seam, without adding production media.
for(const mode of ['missing','sync-error','async-error','normal'])test('media_adapter.'+mode+'_bounded_cleanup',()=>{const h=setup('index.html',{}, {mainMenu:true,storyIntro:true,transformScript:code=>code.replace("media:{kind:'video',assetId:'story/intro',alt:'story.arrival.title'}","media:{kind:'audio',assetId:'qa:future',alt:'story.arrival.title'}")});h.eval("window.m={created:0,disposed:0,paused:[],volume:[],error:null};");if(mode!=='missing')h.eval(`StoryPlayer.registerMediaAdapter('audio',p=>{m.created++;m.error=p.onError;${mode==='sync-error'?'p.onError();':''}return {dispose(){m.disposed++},setPaused(p){m.paused.push(p)},setVolume(v){m.volume.push(v)}}})`);assert.equal(h.eval('V09Saves.newGame(1)'),true);if(mode==='async-error')h.eval('m.error()');if(mode==='normal'){h.eval('StoryPlayer.pause();document.hidden=true');h.emit('visibilitychange',h.doc);h.eval('document.hidden=false');h.emit('visibilitychange',h.doc);assert.equal(h.eval('m.paused.at(-1)'),true);h.eval('masterVolume=0;StoryPlayer.tick(0)');assert.equal(h.eval('m.volume.at(-1)'),0);assert.equal(h.eval('StoryPlayer.inspect().media'),true);}else assert.equal(h.eval('StoryPlayer.inspect().media'),false);h.eval('StoryPlayer.skip()');assert.equal(h.eval('m.disposed'),mode==='missing'?0:1);assert.equal(h.eval('StoryPlayer.active'),false);assert.equal(h.eval('GameFlow.paused'),false);assert.deepEqual(h.errors,[]);});
test('audio_all_accepted_sources_byte_identical',()=>{const base=require('./stage-f-base/release_manifest.json');for(const f of base.files.filter(f=>f.file!=='src/assets/manifest.js'&&(/^src\/(audio|assets)\//.test(f.file)||/^assets\/audio\//.test(f.file))))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f.file)).digest('hex'),f.sha256,f.file);const previous=JSON.parse(fs.readFileSync('qa/stage-f-final-base/js/game.js','utf8').match(/const AssetManifest=(.*);/)[1]),current=J('AssetManifest');delete current.videos;assert.deepEqual(current,previous);});
test('runtime.no_console_errors',()=>assert.deepEqual(r.errors,[]));
const report={version:require('../package.json').version,runtimeSha256:crypto.createHash('sha256').update(fs.readFileSync('js/game.js')).digest('hex'),passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks,limitations:['Deterministic DOM/audio ports. CSS layout, native codecs and real device audio require browser/device verification.']};fs.writeFileSync('qa/results/stage-f.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));if(report.failed)process.exitCode=1;
