const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),checks=[];
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.message});}}
const manifest=JSON.parse(fs.readFileSync(path.join(root,'src/manifest.json'))),parts=manifest.files.map(p=>fs.readFileSync(path.join(root,'src',p),'utf8')),body=parts.join(''),bundle=fs.readFileSync(path.join(root,'js/game.js'),'utf8');
check('build.exactConcatenation',()=>assert.equal(bundle,body+'\n//# sourceMappingURL=game.js.map\n'));
check('build.syntax',()=>new vm.Script(bundle));
const expected=JSON.parse(fs.readFileSync(path.join(__dirname,'stage5-reference.json')));
const acceptedMap=JSON.parse(fs.readFileSync(path.join(__dirname,'stage-a-base/js/game.js.map')));
check('stage5.exactAuditedInputRetained',()=>assert.equal(hash(acceptedMap.sourcesContent.join('')),expected.sourceHash));
check('css.originalOrderAndBytes',()=>assert.equal(hash(fs.readFileSync(path.join(root,'styles/base.css'))),expected.cssHash));
for(const f of [...expected.baselineFiles,...expected.unchangedStage2Sources])check('reference.unchanged.'+f.file,()=>require('./campaign-source-contract.cjs').assertSource(f.file,f.sha256));
for(const f of expected.files)check('source.audit.'+f.file,()=>require('./campaign-source-contract.cjs').assertSource(f.file,f.sha256));
check('save.noGlobalReassignments',()=>assert.ok(!/(?:capture|decode|restore)GameProgress\s*=/.test(body)));
check('save.noModuleBypass',()=>assert.ok(!/V010\.modules\.\w+\s*=/.test(body)));
check('save.stage2AdapterAuditRetained',()=>{const audit=JSON.parse(fs.readFileSync(path.join(__dirname,'adapter-preservation.json')));assert.equal(audit.adapters.length,56);assert.ok(audit.adapters.every(v=>v.bodyPreserved));for(const v of Object.values(audit.baseBodies))assert.equal(v.old,v.new);});
const baseline=fs.readFileSync(path.join(__dirname,'stage2/js/game.js'),'utf8');
const registrations=source=>[...source.matchAll(/GameSave\.extend\('([^']+)','([^']+)'/g)].map(m=>[m[1],m[2]]);
check('save.stage3SameAdapterOrder',()=>assert.deepEqual(registrations(body).filter(([,id])=>id!=='bunker.level1'&&id!=='campaign.foundation'&&id!=='equipment.instances'&&id!=='inventory.head-modules'&&id!=='base.recovery'&&id!=='campaign.chapter-one'&&id!=='equipment.placement'&&id!=='inventory.buildables'&&id!=='base.control'&&id!=='research.foundation'&&id!=='story.archive'&&id!=='world.exploration'),registrations(baseline)));
const oldMap=JSON.parse(fs.readFileSync(path.join(__dirname,'controls-base/js/game.js.map')));
check('stage5.onlyDeclaredSourceChanges',()=>assert.deepEqual(acceptedMap.sources.filter((file,i)=>acceptedMap.sourcesContent[i]!==oldMap.sourcesContent[oldMap.sources.indexOf(file)]).sort(),expected.changedSources));
check('bootstrap.last',()=>assert.equal(manifest.files.at(-1),'bootstrap.js'));
for(const [i,file]of manifest.files.entries())check('syntax.'+file,()=>new vm.Script(parts[i]));
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
for(const m of html.matchAll(/<(?:script|link)\b[^>]*(?:src|href)=["']([^"']+)["'][^>]*>/g))if(!/^https?:/.test(m[1]))check('path.'+m[1],()=>assert.ok(fs.existsSync(path.join(root,m[1].split(/[?#]/)[0]))));
const fingerprint=JSON.parse(fs.readFileSync(path.join(__dirname,'stage0/audit/source_fingerprint.json')));
const moved=Object.fromEntries(require('./asset-migration.json').files.map(f=>[f.old,f.path]));
for(const f of fingerprint.files.filter(f=>f.path.startsWith('assets/')))check('asset.unchanged.'+f.path,()=>assert.equal(hash(fs.readFileSync(path.join(root,moved[f.path]||f.path))),f.sha256));
const oldAssets=JSON.parse(fs.readFileSync(path.join(__dirname,'stage0/audit/assets.json')));
const refs=[...new Set([...body.matchAll(/["'`]((?:assets\/)[\w/.-]+\.(?:png|webp|gif)|[\w/.-]+\.(?:mp3|ogg|wav))["'`]/g)].map(m=>m[1]))];
const missing=refs.filter(p=>!fs.existsSync(path.join(root,p)));
const optional=require('../tools/assets.cjs').validate(require('../assets/manifest.json')).optionalMissing;
check('assets.noNewMissingPaths',()=>assert.deepEqual(missing.sort(),optional.sort()));
check('assets.noOptionalAudioMissing',()=>assert.deepEqual(optional,[]));
const map=JSON.parse(fs.readFileSync(path.join(root,'js/game.js.map')));
check('debug.sourceMap',()=>{assert.deepEqual(map.sources,manifest.files);assert.deepEqual(map.sourcesContent,parts);assert.equal(map.mappings.split(';').length,body.split('\n').length-1);});
const result={passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status!=='PASS').length,checks,knownMissingAudio:missing,notes:['Formerly missing optional audio replaced with explicit required files in the Audio Pass.']};
fs.writeFileSync(path.join(__dirname,'results/verification.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,knownMissingAudio:missing}));if(result.failed)process.exitCode=1;
