// Release 0.28 owner-level integration contracts. Real Canvas2D, modeled DOM.
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');process.chdir(path.resolve(__dirname,'..'));
const {setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),json=v=>JSON.parse(JSON.stringify(v)),checks=[];
const baseline=E('JSON.stringify(captureGameProgress())');
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack?.slice(0,2300)});}}
function reset(){E(`for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);GameFlow.resume();restoreGameProgress(decodeGameProgress(${JSON.stringify(baseline)}));scene='bunker';playerDead=false;document.hidden=false;menuOpen=false;V09Power.running=true;V09Power.fuel=80;V010Energy.battery.charge=V010Energy.battery.capacity;zombies=[];`);}
// 0.43: crops are planted through the current farm owner (the farm is active); the old 0.29 runtime import is gone.
function plant(i=0,crop=4){E(`V011Farm.beginBed(${i},${crop});for(let n=0;n<50;n++)V011Farm.plantOne(${i},n);`);}
function advance(ms){r.advance(ms);E('V011Farm.settle()');}
// 0.43: irrigation buffer capacity is 40 and a new game starts with empty irrigation and clean-water tanks (Pass A).
check('newGame.tanksEmptyCapacity40',()=>{reset();assert.equal(E('GameplayBalance.farm.waterCapacity'),40);assert.equal(E('V011Farm.state.water'),0);assert.equal(E('GameSave.newGameData().farmV011.water'),0);assert.equal(E('GameNewGame.create().farmV011.water'),0);assert.equal(E('GameNewGame.create().bunker043.water.clean'),0);});
// 0.43: removed 'beds.retainedButNotInteractive.0..4', 'irrigation.frozenSprayAndWaitTimers' and 'irrigation.noOfflineCatchupOrConsumption' — the farm is active again (dormant beds, frozen irrigation and suspended catch-up were removed on purpose; planting/growth/irrigation are covered by pass-a.cjs).
// 0.43: tank capacity is 40; a full tank still accepts no refill and consumes nothing.
check('irrigation.unavailableRefillDoesNotConsumeInventory',()=>{reset();E("bag=[];addItem('water',20);V011Farm.state.water=40");assert.equal(E('V011Farm.refill(1000)'),0);assert.equal(E('bagCount("water")'),20);assert.equal(E('V011Farm.state.water'),40);});
check('irrigation.saveLoadExactRemainingNoDuplicateTimers',()=>{reset();plant();const raw=E('JSON.stringify(captureGameProgress())'),q=E('JSON.stringify(farmState.map(s=>s.irrigation028))'),listeners=r.listenerCounts(),loops=json(r.scheduler);for(let n=0;n<8;n++)E(`restoreGameProgress(${raw})`);assert.equal(E('JSON.stringify(farmState.map(s=>s.irrigation028))'),q);assert.deepEqual(r.listenerCounts(),listeners);assert.deepEqual(json(r.scheduler),loops);});
// 0.43: removed 'migration.legacyWaterAndCowOverflowNoLoss' — exact pre-0.43 save/runtime equivalence (old save formats are no longer supported).
// 0.43: animals are inactive (AgricultureTime.animalsAvailable=false), so no births; the six stable stalls, removal and reload are still checked.
// 0.43 Pass B: the legacy cow owner (updateLivestockAnimals/addCow/cowCount) was replaced by GameLivestock; same intent, new owner.
check('cows.sixStableStallsBirthRemovalReload',()=>{reset();const cows=()=>json(E("GameLivestock.list('cow').map(a=>({id:a.id,stall:a.stall}))"));const before=cows();assert.equal(before.length,2);assert.equal(new Set(before.map(c=>c.stall)).size,2);E("GameLivestock.state.animals.push({id:'cow:900',kind:'cow',ageMs:6*GameLivestock.constants.DAY,stage:2,milkMs:0,stall:5});bag=[]");assert.equal(E("GameLivestock.slaughter('cow').ok"),true);const left=cows();assert.equal(left.length,2);E('GameLivestock.state.calfMs=0;V09Power.running=true;V09Power.fuel=100;V09Power.frame++');E('AgricultureTime.advance(15);V09Power.frame++;GameLivestock.settle()');const after=cows();assert.equal(new Set(after.map(c=>c.stall)).size,after.length);assert.ok(after.every(c=>c.stall>=0&&c.stall<6));E('restoreGameProgress(decodeGameProgress(JSON.stringify(captureGameProgress())))');assert.deepEqual(cows(),after);});
check('cows.min2SlaughterAndMeat',()=>{reset();E("bag=[];GameLivestock.state.animals.push({id:'cow:901',kind:'cow',ageMs:6*GameLivestock.constants.DAY,stage:2,milkMs:0,stall:4})");assert.equal(E("GameLivestock.slaughter('cow').ok"),true);assert.equal(E("GameLivestock.list('cow').length"),2);assert.equal(E("GameLivestock.slaughter('cow').ok"),false);assert.equal(E("GameLivestock.list('cow').length"),2);assert.equal(E('bagCount("beef")'),20);});
// 0.43 Pass B: animals are active; troughs/stalls belong to GameLivestock and #13 is retired as an animal-water source.
check('animals.troughCapacitiesAndPantrySupplies',()=>{reset();assert.deepEqual(json(E('GameLivestock.constants.CAP')),{chicken:{feed:3840,water:3840},cow:{feed:7680,water:7680}});assert.equal(E("interactionObjects('bunker').filter(o=>o.id.startsWith('animal_')).length"),0);assert.equal(E('storageCount(12,"animal_feed")'),100);assert.equal(E("interactionObjects('bunker').some(o=>o.id==='chest12')"),true);assert.equal(E("interactionObjects('bunker').some(o=>o.id==='chest13')"),false);});
for(const lang of ['ru','en'])for(const mode of ['PC','MOBILE'])check(`ui.droneOrderNoMaintenanceNoQuick.${lang}.${mode}`,()=>{reset();E(`I18n.setLanguage('${lang}');GameInput.setMode('${mode}');V014Robots.open();V0161UI.refreshQuick();`);const o=r.doc.getElementById('v014DronePanel'),text=o.textContent;assert.equal(o.querySelector('.droneMore'),null);assert.equal(o.querySelector('.v0161QuickWrap'),null);assert.equal(o.querySelector('.droneRescue').children.length,2);const b=o.querySelector('.droneCardBody'),children=[...b.children];assert.ok(children.findIndex(x=>x.classList.contains('droneRescue'))<children.findIndex(x=>x.classList.contains('dronePlayerBag')));assert.ok(!/Обслуживание|Maintenance/.test(text));E("I18n.setLanguage('ru')");});
check('ui.pinGoneQuickRetained',()=>{reset();E("bag=[];addItem('coal',25);V011UI.details('bag',0)");assert.ok(!/Закрепить|Открепить|Pin/.test(r.doc.getElementById('v010ItemDetails').textContent));assert.equal(r.doc.querySelector('.v010LockMark'),null);E("addItem('axe',1)");assert.equal(E("V013Inventory.equip('axe')"),true);});
for(const pointerType of ['mouse','touch'])check('ui.pressFeedback.'+pointerType,()=>{reset();E("GameLivestock.open('cow')");/* 0.43 Pass B: the legacy cow panel is gone; the same menu-button feedback on the new Cow Farm panel */const b=r.doc.getElementById('livestockCows').querySelector('[data-slaughter]');b.disabled=false;r.emit('pointerdown',b,{pointerType});assert.equal(b.classList.contains('buttonPressed028'),true);r.emit('pointerup',b,{pointerType});r.flushTimers(120);assert.equal(b.classList.contains('buttonPressed028'),false);b.disabled=true;r.emit('pointerdown',b,{pointerType});assert.equal(b.classList.contains('buttonPressed028'),false);E("closeOverlay(el('livestockCows'))");});
check('processing.ratiosAndAmmoDataOnly',()=>{reset();assert.deepEqual(json(E('V09Craft.recipes.iron.input')),{iron_ore:2});assert.deepEqual(json(E('V09Craft.recipes.copper.input')),{copper_ore:2});assert.deepEqual(json(E('V09Craft.recipes.concrete.input')),{stone:2});assert.deepEqual(json(E('V09Craft.recipes.gunpowder.input')),{coal:1});assert.equal(E('V09Craft.recipes.gunpowder.qty'),4);for(const type of ['ammo','ammo556']){assert.equal(E(`V09Craft.recipes.${type}.input.gunpowder`),6);assert.equal(E(`V09Craft.recipes.${type}.qty`),30);}});
check('processing.stackLimitsAndPartialOutputNoLoss',()=>{reset();E("bag=[];addItem('gunpowder',990);addItem('coal',100);V09Craft.start('furnace','gunpowder',100);for(let n=0;n<2000;n++)V09Craft.tick(100);V09Craft.collect('furnace')");assert.equal(E('bagCount("coal")'),0);assert.equal(E('bagCount("gunpowder")'),1390);assert.deepEqual(json(E('bag.filter(s=>s?.type==="gunpowder").map(s=>s.qty)')),[1000,390]);assert.equal(E("itemStackLimit('coal')"),100);});
check('processing.ammoRequiresPowderAtomic',()=>{reset();E("bag=[];storageChests.forEach(c=>c.items=[]);addItem('iron',2);addItem('copper',1);");assert.equal(E("V09Craft.start('craft_bench','ammo',1)"),false);assert.equal(E('bagCount("iron")'),2);E("addItem('gunpowder',6)");assert.equal(E("V09Craft.start('craft_bench','ammo',1)"),true);assert.equal(E('bagCount("gunpowder")'),0);});
// 0.43: removed 'processing.legacyPaidOrderRefundNoFreePowder' — exact pre-0.43 save/runtime equivalence (old save formats are no longer supported).
check('resources.noOverlapNoFootprintObstruction',()=>{reset();const errors=E(`(()=>{const a=WorldResourcePlacement.resources,out=[];for(let i=0;i<a.length;i++){const o=a[i],r=WorldResourcePlacement.radius(o);if(!WorldResourcePlacement.staticClear(o.x,o.y,r))out.push('static '+o.id);for(let j=i+1;j<a.length;j++)if(distance(o.x,o.y,a[j].x,a[j].y)<r+WorldResourcePlacement.radius(a[j])+GameplayBalance.resources.spacing-.001)out.push(o.id+' overlaps '+a[j].id);}return out;})()`);assert.deepEqual(json(errors),[]);});
check('resources.fourCoalZonesMultipleDepositsStableIds',()=>{assert.equal(E('WorldResourcePlacement.coalZones.length'),4);assert.equal(E('V09World.ores.filter(o=>o.type==="coal").length'),32);assert.equal(E('new Set(WorldResourcePlacement.resources.map(o=>o.id)).size'),E('WorldResourcePlacement.resources.length'));for(const z of E('WorldResourcePlacement.coalZones.map(z=>z.id)'))assert.equal(E(`V09World.ores.filter(o=>o.zoneId==='${z}').length`),8);});
check('resources.depletionRoundtrip',()=>{reset();E("V09World.ores.find(o=>o.type==='coal').remaining=17");const d=E('JSON.stringify(captureGameProgress())');E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(d)}))`);assert.equal(E("V09World.ores.find(o=>o.type==='coal').remaining"),17);});
for(const t of ['coal','gunpowder'])for(const lang of ['ru','en'])check(`assets.inventoryCrafting.${t}.${lang}`,()=>{reset();E(`I18n.setLanguage('${lang}');bag=[];addItem('${t}',1);renderBag();V09Craft.open('furnace');`);const html=E(`itemIconHTML('${t}')`);assert.ok(html.includes(`assets/icons/items/${t}.png`));assert.ok(fs.existsSync(`assets/icons/items/${t}.png`));assert.equal(E(`I18n.text(ITEM.${t}.name)`),lang==='en'?(t==='coal'?'Coal':'Gunpowder'):(t==='coal'?'Уголь':'Порох'));E("I18n.setLanguage('ru')");});

check('processing.fullBagRetainsUncollectedPowder',()=>{reset();E("bag=[];storageChests.forEach(c=>c.items=[]);addItem('coal',5);V09Craft.start('furnace','gunpowder',5);for(let n=0;n<100;n++)V09Craft.tick(100);bag=Array.from({length:BAG_SLOTS},()=>({type:'wood',qty:100}));bag[0]={type:'gunpowder',qty:995}");assert.equal(E("V09Craft.collect('furnace')"),5);assert.equal(E("V09Craft.craftQueue.readyItems('furnace').gunpowder"),15);const raw=E('JSON.stringify(captureGameProgress())');E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(raw)}));bag[1]=null`);assert.equal(E("V09Craft.collect('furnace')"),15);assert.equal(E('bagCount("gunpowder")'),1015);assert.equal(E("V09Craft.craftQueue.readyItems('furnace').gunpowder||0"),0);});
for(let slot=1;slot<=5;slot++)check(`saveSlots.${slot}.newResourcesAndIrrigation`,()=>{reset();plant(slot-1);E(`bag=[];addItem('coal',${slot});addItem('gunpowder',1000);V011Farm.state.water=${slot+11};/* 0.43: no clean-water inflow while the loaded runtime catches up its clock */BunkerPassA.water.clean=0;V09Power.devices.water_system.enabled=false;farmState[${slot-1}].irrigation028={phase:'spray',remainingMs:5432,rng:1234};`);const raw=E('JSON.stringify(captureGameProgress())'),x=setup('index.html',{['survival_base_v09_slot_'+slot]:raw},{mainMenu:true});x.advance(E('Date.now()')-x.eval('Date.now()'));assert.equal(x.eval(`V09Saves.load(${slot})`),true);assert.equal(x.eval('bagCount("coal")'),slot);assert.equal(x.eval('bagCount("gunpowder")'),1000);assert.equal(x.eval('V011Farm.state.water'),slot+11);/* 0.43: irrigation runs on the active agriculture clock; the loaded game may run at most one 60 Hz frame (16.667 ms step) before this read. */{const left=x.eval(`farmState[${slot-1}].irrigation028.remainingMs`);assert.ok(left<=5432&&left>=5432-17,String(left));}assert.equal(x.eval('saveGameProgress()'),true);const saved=JSON.parse(x.storage.get('survival_base_v09_slot_'+slot));assert.equal(saved.saveVersion,r.eval('SaveFormat.version'));assert.equal(saved.farmV011.water,slot+11);assert.deepEqual(x.errors,[]);});
for(const [name,mutate]of [
 ['waterOverCapacity',d=>d.farmV011.water=41],
 ['invalidTimer',d=>d.farm014.irrigation[0]={phase:'spray',remainingMs:10001}],
 ['unfundedSpray',d=>{d.farm014.irrigation[0]={phase:'spray',remainingMs:5000};d.farmV011.water=0;}],
 ['duplicateCowId',d=>{const c=d.livestock043.animals.filter(a=>a.kind==='cow');c[1].id=c[0].id;}],
 ['duplicateCowSlot',d=>{const c=d.livestock043.animals.filter(a=>a.kind==='cow');c[1].stall=c[0].stall;}]
])check('save.reject.'+name+'.beforeMutation',()=>{reset();plant();const d=json(E('captureGameProgress()'));mutate(d);const before=E('JSON.stringify(captureGameProgress())');assert.throws(()=>E(`restoreGameProgress(${JSON.stringify(d)})`));assert.equal(E('JSON.stringify(captureGameProgress())'),before);});
check('resources.coalUsesExistingMiningOwner',()=>{reset();E("scene='surface';bag=[];addItem('pickaxe',1);V013Inventory.equip('pickaxe');window.coalProbe=V09World.ores.find(o=>o.type==='coal');player.x=coalProbe.x+coalProbe.r+17;player.y=coalProbe.y;movePower=0;executeInteraction(interactionObjects('surface').find(o=>o.id===coalProbe.id));");assert.ok(E('V09World.miningState()'));r.advance(1800);E('V09World.tickMining()');assert.equal(E('bagCount("coal")'),15);assert.equal(E('coalProbe.remaining'),85);E('V09World.stopMining()');});
check('console.noErrors',()=>assert.deepEqual(r.errors,[]));
const result={version:require('../package.json').version,passed:checks.filter(x=>x.status==='PASS').length,failed:checks.filter(x=>x.status==='FAIL').length,checks};fs.mkdirSync('qa/results',{recursive:true});fs.writeFileSync('qa/results/world-farm.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(x=>x.status==='FAIL')}));if(result.failed)process.exitCode=1;
