// Release 0.28 owner-level integration contracts. Real Canvas2D, modeled DOM.
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');process.chdir(path.resolve(__dirname,'..'));
const {setup}=require('./runtime.cjs'),r=setup('index.html'),E=s=>r.eval(s),json=v=>JSON.parse(JSON.stringify(v)),checks=[];
const baseline=E('JSON.stringify(captureGameProgress())');
function check(id,fn){try{fn();checks.push({id,status:'PASS'});}catch(e){checks.push({id,status:'FAIL',error:e.stack?.slice(0,2300)});}}
function reset(){E(`for(const o of document.querySelectorAll('.overlay.open'))closeOverlay(o);GameFlow.resume();restoreGameProgress(decodeGameProgress(${JSON.stringify(baseline)}));scene='bunker';playerDead=false;document.hidden=false;menuOpen=false;V09Power.running=true;V09Power.fuel=80;V010Energy.battery.charge=V010Energy.battery.capacity;zombies=[];`);}
function plant(i=0,crop=4){E(`{const b=getFarmBeds()[${i}];player.x=b.x+b.w/2;player.y=b.y+b.h/2;}`);assert.equal(E(`V0141Farm.plant(${i},${crop})`),true);}
function advance(ms){r.advance(ms);E('V011Farm.settle()');}
check('newGame.full500',()=>{reset();assert.equal(E('V011Farm.state.water'),500);assert.equal(E('GameSave.newGameData().farmV011.water'),500);});
for(let i=0;i<5;i++)check('beds.walkAndPlantNoSeeds.'+i,()=>{reset();E('bag=[];');const before=E('JSON.stringify(storageChests)');plant(i,i);assert.equal(E(`worldCollision(player.x,player.y,player.radius,'bunker')`),false);assert.equal(E('bag.filter(Boolean).length'),0);assert.equal(E('JSON.stringify(storageChests)'),before);assert.equal(E(`V011Farm.plants(farmState[${i}]).length`),50);});
check('beds.independentTimers',()=>{reset();for(let i=0;i<5;i++)plant(i,4);assert.equal(E('new Set(farmState.map(s=>s.irrigation028)).size'),5);assert.ok(E('new Set(farmState.map(s=>s.irrigation028.remainingMs)).size>1'));});
check('irrigation.exact10secondsOneLiterAndWaitRange',()=>{reset();plant();E("farmState[0].irrigation028={phase:'wait',remainingMs:0}");advance(1);assert.equal(E('V011Farm.spraying(0)'),true);advance(9998);assert.equal(E('V011Farm.state.water'),500);advance(1);assert.equal(E('V011Farm.state.water'),499);assert.equal(E('farmState[0].irrigation028.phase'),'wait');assert.ok(E('farmState[0].irrigation028.remainingMs>=60000&&farmState[0].irrigation028.remainingMs<=120000'));});
check('irrigation.noGameClockAcceleration',()=>{reset();plant();E("farmState[0].irrigation028={phase:'wait',remainingMs:30000};WorldClock.restore({schema:1,day:999,minute:1200});V011Farm.settle();");assert.equal(E('farmState[0].irrigation028.remainingMs'),30000);advance(1000);assert.equal(E('farmState[0].irrigation028.remainingMs'),29000);});
check('irrigation.zeroRefillAndReservations',()=>{reset();for(let i=0;i<5;i++)plant(i);E("V011Farm.state.water=0;farmState.forEach(s=>s.irrigation028={phase:'wait',remainingMs:0});");advance(1000);assert.equal(E('farmState.some(s=>s.irrigation028.phase==="spray")'),false);E("bag=[];addItem('water',1);V011Farm.refill(1);");advance(1);assert.equal(E('farmState.filter(s=>s.irrigation028.phase==="spray").length'),1);advance(10000);assert.equal(E('V011Farm.state.water'),0);assert.equal(E('farmState.some(s=>s.irrigation028.phase==="spray")'),false);E("addItem('water',5);V011Farm.refill(5)");advance(1);assert.equal(E('farmState.filter(s=>s.irrigation028.phase==="spray").length'),4);});
check('irrigation.refillClamps500',()=>{reset();E("V011Farm.state.water=497;bag=[];addItem('water',20)");assert.equal(E('V011Farm.refill(1000)'),3);assert.equal(E('V011Farm.state.water'),500);assert.equal(E('bagCount("water")'),17);});
check('irrigation.readyCancelsPartialNoDebit',()=>{reset();plant();E("farmState[0].irrigation028={phase:'spray',remainingMs:4000};V011Farm.plants(farmState[0]).forEach(p=>p.elapsed=p.duration-500);");advance(1000);assert.equal(E('V011Farm.ready(0)'),true);assert.equal(E('V011Farm.spraying(0)'),false);assert.equal(E('V011Farm.state.water'),500);advance(180000);assert.equal(E('V011Farm.state.water'),500);assert.ok(E('V0141Farm.harvest(0)>0'));plant();assert.equal(E('farmState[0].irrigation028.phase'),'wait');});
check('irrigation.saveLoadExactRemainingNoDuplicateTimers',()=>{reset();for(let i=0;i<5;i++)plant(i);E("farmState.forEach((s,i)=>s.irrigation028={phase:i%2?'wait':'spray',remainingMs:i%2?60000+i:5000+i});V011Farm.state.water=123;");const raw=E('JSON.stringify(captureGameProgress())'),q=E('JSON.stringify(farmState.map(s=>s.irrigation028))'),listeners=r.listenerCounts(),loops=json(r.scheduler);for(let n=0;n<8;n++)E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(raw)}));`);assert.equal(E('JSON.stringify(farmState.map(s=>s.irrigation028))'),q);assert.equal(E('V011Farm.state.water'),123);assert.deepEqual(r.listenerCounts(),listeners);assert.deepEqual(json(r.scheduler),loops);advance(5005);assert.equal(E('V011Farm.state.water'),120);});
check('irrigation.offlineGrowthNoOfflineWaterUse',()=>{reset();plant();E("farmState[0].irrigation028={phase:'spray',remainingMs:5000};V011Farm.state.water=71;");const raw=E('JSON.stringify(captureGameProgress())');r.advance(60000);E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(raw)}))`);assert.equal(E('V011Farm.state.water'),71);assert.equal(E('farmState[0].irrigation028.remainingMs'),5000);assert.ok(E('V011Farm.plants(farmState[0])[0].elapsed>=60000'));});
check('migration.legacyWaterAndCowOverflowNoLoss',()=>{reset();const d=json(E('captureGameProgress()'));d.saveVersion=2;d.gameVersion='0.27.1';d.farmV011.schema=1;d.farmV011.water=37;d.farm014={...d.farm014,schema:1,next:0,end:0};delete d.farm014.irrigation;delete d.livestock.schema;delete d.livestock.reserve;delete d.livestock.nextCow;const cow=d.livestock.animals.find(a=>a.kind==='cow');while(d.livestock.animals.filter(a=>a.kind==='cow').length<12)d.livestock.animals.push({...cow});d.bag=[{type:'coal',qty:3,locked:true}];E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(JSON.stringify(d))}))`);assert.equal(E('cowCount()'),6);assert.equal(E('GameLivestock.reserve.length'),6);assert.equal(E('V011Farm.state.water'),37);assert.equal(E('bag[0].locked'),undefined);const saved=E('JSON.stringify(captureGameProgress())');E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(saved)}))`);assert.equal(E('GameLivestock.reserve.length'),6);assert.equal(E('V011Farm.state.water'),37);E("livestockAnimals.splice(livestockAnimals.findIndex(a=>a.kind==='cow'),1)");assert.equal(E('GameLivestock.restoreReserve()'),true);assert.equal(E('GameLivestock.reserve.length'),5);});
check('cows.sixStableSlotsBirthRemovalReload',()=>{reset();E('while(addCow());updateLivestockAnimals()');assert.equal(E('cowCount()'),6);assert.equal(E('addCow()'),false);const before=json(E('livestockAnimals.filter(a=>a.kind==="cow").map(a=>({id:a.instanceId,slot:a.stallId,x:a.x,y:a.y}))'));E("livestockAnimals.splice(livestockAnimals.findIndex(a=>a.stallId==='cow_slot_3'),1);updateLivestockAnimals();");assert.deepEqual(json(E('livestockAnimals.filter(a=>a.kind==="cow").map(a=>({id:a.instanceId,slot:a.stallId,x:a.x,y:a.y}))')),before.filter(a=>a.slot!=='cow_slot_3'));assert.equal(E('V011Farm.cowStalls().length'),6);const raw=E('JSON.stringify(captureGameProgress())');E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(raw)}));updateLivestockAnimals();`);assert.equal(E("livestockAnimals.some(a=>a.stallId==='cow_slot_3')"),false);assert.equal(E('addCow()'),true);assert.equal(E("livestockAnimals.at(-1).stallId"),'cow_slot_3');});
check('cows.min2AndMilkActions',()=>{reset();E("bag=[];renderCowMenu();");const b=r.doc.getElementById('cowSlaughterBtn');r.emit('click',b);assert.equal(E('cowCount()'),2);r.emit('click',b);assert.equal(E('cowCount()'),2);assert.equal(E('bagCount("beef")'),20);assert.equal(b.disabled,true);});
check('animals.fourVisualTroughsTwoCommonSupplies',()=>{reset();assert.deepEqual(Object.keys(json(E('V011Farm.troughs()'))),['cow','cowWater','chicken','chickenWater']);assert.equal(E("interactionObjects('bunker').filter(o=>o.id.startsWith('animal_')).length"),4);assert.equal(E('storageCount(12,"animal_feed")'),100);assert.equal(E('storageCount(13,"water")'),100);assert.ok(E('V011Farm.cowStalls().every(s=>s.w===37&&s.h===60)'));});
for(const lang of ['ru','en'])for(const mode of ['PC','MOBILE'])check(`ui.droneOrderNoMaintenanceNoQuick.${lang}.${mode}`,()=>{reset();E(`I18n.setLanguage('${lang}');GameInput.setMode('${mode}');V014Robots.open();V0161UI.refreshQuick();`);const o=r.doc.getElementById('v014DronePanel'),text=o.textContent;assert.equal(o.querySelector('.droneMore'),null);assert.equal(o.querySelector('.v0161QuickWrap'),null);assert.equal(o.querySelector('.droneRescue').children.length,2);const b=o.querySelector('.droneCardBody'),children=[...b.children];assert.ok(children.findIndex(x=>x.classList.contains('droneRescue'))<children.findIndex(x=>x.classList.contains('dronePlayerBag')));assert.ok(!/Обслуживание|Maintenance/.test(text));E("I18n.setLanguage('ru')");});
check('ui.pinGoneQuickRetained',()=>{reset();E("bag=[];addItem('coal',25);V011UI.details('bag',0)");assert.ok(!/Закрепить|Открепить|Pin/.test(r.doc.getElementById('v010ItemDetails').textContent));assert.equal(r.doc.querySelector('.v010LockMark'),null);E("addItem('axe',1)");assert.equal(E("V013Inventory.equip('axe')"),true);});
for(const pointerType of ['mouse','touch'])check('ui.pressFeedback.'+pointerType,()=>{reset();const b=r.doc.getElementById('cowSlaughterBtn');b.disabled=false;r.emit('pointerdown',b,{pointerType});assert.equal(b.classList.contains('buttonPressed028'),true);r.emit('pointerup',b,{pointerType});r.flushTimers(120);assert.equal(b.classList.contains('buttonPressed028'),false);b.disabled=true;r.emit('pointerdown',b,{pointerType});assert.equal(b.classList.contains('buttonPressed028'),false);});
check('processing.ratiosAndAmmoDataOnly',()=>{reset();assert.deepEqual(json(E('V09Craft.recipes.iron.input')),{iron_ore:2});assert.deepEqual(json(E('V09Craft.recipes.copper.input')),{copper_ore:2});assert.deepEqual(json(E('V09Craft.recipes.concrete.input')),{stone:2});assert.deepEqual(json(E('V09Craft.recipes.gunpowder.input')),{coal:1});assert.equal(E('V09Craft.recipes.gunpowder.qty'),4);for(const type of ['ammo','ammo556']){assert.equal(E(`V09Craft.recipes.${type}.input.gunpowder`),6);assert.equal(E(`V09Craft.recipes.${type}.qty`),30);}});
check('processing.stackLimitsAndPartialOutputNoLoss',()=>{reset();E("bag=[];addItem('gunpowder',990);addItem('coal',100);V09Craft.start('furnace','gunpowder',100);for(let n=0;n<2000;n++)V09Craft.tick(100);V09Craft.collect('furnace')");assert.equal(E('bagCount("coal")'),0);assert.equal(E('bagCount("gunpowder")'),1390);assert.deepEqual(json(E('bag.filter(s=>s?.type==="gunpowder").map(s=>s.qty)')),[1000,390]);assert.equal(E("itemStackLimit('coal')"),100);});
check('processing.ammoRequiresPowderAtomic',()=>{reset();E("bag=[];storageChests.forEach(c=>c.items=[]);addItem('iron',2);addItem('copper',1);");assert.equal(E("V09Craft.start('craft_bench','ammo',1)"),false);assert.equal(E('bagCount("iron")'),2);E("addItem('gunpowder',6)");assert.equal(E("V09Craft.start('craft_bench','ammo',1)"),true);assert.equal(E('bagCount("gunpowder")'),0);});
check('processing.legacyPaidOrderRefundNoFreePowder',()=>{reset();const d=json(E('captureGameProgress()'));d.saveVersion=2;d.gameVersion='0.27.1';d.v09.crafting.jobs.craft_bench={recipe:'ammo',batches:1,totalMs:10000,remainingMs:10000,completedBatches:0,outputQty:0,collectedQty:0};E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(JSON.stringify(d))}));bag=[];storageChests.forEach(c=>c.items=[]);V09Craft.craftQueue.cancelUnstarted('craft_bench');`);assert.equal(E('bagCount("gunpowder")'),0);assert.equal(E('bagCount("iron")'),2);assert.equal(E('bagCount("copper")'),1);});
check('resources.noOverlapNoFootprintObstruction',()=>{reset();const errors=E(`(()=>{const a=WorldResourcePlacement.resources,out=[];for(let i=0;i<a.length;i++){const o=a[i],r=WorldResourcePlacement.radius(o);if(!WorldResourcePlacement.staticClear(o.x,o.y,r))out.push('static '+o.id);for(let j=i+1;j<a.length;j++)if(distance(o.x,o.y,a[j].x,a[j].y)<r+WorldResourcePlacement.radius(a[j])+GameplayBalance.resources.spacing-.001)out.push(o.id+' overlaps '+a[j].id);}return out;})()`);assert.deepEqual(json(errors),[]);});
check('resources.fourCoalZonesMultipleDepositsStableIds',()=>{assert.equal(E('WorldResourcePlacement.coalZones.length'),4);assert.equal(E('V09World.ores.filter(o=>o.type==="coal").length'),32);assert.equal(E('new Set(WorldResourcePlacement.resources.map(o=>o.id)).size'),E('WorldResourcePlacement.resources.length'));for(const z of E('WorldResourcePlacement.coalZones.map(z=>z.id)'))assert.equal(E(`V09World.ores.filter(o=>o.zoneId==='${z}').length`),8);});
check('resources.depletionRoundtrip',()=>{reset();E("V09World.ores.find(o=>o.type==='coal').remaining=17");const d=E('JSON.stringify(captureGameProgress())');E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(d)}))`);assert.equal(E("V09World.ores.find(o=>o.type==='coal').remaining"),17);});
for(const t of ['coal','gunpowder'])for(const lang of ['ru','en'])check(`assets.inventoryCrafting.${t}.${lang}`,()=>{reset();E(`I18n.setLanguage('${lang}');bag=[];addItem('${t}',1);renderBag();V09Craft.open('furnace');`);const html=E(`itemIconHTML('${t}')`);assert.ok(html.includes(`assets/icons/items/${t}.png`));assert.ok(fs.existsSync(`assets/icons/items/${t}.png`));assert.equal(E(`I18n.text(ITEM.${t}.name)`),lang==='en'?(t==='coal'?'Coal':'Gunpowder'):(t==='coal'?'Уголь':'Порох'));E("I18n.setLanguage('ru')");});

check('processing.fullBagRetainsUncollectedPowder',()=>{reset();E("bag=[];storageChests.forEach(c=>c.items=[]);addItem('coal',5);V09Craft.start('furnace','gunpowder',5);for(let n=0;n<100;n++)V09Craft.tick(100);bag=Array.from({length:BAG_SLOTS},()=>({type:'wood',qty:100}));bag[0]={type:'gunpowder',qty:995}");assert.equal(E("V09Craft.collect('furnace')"),5);assert.equal(E("V09Craft.craftQueue.readyItems('furnace').gunpowder"),15);const raw=E('JSON.stringify(captureGameProgress())');E(`restoreGameProgress(decodeGameProgress(${JSON.stringify(raw)}));bag[1]=null`);assert.equal(E("V09Craft.collect('furnace')"),15);assert.equal(E('bagCount("gunpowder")'),1015);assert.equal(E("V09Craft.craftQueue.readyItems('furnace').gunpowder||0"),0);});
for(let slot=1;slot<=5;slot++)check(`saveSlots.${slot}.newResourcesAndIrrigation`,()=>{reset();plant(slot-1);E(`bag=[];addItem('coal',${slot});addItem('gunpowder',1000);V011Farm.state.water=${slot+11};farmState[${slot-1}].irrigation028={phase:'spray',remainingMs:5432,rng:1234};`);const raw=E('JSON.stringify(captureGameProgress())'),x=setup('index.html',{['survival_base_v09_slot_'+slot]:raw},{mainMenu:true});x.advance(E('Date.now()')-x.eval('Date.now()'));assert.equal(x.eval(`V09Saves.load(${slot})`),true);assert.equal(x.eval('bagCount("coal")'),slot);assert.equal(x.eval('bagCount("gunpowder")'),1000);assert.equal(x.eval('V011Farm.state.water'),slot+11);assert.equal(x.eval(`farmState[${slot-1}].irrigation028.remainingMs`),5432);assert.equal(x.eval('saveGameProgress()'),true);const saved=JSON.parse(x.storage.get('survival_base_v09_slot_'+slot));assert.equal(saved.saveVersion,3);assert.equal(saved.farmV011.water,slot+11);assert.deepEqual(x.errors,[]);});
for(const [name,mutate]of [
 ['waterOverCapacity',d=>d.farmV011.water=501],
 ['invalidTimer',d=>d.farm014.irrigation[0]={phase:'spray',remainingMs:10001}],
 ['unfundedSpray',d=>{d.farm014.irrigation[0]={phase:'spray',remainingMs:5000};d.farmV011.water=0;}],
 ['duplicateCowId',d=>d.livestock.animals[1].instanceId=d.livestock.animals[0].instanceId],
 ['duplicateCowSlot',d=>d.livestock.animals[1].stallId=d.livestock.animals[0].stallId]
])check('save.reject.'+name+'.beforeMutation',()=>{reset();plant();const d=json(E('captureGameProgress()'));mutate(d);const before=E('JSON.stringify(captureGameProgress())');assert.throws(()=>E(`restoreGameProgress(${JSON.stringify(d)})`));assert.equal(E('JSON.stringify(captureGameProgress())'),before);});
check('resources.coalUsesExistingMiningOwner',()=>{reset();E("scene='surface';bag=[];addItem('pickaxe',1);V013Inventory.equip('pickaxe');window.coalProbe=V09World.ores.find(o=>o.type==='coal');player.x=coalProbe.x+coalProbe.r+17;player.y=coalProbe.y;movePower=0;executeInteraction(interactionObjects('surface').find(o=>o.id===coalProbe.id));");assert.ok(E('V09World.miningState()'));r.advance(1800);E('V09World.tickMining()');assert.equal(E('bagCount("coal")'),10);assert.equal(E('coalProbe.remaining'),90);E('V09World.stopMining()');});
check('console.noErrors',()=>assert.deepEqual(r.errors,[]));
const result={version:require('../package.json').version,passed:checks.filter(x=>x.status==='PASS').length,failed:checks.filter(x=>x.status==='FAIL').length,checks};fs.mkdirSync('qa/results',{recursive:true});fs.writeFileSync('qa/results/world-farm.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(x=>x.status==='FAIL')}));if(result.failed)process.exitCode=1;
